### ISSUE TITLE
Strange dialog behavior inside tab

### ISSUE THREAD

**Issue by irvanherz** [tailwindlabs/headlessui#1002]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v0.3.1

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/irvanherz/tailwind-dialog-bug

**Describe your issue**

I created 2 Tabs. In each pane, I put <Modal />  component which is a Dialog and a trigger button. 
Whenever I open and close that modal in a tab, I can't do same thing on another tab.

[Demo video](https://youtu.be/HvesL8tCVBM)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed if you install the latest version of Headless UI:
```sh
npm install @headlessui/react@latest
```
