### ISSUE TITLE
Feature: Stagger Appear for Transition.Child

### ISSUE THREAD

**Issue by mikehawkfish** [tailwindlabs/headlessui#101]
Hey Tailwind Team,

The `Transition` utility is really nice! I'm currently interested in the ability to stagger elements with `Transition.Child`.

I realize the lift on this might be tough but something like:

```jsx
<Transtion
  show
  appear
  stagger
  enter="transition duration-75 delay-100"
  enterFrom="opacity-0"
  enterTo="opacity-100"
>
<TranstionChild 
  enter="transition duration-75 delay-500"
  enterFrom="opacity-0"
  enterTo="opacity-100"
>
  I Will Wait until 100ms to begin my 500ms delay and animate in
</TranstionChild>

</Transition>
```

This probably goes into string parsing territory, but the API could allow for a prop to be passed down in this case.

What do you think? Possible?

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

I get that it might be handy, but I believe that this will do more harm than good. I think that this behaviour will be considered too "magic". As an alternatively, I would use a `delay-600` on the `Transition.Child` to get the same effect which will be way simpler and easier to reason about.

**Comment by mikehawkfish** [comment]
Hey thanks for the quick reply! I definitely hear you on adding complexity.

How would you handle a case where you have `n` children to render? 

It doesn't seem like it would be possible to dynamically apply transition delays unless you had it configured to generate those classes beforehand.

Thanks!

**Comment by JohnBDonner** [comment]
For anyone who comes here, you can accomplish this by dynamically adding the corresponding delay class via Tailwind v3 arbitrary values:

```typescript
const transitionDelayForN = (i: number) => {
  switch (i + 1) {
    case 1:
      return 'delay-[100ms]'
    case 2:
      return 'delay-[200ms]'
    case 3:
      return 'delay-[300ms]'
    case 4:
      return 'delay-[400ms]'
    case 5:
      return 'delay-[500ms]'
    case 6:
      return 'delay-[600ms]'
    case 7:
      return 'delay-[700ms]'
    case 8:
      return 'delay-[800ms]'
    case 9:
      return 'delay-[900ms]'
    default:
      return ''
  }
}
```

You could do the same in lower Tailwind versions without arbitrary values, by setting your values in your theme.

And ideally you'd be able to just do something like:
```typescript
const transitionDelayForN = (i: number) => `delay-[${(i + 1) * 100}ms]`
```

However there seems to be a bug with Tailwind v3's arbitrary values and string interpolation 🤷‍♂️
