### ISSUE TITLE
Running playgrounds from repo

### ISSUE THREAD

**Issue by corvino** [tailwindlabs/headlessui#1042]
I spelled this out in a discussion in November, but I am still seeing the same issue.

Essentially, the README doesn't specify how to install the dependencies or run the playgrounds.

That seems like it should be pretty straightforward, but it produces an error with exports between dependencies. It looks it might be a conflict with dependency versions. (I also tried deleting the yarn.lock before install decencies.)

### Discussed in https://github.com/tailwindlabs/headlessui/discussions/934

<div type='discussions-op-text'>

<sup>Originally posted by **corvino** November 16, 2021</sup>
I'm trying to run the React playground from the repo to play with component code (for potentially developing a new component the same way), but not having much success.

Trying to get started, I run (from the root of the repo):

```
yarn set version berry
yarn install
yarn react playground
```

and get the following error:

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/vino/code/opensource/headlessui/node_modules/next/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.552 (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __webpack_require__ (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.270 (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __webpack_require__ (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.327 (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __webpack_require__ (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.845 (/Users/vino/code/opensource/headlessui/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I've tried changing things a bit, trying to get various build scripts to run, and haven't had much success.

The due playground does run with `yarn react playground`, but I get the following error message:

```
[vite] Failed to resolve module import "@headlessui/vue/dist/index.esm.js". (imported by /src/components/menu/menu.vue)
```

Any advice would be appreciated. Is their a guide for developing and contributing?

Nathan</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I've added some contributing guidelines but currently they don't talk about the playgrounds itself. We use yarn 1, not berry, so that might be important as well.

We are considering of removing the playgrounds or moving them to somewhere else because those are just a small playgrounds to test things out in the browser and aren't that important to the project. It's also very low priority for us to maintain those, actual component development and bug fixes are way more important. So for that reason, I'm going to close this issue, hope you understand.

**Comment by corvino** [comment]
Thank you for the quick response.

Let me give you a quick description of what I'm trying to do, and maybe that can inform what is the best way to proceed.

I've got a project using React and headlessui that wanted to add an interface for mapping an item to a subset of a set of other items. Looking through the headlessui components, I thought Listbox was the closest fit, although it lacked a multi-select option like html select.

I thought adding support for multi-select to Listbox, or creating an additional component like Listbox but with multi-selection, where both viable options, and cloned the repo to evaluate. Modifying Listbox in-place seemed like great place to start, but since I couldn't run the playground to see the component on screen, it wasn't viable.

I tried copying Listbox and it's dependencies to my project to run and evaluate, but I ended up needing a lot of hooks that aren't exported outside the project. It looked like I could get this to work, but it required enough code duplication from the project that it started to feel unwise before I finished working out the details.

From my viewpoint, these seem advantageous for both the project and users:

- Support some form of easy build and run

  This could be simply instructions for how to clone the repo and link to it from another project using the preferred version tool. Reverse engineering this seems suboptimal; as we see above, I didn't determine the correct version of yarn. You probably do some version of this for your own development, so sharing instructions for your development setup would be very helpful.

- Support 3rd party components using all the headlessui infrastructure

  There appear to be a lot of hooks used across the components. Exporting them so that they are available would be helpful, even if it comes with the caveat that they aren't a stable api.

I'd be interesting in contributing code back to headlessui if any changes that were useful, but there is no way to do that development if I can't make changes to headlessui and see those reflected in a browser some how.

Thanks,
Nathan

**Comment by RobinMalfait** [comment]
@corvino I get what you are saying and we will improve upon your first point regarding the setup of the playground and stuff. But I can't promise you an ETA since this is a lower priority for us.

For your second point, we are very hesitant of exposing internal tools. Maybe if we have the time we can export _some_ tools/functions, but not our highest priority right now. The biggest issue is that once we do that, it becomes a public API that needs to be maintained and where we have to be very cautious about so that we don't introduce breaking changes because now a lot of people will be using those tools. We wrote more on this topic here: https://github.com/tailwindlabs/headlessui/pull/896#issuecomment-954098640
