### ISSUE TITLE
`<Transition appear={false} />` fails when coupled with `useEffect`

### ISSUE THREAD

**Issue by marksalpeter** [tailwindlabs/headlessui#1060]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.4.3

**What browser are you using?**
Chrome

**Reproduction URL**
[https://codesandbox.io/s/modest-euler-pmt7g](https://codesandbox.io/s/modest-euler-pmt7g?file=/pages/index.js)

**Describe your issue**
The `Transition` components `appear={false}` functionality fails if `useEffect(() => setState(...), [])` occurs in the component with the transition. This is very common behavior for components that load data from the server on mount.

**Comment by marksalpeter** [comment]
Quick update
I was able to wrap my animation component in `React.memo` and move the `useEffect` outside of the component. That seems to have fixed my issue. Maybe this is more of a documentation issue than a bug? Thoughts?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1179, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
