### ISSUE TITLE
[DOCS]: React.js Tabs - Missing disabled prop from Component API

### ISSUE THREAD

**Issue by a777med** [tailwindlabs/headlessui#1063]
The `disabled` prop is missing from the "Component API" section of the Tab component in React.js.
[https://headlessui.dev/react/tabs#tab](https://headlessui.dev/react/tabs#tab)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This should be fixed and will be live soon!
