### ISSUE TITLE
Missing 'transform' class breaks Modal (in Tailwindcss v3)

### ISSUE THREAD

**Issue by OmerWow** [tailwindlabs/headlessui#1075]
@headlessui/react

**What version of that package are you using?**

Latest, 1.4.3.
But i tried with any version starting from 1.2.0 and the bug was always there.

**What browser are you using?**

Safari & Brave (Chromium).
Both last few versions and always up-to-date.

**Reproduction URL**

I've tried for like an hour to get a coding site like CodeSandbox/CodePen/StackBlitz to work with Tailwind but for some reason I just couldn't get it to work. However it seems like a pretty simple problem so I'm just going to provide the code for the component and pictures in the description.

The code:
https://pastebin.com/35SFTxpq

And the unsuccessful attempt at creating CodeSandBox:
https://codesandbox.io/s/loving-noether-qw2t5

NOTE THAT THE CODE IN BOTH LINKS IS THE ONE THAT WORKS FINE AND INCLUDES THE TRANSFORM CLASS IN THE DIV ON LINE 36. REMOVE THIS CLASS FOR IT TO BREAK.

**Describe your issue**

OK so basically after a few days that the Modal in my project was misbehaving and downgrading many dependencies had no effect, I just decided to go through my comment history one by one, until I found the one where I deleted all of the 'flex' and 'transform' classes, alongside other changes and removals of changed/unnecessary classes in TailwindCSS v3.

As far as I can tell all of the changes in all 48 files went smoothly, only this little change in the Modal file was pretty much breaking it completely.

The class needs to be in the first div child of the Transition.Child component, on line 36.

This is how the modal SHOULD look like, when the first child div of the Transition.Child on line 36 HAS the 'transform' class:

![Screen Shot 2022-01-29 at 19 35 14](https://user-images.githubusercontent.com/12970637/151671588-e05fadd1-d9fe-4896-9e16-d1a1dbcac283.png)

And this is how it looks like when it's broken and the div doesn’t have the transform class:

![Screen Shot 2022-01-29 at 19 34 43](https://user-images.githubusercontent.com/12970637/151671502-51bae8fa-34a1-4a94-a097-86c0c33d7947.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a side effect of the `transform` class. It creates a new stacking context and if you delete it then it is gone. To fix this you can either add `relative` or `isolate` instead of the `transform`.

Made a note internally to document this in the docs / upgrade guide.
