### ISSUE TITLE
Typeahead search jumps back and forth between same items

### ISSUE THREAD

**Issue by LeanderG** [tailwindlabs/headlessui#1090]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

current master branch

**What browser are you using?**

Chrome, Firefox

**Describe your issue**

This PR https://github.com/tailwindlabs/headlessui/pull/1051 introduced a bug.

Let's take the example from the PR. We have 4 items in a menu:

- Alice
- Bob
- Charlie
- Bob

If you type Bob quickly it jumps from the first Bob to the second and back to the first. The expected behavior is that it should keep the first Bob selected. Only if you type b repeatedly slowly should it jump back and forth.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
