### ISSUE TITLE
Tabs: On updating the list of tabs and panels, the selected tab remains same, resulting in no panel being renedered on screen.

### ISSUE THREAD

**Issue by rumansaleem** [tailwindlabs/headlessui#1092]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.4.3

**What browser are you using?**

Firefox

**Reproduction URL**

[Code Sandbox Reproducible minimal example](https://codesandbox.io/s/filtering-headlessui-tabs-imjux?file=/src/App.js)

**Describe your issue**

Go to a tab that will be filtered out (in the above example any **even** tab), click on "Toggle Filter" button.  As soon as the panel is filtered out, No panel/tab is selected. No Tab is selected without any fallback. No Api to fallback, atleast not in docs.

**Comment by rumansaleem** [comment]
Found out we have a `selectedIndex` prop to bind to `Tab.Group` component. Apparently, not mentioned in the docs.

**Comment by livwvil** [comment]
I run into the similar issue. When I delete the last item in collection no one tab is selected and no panel is displayed after rerender. There is no fallback to defaultIndex tab. Is it correct  behaviour? I believe it should select last one or default tab.
