### ISSUE TITLE
Combobox Concerns

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/headlessui#1094]
Regarding https://github.com/tailwindlabs/headlessui/pull/1047

**What package within Headless UI are you using?**

@headlessui/react@insiders; Commit: 6fc28c610f14a3ab88a425cf97a67cee9bcb8e71 (third commit on Feb 2, 2022)

Chrome and Safari

**Reproduction URL**

[headless/packages/playground-react/pages/combobox/combobox-with-pure-tailwind](https://github.com/tailwindlabs/headlessui/blob/fbaa1ae9da8788910ce8b240851f9779630babcb/packages/playground-react/pages/combobox/combobox-with-pure-tailwind.tsx)

**Describe your issue**

1. We needed to add a z-index as the select menu was showing below other input fields on the screen.
2. It would be great if the search box was cleared when you reopen it after selecting an item from dropdown. I'm happy to make a quick video to demonstrate this. Via HeadlessUI's discussion board, I see other users are using https://react-select.com which behaves this way: (a) select United States via dropdown, (b) type in England to change my selection rather than (a) select United States via dropdown, (b) start typing England, (c) notice you get no results so you hit backspace a bunch of times until United States is no longer in the search field, (d) type England again.
3. Add `w-full` so the field matches the select menus on [tailwindui.com](https://tailwindui.com/components/application-ui/forms/select-menus).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your concerns!
Much appreciated! 🙏

Regarding point 1 and 3, Headless UI is headless and styling is completely up to you. The example in playground-react is just a basic example to play with it in the browser instead of in tests. This is not production ready code or anything like that. We will have proper components for it in Tailwind UI itself.

Regarding point 2, can you elaborate / create a video on what you mean exactly? I'm not entirely sure what you mean and the react-select doesn't seem to have a United States related dropdown (or at least I can't seem to find it 🤔)

**Comment by timomeh** [comment]
Regarding point 2, i noticed the same thing today and I think react-select offers a nicer UX here. I didn't find a way to implement the same behavior using Headless UI, it seems like the `Combobox.Input` always starts with adding the value to the input query.

react-select seems to solve this by overlaying the display value as an absolute positioned `div` above the input. The input itself is empty, and if a query is entered, the overlay is being hidden.

I made a quick video (hope you don't mind @ACPK – and I hope we mean the same thing 🙂 )

## Example using react-select

https://user-images.githubusercontent.com/4227520/153291221-1333eb7b-61f7-40a9-8b29-a4cfbbf85bc1.mp4


## Example using Headless UI

https://user-images.githubusercontent.com/4227520/153291249-bc0cab3e-9ed0-4cf3-b81f-645fe138a209.mp4

**Comment by ACPK** [comment]
@RobinMalfait - @timomeh Did a great job creating the videos and explaining it!

**Comment by RobinMalfait** [comment]
Aha I see what you mean. The thing is Headless UI is headless so it's a bit tough to do positioning like this for you. However, one thing you can do is apply `select-all` to the actual input. This will always select all the text when you focus the input or when you click it.

If everything is selected then you will be able to just type instead of removing your contents first.

Another potential solution is setting the placeholder text to the selected item but that might be not too great for accessibility reasons.

**Comment by RobinMalfait** [comment]
If you want to implement this behaviour yourself, you can also listen of focus / click events on the input if you want to. Here is an example: https://codesandbox.io/s/unruffled-sun-9oenil?file=/src/App.js:1726-1996

**Comment by lveillard** [comment]
@RobinMalfait  your solution is perfect!
Only thing i would love it to have is to open whenever is clicked, not only with the button. Struggling a bit but you already solved 99% of my use case thanks!

**Comment by Asifm95** [comment]
@lveillard You could try wrapping the `Combobox.Input` with `Combobox.Button` to open dropdown when input is clicked.

```
<Combobox.Button>
   <Combobox.Input>
</Combobox.Button>

```

**Comment by lveillard** [comment]
> @lveillard You could try wrapping the `Combobox.Input` with `Combobox.Button` to open dropdown when input is clicked.
> 
> ```
> <Combobox.Button>
>    <Combobox.Input>
> </Combobox.Button>
> ```

Awesome idea. A bit tricky to style but it kinda works.

**Comment by lveillard** [comment]
It actually adds events, for example whenever using the space keyboard. 
I really the default behaviour should be to open it if it was empty, and select the current text if it's not

**Comment by Asifm95** [comment]
You're right. You could work around that by adding a preventDefault on keyup event to the Input.

```
<Combobox.Button>
   <Combobox.Input onKeyUp={(event) => event.preventDefault()}>
</Combobox.Button>

```

Btw this just opens the dropdown on click regardless of the input being empty or not. If you want it to open only when empty, currently your best bet would be to make the `Combobox.Options` static & handle the state end events yourself.

**Comment by eakl** [comment]
> Regarding point 2, i noticed the same behavior today and I think react-select offers a nicer UX here. I didn't find a way to implement the same behavior using Headless UI, it seems like the `Combobox.Input` always displays the current value when the search query is empty.
> 
> react-select seems to solve this by overlaying the current value as an absolute positioned `div` above the input. The input itself is empty, and if a query is entered, the overlay is being hidden.
> 
> I made a quick video (hope you don't mind @ACPK – and I hope we mean the same thing 🙂 )
> 
> ## Example using react-select
>  ScreenShot.2022-02-09.at.22.11.25.mp4 
> ## Example using Headless UI
>  ScreenShot.2022-02-09.at.22.12.41.mp4

I second this feature request. I have played with both Headless UI and react-select. react-select is hard to style with tailwind but IMO this is the best UX for a combobox. It would be amazing to have such UX possibility. I have tried to build it but couldn't get the all event handlers to work nicely.

I have tried to add a div below the Combobox.Input with the last known selection but then it becomes hard to manage the input state which is reseted on selection change and the the div state which hold the value. Making the combobox a controlled component and managing all keyboard events is out of my current knowledge in React.
