### ISSUE TITLE
Can't change tab with Dialog inside of TabPanel

### ISSUE THREAD

**Issue by m-stilling** [tailwindlabs/headlessui#1100]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.4.3

**What browser are you using?**

Firefox 96.0.3

**Reproduction URL**

https://github.com/michal-cic/headless-ui-modal-issue

**Describe your issue**

If a `Dialog` with `isOpen = ref(false)` is placed inside of a `TabPanel`, switching to the dialog tab will prevent you from switching to other tabs. Looking at the trace, the focus trap seems to be switching back to the dialog tab immediately.

I can get around it by setting `:unmount="false"` on the `Dialog`, or setting `isOpen.value = false` on `mounted()`.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a very good bug report and a funny bug. I will get it fixed, thanks for notifying. Will explain more about this in my PR.

**Comment by RobinMalfait** [comment]
This should be fixed by #1149, and will be available in the next release.

You can already try it using `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
