### ISSUE TITLE
Remux run breaks after upgrading headlessui to v1.5

### ISSUE THREAD

**Issue by garth** [tailwindlabs/headlessui#1119]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.5

**What browser are you using?**

Firefox

**Describe your issue**

After updating to v1.5 there seem to be duplicate React imports generated in the remix build output.

The first import comes from remix

```js
import {
  React,
  __toModule,
  init_react,
  require_react
} from "/static/_shared/chunk-57HJTKFB.js";
```

Then later we have a conflict with this

```js
// node_modules/.pnpm/@heroicons+react@1.0.5_react@17.0.2/node_modules/@heroicons/react/outline/esm/AcademicCapIcon.js
init_react();
var React = __toModule(require_react());
```

Not really sure why it would be caused by a heroicon import, but as soon as I downgrade to `@headlessui/react@1.4.3` everything is fine again.

I guess this might have something to do with the move to esbuild?

**Comment by garth** [comment]
Just tested with yarn 1 just to be sure it wasn't related to pnpm. Also tried with  Remix v1.1 and v1.2 and the last couple of releases of esbuild just to be sure. In all cases the results were the same, there is only an import conflict when headlessui v1.5 is installed.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by garth** [comment]
In-case anyone else has this issue, I did some debugging and found some workarounds.

The issue seems to happen when your remix project uses both `@heroicons/react/outline` and `@heroicons/react/solid` in different components on the same page with `@headlessui/react@1.5.0`.

I found 2 workarounds:

1. Use either outline or solid, but not both - of course this means you don't get the exact icons you want

```diff
- import { MenuIcon, XIcon } from '@heroicons/react/outline'
+ import { MenuIcon, XIcon } from '@heroicons/react/solid'
```

2. import each icon individually - at least you get the icons you want

```diff
- import { MenuIcon, XIcon } from '@heroicons/react/outline'
+ import MenuIcon from '@heroicons/react/outline/MenuIcon'
+ import XIcon from '@heroicons/react/outline/MenuIcon'
```

I still couldn't find out why this issue only happens after `@headlessui/react` moved to esbuild, but at least you can continue using v1.5 features.
