### ISSUE TITLE
HeadlessUI is not working with Nextjs 12.1.0 

### ISSUE THREAD

**Issue by askemeline** [tailwindlabs/headlessui#1120]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**

```
  "dependencies": {
    "@headlessui/react": "^1.5.0",
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "^4.3.1",
    "tailwindcss": "^3.0.23"
  },
```
**What browser are you using?**

Chrome

**Describe your issue**

I follow the documentation to try with Next Js . Just copy paste this https://headlessui.dev/react/menu#integrating-with-next-js 
And it's not working I got this error.
Anyone got this error too ?

SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const {Fragment as Cr,createContext as lo,createRef as Ge,useCallback as B,useContext as ao,useMemo as oe,useReducer as Sr,useRef as He}from"react";import{useState as Yo,useEffect as Xo}from"react";function k(){let e=[],t=[],r={enqueue(o){t.push(o)},requestAnimationFrame(...o){let n=requestAnimationFrame(...o);r.add(()=>cancelAnimationFrame(n))},nextFrame(...o){r.requestAnimationFrame(()=>{r.requestAnimationFrame(...o)})},setTimeout(...o){let n=setTimeout(...o);r.add(()=>clearTimeout(n))},add(o){e.push(o)},dispose(){for(let o of e.splice(0))o()},async workQueue(){for(let o of t.splice(0))await o()}};return r}function Q(){let[e]=Yo(k);return Xo(()=>()=>e.dispose(),[e]),e}import{useState as tr}from"react";import{useLayoutEffect as Jo,useEffect as Zo}from"react";var x=typeof window!="undefined"?Jo:Zo;import{useState as er,useEffect as eo}from"react";var yt={serverHandoffComplete:!1};function q(){let[e,t]=er(yt.serverHandoffComplete);return eo(()=>{e!==!0&&t(!0)},[e]),eo(()=>{yt.serverHandoffComplete===!1&&(yt.serverHandoffComplete=!0)},[]),e}var or=0;function to(){return++or}function A(){let e=q(),[t,r]=tr(e?to:null);return x(()=>{t===null&&r(to())},[t]),t!=null?""+t:void 0}import{useState as ir}from"react";import{useRef as rr,useEffect as nr}from"react";function ke(e){let t=rr(e);return nr(()=>{t.current=e},[e]),t}function ee(e,t){let[r,o]=ir(e),n=ke(e);return x(()=>o(n.current),[n,o,...t]),r}import{useRef as lr,useEffect as ar,useCallback as sr}from"react";function I(...e){let t=lr(e);return ar(()=>{t.current=e},[e]),sr(r=>{for(let o of t.current)o!=null&&(typeof o=="function"?o(r):o.current=r)},[t])}import{Fragment as oo,cloneElement as ur,createElement as pr,forwardRef as dr,isValidElement as cr}from"react";function S(e,t,...r){if(e in t){let n=t[e];return typeof n=="function"?n(...r):n}let o=new Error(`Tried to handle "${e}" but there is no handler defined. Only defined handlers are: ${Object.keys(t).map(n=>`"${n}"`).join(", ")}.`);throw Error.captureStackTrace&&Error.captureStackTrace(o,S),o}function E({props:e,slot:t,defaultTag:r,features:o,visible:n=!0,name:i}){if(n)return _e(e,t,r,i);let a=o!=null?o:0;if(a&2){let{static:l=!1,...s}=e;if(l)return _e(s,t,r,i)}if(a&1){let{unmount:l=!0,...s}=e;return S(l?0:1,{[0](){return null},[1](){return _e({...s,hidden:!0,style:{display:"none"}},t,r,i)}})}return _e(e,t,r,i)}function _e(e,t={},r,o){let{as:n=r,children:i,refName:a="ref",...l}=gt(e,["unmount","static"]),s=e.ref!==void 0?{[a]:e.ref}:{},u=typeof i=="function"?i(t):i;if(l.className&&typeof l.className=="function"&&(l.className=l.className(t)),n===oo&&Object.keys(l).length>0){if(!cr(u)||Array.isArray(u)&&u.length>1)throw new Error(['Passing props on "Fragment"!',"",`The current component <${o} /> is rendering a "Fragment".`,"However we need to passthrough the following props:",Object.keys(l).map(c=>`  - ${c} = pkg;

**Comment by mohammadzolfali** [comment]
در تاریخ یکشنبه ۲۰ فوریهٔ ۲۰۲۲،‏ ۱۵:۲۱ Emeline Garo <
***@***.***> نوشت:

**Comment by simonswiss** [comment]
Hey!

Headless UI definitely works with Next.js 12.1.

Looks like you've pasted some minified code. Instead, please create a little GitHub repo where the issue you're describing is happening.

It's practically impossible to help you without this code repro. I'm going to close this issue, but feel free to re-open if you can provide a code example of your issue.

Thanks!
