### ISSUE TITLE
Combobox: Tabbing out reverts to the last selected item - clicking outside does not

### ISSUE THREAD

**Issue by ahoiroman** [tailwindlabs/headlessui#1136]
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

1.5.0

**What browser are you using?**

Safari

**Reproduction URL**

https://headlessui.dev/vue/combobox

**Describe your issue**

I mentioned this behavior: If I use a ComboBox to search for some item that does not exist (or I leave the field empty) and press tab, the last selected item is being reverted to the item that has been recently selected.

If I click outside, it is not, as you can see in this little screencast:

https://user-images.githubusercontent.com/23051150/155287085-57c96e72-54a3-4c1d-9c94-469b402c1420.mp4

**Comment by mohammadzolfali** [comment]
F5%7.%%7 g.

در تاریخ چهارشنبه ۲۳ فوریهٔ ۲۰۲۲،‏ ۱۲:۲۲ ahoiroman ***@***.***>
نوشت:

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1137, and will be available in the next release.

You can already try it using: 
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by ahoiroman** [comment]
Yep, works fine in the insiders preview.

Thanks!
