### ISSUE TITLE
[Bug]: Clicking elements outside Dialogs closes dialog

### ISSUE THREAD

**Issue by michael-vasyliv** [tailwindlabs/headlessui#1138]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.5.0

**What browser are you using?**
Chrome

**Reproduction URL**
https://n797o6.csb.app/

**Describe your issue**
Scenario: We have a HeadlessUI `Dialog` and `react-toastify`. When a dialog is open we click on a notification to close it but it also closes the dialog.
In my opinion, it will be easy to remove/disable [this listener](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L210)  and just use this
```
<Dialog.Overlay className="fixed inset-0 bg-black bg-opacity-50" onClick={closeThisDialogWithoutAnyFckPain} />
```
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L210

_I've tried the solution with `Portal` but it didn't help_

**Related issues**
https://github.com/tailwindlabs/headlessui/issues/780
https://github.com/tailwindlabs/headlessui/issues/432

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The Portal solution only works if **you** are in control of rendering the toast yourself AND if you render the Portal as part of the Dialog. Here is an updated codesandbox: https://codesandbox.io/s/lucid-hugle-vn8w52?file=/src/App.js

The Portal itself will still render it in the DOM in a portal root right underneath the `body`. But the nesting is important from React's perspective so that we can look at the React tree and communicate between the components via context.

**Comment by michael-vasyliv** [comment]
@RobinMalfait thank you for the idea but it does not help for a "real project", the problem is that basically `ToastContainer` is placed in the root app component while the `Dialog` is placed somewhere in deep, so adding `ToastContainer` for each `Dialog` is not a good solution.
So how can I disable https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L210

**Comment by aquaticone** [comment]
I'd also like to be able to disable the `mousedown` event handler.

There are a number of scenarios in which this global handling is problematic, including toasts.

**Comment by kennyyS** [comment]
Any news about that ?

**Comment by peterKaleta** [comment]
@RobinMalfait I'll agree with @michael-vasyliv here. The `<Portal>` solution is not really usable across bigger projects with generic use of `react-toastify`. The mousedown/implicit passing of closing method sounds good.

**Comment by connorlindsey** [comment]
Was running into the same problem except for a custom notification/toast component and found a solution that's working well for my app. I added a check to the `onClose` function and check if the notification component was clicked. In my case, I had to check the click events path to get it working. 

Depending on your app, you'll need to change the if statement, but hopefully it gives you an idea of how to solve this while still retaining the nice parts of detecting click outside.

```Modal.tsx
<Dialog ...
  onClose={(val) => {
    // Don't close if clicked on a notification
    if (event.path.some((elem) => elem.classList?.contains("notification"))) {
      return null
    }
    setOpen(val)
  }
...></Dialog>
```

**Comment by Aravinda93** [comment]
@connorlindsey @RobinMalfait 
I am facing the similar issue in my Headless UI Vue, can you please have a look and provide some solution?
Issue: https://github.com/tailwindlabs/headlessui/discussions/3199

[Minimal reproduction repo in CodeSandBox](https://codesandbox.io/p/devbox/admiring-bas-3kh2ws?embed=1&file=%2Fpages%2Findex.vue)
