### ISSUE TITLE
Tab index 0 is set on every radio input inside a popover when interacting via keyboard

### ISSUE THREAD

**Issue by rmales** [tailwindlabs/headlessui#1140]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.4.3

**What browser are you using?**

N/A

**Reproduction URL**

https://codesandbox.io/s/funny-field-zp1cie?file=/src/App.js

**Describe your issue**

When I have radio inputs inside a popover and I open the popover via the keyboard and tab to them, all the radio inputs have their tab index attribute set to zero. This inserts them into the tab order, which is not expected as groups of radio inputs are normally navigated using the arrows keys (as I'm sure you're aware). I guess this is more an annoyance than a bug.

**Comment by hodela** [comment]
I have the same problem, I have a registration form inside the dialog, when I enter "Nguyễn Hải" in the name input and press Tab key, the word "Hải" is immediately filled in the email input below and focus on the password input. I use a simple telex keyboard on my Mac

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1440, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
