### ISSUE TITLE
ComboBox: First key-down is being ignored

### ISSUE THREAD

**Issue by ahoiroman** [tailwindlabs/headlessui#1141]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

0.0.0-insiders.475568b

**What browser are you using?**

Safari

**Reproduction URL**

https://headlessui.dev/vue/combobox#keyboard-interaction

**Describe your issue**

If you tab into a combobox and start typing, the first keystroke is being ignored. This could be a bit annoying if the user is expecting a "typeahead" search.

In my demo video I typed "T", then the dropdown opened, and continued writing "est". The user would expect to see "Test", but it's only "est".

https://user-images.githubusercontent.com/23051150/155334019-18351c8f-68ad-4376-ab90-d6b3f031ef98.mp4

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently only an issue on the Headless UI docs because what happens is that the iframe is stealing focus and we return focus to the document. We are working on a demoMode so that this doesn't happen on the documentation site.

**Comment by ahoiroman** [comment]
Hmmm... It also happens on my web app. So either I got the same problem with stealing focus (but I don't use an iframe) or something else is going on.

**Comment by ahoiroman** [comment]
But the hint regarding the focus is great. I am evaluating this, so thanks for your response - I really appreciate your work :-)

**Comment by dbousamra** [comment]
I have the same issue

**Comment by RobinMalfait** [comment]
@dbousamra please open a new issue with a minimal reproduction repo attached or a CodeSandbox that showcases the issue.
