### ISSUE TITLE
`ComboboxOptions` is not hidden when `ComboboxInput` is blurred

### ISSUE THREAD

**Issue by MaximeWillinger** [tailwindlabs/headlessui#1147]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Brave, Safari

**Reproduction URL**

https://codesandbox.io/s/hardcore-hofstadter-mwq85g

> _If you get the error "Cannot use import statement outside a module", just click on the "reload" button._
> _It's a  [known CodeSandbox issue.](https://github.com/codesandbox/codesandbox-client/issues/5464)_

**Describe your issue**

The `ComboboxOptions` component is - sometimes - not hidden when the `ComboboxInput` is blurred.

**Steps to reproduce**

- Click on the left input (the `ComboboxInput`)
- Type a letter, for example "a" in order to open the `ComboboxOptions`
- Press tab to focus the next input

The `ComboboxOptions` should disappear, but it remains visible instead.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Hmm very odd, I can reproduce it so will take a look. Thanks!

**Comment by RobinMalfait** [comment]
This should be fixed by #1148, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
