### ISSUE TITLE
Feature Request: Add onClose prop to Menu component

### ISSUE THREAD

**Issue by stevecastaneda** [tailwindlabs/headlessui#115]
On occasion, I'd like to be able to run a function when a menu or dropdown closes.  I was hoping we could do something like:

```
<Menu onClose={() => handleMenuClose()}>
...
</Menu>
```
Where `onClose` is of type `() => void`.  Or is there another way to do this that will support the current API without changes?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

@stevecastaneda what is the exact use case for this? Because there are currently a few ways to "close" a Menu.

1. When you click outside the Menu
2. When you click on a Menu Item
3. When you click the Menu Button again
4. When you press `esc`

If your use case is: "I want to do something when a `Menu Item` is clicked", then you can add an `onClick` on the actual `Menu Item`.
I'm just trying to understand what some useful use cases are.

**Comment by stevecastaneda** [comment]
In my particular use case, I have a reducer function that is called when an item is clicked and I only update the database (Firestore) when I think the user is done making quick adjustments to the state.

1. When an input is blurred
2. When a dropdown is blurred (or open is now false)

So for me, it's knowing when to synchronize a local state with the backend (Firestore).  For a Dropdown, that's when open goes from true to false, so I can check to see if the database needs to be sync'd.

I have a feeling there is a better way to do this though.  For now, I'm using a ref to watch for when the local state is updated and when I need to update the database, bypassing the need for an `onClose` prop for the menu.  Perhaps this is the better way to go?

**Comment by RobinMalfait** [comment]
Hey @stevecastaneda 

I think it is indeed better to do your action when you click an item. If you do this when the Menu closes, then you can have the potential issue that the user never closed the Menu and closes the browser tab (aka, your call is never executed).

Also currently inputs are not really supported inside the `Menu` (you can't tab to it).
Additionally, when you click an item, the Menu should close automatically (unless you used an `as={MyComponent}` prop and didn't forward all the props to your MyComponent itself), if this is not the case, then we probably have a bug 😅.

Going to close it for now, maybe we can implement it later if it is really needed. Thanks for the suggestion!

**Comment by stevecastaneda** [comment]
Sounds good - didn't think of all those cases.  Appreciate it, sir!

**Comment by jeffminsungkim** [comment]
@RobinMalfait Is there any way to detect the menu is closed? For instance, the user clicks the body of the page while the menu is still stay open.
