### ISSUE TITLE
@change does not work with Combobox (VueJs)

### ISSUE THREAD

**Issue by james-wong123** [tailwindlabs/headlessui#1171]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

 v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

```
<Combobox
     v-model="selectedPerson"
     @change="window.location.href = selectedPerson.url"
     as="div"
>
          <ComboboxInput  
                    placeholder="Search..."
                    @change="query = $event.target.value"
                    :displayValue="(person) => person.name"
          />
          <ComboboxOptions
                     static
                              >
                    <ComboboxOption
                               v-slot="{ active }"
                               v-for="person in filteredPeople"
                               :disabled="person.unavailable"
                              :key="person.id"
                               :value="person"
                                            >
                    </ComboboxOption>
          </ComboboxOptions>

<Combobox/>

```
When there are actions like `click` or `enter` to the ComboxOption, the value in `v-model="selectedPerson"`  changed,.
I used `@change` to catch all those changes and redirect the window to the respective `URL`

But it does not seem to be working, nothing happened after `clicking `or `entering`

> Before `clicking `or `entering` 
![image](https://user-images.githubusercontent.com/87692325/156141059-3339c14f-e211-4638-bec6-c62ad1552b36.png)

> After`clicking `or `entering` 
![image](https://user-images.githubusercontent.com/87692325/156141357-1062f772-eb59-41ab-8cdb-bbe16d43ee11.png)

**Comment by adamwathan** [comment]
Think I'm seeing this as well, here's a little video to help @RobinMalfait or @thecrypticace when they see this:

https://user-images.githubusercontent.com/4323180/156177508-74a38cd1-0ff1-4688-ade3-0e2c9b1f1ddd.mov

And a link to a reproduction:

https://stackblitz.com/edit/vue-tgcptx?file=public%2Findex.html

**Comment by thecrypticace** [comment]
In Vue we use v-model instead of custom props and events. To react to changes without using `computed`, `watch`, etc… you need to use the same event used by v-model: `update:modelValue`. 

Which. means the code above should be written as:
```html
<Combobox
  v-model="selectedPerson"
  @update:modelValue="window.location.href = selectedPerson.url"
  as="div"
>
  …
</Combobox>
```

Link: https://stackblitz.com/edit/vue-sv3ctl

Aside:
1. @adamwathan apparently `console.count()` doesn't work on StackBlitz console.
2. Should we add a change event just to more closely match the API of the React component? It's not idiomatic Vue but it might still be a better DX.

**Comment by james-wong123** [comment]
Thx @adamwathan & @thecrypticace for replying to this, totally appreciated from the deep of my heart!

@thecrypticace 's method worked well.

And I noticed that headlessui@vue is missing an `onchange` props.

**Comment by thecrypticace** [comment]
Ah, excellent. Glad that worked!

> And I noticed that headlessui@vue is missing an `onchange` props for `Combobox`

Given that we're relying on v-model and it's events the `Combobox` indeed does not have an `onChange` prop / event but `onUpdate:modelValue` as described above — though technically it is specified in `emits` not `props` but it functions the same. We've decided to stick with the `onUpdate:modelValue` / `@update:modelValue` event setup we're currently using but will look at calling this out explicitly in the docs. Thanks!

**Comment by james-wong123** [comment]
@thecrypticace Just an add on question for `ComboboxInput`,  a lot of people has been asking this question recently.

How can we `clear` or `overwrite` the `ComboboxInput` ? In the following sample, there's a close button to clear and delete all the values in the `ComboboxInput`. But have no idea how to do it.

```
<ComboboxInput
         placeholder="Search..."
         @change="query = $event.target.value"
         :displayValue="(person) => person.name"
         />
         <div
              @click="query = ''"
              class="cursor-pointer"
              v-show="query"
         >
             <span class="sr-only">Close button</span>
             <svg
             </svg>
         </div>
</ComboboxInput>
```


![image](https://user-images.githubusercontent.com/87692325/156260774-b7646d41-57de-4889-bfc5-0f26dc9b0961.png)

**Comment by thecrypticace** [comment]
In the latest insiders build the input is cleared when you clear the value used by v-model.

**Comment by james-wong123** [comment]
@thecrypticace But then is just a regular input, is not selecting anything.

**Comment by james-wong123** [comment]
Thx @thecrypticace, I solved this by 

```
clearInput() {
                query.value = "";
                selectedPerson.value = {
                    id: null,
                    name: "",
                    field: "",
                    method: "",
                    unavailable: false,
                    url: "",
                };
            },
```

**Comment by james-wong123** [comment]
@thecrypticace Not sure if there is a way to display activeOption in the ComboboxInput?
