### ISSUE TITLE
[BUG] Touch event does not close an open Popover on iOS

### ISSUE THREAD

**Issue by ddahan** [tailwindlabs/headlessui#1173]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.5.0 (with Vue v3.2.26)

**What browser are you using?**
Chrome/Safari on iOS

**Reproduction URL**
https://stackblitz.com/edit/vue-ykt4oa?file=src/App.vue

**Describe your issue**
When using a simple headlessUI Popover component:
- On desktop (macOS + all major browsers), it works as expected: when I click outside the open popover, it disappears.
- However, on iPad/iOS (tested with Chrome and Safari), when I *touch* outside of the open popever, it does NOT disappear.

I made a [stackblitz](https://stackblitz.com/edit/vue-ykt4oa?file=src/App.vue) to show the issue (to be opened with an iOS touch device to actually see the issue)

**Additional notes**

- The issue is similar if I use a Menu component.
- I'm already aware of [this similar issue](https://github.com/tailwindlabs/headlessui/issues/919) but decided to create a new one as it may not be the same case since the OP has resolved its issue by upgrading to a new Headless UI version, not me.

**Comment by oberocks** [comment]
I can second this one with @ddahan . Have confirmed this issue to exist/persist on iPad iOS and iOS Safari.

**Comment by oberocks** [comment]
@ddahan PS - just so it's not missed and in case you are still having trouble - pls see a fix for your Popover/v-click-to-close situation https://github.com/tailwindlabs/headlessui/issues/919#issuecomment-1055338173

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by sornt** [comment]
@RobinMalfait Thank you so much. It is working!!!
