### ISSUE TITLE
[Vue] ComboboInput can't display actionOption

### ISSUE THREAD

**Issue by james-wong123** [tailwindlabs/headlessui#1195]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

**Describe your issue**
ComboboInput does not seem to be able to display `actionOption` 

```
<Combobox
      v-model="selectedPerson"
      v-slot="{ activeOption }"
>
   <ComboboxInput
         @change="query = $event.target.value"
         :displayValue="
                            () => {
                                activeOption.name
                            }
                            "
    ></ComboboxInput>

    <div v-if="activeOption">
          The current active user is: {{ activeOption.name }}
     </div>
```

![image](https://user-images.githubusercontent.com/87692325/156853161-c4f2313c-ef89-4c3d-9179-aca03621cc95.png)

when the option is being selected, the bottom div show

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We only sync the input with the `selected` option, not with the `active` option. One thing to keep in mind is that your `displayValue` isn't returning anything, so make sure to return the string version of your `selected` option. 

If you also want to sync the `active` option (meaning, when you use your arrow keys or mouse) then you can set the value like `:value="activeOption?.name"`.

Hope this helps!
