### ISSUE TITLE
[React][Combobox] Unexpectedly clears when clicking outside Combobox.Input

### ISSUE THREAD

**Issue by cabello** [tailwindlabs/headlessui#1197]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

Is there a code sandbox sample I can leverage to demonstrate it?

**Describe your issue**

I have a ComboBox with a icon besides it, clicking the icon or any other thing clears the ComboBox

In the following screenshot I had `cam` typed in the input and I clicked somewhere that did not close the Dialog that I have but not the input and it cleared.

<img width="788" alt="Screen Shot 2022-03-04 at 10 34 40 PM" src="https://user-images.githubusercontent.com/60936/156866315-8aa226e7-33c2-4125-8f59-e5caeda634e1.png">

```jsx
<div className='tw-flex tw-items-center tw-px-4'>
  <FontAwesomeIcon icon={faSearch} className='tw-text-gray-500' />
  <Combobox.Input
    value={query}
    onChange={(event) => {
      setQuery(event.target.value);
    }}
    className='tw-w-full tw-bg-transparent tw-border-0 focus:tw-outline-none tw-text-sm tw-text-gray-800 placeholder:tw-text-gray-400 tw-h-12 tw-px-2'
    placeholder='Search...'
  />
</div>
<Combobox.Options
  static
  className='tw-py-4 tw-text-sm tw-max-h-60 tw-overflow-y-auto'
>
....
</Combobox.Options>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

When you click outside the Combobox, then the Combobox will close. It will also re-sync the input. This means that it will either remove any searched contents, or re-set it to the currently selected value.

Currently in your screenshot it doesn't look closed because you used the `static` prop. More information on that topic can be found here: https://headlessui.dev/react/combobox#showing-hiding-the-combobox

**Comment by cabello** [comment]
@RobinMalfait appreciate the reply, thank you 🙇 

Does that mean I can't keep the value `cam` in the input if using a Combobox? I explicitly set the `value={query}` but whe it. "closes" (it doesn't because it's `static` right now), it clears the value, not sure how I can leverage `open` to keep the value in the `Combobox.Input`.

**Comment by Yankovsky** [comment]
@RobinMalfait I have the same problem. I want to leave the entered value in the input even if the combobox is closed. Any way to achieve that?

**Comment by christophershi** [comment]
@cabello @Yankovsky 

to leave the value in the ComboBox.Input when you click/tapout/blue the ComboBox, add the `displayValue` property to ComboBox.Input:

```
<Combobox.Input
  onChange={(event) => setQuery(event.target.value)}
  displayValue={(_) => query}
  value={query}
/>
```
or

```
<Combobox.Input
  onChange={(event) => setQuery(event.target.value)}
  displayValue={(person) => person.name}
  value={query}
/>
```

more info here: [https://headlessui.com/react/combobox#combobox-input](https://headlessui.com/react/combobox#combobox-input)

hope this helps someone, I dealt with this today!

**Comment by lordvcs** [comment]
if the above comment is not working and if you are working based on the example given on the headless UI site, make sure to delete `afterLeave={() => setQuery("")}` on the Transition element
