### ISSUE TITLE
Trigger the Menu to close

### ISSUE THREAD

**Issue by nath-green** [tailwindlabs/headlessui#120]
Hello, great work on this library!

I've implemented the `Menu` component in a NextJS project - all working fine. I'm wondering if there is ability to close the menu without a click, say when you change a route?

If the close action can be exposed then this could be called on route change.

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

I'm trying to understand why this isn't working already? If you click a link to change a route, then it should already close because it is considered an "outside click". Are you doing programatic redirects without any user interaction at all?

**Comment by nath-green** [comment]
I'm clicking a link inside the menu using NextJS `<Link>` component which just renders as an `<a>`, the route changes but the menu stays open. It could be a NextJS thing? Unsure if you have tried this library with that before?

**Comment by RobinMalfait** [comment]
Sorry for the late answer!

I think that the `Link` component of Next is not forwarding all the props. Can you try to use something like this:

```js
function NextLink(props) {
  const { href, children, ...rest } = props;
  return (
    <Link href={href}><a {...rest}>{children}</a></Link>
  )
}
```

You can then use it as:

```js
<Menu.Item as={NextLink}>...</Menu.Item>
```

**Comment by nath-green** [comment]
That has worked! Thank you very much for your help

**Comment by RobinMalfait** [comment]
Perfect!

**Comment by mathiassdev** [comment]
> Sorry for the late answer!
> 
> I think that the `Link` component of Next is not forwarding all the props. Can you try to use something like this:
> 
> ```js
> function NextLink(props) {
>   const { href, children, ...rest } = props;
>   return (
>     <Link href={href}><a {...rest}>{children}</a></Link>
>   )
> }
> ```
> 
> You can then use it as:
> 
> ```js
> <Menu.Item as={NextLink}>...</Menu.Item>
> ```

I was trying using it like described, but it wouldn't let me. Can you elaborate on what to insert in the `<Menu.Item as={NextLink}>...</Menu.Item>` to get it to work?

**Comment by RobinMalfait** [comment]
@mathiassdev I think that it would be easier if you open a new issue with a minimal reproduction repository, the current behaviour (and/or errors) and the expected behaviour.
