### ISSUE TITLE
onChange type for `ListBox` is incorrect

### ISSUE THREAD

**Issue by aequasi** [tailwindlabs/headlessui#121]
Because the listbox uses the props from the TTag as well, the TTag `onChange` type is overwriting the `onChange(value: TType): void` type

![image](https://i.imgur.com/k4zt8cb.jpg)

**Comment by Akirtovskis** [comment]
Facing the same issue!

**Comment by afmelo92** [comment]
How do you handle this? I'm having the same issue and can't find a decent answer.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This will be fixed in the next version.

You can already test it when using the dev channel `yarn add @headlessui/react@dev`
