### ISSUE TITLE
[Bug] Input autofill when Tab key is pressed on Mac using Simple Telex keyboard

### ISSUE THREAD

**Issue by hodela** [tailwindlabs/headlessui#1215]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.4.3

**What browser are you using?**

Chrome

**Reproduction URL**
https://codesandbox.io/s/headlessui-popover-form-jrkcq5?file=/src/App.js

**Describe your issue**

Use the Simple Telex keyboard on your Mac and type "hair" (it will become "hải") into the Name input and press the Tab key.
**Expectation**: Focus on the Email input
**Reality**: The word "hải" automatically fills in the Email input and focuses on the Address input
<img width="452" alt="Screen Shot 2022-03-09 at 10 52 29" src="https://user-images.githubusercontent.com/23092568/157369518-1b7ab7bf-0fff-4655-b124-f8932cb9bdd0.png">
<img width="452" alt="Screen Shot 2022-03-09 at 10 52 45" src="https://user-images.githubusercontent.com/23092568/157369524-1fde7263-0383-4315-95da-060112226c0f.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1440, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
