### ISSUE TITLE
Menu Items with Popper modifications stopped working

### ISSUE THREAD

**Issue by neoighodaro** [tailwindlabs/headlessui#1222]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.5.0

**What browser are you using?**
Chrome

**Reproduction**
Run Playground Example (menu items with Popper): [packages/playground-vue](https://github.com/tailwindlabs/headlessui/tree/main/packages/playground-vue)

**Describe your issue**
Previously, the Popper modifier was working correctly [using the hook](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/playground-utils/hooks/use-popper.js) but recently it does not work anymore. Just a minor investigation shows that [line 16](https://github.com/tailwindlabs/headlessui/blob/07c3a61b5c4f049d0818afad074eb665ed4e2e4b/packages/playground-vue/src/playground-utils/hooks/use-popper.js#L16) and 17 do not return `HTMLElement` anymore. So the `createPopper` call is not made at all.

Not entirely sure what to report it as since the actual component seems to work, but the example does not work anymore, thus no easy (or documented) way to modify the underlying Popper. Perhaps it just needs to be updated.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1230, and will be available in the next release.

You can already try it using `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
