### ISSUE TITLE
[React][Combobox] selected prop always returns false for dynamic objects

### ISSUE THREAD

**Issue by garth** [tailwindlabs/headlessui#1224]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.5.0

**What browser are you using?**

FireFox

**Describe your issue**

Where the list of items is a dynamically generated list of objects, the combobox uses a `===` comparison which will always be false. This could be fixed by adding the option to pass a comparison function so that we can compare by id or similar.

**Example**

To reproduce, replace the `const filteredPeople ...` from the docs with the following:

```ts
import Fuse from 'fuse.js'

//...

  const fuse = useMemo(() => new Fuse(people, { keys: ['name'] }), [people])
  const filteredPeople = query === '' ? people : fuse.search(query).map(({ item }) => item)

//...
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

In this case it depends on where the `people` variable is coming from. If that is defined within the component itself, then every render each object will have a new identity and the `===` will fail. I'm not sure if Fuse mutates the internal objects or not which can also lead to a new reference.

Instead, you can use a unique primitive as the value. E.g.: `<Combobox.Option value={person.id} />`

**Comment by garth** [comment]
Would you accept a PR with an optional compare fn prop?
