### ISSUE TITLE
[Combobox] Out of order when using arrows

### ISSUE THREAD

**Issue by cabello** [tailwindlabs/headlessui#1234]
**What package within Headless UI are you using?**
**What version of that package are you using?**

"@headlessui/react": "^1.5.0",

**What browser are you using?**

Chrome

**Reproduction URL**

Not available.

**Describe your issue**

I am building a command palette **heavily** inspired by the official Tailwind Labs channel https://www.youtube.com/watch?v=-jix4KyxLuQ

I noticed while filtering commands using a search mechanism that it's easy to get in a place where down arrow / up arrow go into items out of order (first 1/3 of the video), typing more things that cause the conditional render to change eventually fix the behaviour (remaining 2/3 of the video). 

https://user-images.githubusercontent.com/60936/157751106-ca3110f6-2488-4424-8e2c-d42eb1ae00c9.mp4

The key portion of the conditional rendering:

```jsx
{filteredCommands.length > 0 && (
    <Combobox.Options
    static
    className='tw-py-4 tw-text-sm tw-max-h-[13.5rem] tw-overflow-y-auto'
    >
    {filteredCommands.map((command: Command) => (
        <Combobox.Option
        key={command.item.id}
        value={command.item.id}
        >
        {({ active }) => (
            <div
            className={`tw-flex tw-flex-row tw-px-4 tw-py-2 ${
                active ? 'tw-bg-amber-400' : 'tw-bg-white'
            }`}
            >
                {command.item.label}
            </div>
        )}
        </Combobox.Option>
    ))}
    </Combobox.Options>
)}
{filteredCommands.length === 0 && query.length > 0 && (
    <div className='tw-p-4 tw-text-gray-500'>
    <FormattedMessage defaultMessage='No results found.' />
    </div>
)}
{filteredCommands.length === 0 && query.length === 0 && (
    <div className='tw-p-4 tw-text-gray-500'>
    <FormattedMessage defaultMessage='No commands available in this context.' />
    </div>
)}
```

As you can see there is nothing crazy special about it.

Thank you making headless ui open source and sharing with me 💜

**Comment by cabello** [comment]
I believe I found a way to fix it by making the key of the options dependent on the search query:

```
<Combobox.Option
  key={`${query}-${command.item.id}`}
  value={command.item.id}
>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The key depending on the `query` should not be necessary. This will cause unnecessary unmounts/mounts and might degrade performance. 

I would suggest to just `key={command.item.id}`.

This is indeed a bug in the current version, but the `insiders` build should work for you without the `query` inside the key.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
