### ISSUE TITLE
Question: Ideas on transitioning height with <Transition />?

### ISSUE THREAD

**Issue by samselikoff** [tailwindlabs/headlessui#126]
I know CSS doesn't let you transition `height: 0` to `height: auto` so just curious if you've thought about any ways to accomplish this with the `<Transition />` component.

I was thinking of bringing in a hook to calculate the final height of the DOM node but then I think I'd need another API to pass it to `<Transition />`, maybe `enterToStyle`?

```js
<Transition
  show={open}
  enter="transition ease-out"
  enterFrom="transform h-0 opacity-0"
  enterTo="transform h-40 opacity-100"
  enterToStyle={{
    height: finalHeight
  }}
>
```

Something like this. Any thoughts?

**Comment by samselikoff** [comment]
I tried using `max-w-0` to a larger number and that worked but, is not great because the easing + duration doesn't line up with the content. I think you need to use JS to calculate the final height.

**Comment by samselikoff** [comment]
This is headlessui/react btw.

**Comment by adamwathan** [comment]
From our perspective the Transition component really only exists so we have a story for Tailwind UI customers who want to do enter/leave transitions based on Tailwind classes like customers who use Vue or Alpine can. If you want to do JS-based transitions there are way better tools for that, like Framer Motion.

We use Framer Motion ourselves for any React stuff we do even. We definitely aren't interested in competing there, that tool is incredibly good and I'm grateful we don't have to solve that problem 😅

**Comment by samselikoff** [comment]
Gotchu, makes sense! Will try

**Comment by samselikoff** [comment]
More just curious your thinking on where Headless UI fits into a React/SPA devs toolkit

**Comment by thien-do** [comment]
Hey guys, I actually found a way to animating "height" using Tailwind and HeadlessUI's Transition component :D the key is to programmatically set the height before the animation happens:

```css
.height-0-important {
  height: 0 !important; /* to win the inline style we set */
}
```

```jsx
<Transition
  enter="transition, you know the stuff"
  enterFrom="height-0-important"
  enterTo="" /* don't need this! */
  beforeEnter={() => {
	  const elm = panel.current; /* React's ref */
	  elm.parentElement.style.height = `${elm.clientHeight}px`;
  }}
>
  <Disclosure.Panel ref={panel}>
    {props.item.answer}
  </Disclosure.Panel>
```

**Comment by farmerpaul** [comment]
Here's my TypeScript-friendly version of @thien-do's suggested implementation (brilliant, @thien-do!) with the addition of the following:
- included the leave transition
- content height will continue to resize appropriately based on its content and container/window after transition is complete
- updated for Tailwind 3

```tsx
  const ref = useRef<HTMLDivElement>(null);
  const [shown, setShown] = useState(false);

  const captureHeight = () =>
    ref.current && (ref.current.style.height = `${ref.current.clientHeight}px`);
  const clearHeight = () => ref.current && (ref.current.style.height = '');

  return (
    <Transition
      ref={ref}
      show={shown}
      enter="transition-[height] duration-300 overflow-hidden"
      enterFrom="!h-0"
      beforeEnter={captureHeight}
      afterEnter={clearHeight}
      leave="transition-[height] duration-300 overflow-hidden"
      leaveTo="!h-0"
      beforeLeave={captureHeight}
      afterLeave={clearHeight}
    >
      <div>Some variable height content</div>
    </Transition>
  );
```
