### ISSUE TITLE
[DOCS]: Page meta title incorrectly implemented

### ISSUE THREAD

**Issue by davidluhr** [tailwindlabs/headlessui#1266]
### Issue
When leaving the mouse idle on a documentation page's main content, a `title` attribute tooltip appears unexpectedly. Additionally, the page's tab title does not change when navigation the documentation site.

### Cause
This is caused by an accidental `title` attribute on the `<main>` element for each page.

### Solution
I believe this was originally intended to be the meta `<title>` tag in the `<head>`. A quick template update should fix this.

**Comment by adamwathan** [comment]
Ah yikes good catch, should be fixed now! Thanks @davidluhr!
