### ISSUE TITLE
Combobox: Shift+Tab triggers option submit

### ISSUE THREAD

**Issue by max-sym** [tailwindlabs/headlessui#1288]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`^1.5.0`

**What browser are you using?**

`Google Chrome`

**Reproduction URL**

https://codesandbox.io/s/happy-alex-1ewcf2?file=/src/App.tsx

**Describe your issue**

I want to make it so that my React form inputs are accessible using keyboard navigation (specifically, `tab` and `shift+tab` keys).
Currently I make it so that when the option of the combobox is selected, the focus would shift to the next form input.
When I use `tab` key everything works fine, but whenever it is `shift+tab` (which is usually expected to navigate back) would also trigger the `onChange` on the Combobox root.

Steps to reproduce in the example above:
- Click on the first input;
- Use keyboard arrows to select the option `b` and press `Enter` or `Tab`;
- Notice that the focus would shift to the second input (as expected);
- Use arrows to go to any option, but instead of pressing `Enter`, press `Shift+Tab`;
- **Notice that the focus goes to the previous element, but also that the option in the second input got set. Should that happen? Usually `shift+tab` is used to go back and here it would make sense to cancel the action of setting the option value on the second combobox.** 

Is it possible to make it so that `shift+tab` doesn't submit the action described above? Thanks!

**Comment by lveillard** [comment]
Hello! For me it makes sense to commit on shift+tab, is the behaviour I would expect. But i guess you could set up a custom behaviour for that combination of keys 🤔

**Comment by max-sym** [comment]
I don't see how it could be done since it seems to be hardcoded in the component itself.
Shift+Tab is usually for "Going Back", no? And tab is to "Move Forward" / "Go to next input" / "Submit"

**Comment by lveillard** [comment]
From my point of view, in the same way that the input changes are commited pressing TAB, they should do the same while pressing SHIFT+TAB, which is the behavioir by default here.

To customize the keys events, I never tried it with this component, but maybe something like this? https://stackoverflow.com/questions/56336479/how-to-do-event-stoppropagation-to-react-select-input-field-when-arrow-keys-an

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently working as expected, we are using the WAI ARIA best practices as a guide where we also make certain decisions on how the behaviour works. The WAI ARIA best practices have an example where this behaves the same as ours: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-select-only.html

That said, as long as the combobox is not in an open state, tabbing "backwards" doesn't change the actual value. If the combobox is open, then by default the selected item will be the active one, so pressing shift+tab is also a no-op. If the combobox is open, and you made a change, then the change would be applied on either tab or shift+tab. You can always press escape to close and reset the value.

Currently we don't have any plans to change this behaviour or provide an option.
