### ISSUE TITLE
[BUG] Cannot set properties of undefined (setting 'inputPropsRef')

### ISSUE THREAD

**Issue by agtabesh** [tailwindlabs/headlessui#1289]
I'm using `@headlessui/vue` within a `nuxtjs v3` project. When I build and run the project in production, I get error: `Cannot set properties of undefined (setting 'inputPropsRef')`.

As a notice, I'm using the latest version of all packages. It's a bit weird as there isn't any documentation nowhere!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We've seen similar issues before, which are Nuxt issues while using SSR (the browser should work fine): https://github.com/tailwindlabs/headlessui/issues/982#issuecomment-1026007771

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
