### ISSUE TITLE
"provide() can only be used inside setup()." when using custom UI library built by tailwind CSS, headlessui, Vue 3.2.25, Vite

### ISSUE THREAD

**Issue by tewshi** [tailwindlabs/headlessui#1296]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Describe your issue**

I've build UI library for company and used tailwindui components that contains the headlessui components.
Library itself is built well and storybook shows what I need to get but when I use it on my other project as library, it shows the warnings and errors.

`provide() can only be used inside setup().`
`inject() can only be used inside setup() or functional components.`
`Uncaught TypeError: Cannot read properties of undefined (reading 'buttonRef')`

**Comment by tewshi** [comment]
I've removed node_modules folder and reinstalled it, and everything works now.

**Comment by bengreenbank** [comment]
I am also experiencing this error. The component works fine when it is included directly in my project, however, when imported from my Vite component library it throws these errors.

Here are the dependencies in my library:
```
  "dependencies": {
    "@headlessui/vue": "^1.6.1",
    "vue-cookies": "^1.8.1",
    "vue": "^3.2.33"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.3.1",
    "vite": "^2.9.7"
  },
```

**Comment by loeffel-io** [comment]
same here!
