### ISSUE TITLE
Question: how does/will this integrate with Tailwind UI?

### ISSUE THREAD

**Issue by fergusmeiklejohn** [tailwindlabs/headlessui#13]
Is this a dependency of Tailwind UI? How would early adopters of TailwindUI use this today?

**Comment by RobinMalfait** [comment]
You can look at one of the codesandboxes mentioned in the readme (they use this library + Tailwind UI).

Long story short, you `npm install @headlessui/react` for example, and attach the classes you want from Tailwind UI. This library doesn't render anything and accepts classes so you can do whatever you want with it.

I hope this answers your question!
