### ISSUE TITLE
Missing Unique 'key' Prop

### ISSUE THREAD

**Issue by 3200pro** [tailwindlabs/headlessui#1306]
Package: @headlessui/react 
V: ^1.5.0
Browser: Chrome

**Describe your issue**

I'm getting an error within the development and production build:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Ye`. It was passed a child from Navigation. See https://reactjs.org/link/warning-keys for more information.
    at div
    at Ye (webpack-internal:///./node_modules/@headlessui/react/dist/headlessui.esm.js:21:27871)
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
