### ISSUE TITLE
`Active` state in components are returning true on element hover

### ISSUE THREAD

**Issue by Snazzie** [tailwindlabs/headlessui#132]
The `Active` state inside your componenets are returning true when cursor is hovered over the element.

### Snippet of code

```
{({ active }) => (
            <a className={`${active && 'bg-blue-500'}`} href="/account-settings">
              Account settings
            </a>
          )}
```

**Comment by RobinMalfait** [comment]
Hey!

I'm not sure if you are talking about the Listbox or Menu component.
However, `active` in both scenarios mean: "When either the mouse is over the item OR the keyboard is focusing on the item". So this is expected behaviour.

Note that a Menu doesn't have a "value" attached to it.
Also note that the Listbox *does* have a "value" attached to it. If you want to style things based on whether the value is "selected" or not, then you can use the `{ selected }` value instead.

So what you are describing is expected behaviour.

**Comment by Snazzie** [comment]
Hello!
> I'm not sure if you are talking about the Listbox or Menu component.

Actually both :) 

>active in both scenarios mean: "When either the mouse is over the item OR the keyboard is focusing on the item" So this is expected behaviour.

Actually this is incorrect, 
`Hover` is when cursor is over the element.
`Active` is when cursor is pressed onto the element. 
`Focus` is when the keyboard is focused on the item.

Please refer to the following blog on the definitions for pseudo-classes.
https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/

**Comment by Snazzie** [comment]
I dont think its correct merging these different behaviors into one. :)

**Comment by RobinMalfait** [comment]
I'm not talking about css states in this case, I'm talking about usability in general. We make menu items and listbox options "active" when that specific item is active being hovered (mouse) or active via keyboard shortcuts. You can still use the `active:..`, `focus:..`, and `hover:` tailwind classes if you want. This is just extra state that we expose to make your components more consistent for both keyboard and mouse users.

**Comment by morganfeeney** [comment]
This is confusing terminology, I was expecting active to mean what it says. FWIW: I've ended up on this issue because I was looking for clarification, I don't think the docs cover it as well as they could.

e.g.

> which tells you if the item is currently focused via the mouse or keyboard

No idea what that means

@RobinMalfait  What you say here is a better explanation:
> We make menu items and listbox options "active" when that specific item is active being hovered (mouse) or active via keyboard shortcuts. You can still use the active:.., focus:.., and hover: tailwind classes if you want. This is just extra state that we expose to make your components more consistent for both keyboard and mouse users.
