### ISSUE TITLE
Open for contributions?

### ISSUE THREAD

**Issue by MaxAst** [tailwindlabs/headlessui#133]
Hi Tailwind Labs team,

first off, thanks a lot for this library! I'm going to have to implement a multi-select element in the near future using TailwindUI. Are you guys open to contributions/collaboration on this? I haven't seen any contribution guidelines and/or roadmap so I wanted to ask first. With multi-select, I mean a headless version of something along the lines of what https://react-select.com offers

**Comment by theMasix** [comment]
Hello. Duplicate. #58

**Comment by stepanjakl** [comment]
+1 for multiselect
