### ISSUE TITLE
Combobox opens the dropdown list when user is clicking the Tab key

### ISSUE THREAD

**Issue by piter75git** [tailwindlabs/headlessui#1337]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
Latest

**What browser are you using?**
Chrome

**Reproduction URL**
1. Create new Vue project
2. Take the first example code from https://headlessui.dev/vue/combobox
3. Add after the Combobox the "input" field.

https://stackblitz.com/edit/vue-vv6zyv

**Describe your issue**
1. Go to the combobox and type and select (arrow keys + Enter) an element from the dropdown list
2. Press "Tab" to leave the combobox and focus the input field.
3. Combobox opens the dropdown list.

Combobox shouldn't open the dropdown list.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I bumped the Headless UI version to the latest insiders build and I can't seem to reproduce it. Can you check if it is fixed in the latest insiders build?

https://stackblitz.com/edit/vue-2fhyw6

**Comment by piter75git** [comment]
Hello Robin,

I've just created that mentioned example:
https://stackblitz.com/edit/vue-vv6zyv
so I suppose this is the latest version of H.

I've just recorded the screen, maybe it helps (keyboard on the screen is only to show what I'm clicking, the issue is the same using the "hardware" keyboard):
https://files.fm/u/zgakyder5

**Comment by piter75git** [comment]
Hello Robin,

I'm sorry, I didn't noticed that your link is a new one.
I've checked that - the issue is not happening.
Thank you for so quick response.
