### ISSUE TITLE
Popover.Panel focus=true cause undesired open behavior when clicking multiple times on Popover.Button

### ISSUE THREAD

**Issue by pawelkondraciuk** [tailwindlabs/headlessui#1342]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.5.0

**What browser are you using?**
Chrome

**Reproduction URL**
https://codesandbox.io/s/headlessui-popover-form-forked-cx4lmn

**Describe your issue**
✔️ When you try to click multiple times on the first red "Popover" button, popover panel will open -> close -> open -> close. That's ok
❌ When you try to do the same on the second "Popover with focus=true" button, popover panel will open -> open -> open -> open which is incorrect, should be the same as above. Clicking second time on a button should close popover (as you would click on overlay)

The only difference is focus={true} attribute added to second Popover.Panel

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1477, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
