### ISSUE TITLE
Transition component causing an error message on mobile.

### ISSUE THREAD

**Issue by nitinpunjabi** [tailwindlabs/headlessui#1344]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

"^0.0.0-insiders.b4a4e0b"

**What browser are you using?**

Chrome on Ubuntu and Chrome on iOS.

**Reproduction URL**

https://github.com/nitinpunjabi/headlessui_transition_bug

**Describe your issue**

Dependencies:
- "@headlessui/react": "^0.0.0-insiders.b4a4e0b",
- "next": "12.1.5",
- "react": "18.0.0",
- "react-dom": "18.0.0"

The *insiders* build is being used because transitions don't work otherwise with React 18. See this discussion:
https://github.com/tailwindlabs/headlessui/issues/681

With the *insiders* version, the transition component is causing an issue on mobile. With the _latest_ version, it doesn't work in development mode.

To recreate:
1. Start a new Next project.
2. Run *npm install @headlessui/react@insiders*
3. Copy and paste this example into index.js: https://headlessui.dev/react/transition
4. Start the dev server.
5. Visit localhost:3000 on **desktop** and confirm it works.
6. Visit *http : // Local IP Address:port number*  on your mobile phone.

Expectation: same behaviour on mobile as on desktop.

Actual result: error messages.

On the mobile browser, I get this error message: https://imgur.com/a/oUKSsNg

When I use chrome://inspect to capture the console logs, I see this: https://imgur.com/a/pk48dUk

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This has been fixed by https://github.com/tailwindlabs/headlessui/commit/591b32861a42468a70523aba82e1844d0fda1351 and will be available in the next insiders release

**Comment by nitinpunjabi** [comment]
Thank you for the fast fix!

**Comment by TienPham18** [comment]
Thank you for your bug report! it helps
