### ISSUE TITLE
Transition Not working with PopOver

### ISSUE THREAD

**Issue by dynamite-bud** [tailwindlabs/headlessui#1345]
**@headlessui/react**

**1.5.0**

**stackblitz web container**

**https://stackblitz.com/edit/node-4hg8tw?file=src/PopOver.jsx**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

As seen on this page https://headlessui.dev/react/popover. I am not able to achieve this behaviour with popover including transitions.

If you remove the transition tags line [44-52] and closing subsequent tag. The popover works fine but not with transition tag around it.

With Transition tag around Popover Panel.
https://user-images.githubusercontent.com/41326026/163940333-eb504222-4b59-4f80-8da9-3556bfae50f4.mp4

Without Transition Tag around Popover Panel
https://user-images.githubusercontent.com/41326026/163940379-97e7c5b3-1494-4d2c-ac51-d36cc4df6f23.mp4

**Comment by Soham-2224** [comment]
**Transition component wont work**
when transition component is added the dropdown won't show up. But when it is removed the dropdown works perfectly fine.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is related to React 18, use he latest `insiders` build to fix this issue: https://stackblitz.com/edit/node-h2rwyp?file=package.json

More info can be found in: #681

**Comment by dynamite-bud** [comment]
Thanks Robin
