### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by guvenakcoban** [tailwindlabs/headlessui#135]
Hi,

Can you publish a new release? Why latest npm version doesn't update? I am not sure how can I use the master branch on this package.

**Comment by natedunn** [comment]
> Can you publish a new release?

😑

> Why latest npm version doesn't update? 

The latest release of Headless UI is up-to-date on NPM. You don't want to use a branch directly. Wait for them to work on updates as they can, and then they will update those packages.

**Comment by RobinMalfait** [comment]
We will release a new version shortly! 
You can test the dev channel, for example: `yarn add @headlessui/react@dev`
