### ISSUE TITLE
[Bug] Dialog.Overlay doesn't close together with Dialog on latest main commit (591b328)

### ISSUE THREAD

**Issue by spvn** [tailwindlabs/headlessui#1351]
**What package within Headless UI are you using?**

@headlessui/react@insiders.591b328

**What browser are you using?**

Firefox

**Describe your issue**

Not sure if it's only affecting me, but I'm using the current insiders version and Dialog.Overlay stays visible even when you close the Dialog it belongs to, blocking inputs to the underlying page. I reverted to commit ab6310 and this issue went away, but it also resulted in issues with using datepickers in modals (i.e. the fix that was supposed to come with this pull request doesn't work, and clicking inside a datepicker in a dialog will cause the dialog to close. https://github.com/tailwindlabs/headlessui/pull/1268).

EDIT: I have come to realise that strangely, this bug only happens IF you have an opacity class on the Dialog.Overlay component. For example the overlay closes if it looks like that:

`                        <Dialog.Overlay className="fixed inset-0 bg-black"/>
`

but does NOT close if it's like that:

`                        <Dialog.Overlay className="fixed inset-0 bg-black opacity-30"/>
`

I'm using a Transition for this overlay just like in this codesandbox that was posted when fixing #432 

After some further testing, removing the surrounding <Transition> tag fixes the issue, so there's probably some conflict with transitioning the opacity.

**Comment by spvn** [comment]
Will create one when I'm free, but just FYI the sample code for Dialog on the website will break. I'm referring to the sample dialog at the top of this page: https://headlessui.dev/react/dialog

Removing `as={Fragment}` from <Transition.Child> fixes the problem

**Comment by GrefriT** [comment]
Can confirm that dialog doesn't close on 591b328 when using with Transition component, but it's working in b4a4e0b

**Comment by RobinMalfait** [comment]
@GrefriT can you create a reproduction repo / CodeSandbox and share it?

**Comment by RobinMalfait** [comment]
Hey!

Going to close this for now, if you still have this issue please create a new issue with a reproduction repo / CodeSandbox attached.

**Comment by ravenstar** [comment]
I was having the same issue as @spvn , until I realised the <Transition.Child> that wrapped the <Dialog.Overlay> had a `enterTo` and `enterFrom` value of `opacity-100`. When I changed them to use the same opacity value as the <Dialog.Overlay> (`opacity-30`), everything worked fine and the overlay disappeared as expected.

**Comment by StwardPC** [comment]
> Removing `as={Fragment}` from Dialog.Overlay's <Transition.Child> fixes the problem

This solved the issue on my end.
