### ISSUE TITLE
Popover does not work with React 18

### ISSUE THREAD

**Issue by tronglongphung** [tailwindlabs/headlessui#1354]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/recursing-herschel-8x4rkf?file=/src/App.js

**Describe your issue**

Popover does not open on click

**Comment by tronglongphung** [comment]
Update: It worked using `npm install @headlessui/react@insiders`

**Comment by TeXmeijin** [comment]
`@headlessui/react@insiders`

It works on my environment too. Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Glad the `insiders` build works for you. We are almost ready to release it, just finishing of the documentation around all the new features!
