### ISSUE TITLE
[Combobox] Display value not updating on reset function

### ISSUE THREAD

**Issue by engine89** [tailwindlabs/headlessui#1356]
**What package within Headless UI are you using?**

n/a

**What version of that package are you using?**

n/a

**What browser are you using?**

Edge

**Reproduction URL**

https://codesandbox.io/s/headlessui-react-menu-example-forked-gk51hb?file=/src/TypeAhead.js:1265-1272

**Describe your issue**

I have a function that I want to use to reset the selected Combobox option but the label is not updating when my state changes. I have confirmed the value i need is being updated but not being reflected in displayValue. Please take a look at the codesandbox.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You are passing through a `selectedOption`, but you are not using it in the TypeAhead code. Here is an updated link: https://codesandbox.io/s/headlessui-react-menu-example-forked-rnrgc7?file=/src/TypeAhead.js
