### ISSUE TITLE
Vuejs 2.6?

### ISSUE THREAD

**Issue by helioh3** [tailwindlabs/headlessui#136]
I am stubborn, I saw in the doc that and only for vue 3, I can run in vue 2.6?

**Comment by adamwathan** [comment]
Hey! Sorry only for Vue 3 currently, won't work in Vue 2.

**Comment by helioh3** [comment]
Thanks for ask @adamwathan

**Comment by helioh3** [comment]
> Hey! Sorry only for Vue 3 currently, won't work in Vue 2.

**Comment by helioh3** [comment]
> Hey! Sorry only for Vue 3 currently, won't work in Vue 2.

Thank! for ask
