### ISSUE TITLE
Consider supporting Blazor web framework

### ISSUE THREAD

**Issue by juho-hanhimaki** [tailwindlabs/headlessui#137]
Blazor is blazing hot open-source web framework built by Microsoft on modern open source .NET. It was initially released in 2018, with Knockout.js creator [Steve Sanderson](https://twitter.com/stevensanderson) as the main developer.

Blazor apps are fully component based. The component system is known as Razor components and the components are implemented using C#, HTML, and CSS. The client-side Blazor apps are compiled to WebAssembly, but there is also full JavaScript interop for integrating with JavaScript libraries.

I've used Tailwind UI on Blazor and it seems like a great fit for developing web apps on Blazor. There are many free and commercial [component libraries](https://github.com/AdrienTorris/awesome-blazor#libraries--extensions) available on Blazor, but as stands one has to create their own Tailwind components which can be a lot of work.

As I understand, Microsoft is committed to supporting far into the future as a part of modern .NET and ASP.NET Core.

I hope you will consider bringing the awesomeness of Tailwind components to Blazor in the future!

You can find more information about Blazor on google and at these links:
https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor
https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0
https://github.com/dotnet/aspnetcore

Feel free to correct me if I got some facts about Blazor wrong.

**Comment by xt0rted** [comment]
My projects are asp.net core mvc without a frontend framework. I've started building some web components to make using tailwind css/ui easier. I plan on open sourcing them once they seem somewhat stable. So far I have a transition component and a toggle component. These should drop into blazor easily but I haven't tried them with it yet. I should hopefully have something to show over the next week or two.

**Comment by juho-hanhimaki** [comment]
Hey, everyone who keeps giving thumbs down without any constructive criticism. Why are you rude? This is OSS and I would expect the community to be welcoming to new people and ideas.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

For now we are focusing on a limited set of implementations, mainly React and Vue.
The reason being is that when we focus on these implementations then we can test those and shorten the feedback cycle, because we use those technologies ourselves. 

It might be that we support other frameworks in the future, but we want to focus on those for now and make those really good before we implement the components for other frameworks.

**Comment by juho-hanhimaki** [comment]
That is very understandable.

However if this is something you might reconsider in future why not keep the issue open (and possibly label it to some low priority) so it is tracked ?

Rock on!

**Comment by galvesribeiro** [comment]
@RobinMalfait would PR adding Blazor support acceptable here?
