### ISSUE TITLE
Classes assigned to a component using as="<element>" aren't assigned

### ISSUE THREAD

**Issue by oKokoschka** [tailwindlabs/headlessui#1373]
@headlessui/vue
v1.6.0
Firefox/MacOS

`<Combobox v-slot="{ open }" v-model="address" as="div" class="relative w-full" >`
  will render as 
  `<div>`
  
  I found this to occur on any headlessui components where you stipulate the element to render it as, and classes to assign to it.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1372, and will be available in the next release.

You can already try it using `npm install @headlessui/vue@insiders`.
