### ISSUE TITLE
[DOCS]: Can't open headlessui.dev section pages

### ISSUE THREAD

**Issue by sizumita** [tailwindlabs/headlessui#1374]
I can't open headlessui.dev pages without top page.

computer: M1 macOS 12.2
safari: 15.3

here is video:
https://user-images.githubusercontent.com/17804838/165675576-ecb3a189-13c5-4c09-9050-889f24673e9f.mov

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed now 👍

**Comment by sizumita** [comment]
It's fixed now! Thanks! 👍
