### ISSUE TITLE
Switch Component - 1.6.0 breaking change

### ISSUE THREAD

**Issue by anthereum** [tailwindlabs/headlessui#1376]
This breaks in 1.6.0 not 1.5.0

```
    <Switch
      checked={checked!}
      onChange={onChange!}
      type="button"
      ref={ref}
      className=""
    >
      <span>some text</span>
    </Switch>
```

![image](https://user-images.githubusercontent.com/87685331/165870923-4cae0814-2cb5-42c5-81ca-80429f90c67a.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

---

If I would make a guess, my guess would be that you have some wrapping component like:

```js
function MySwitch(props, ref) {
  return <Switch {...props} ref={ref} />
}
```

But forgot to use the `React.forwardRef` on that component. This would also happen for a simple div and not just Headless UI components:

```js
function MyComponent(props, ref) {
  return <div ref={ref} />;
}
```
