### ISSUE TITLE
[Bug] Hidden inputs are not rendered after adding name prop to listbox

### ISSUE THREAD

**Issue by lightiverson** [tailwindlabs/headlessui#1379]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.4.2

**What browser are you using?**

Chrome and Firefox

**Describe your issue**

According to the [Headless UI docs](https://headlessui.dev/react/radio-group#using-with-html-forms) it should be possible to render hidden input elements, and they should be able to keep in sync with the selected value.

However, with the example code as well as my own code I'm unable to get input fields rendered by adding the name prop to my listbox.

**Comment by adamwathan** [comment]
Hey! This is a new feature in v1.6+ and it looks like you are on v1.4.2. Can you update to the latest version and try there?

**Comment by lightiverson** [comment]
Hi! You're right. I updated to v1.6 and it works. Thank you!
