### ISSUE TITLE
snackbar for headlessui

### ISSUE THREAD

**Issue by JoseJuan81** [tailwindlabs/headlessui#138]
Hello, 
I made this [snackbar](https://josejuan81.github.io/dl-notificator/) because I need it in a project and I think headlessui doesn't have one so, It would be very nice if I can collaborate with this component.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

Currently we focus on headless components, without any styles.
I don't think that this component is currently suitable for Headless UI.
