### ISSUE TITLE
List.Button can't stop propagation

### ISSUE THREAD

**Issue by toantran201** [tailwindlabs/headlessui#1380]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.5.0

**What browser are you using?**

For example: Chrome

**Describe your issue**
When I set a click event on parent, inner Listbox.button click event not stop propagation.

**Comment by Foprta** [comment]
You can do it yourself `<Listbox.Button onClick={(e) => e.stopPropagation()} />`

**Comment by toantran201** [comment]
You can check this issue at the link below
https://codesandbox.io/s/listbox-button-propagation-sjj2hm

**Comment by Foprta** [comment]
Seems like it was fixed in 1.6.0.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I've updated your provided CodeSandbox to use version 1.6.0 where this behaviour works as expected: https://codesandbox.io/s/listbox-button-propagation-forked-b3qhs1
