### ISSUE TITLE
Dialog.Panel: Time to respond to close event longer that a click period

### ISSUE THREAD

**Issue by mannyanebi** [tailwindlabs/headlessui#1382]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1381

<div type='discussions-op-text'>

<sup>Originally posted by **mannyanebi** April 29, 2022</sup>
In my app, I noticed that the `Dialog.Panel` takes more than a split second to respond to the Close event, which doesn't act as said in the release notes, `the dialog is closed any time you click any element outside of it` [https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v1.6.0](url)

You'll have to touch and hold before it closes, rather than the "click" experience one expects or is used to. Thanks</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
