### ISSUE TITLE
headless ui components as form controls (listbox and combobox)

### ISSUE THREAD

**Issue by Emokores256** [tailwindlabs/headlessui#1386]
Is there a way the documentation can document how to use the Listbox and Combobox as form controls? They are very useful components but it seems they are impossible to use as form controls.

**Comment by RobinMalfait** [comment]
Hey!

Anything you are missing from these docs?

- https://headlessui.dev/react/listbox#using-with-html-forms
- https://headlessui.dev/react/combobox#using-with-html-forms
- https://headlessui.dev/vue/listbox#using-with-html-forms
- https://headlessui.dev/vue/combobox#using-with-html-forms

**Comment by Emokores256** [comment]
I've been trying to make this a bit practical but with little effort. How can one pick the `<input name={`assignee[id]`} />` having the `id` value and send it to the database? In my case, I'm using Laravel/Inertia with ReactJS.
