### ISSUE TITLE
trigger popover button on "hover" event instead of "onClick" event.

### ISSUE THREAD

**Issue by Obiwarn** [tailwindlabs/headlessui#1397]
on popular demand:

### Discussed in https://github.com/tailwindlabs/headlessui/discussions/425

<div type='discussions-op-text'>

<sup>Originally posted by **MAfzalKhan1997** April 22, 2021</sup>
![image](https://user-images.githubusercontent.com/37745422/115682133-9d8e2280-a36e-11eb-9c09-29530b291fa4.png)

I'm new to tailwind CSS and using headless-ui/react for my Next Js project. 
I want to open these navigation menus on hover but I couldn't find any solution please help me out for that.
</div>

**Comment by hichemfantar** [comment]
@RobinMalfait any plans to add this, it's a pretty nice feature for a great ux

**Comment by isnolan** [comment]
This is crucial for the navigation experience and conversion of the Landing Page. In fact, this is my third time to explore progress. I really don’t want to use multiple ux libraries in the same project.

**Comment by isnolan** [comment]
@RobinMalfait This is crucial for the navigation experience and conversion of the Landing Page. In fact, this is my third time to explore progress. I really don’t want to use multiple ux libraries in the same project.
