### ISSUE TITLE
[Vue] Menu item anchor don't seem to be clickable 

### ISSUE THREAD

**Issue by GavinJoyce** [tailwindlabs/headlessui#14]
Using the "Menu (basic)" example, when I click on "Account settings" the menu closes but the URL does not update. When I select it by pressing "Enter", it updates to `http://localhost:3000/menu/menu#account-settings` as expected.

<img width="1440" alt="Screenshot 2020-09-25 at 15 37 31" src="https://user-images.githubusercontent.com/2526/94280410-498c9e00-ff45-11ea-9ac9-04fa7460e121.png">

**Comment by RobinMalfait** [comment]
Hey! Thanks for the bug report. I'll look into it, thanks!
