### ISSUE TITLE
Listbox scrollbar in headlessui/react

### ISSUE THREAD

**Issue by socmov** [tailwindlabs/headlessui#140]
This could be user error but I can't find how to set a max height / enforce a scrollbar on a listbox with a lot of options. The current code seems to render the full list with some options rendered off screen without a way to scroll to them. 

Thanks for the great library.

**Comment by RobinMalfait** [comment]
Hey!

You are in control of rendering, so a `h-64 overflow-auto` could do the trick here, assuming you are using Tailwind as well.
