### ISSUE TITLE
Dialog.Overlay doesn't close together with Dialog on latest main commit (Also 1.6.1)

### ISSUE THREAD

**Issue by conspiracynomad** [tailwindlabs/headlessui#1402]
I have the absolutely same issue: https://github.com/tailwindlabs/headlessui/issues/1351

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
