### ISSUE TITLE
ERROR using "Integrating with Next.js" - Menu (Dropdown) Example

### ISSUE THREAD

**Issue by meveh14608** [tailwindlabs/headlessui#1405]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1400

<div type='discussions-op-text'>

<sup>Originally posted by **meveh14608** May  4, 2022</sup>
Hello,

I am trying Headless UI out with NextJS although I am running into an issue whilst following the example here: https://headlessui.dev/react/menu#integrating-with-next-js.

When using the example I get the following error:

![V8drScEv](https://user-images.githubusercontent.com/104916923/166712256-87f9bf40-6ea4-4561-8cb7-cb73d24524d9.png)

If I switch out the `Link` component from `next/link` with a regular `<a>` tag there's no errors.

Please can you help me. This is the snippet I am using, provided by you:
```
import Link from 'next/link'
import { Menu } from '@headlessui/react'

function MyLink(props) {
  let { href, children, ...rest } = props
  return (
    <Link href={href}>
      <a {...rest}>{children}</a>
    </Link>
  )
}

function Example() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          <MyLink href="/profile">Profile</MyLink> {/* This doesn't work */}
          <a href="/profile">Profile</a> {/* This works */}
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}
```

These are my dependencies and their versions:
> I saw the pinned issue regarding react 18, and tried the insider version of headlessui however there was no change.

```
"@headlessui/react": "^1.6.1",
"next": "12.1.5",
"react": "18.0.0",
"react-dom": "18.0.0"
```

I'm new to GitHub, so hopefully this is the right place to ask. Thank you.</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You have to forward the `ref` on the `MyLink` component:

```js
let MyLink = React.forwardRef((props, ref) => {
  let { href, children, ...rest } = props
  return (
    <Link href={href}>
      <a ref={ref} {...rest}>{children}</a>
    </Link>
  )
})
```

Will update the docs to make sure this is clear 👍 
-> https://headlessui.dev/react/menu#integrating-with-next-js
