### ISSUE TITLE
Popover with transition closes while clicking inside (occurs only on react 18).

### ISSUE THREAD

**Issue by Bjornjansfelt** [tailwindlabs/headlessui#1407]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.1

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/shy-field-8erb30?file=/src/App.js

**Describe your issue**

A popover wrapped in a transition component closes while clicking inside on React 18 but it stays open on react 17 which is the expected behaviour.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1409, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by Bjornjansfelt** [comment]
Thank you @RobinMalfait !
I can confirm that it works now with the insiders build in my "real" project. Thanks for the quick response and action!
