### ISSUE TITLE
[Bug] Listbox cause unexpected scroll behavior when it is used with a `position: sticky` container

### ISSUE THREAD

**Issue by promer94** [tailwindlabs/headlessui#1412]
**What package within Headless UI are you using?**

 @headlessui/react

**What version of that package are you using?**

v1.6.1

**What browser are you using?**

Chrome: Version 101.0.4951.64 (Official Build) (arm64)

**Reproduction URL**
https://codesandbox.io/s/headlessui-react-unexpected-scroll-behavior-9jvger?file=/src/App.js

**Describe your issue**
Listbox cause unexpected scroll behavior when it is used with a `position: sticky` container

https://user-images.githubusercontent.com/15878786/167044067-8d613aa2-7ec7-4235-84e0-43facb944bd7.mov

https://www.npmjs.com/package/scroll-into-view-if-needed might be a good choice to solve this problem.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Quick question: What OS and which version of Chrome are you on? I can't seem to reproduce it. Is this still happening for you?

**Comment by promer94** [comment]
Chrome: Version 101.0.4951.64 (Official Build) (arm64) 
OS: macOS Monterey 12.3.1(21E257)

Yes, it still happens

**Comment by RobinMalfait** [comment]
Hmm I'm on basically the exact same versions as you are:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/1834413/169119783-c59cc564-142d-4eb2-b4fd-61c59fb2e20d.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/1834413/169119844-27f826d8-15c0-4cbd-88f3-c04b036584c7.png">

And I can't reproduce it at all. Do you have any extensions installed that could cause an issue? Can you check in incognito mode or another browser by any chance? Do you have any special system wide settings enabled?


https://user-images.githubusercontent.com/1834413/169120701-494813c3-9d73-4287-9b02-a2360b5b599c.mov

**Comment by promer94** [comment]
You are right, after reset everything at chrome://flags, it's now works as expected.
I also tested it with firefox and safari, both works well.
Thanks for the tips and time. Really appreciated !

**Comment by RobinMalfait** [comment]
Glad you figured it out! I'm very curious about what the culprit actually was though!

**Comment by promer94** [comment]
<img width="1034" alt="Screen Shot 2022-05-19 at 20 37 03" src="https://user-images.githubusercontent.com/15878786/169294946-3fe84748-7566-453d-80a4-3fb05c2bcd17.png">
