### ISSUE TITLE
Type Error for `Dialog.Panel`: ts(2339)

### ISSUE THREAD

**Issue by felixhaeberle** [tailwindlabs/headlessui#1419]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

latest

**Describe your issue**

There is a type error with `Dialog.Panel` in the latest version. VS Code can't find the type of `Panel`

```
error TS2339: Property 'Panel' does not exist on type '(<TTag extends ElementType<any> = "div">(props: Props<TTag, DialogRenderPropArg, DialogPropsWeControl> & (({ static?: undefined; } & { ...; }) | ({ ...; } & { ...; })) & { ...; }, ref: Ref<...>) => Element) & { ...; } & { ...; }'.

75               </Dialog.Panel>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Here is a list of things to try:
1. Restart VS Code, sounds silly but a lot of people report "issues" on Discord and after a restart it is fixed.
2. Make sure that you are on the latest version `npm install @headlessui/react@latest`
3. Restart the TypeScript Language Server (tsserver). A restart/reload of VS Code should do the same thing.

Here is a very basic CodeSandbox with React, TypeScript and Headless UI proving that `Dialog.Panel` does exist. https://codesandbox.io/s/laughing-edison-182d99?file=/src/App.tsx
