### ISSUE TITLE
[react][firefox] right click should not open listbox

### ISSUE THREAD

**Issue by stefanprobst** [tailwindlabs/headlessui#142]
currently, clicking a listbox button with the right mouse button in firefox opens it. seems to work correctly in chrome.

reproducable in the [listbox example csb](https://codesandbox.io/s/headlessuireact-listbox-example-57eoj?file=/src/App.js) in the docs.

tested with firefox 82

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Will look into it now, nice find!

**Comment by RobinMalfait** [comment]
This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.

Here is the same codesandbox, but with the latest dev dependency: https://codesandbox.io/s/headlessuireact-listbox-example-forked-6u62k
