### ISSUE TITLE
Listbox inside Dialog

### ISSUE THREAD

**Issue by abduraufsherkulov** [tailwindlabs/headlessui#1420]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.1

**What browser are you using?**

Chrome

**Reproduction URL**

[codesandbox](https://codesandbox.io/s/headless-ui-dialog-forked-4gbhn7)

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

I am using Headless UI Listbox inside Dialog, however, it seems like listbox items are blocked inside Dialog.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You have 2 issues that I can see:
1. The Listbox has a `fixed` class, which positions it in a strange location, you can remove that to make it sit above the "Got it, thanks" button.
2. Due to the `overflow-hidden` on the `Dialog.Panel`, your Listbox options are cut off. You can either remove the overflow-hidden or use a Portal + a positioning library like Popper.js or Floating UI.

Here is an updated CodeSandbox: https://codesandbox.io/s/headless-ui-dialog-forked-mezken?file=/src/Modal.tsx

**Comment by leonatajeff** [comment]
I used Floating UI previously but with the new v2 release with `anchor`, id like to only use headless. 

I am refactoring atm and I am having a similar issue. My set up is nearly identical here (w/o the dot notation and `anchor="button"` 

How does this work with the new `anchor` positioning method in v2? My listbox options is not showing when i open it.

ListboxOptions appears if i have Floating UI and remove anchor.

@RobinMalfait

**Comment by Plotist** [comment]
> I used Floating UI previously but with the new v2 release with `anchor`, id like to only use headless.
> 
> I am refactoring atm and I am having a similar issue. My set up is nearly identical here (w/o the dot notation and `anchor="button"`
> 
> How does this work with the new `anchor` positioning method in v2? My listbox options is not showing when i open it.
> 
> ListboxOptions appears if i have Floating UI and remove anchor.
> 
> @RobinMalfait

Switching to `anchor` worked like magic in my case. Didn't even have to change anything aside from adding this prop. 

Can you give more details on the issue?

**Comment by Kelp1e** [comment]
I don't know why, but when I used `transition={true}` for `<ListboxOptions/>`, it worked for me.

**Comment by ariaspabloi** [comment]
> I don't know why, but when I used `transition={true}` for `<ListboxOptions/>`, it worked for me.

thanks, I couldn't select any ListboxOption without it
