### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Emokores256** [tailwindlabs/headlessui#1425]
Hey!

Anything you are missing from these docs?

- https://headlessui.dev/react/listbox#using-with-html-forms
- https://headlessui.dev/react/combobox#using-with-html-forms
- https://headlessui.dev/vue/listbox#using-with-html-forms
- https://headlessui.dev/vue/combobox#using-with-html-forms

_Originally posted by @RobinMalfait in https://github.com/tailwindlabs/headlessui/issues/1386#issuecomment-1113958581_

**Comment by adamwathan** [comment]
Let’s keep this in the discussions 👍🏻
