### ISSUE TITLE
Error 500 [Headless UI]: Cannot find ownerDocument for contextElement: null

### ISSUE THREAD

**Issue by TechhDan** [tailwindlabs/headlessui#1429]
Package: @headlessui/vue
Package Version: ^1.6.1
Browser: Chrome
Reproduction URL : https://github.com/TechhDan/headlessui-nuxt3-bug 

Description: Some of the components are not rendering correct in the Vue environment. I'm getting an error 500 for some of the components. If you look at the reproduction URL repo you can see that localhost:3000/dialog does not work but localhost:3000/disclosure does work. These are both copied directly from the examples.

![image](https://user-images.githubusercontent.com/11691784/167522462-2c34f465-3a83-4992-9c73-da37e31b68b4.png)

**Comment by MrJmpl3** [comment]
I think is a SSR problem, because the problem don't show when the Dialog component is wrapped with ClientOnly component

**Comment by kelvin-zhao** [comment]
I'm also having this issue when rendering with AstroJS. Is there a workaround or solution for this?

**Comment by thecrypticace** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1459, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/vue@insiders`.
