### ISSUE TITLE
Popover within a Tab

### ISSUE THREAD

**Issue by amrani** [tailwindlabs/headlessui#1437]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.6.1

**What browser are you using?**
Firefox / Safari

**Reproduction URL**
https://codesandbox.io/s/gallant-leftpad-40rs9h?file=/src/App.js

**Describe your issue**

I am using a Popover within a Tab. Clicking the `Popover.Panel` closes the Popover. 

I also tried react 17/18, a static panel, insiders (`0.0.0-insiders.bf0d112`), with and without `Transition`, and `as=` a number of element types.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1443, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
