### ISSUE TITLE
Disabling enter key behaviour on switch component

### ISSUE THREAD

**Issue by kingroho** [tailwindlabs/headlessui#144]
Hi there! I just want to ask if I can disable the default behaviour of the switch component when pressing enter? It keeps toggling even when the focus is on the other input. It overrides the behaviour of the form. I tried `<Switch @keydown.enter.prevent />` but it doesn't seem to work.

Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is fixed, you shouldn't need to do anything in order to make the this happen. This was a bug and it will be in the next version we publish!

**Comment by adaddeo** [comment]
I'm seeing this same thing. When focus is on other inputs the Switch component toggles when Enter is pressed. When focus is on the Switch component Enter does not toggle the Switch. Using version 1.3.
