### ISSUE TITLE
Missing props on Menu.Item when element is next/link

### ISSUE THREAD

**Issue by nath-green** [tailwindlabs/headlessui#145]
Hello

I think I may have come across an issue where the `<Menu.Item>` doesn't get the correct properties when using `next/link` `<Link>` component. The rendered `<a>` doesn't have a `role` or `id` which means the `active` state doesn't work.

Any suggestions of a workaround?

Many thanks!

**Comment by nikosolihin** [comment]
You'll need to wrap <Link> in a function component which passes down `props` to `<a>`:

`
const LinkWrapper = React.forwardRef(({ href, active, ...props }, ref) => {
  return (
    <Link href={href}>
      <a ref={ref} {...props}>{active ? 'Active' : 'Inactive'}</a>
    </Link>
  );
});

function MyDropdown() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          {({ active }) => <LinkWrapper href="/page-2" active={active}>{children}</LinkWrapper>}
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}
`

**Comment by ynotdraw** [comment]
Thanks @nikosolihin, this worked for me! 🎉

**Comment by RobinMalfait** [comment]
Hey! Glad this got fixed already!

We saw this issue ourselves and added a small wrapper around the next/link: https://github.com/tailwindlabs/headlessui/blob/24725216e4e2fb9280bdf3b96583a9fe573410e4/packages/%40headlessui-react/pages/menu/menu-with-framer-motion.tsx#L71-L78

**Comment by ecklf** [comment]
@RobinMalfait just a heads up. This would break usage of `next-link` with it's other props.

I extended the above to include missing props:

```tsx
import Link, { LinkProps } from "next/link";
import React from "react";

// https://nextjs.org/docs/api-reference/next/link
type Props = React.ComponentProps<"a"> & React.PropsWithChildren<LinkProps>;

const NextLink = (props: Props) => {
  const {
    href,
    as,
    replace,
    scroll,
    shallow,
    passHref,
    prefetch,
    locale,
    children,
    ...rest
  } = props;
  return (
    <Link
      href={href}
      as={as}
      passHref={passHref}
      prefetch={prefetch}
      replace={replace}
      scroll={scroll}
      shallow={shallow}
      locale={locale}
    >
      <a {...rest}>{children}</a>
    </Link>
  );
};

export default NextLink;
```
