### ISSUE TITLE
[1.6.1] Tabs component `selected` mismatches when using SSR (Next.js) leading to hydration error

### ISSUE THREAD

**Issue by merlindru** [tailwindlabs/headlessui#1453]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.6.1

**What browser are you using?**

For example: Edge (Chromium)

**Describe your issue**

I'm using the `selected` prop passed to `Tab` to set `className`s based on the prop (untested example).

```tsx
// custom array of objects we're making
// each `tab` object has a `title` in this example
props.tabs.map((tab, i) => (
	<Tab key={i} className="sm-:flex-1 sm-:flex-shrink-0">
		{({ selected }) => (
			<span
				className={classNames(
					"font-semibold text-sm md:text-base",
					selected ? "text-black" : "text-gray-500"
				)}
			>
				{tab.title}
			</span>
		)}
	</Tab>
))
```

This leads to the following error:

```
Warning: Prop `className` did not match. Server: "font-semibold text-sm md:text-base text-black" Client: "font-semibold text-sm md:text-base text-gray-500"
    at span
    ...
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Are you 100% sure that you are on Headless UI 1.6.1? This is the one issue we solved in that version 😅 

If you are using Next.js:
```
rm -rf .next
```

Make sure that you are actually on the latest version
```
npm install @headlessui/react@latest
```

Doesn't work? Nuke node_modules and try again.

Here is a link to our playground where we are styling the active tab based on the `selected` state and it is properly server side rendered. https://headlessui-react-dqxf31z4j-tailwindlabs.vercel.app/tabs/tabs-with-pure-tailwind


If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
