### ISSUE TITLE
Expose toggle function as part of Menu

### ISSUE THREAD

**Issue by timReynolds** [tailwindlabs/headlessui#146]
Menu is currently great when wanting to display a list of options however when you stray from the a simple list to something more complex which for example might include a reset button it's not possible programatically close the menu as no toggle option is exposed on the components. 

My guess is there are two ways this could be done,

1. Exposing it as a prop in the render function 
2. Expose useMenuContext to consuming applications 

Exposing the menu context would actually be beneficial for other uses, like accessing open without the use of the render prop or getting the trigger reference to calculate the drop down position but would expose a lot more about the internal workings to a consumer. 

Apologies if I've just missed how to do this

**Comment by mattgreenfield** [comment]
I am also trying to use the Menu component as more of a dropdown (without menu items) and am finding that the focus management is causing issues.

I've created a demo of the issue and roughly what I'd like to achieve. I've added a red border to the currently focused item so you can see that focus keeps getting reset to the menu container. There's also a button in there as per @timReynolds use case. https://codesandbox.io/s/headlessuireact-menu-example-forked-n6p3t?file=/src/App.js

Sorry to hijack the post but I do wonder if the answer to both our questions is the same - we're using a component for something it's not meant to be used for.

Maybe there's a need for a higher level component that handles open/close of dropdowns, the aria roles and focus management. The current Menu component could then use that and add the logic for menu items and keyboard navigation. We could then both use that Dropdown component directly.

Thanks for your help.

**Comment by pikeas** [comment]
I was wondering the same thing when I posted https://github.com/tailwindlabs/headlessui/issues/130#issuecomment-739561320

**Comment by mattgreenfield** [comment]
Thanks @pikeas I think that answers my question. What we are trying to do is not the intended purpose of this component and as @RobinMalfait points out, we need a disclosure component.

I've switched to using HTMLs built in `<details><summary></summary></details>` elements - MDN describes them as "a disclosure widget" [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).
It's a shame there's no way to animate it though and I need to write my own code for ensuring only one can be open at a time and possibly a focus trap too.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

@timReynolds I think you might be sort of abusing the component a little. For example, when you talk about "reset", if you have a button as a Menu.Item then the `onClick` should work (which will also close the Menu).

I wrote about the Menu component here: https://github.com/tailwindlabs/headlessui/issues/130#issuecomment-717172240. I also wrote about some problems with hooks for exposing this data here: https://github.com/tailwindlabs/headlessui/issues/205#issuecomment-769764779.
For the additional question in your comment about "getting the trigger reference", you should be able to put a ref on that component.

---

@mattgreenfield We have an experimental Disclosure component (undocumented, API *might* change), you can find the source for it here: https://github.com/tailwindlabs/headlessui/pull/207. 
You can already try it using `npm install @headlessui/react@internal` or `yarn add @headlessui/react@internal`.
