### ISSUE TITLE
Get access to ref on Transition.Child

### ISSUE THREAD

**Issue by ARkrOSClou** [tailwindlabs/headlessui#1472]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`v1.6.1`, `@insiders`

**What browser are you using?**

Chrome

**Reproduction URL**

repo: https://github.com/ARkrOSClou/headlessui_ref_issue
code: https://github.com/ARkrOSClou/headlessui_ref_issue/blob/main/src/App.js
build: https://headlessui-ref-issue.vercel.app/

**Describe your issue**

As a continuation of this issue https://github.com/tailwindlabs/headlessui/issues/273
`ref` still doesn't work when used on `<Transition.Child>`

`console.log('refParent', refParent.current)`
`console.log('refChild', refChild.current)`
![image](https://user-images.githubusercontent.com/46116126/169271209-82e70e91-b710-47a3-9cdd-d9590a142449.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1473, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by ARkrOSClou** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> This should be fixed by #1473, and will be available in the next release.
> 
> You can already try it using `npm install @headlessui/react@insiders`.

thanks, damn fast!
