### ISSUE TITLE
Some components block click event listeners

### ISSUE THREAD

**Issue by cyruscollier** [tailwindlabs/headlessui#1480]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.2

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/cyruscollier/nuxt3-demos/tree/headlessui

**Describe your issue**

Some components block external click event listeners when pressing buttons and links that are part of or inside the component. This is an issue when using analytics libraries and other marketing/UX testing tools to track user interactions on a page, all of which are obviously outside a Vue rendering context. Here are the issues observed so far, but there may be others:

1. Dialog: Buttons or links inside Dialog / DialogPanel are not responding to click event listeners
2. Popover: The PopoverButton is not responding to click event listeners
3. Menu: The MenuButton is responding to click event listeners on close, but not on open.

To replicate, clone the example repo above, run `yarn`, `yarn dev`, then open http://localhost:3000/. Open the console and observe the logging or lack of logging when buttons or links are clicked.

**Comment by ricopozzi** [comment]
I am having this issue too... waiting for someone to fix it ! :)

**Comment by cyruscollier** [comment]
I've guessing there is an `event.preventDefault()` or `event.stopPropagation()` somewhere that is preventing the capture of some of these events, possibly in Focus Trap or one of the other helpers utilities. It's strange that it's so inconsistent across components, which worries me a little because it means the issue might be coming from multiple sources. I'm going to take a deeper look myself over the next few days, but it would be great if a maintainer could weigh in on this issue.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

It's true that in some components we have to use `event.preventDefault()` and `event.stopPropagation()`. It's not consistent because the use cases differ in these scenario's.

We don't really have plans to change that behaviour so going to close this issue.

If you really want to track clicks, then you can use the `capture` phase of your event handlers because usually we don't use those to `preventDefault`.

```js
  document.addEventListener('click', (e) => {
    const el = e.target
    if (!(el instanceof HTMLElement)) {
      return
    }
    if (el.matches('a, button')) {
      console.log('Tracked interaction:', el.textContent)
    }
  }, { capture: true })
```

**Comment by cyruscollier** [comment]
Thanks for your suggestion @RobinMalfait . I had used `{ capture: true }` in previous tests and it didn't seem to make any difference and was causing more issues (like triggering double events as such). However, now it does seem to be tracking everything fine with `{ capture: true }`, so I must have been doing something else wrong before. Keep up the great work you and the rest of the team is doing with this awesome library!
