### ISSUE TITLE
[BUG] TabList Tabs don't support child buttons with script setup

### ISSUE THREAD

**Issue by dpschen** [tailwindlabs/headlessui#1481]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.2

**What browser are you using?**

Chromium

**Reproduction URL**

https://stackblitz.com/edit/headless-ui-tabs-script-setup-button?file=src/MyButton.vue

**Describe your issue**

I want to use the headless UI tabs / Vue component.
Inside the TabList Tab components I want to use my button component that uses `script setup`:

```vue
<!-- MyButton.vue -->
<template>
  <button type="button">
    <slot />
  </button>
</template>

<!-- This does not work -->
<script setup lang="ts">
// something inside script tag so that it compiles
</script>
```

```vue
<!-- MyTabs.vue -->
<TabGroup>
  <TabList>
    <Tab as="template">
      <MyButton class="my-tab">Tab 1</MyButton>
    </Tab>
    <Tab>Tab 2</Tab>
    <Tab>Tab 3</Tab>
  </TabList>
  <TabPanels>
    <TabPanel>Content 1</TabPanel>
    <TabPanel>Content 2</TabPanel>
    <TabPanel>Content 3</TabPanel>
  </TabPanels>
</TabGroup>

<script setup>
import { TabGroup, TabList, Tab, TabPanels, TabPanel } from '@headlessui/vue';
import MyButton from './MyButton.vue';
</script>
```

When mounting the `MyTabs.vue` component I get the following error:

![image](https://user-images.githubusercontent.com/6173598/169530041-109b1bdf-89b4-4e3d-8180-29c2b98097fb.png)

When removing the `setup` attribute in the `MyButton.vue` component the error goes away.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The moment you use a `setup` function then nothing is "exposed" anymore (https://vuejs.org/api/sfc-script-setup.html#defineexpose), we do need access to the DOM node of the button so you have to make sure that you expose it again (here is a quick version of this): https://stackblitz.com/edit/headless-ui-tabs-script-setup-button-vad4bs?file=src/MyButton.vue

```vue
<script setup lang="ts">
// something inside script tag so that it compiles
import { expose } from 'vue';
expose({ $el: this });
</script>
```

**Comment by dpschen** [comment]
Wow, thank you so much!
I was aware of the `expose` function, but now that you need it to expose `$el`. Makes sense!
