### ISSUE TITLE
Hydration children mismatch error using Dialog

### ISSUE THREAD

**Issue by alehano** [tailwindlabs/headlessui#1485]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

"@headlessui/vue": "^1.6.2",
"nuxt": "3.0.0-rc.3"

**What browser are you using?**

Chrome

**Describe your issue**

I use Dialog component and get this error:

```
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Portal> 
  at <ForcePortalRoot force=true > 
  at <Dialog as="div" onClose=fn<close> open=false > 
  at <Modal open=false onClose=fn > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <Anonymous > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by ljnsn** [comment]
Hi, I encountered the same issue and made a minimal repository to reproduce it here: https://github.com/ljnsn/nuxt3-headlessui-hydration-bug

Could you please reopen?

**Comment by christophheich** [comment]
> Hi, I encountered the same issue and made a minimal repository to reproduce it here: https://github.com/ljnsn/nuxt3-headlessui-hydration-bug
> 
> Could you please reopen?
> 
> **Edit**: By the way, the error does not appear when wrapping `Dialog` in `ClientOnly`, so it's somehow SSR related.

I also encountered this issue, wrapping it in ClientOnly resolves it.

**Comment by alehano** [comment]
I think it's related to this issue https://github.com/nuxt/nuxt.js/discussions/10232
@RobinMalfait, would you check, please?
