### ISSUE TITLE
Using custom values in Combobox causes "Maximum recursive updates exceeded" warning

### ISSUE THREAD

**Issue by bakerkretzmar** [tailwindlabs/headlessui#1486]
**What package within Headless UI are you using?**

`@headlessui/vue`

**What version of that package are you using?**

v1.6.2

**What browser are you using?**

Firefox

**Reproduction URL**

Repo - fresh Vue/Vite app, just `npm i && npm run dev` and open in a browser: https://github.com/bakerkretzmar/headless-ui-recursive-issue

Codesandbox: https://codesandbox.io/s/places-combobox-forked-2eyihf?file=/src/App.vue

**Describe your issue**

The [Allowing custom values](https://headlessui.dev/vue/combobox#allowing-custom-values) example from the docs produces several hundred console warnings from Vue that the maximum recursive updates have been exceeded.

Typing anything into the combobox produces about a hundred warnings immediately, and then hovering over each option in the list logs an additional error or two every time.

**Comment by HeartwinJ** [comment]
I am facing the same issue on my project, and it seems to be the same on Firefox and Chrome.

**Comment by Kavehrafie** [comment]
Same here.

**Comment by thecrypticace** [comment]
This is a result of two things `:value="{ id: null, name: query }"` producing a new object every render and the internal active option tracking we do. We're going to update the documentation to recommend a `computed()` property wrapping that value to work around this. I'll leave this open until we've done that.

**Comment by RobinMalfait** [comment]
Hey!

We've updated the documentation to reflect the changes @thecrypticace mentioned. Hope this helps! https://headlessui.dev/vue/combobox#allowing-custom-values

I've also updated your CodeSandbox example that reflects the code changes: https://codesandbox.io/s/places-combobox-forked-5y8lt6?file=/src/App.vue

Hope this helps!

**Comment by bakerkretzmar** [comment]
Fantastic, thanks so much!
