### ISSUE TITLE
The closed event executes twice for Dialog components

### ISSUE THREAD

**Issue by druc** [tailwindlabs/headlessui#1490]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.6.2

**What browser are you using?**
Chrome, Firefox

**Reproduction URL**
https://github.com/druc/headlessui/pull/1/files

**Describe your issue**
When using a `Dialog` without specifying an `open` prop, the `closed` event fires twice when clicking outside the `DialogPanel`.

From my investigations the reason seems to be the outside click handler executing twice; even though the intention is to only do it once: https://github.com/tailwindlabs/headlessui/pull/1175

Replacing `queueMicrotask` with `setTimeout` fixes it but I'm not sure it's the *best* solution.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1546, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by chiuwah** [comment]
Hi, I am having the same problem with @headlessui/vue v1.7.16
Was this issue solved already?
