### ISSUE TITLE
Hydration children mismatch error when using Dialog component

### ISSUE THREAD

**Issue by christophheich** [tailwindlabs/headlessui#1496]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

"@headlessui/vue": "^1.6.2",
"nuxt": "3.0.0-rc.3"

**What browser are you using?**

Chrome, Firefox

**Reproduction URL**

https://github.com/ljnsn/nuxt3-headlessui-hydration-bug

**Describe your issue**

When using the Dialog component the following warning/error is shown:

```
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Portal> 
  at <ForcePortalRoot force=true > 
  at <Dialog as="div" onClose=fn<close> open=false > 
  at <Modal open=false onClose=fn > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <Anonymous > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

Wrapping Dialog in `ClientOnly` resolves this issue.

As @alehano stated, it might be related to this discussion/issue: https://github.com/nuxt/nuxt.js/discussions/10232

Some more informations regarding the same issue: https://github.com/tailwindlabs/headlessui/issues/1485

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Since the `Dialog` is always using a portal it is considered a client-only component and we don't have an SSR story for the `Dialog` component.

I would recommend to wrap the `Dialog` in a `ClientOnly` component if you want to use SSR without warnings 👍 

I don't think it is related to https://github.com/nuxt/nuxt.js/discussions/10232 because that happens if you create "illegal" HTML where an `<a>` is part of an `<a>` for example. In our case the Dialog is just rendering a handful of nested divs which is totally legal.

```html
<div id="headlessui-portal-root">
  <div data-headlessui-portal="">
    <!---->
    <div>
      <!---->
    </div>
    <!---->
  </div>
</div>
```

**Comment by ianjamieson** [comment]
If you are using Nuxt then you can just rename your component from `components/Dialog.vue` to `components/Dialog.client.vue`

**Comment by reimnm** [comment]
Nuxt 3.6.5 + pages
With moving <Dialog> tag into <client-only> tag issue fixed.
Dialog will crash <NuxtLink> tag. When link is clicked,  screen will not render the next page.

**Comment by rayalex** [comment]
> Nuxt 3.6.5 + pages With moving Dialog tag into client-only tag issue fixed. Dialog will crash NuxtLink tag. When link is clicked, screen will not render the next page.

Thanks, took me a while to figure out this is the issue. In case someone else needs to google this issue:

```
chunk-RAKT47ZN.js:9137 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
```

**Comment by recoiladam** [comment]
Just FYI for anyone else who gets here. The Menu, MenuItems and MenuButton also produced these warnings and should be wrapped in a <ClientOnly> only as well.

**Comment by spaceemotion** [comment]
I am getting the same with radio buttons, but I need them to exist during the static build as well :/ It makes sense for the counter to be incremental, but it breaks for static websites (astro in this case).
