### ISSUE TITLE
Can we add class after animate?

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/headlessui#150]
HI, let's take a look this demo[https://codesandbox.io/s/headlessuireact-menu-example-forked-d5h1x?file=/src/App.js]( https://codesandbox.io/s/headlessuireact-menu-example-forked-d5h1x?file=/src/App.js)
The menu not full height because of an empty div tag of Transition component, can we have a props which will apear after animate ex: defaultClass ?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I think a better solution might be to put your classes onto the `Transition` and `Transition.Child` components themselves:

https://codesandbox.io/s/headlessuireact-menu-example-forked-uobmr?file=/src/App.js

The noticeable differences here are:

### First change

From:

```jsx
<div className={state ? "fixed inset-0 overflow-hidden z-50" : "hidden"}>
  <Transition show={state}>
    {/* ... */}
  </Transition>
</div>
```

To:

```jsx
<Transition show={state} className="fixed inset-0 overflow-hidden z-50">
  {/* ... */}
</Transition>
```

### Second change

From:

```jsx
<section className="absolute inset-y-0 right-0 pl-10 max-w-full flex">
  <Transition.Child
    // ... all enter/leave classes
  >
    {/* ... */}
  </Transition.Child>
</section>
```

To:

```jsx
<Transition.Child
  as="section"
  // ... all enter/leave classes
  className="absolute inset-y-0 right-0 pl-10 max-w-full flex"
>
```


---

This will make the code a bit shorter, and should fix your issue. What do you think?
