### ISSUE TITLE
Combox : open dropdown on click

### ISSUE THREAD

**Issue by ootsun** [tailwindlabs/headlessui#1501]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1205

<div type='discussions-op-text'>

<sup>Originally posted by **ootsun** March  7, 2022</sup>
Hello,
I'm using combobox and I'd like that a click in the input causes the dropdown to open.
Is this comportement already implemented and I'm doing something wrong or is it normal that nothing happens on click?
![image](https://user-images.githubusercontent.com/25452154/157121622-b4f3dbd2-2365-49ab-8ecf-14cfda6df2ab.png)
</div>

**Comment by ootsun** [comment]
Workaround : https://github.com/tailwindlabs/headlessui/discussions/1205#discussioncomment-2822858

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Let's keep it in the discussions 👍 

But yeah currently we don't support that, the list will open the moment you start typing or use one of your arrow keys. Not on click / focus.
