### ISSUE TITLE
Menu item blur - since 1.6.0, next.js link

### ISSUE THREAD

**Issue by michalbundyra** [tailwindlabs/headlessui#1504]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.3 (issue since 1.6.0)

**What browser are you using?**

Chrome, Safari

**Reproduction Code**

```typescript
import { Menu } from '@headlessui/react'
import Link from 'next/link'

const MyMenu = () => (
  <Menu>
    <Menu.Button>Menu</Menu.Button>
    <Menu.Items as="ul">
      <MenuLink href="/profile" title="My profile" />
      <MenuLink href="/settings" title="Settings" />
      <Menu.Item as="li">
        <button type="button" onClick={logout}>Logout</button>
      </Menu.Item>
    </Menu.Items>
  </Menu>
)

const MenuLink = ({ href, title }: { href: string; title: string }) => (
  <Menu.Item as="li">
    <Link href={href}>
      <a onClick={(e) => e.currentTarget.blur()}>{title}</a>
    </Link>
  </Menu.Item>
)
```

**Describe your issue**

The issue is that with Next.js I had to add `onClick={(e) => e.currentTarget.blur()}` on links to close the menu on clicking the item.
It was all good until 1.6.0. Since this version it stopped working and I cannot find any workaround. Is it something to investigate on headlessui component or I should take another approach on this case?

It works as expected when I use normal `a` or `button`.

Thanks

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is that you are not forwarding all the incoming props from `<Menu.Item />` onto the `<a>` tag and the `<Link/>` component from Next.js doesn't forward those props either.

Create a custom `Link` component as described here: https://headlessui.dev/react/menu#integrating-with-next-js
