### ISSUE TITLE
Comboboxes in modal dialogs - Esc key not working

### ISSUE THREAD

**Issue by jdlien** [tailwindlabs/headlessui#1506]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.3

**What browser are you using?**

Chrome 101, Firefox 100

**Reproduction URL**

https://github.com/EPLibrary/esc-bug

**Describe your issue**

This project demonstrates a bug with comboboxes in modal dialogs in recent versions of
HeadlessUI. This applies to contexts such as TailwindUI's command palettes.

When the combobox input has focus, pressing esc does not close the dialog.

Pressing esc does work properly if you click just below the input inside of the modal.

HeadlessUI v.1.6.1 works fine, but v.1.6.2 does not.
You can test this by downgrading headlessui to v.1.6.1 and running npm install, then rebuilding this project.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Good catch! This was sort of a regression, sorry about that!

This should be fixed by #1511, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by jdlien** [comment]
Awesome! Thanks so much for fixing this so quickly.
