### ISSUE TITLE
`mergeProps` breaks event handlers with arity > 1

### ISSUE THREAD

**Issue by smithki** [tailwindlabs/headlessui#1513]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`v1.6.3`

**What browser are you using?**

Chrome, Safari, Firefox, etc. (affects all browsers)

**Reproduction URL**

Using `<Tab>` + `framer-motion`:

```tsx
import React, { useCallback } from 'react';
import { Tab } from '@headlessui/react';
import { motion } from 'framer-motion';

export function TabsTabsTabs() {
  const handleDragEnd = useCallback((event, panInfo) => {
    console.log(panInfo);
    // => undefined 😨
  }, []);

  return (
    <Tab.Group>
      <Tab.Panels>
        <Tab.Panel
          static
          as={motion.div}
          drag="x"
          dragConstraints={{ left: 0, right: 0 }}
          dragElastic={1}
          onDragEnd={handleDragEnd}
        >
          {/* Render the tab panel... */}
        </Tab.Panel>
      </Tab.Panels>

      <Tab.List>
        {/* Render the tab list... */}
      </Tab.List>
    </Tab.Group>
  );
}
```

This example behaves as expected in `v1.5.0`.

**Describe your issue**

I believe a regression was unintentionally introduced by [this change](https://github.com/tailwindlabs/headlessui/commit/3e19aa5c97f98aaa4106db3f8a2c9f9fb1ce8386#diff-2accd4971d1f1b1221a03cd2d5f32819219b780e3938a13dd6c496ac35df9ec6R219), where any prop prefixed with `on...` is assumed to be a function with arity of exactly 1. In a library like `framer-motion`, some native events are overloaded with additional arguments (`onDragEnd` is the example I'm highlighting here).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Very good catch, I didn't even know there were events that had additional parameters 😅 
This should be fixed by #1515, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
