### ISSUE TITLE
[BUG] Closing dialog from children button/onClick randomly freezes the app

### ISSUE THREAD

**Issue by lmlorca** [tailwindlabs/headlessui#1517]
What package within Headless UI are you using?

@headlessui/react

What version of that package are you using?

v1.6.3

What browser are you using?

Chrome

Reproduction
https://github.com/lmlorca/dialog-bug/blob/master/pages/components/Dialog.tsx

* Using the default example from https://headlessui.dev/react/dialog
* Add `active:bg-blue-400` and `transition-colors` to the button className.
* App sometimes freezes (at least in dev), after closing the modal clicking that button.

Description

Similar to this: https://github.com/tailwindlabs/headlessui/issues/1417 
BUT only happens (AFAIK) when the button has css `transition-all` / `transition-colors` and `active:bg-` modifier (at least, thats the minimum steps to reproduce it, using the default example from https://headlessui.dev/react/dialog)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1537, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
