### ISSUE TITLE
[DOCS]: React Dialog, replace `class` by `className`

### ISSUE THREAD

**Issue by matschik** [tailwindlabs/headlessui#1518]
In Dialog React documentation, replace `class` by `className` in snippet examples.
I checked all other component documentation, everything is good except Dialog component doc.
https://headlessui.dev/react/dialog

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We've updated the docs, they should be deployed soon!
