### ISSUE TITLE
RadioGroup: active state remains active even after focus has moved to next RadioGroup.Option

### ISSUE THREAD

**Issue by TommasoAmici** [tailwindlabs/headlessui#1521]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.3

**What browser are you using?**

For example: Firefox 101

**Reproduction URL**
https://github.com/TommasoAmici/headlessui-radiogroup-focus-bug

**Describe your issue**

When upgrading from v1.6.2 to v1.6.3, the `RadioGroup` component's behavior breaks.

When navigating with a keyboard, the `active` state remains active even after focus has
moved from one `RadioGroup.Option` to the next.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1522, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by TommasoAmici** [comment]
Super quick! Thanks!
