### ISSUE TITLE
[DOCS]: multiple is missing in component API section

### ISSUE THREAD

**Issue by aliazizi** [tailwindlabs/headlessui#1524]
multiple value is missing from component API section for select box

here is the link

https://headlessui.dev/react/listbox#listbox

**Comment by adamwathan** [comment]
Deploying updated docs as we speak, thanks!

**Comment by aliazizi** [comment]
@adamwathan I think default value should be `false`

**Comment by adamwathan** [comment]
Ah thanks, added!
