### ISSUE TITLE
Can not scrolling while popup over two dialog.

### ISSUE THREAD

**Issue by tianyingchun** [tailwindlabs/headlessui#1535]
**What package within Headless UI are you using?**
@headlessui/react 1.6.4

**What version of that package are you using?**
@headlessui/react 1.6.4

**What browser are you using?**

 Chrome
 
**Describe your issue**

1. popup one dialog
<img width="934" alt="image" src="https://user-images.githubusercontent.com/2833251/171181616-c4a20fc3-d3d9-4d7b-aff1-60de8a0289c3.png">
2. and then popup two
<img width="985" alt="image" src="https://user-images.githubusercontent.com/2833251/171181998-7be6acdd-f4f9-4d14-88fe-e85b5ec69e8b.png">
3.  close new popup.
<img width="966" alt="image" src="https://user-images.githubusercontent.com/2833251/171182116-434e4bdb-6195-47fa-95f8-dd5c3038bae8.png">

the body always keep `style="overflow: hidden; padding-right: 0px;"`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
