### ISSUE TITLE
Two Dialog use react context trigger close will result someone can not correct closed & wrong body overflow:hidden

### ISSUE THREAD

**Issue by tianyingchun** [tailwindlabs/headlessui#1539]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**
1.6.4

**What browser are you using?**

Chrome 

**Reproduction URL**

https://github.com/tianyingchun/headlessui
```shell
yarn install
yarn dev
http://localhost:3000/
```

**Describe your issue**
1. open dev  page
2. click `Open Sidebar`
3. and then click `open Bottomup`
4. and close bottomup
5. see `overflow: hidden;` could correctly removed from `body`

**Comment by ivanvanderbyl** [comment]
I'm having this issue as well. If I close the Dialog by clicking outside the `Dialog.Panel` it correctly closes and cleans up, however, if I close it by setting `open=false` it closes the panel by leaves the overlay and overflow: hidden style, making the app unusable.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Currently we don't support simultaneous dialogs that are not nested, we currently only support nested Dialogs that are nested inside one another to guarantee the order of the Dialog's.

Going to close this in favor of a discussion https://github.com/tailwindlabs/headlessui/discussions/1564
