### ISSUE TITLE
[DOCS]: Unused 'filteredPeople' in Combobox example.

### ISSUE THREAD

**Issue by roydigerhund** [tailwindlabs/headlessui#1547]
In the example for multiple values support in the Combobox documentation the dropdown uses `people` instead of `filteredPeople`.

https://headlessui.dev/react/combobox#selecting-multiple-values

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/10884413/171640337-8989cfa6-1e77-4c52-a3c7-90796abd93e6.png">

**Comment by adamwathan** [comment]
Ah good catch, pushing the change now! ❤️
