### ISSUE TITLE
Feature request: Option to add callback functions for the different animation stages.

### ISSUE THREAD

**Issue by SelvinM** [tailwindlabs/headlessui#155]
It would be very useful if we could do something like React Transition Group does https://reactcommunity.org/react-transition-group/transition#Transition-prop-onEnter 
with the props onEnter, onExit, onExiting, and onExited.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

Currently this has already been implemented, but not yet released. You can get it if you use `yarn add @headlessui/react@dev` or `npm install @headlessui/react@dev`.

You can find the documentation here: https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#props
