### ISSUE TITLE
Listbox - turn off Space keyboard key handling

### ISSUE THREAD

**Issue by dukkee** [tailwindlabs/headlessui#1554]
**What package within Headless UI are you using?** @headlessui/vue

**What version of that package are you using?** v1.4.1

**What browser are you using?** Chrome

**Describe your issue**

I implemented a simple search block inside Listbox, but I can't enter Space into this search input due to the existed Space handling.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is by design, you can think of a `Listbox` as a `<select>`. We are not going to change this behaviour.
You probably want to look at a Combobox instead: https://headlessui.dev/vue/combobox

**Comment by dukkee** [comment]
@RobinMalfait Thank you a lot, yes, you are right, Combobox looks fine and more suitable for my case at the first glance.
