### ISSUE TITLE
Custom "as" component provided to Combobox.Input makes text disappear

### ISSUE THREAD

**Issue by FezVrasta** [tailwindlabs/headlessui#1558]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.6.4

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/cranky-dawn-jjskze?file=/src/App.js

**Describe your issue**

If I define a simple input component (`const Input = props => <input {...props} />`) and provide it to `Combobox.Input`'s `as` property, its `value` is not populated anymore.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You get a warning in the console:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

Make sure to use a forward the ref: https://codesandbox.io/s/agitated-payne-ycl9zd

**Comment by RobinMalfait** [comment]
Your example is still a bit confusing to me, however you can use the `refName` prop to rename the ref. I created a new CodeSandbox with your new changes and the `refName` prop: https://codesandbox.io/s/red-sunset-0nqzd9?file=/src/App.js:1403-1436

Hope this helps!

**Comment by FezVrasta** [comment]
Thanks! Is this documented anywhere? Would you mind linking me the relative doc page please?

**Comment by Birssan** [comment]
Hi,
I'm looking to achieve the same thing with Vue, is there a way to forward the ref as the "inputRef" is not set if you use your own component as ComboboxInput ?

Thanks

**Comment by solodukhin-e** [comment]
@RobinMalfait, can you help with same problem in vue?

**Comment by RobinMalfait** [comment]
@Birssan @solodukhin-e Hey, if this is still an issue for you could you open a new issue with a minimal reproduction repo / CodeSandbox attached that showcases the issue? Thanks!
