### ISSUE TITLE
[react][safari] Funky outline paddings in Listbox items

### ISSUE THREAD

**Issue by janniks** [tailwindlabs/headlessui#156]
There is some empty space between a selected/focused item and the outline (above and below item, on click). This does not exist on Chrome.

![headlessuireact-listbox-example-safari](https://user-images.githubusercontent.com/6362150/100368840-5e98b280-3004-11eb-935f-5fd109fd7938.gif)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You are in control of the rendering part os this is not an issue of Headless UI.
That said, it seems that it is not related to padding, but that it is some sort of outline/focus ring that is happening.

**Comment by janniks** [comment]
Got it, maybe this is a tailwind issue - the screengrab is from the headless ui example sandbox...
