### ISSUE TITLE
Dialog not closing when clicking near outer edges of parent container

### ISSUE THREAD

**Issue by Natas0007** [tailwindlabs/headlessui#1565]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

@headlessui/react v1.6.4
tailwindcss v3.0.24

**What browser are you using?**

Reproduced in latest Chrome, Edge, & Firefox

**Reproduction URL**

https://headlessui.dev/react/dialog (reference included image for illustration of behavior)

**Describe your issue**

As illustrated in the below image, clicking in the area outside of the highlighted area does not close the Dialog.  I discovered this after noticing that one of my full-height right-side slide-in dialogs was not closing when clicking around the outside edges of the entire window.  This is not that big of a deal on desktop, but on mobile, it forces the user to use the close button inside of the Panel instead of clicking just to the left of the slide-in dialog to get it closed.  I'm assuming this is not by design, but if it is, how can I force any clicked pixel inside of the parent container to close the dialog.  Thank you for your time and you guys rock!  I love everything tailwind!

![Dialog-Not-Closing-Example-From-Docs](https://user-images.githubusercontent.com/5757764/172700217-d2494041-4293-4cfd-a437-155de73efc66.jpg)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should already be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

I'll bump the versions in the docs, thanks!
