### ISSUE TITLE
[react] beforeEnter afterEnter beforeLeave afterLeave dont exist

### ISSUE THREAD

**Issue by g0shed** [tailwindlabs/headlessui#157]
these callbacks don't exist, but they are in the documentation

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

They do exist, but they the new version has not been published yet.
Will do this soon!

**Comment by gthmb** [comment]
hello, is this released yet? I see some references to them in the 0.2.0 source code, but I don't think they are available props as the docs describe. thanks!

**Comment by RobinMalfait** [comment]
@gthmb it's not released on the "latest" tag, but you can use it with the "dev" tag: `yarn add @headlessui/react@dev` or `npm install @headlessui/react@dev`.

**Comment by gthmb** [comment]
@RobinMalfait cool, thanks!
