### ISSUE TITLE
Combobox (autocomplete) active entry

### ISSUE THREAD

**Issue by brampurnot** [tailwindlabs/headlessui#1575]
hi all!

Love these components btw 🥇 ! I'm currently implementing the combobox for an autocomplete use-case and I'm struggling with the following:
the first element in the list is automatically set to active. Is there a way to not select anything?

I have tried with the nullable option but for some reason it keeps on activating the first element. Since we want to use this in a search functionality, it would want it to not be active unless the user selects it.

Any help is appreciated!
Bram

**Comment by nrgnrg** [comment]
You can add a `Combobox.Option` as the first item with a class of `invisible` to achieve this

**Comment by PrajwalPrashanth** [comment]
By `active`, do you mean `selected`? If you are following the examples https://headlessui.com/react/combobox#basic-example, it would have default selected value as the first element. If this is the case you should set a null default state for your Combobox value

```
const [selectedPerson, setSelectedPerson] = useState(people[0]) # shown in example

const [selectedPerson, setSelectedPerson] = useState() # use this instead
```
