### ISSUE TITLE
Manually showing/hiding the popover - open() is not a function

### ISSUE THREAD

**Issue by JoeriTheGreat** [tailwindlabs/headlessui#1598]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.6.4

**What browser are you using?**
Chrome and FIrefox

**Reproduction URL**
https://stackblitz.com/edit/vitejs-vite-gxxbua?file=src%2FApp.vue

**Describe your issue**
Using the provided docs https://headlessui.dev/vue/popover#showing-hiding-the-popover
I'm trying to manually open/close the popover @mouseover or even @click
Closing the popoverPanel is no issue but when i try to do the same with open() i get an console error open() is not a function

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is not a bug, the `open` value you get from the `v-slot` is the current state of the popover whether or not it is open (a boolean).

Currently we don't have the functionality to manually open a popover, you can only open it via a `PopoverButton`.

**Comment by oripka** [comment]
Workaround manually triggering click on invisible button 

```
<template>
    <div>
        <Popover v-slot="{ open }" class="relative">
            <PopoverButton class="hidden" ref="button"></PopoverButton>
            <Combobox>
                <ComboboxInput @click="openMegaMenu()"/>
                <TransitionRoot>
                    <ComboboxOptions>
                        <ComboboxOption>
                        </ComboboxOption>
                    </ComboboxOptions>
                </TransitionRoot>
            </Combobox>
            <SearchMegaMenu :isopen="open" />
        </Popover>
    </div>
</template>

<script setup>
import {
    Combobox,
    ComboboxInput,
    ComboboxButton,
    ComboboxOptions,
    ComboboxOption,
    TransitionRoot,
    PopoverButton,
    Popover
} from "@headlessui/vue";

const button = ref(null);

function openMegaMenu(val) {
    let el = button.value.$el
    el.click()()
}
</script>
```

**Comment by andirsun** [comment]
You can also emulate a click using ```ref```, this is an example to open the popover hovering the button instead of clicking it.
```
import { Popover } from '@headlessui/react'

function MyPopover() {
  const [buttonRef, setButtonRef] = useState<HTMLButtonElement | null>(null)
  
  return (
    <Popover className="relative">
      <Popover.Button
         ref={setButtonRef}
         onMouseEnter={() => buttonRef && buttonRef.click()}
      >Solutions</Popover.Button>

      <Popover.Panel className="absolute z-10">
        /// Content
      </Popover.Panel>
    </Popover>
  )
}
```
So this is going to open when you hover the button (click also works and close has default behavior)
