### ISSUE TITLE
Dialog.Overlay does not stop propagation

### ISSUE THREAD

**Issue by binajmen** [tailwindlabs/headlessui#1601]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.4

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/headlessui-popover-overlay-mobile-y3dsic?file=App.tsx

**Describe your issue**

When clicking outside the `Dialog`, the element behind the overlay is activated on mobile (part 1 of the short clip). It seems to stop the propagation on Desktop (part 2 of the short clip – I'm clicking a second time to show the alert).

https://user-images.githubusercontent.com/15611419/174426145-f95bb251-53bf-4efa-b313-65895827fd09.mov

It has already been reported for Popover: https://github.com/tailwindlabs/headlessui/issues/1418. Perhaps similar solution/issue?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should have already been fixed by #1546, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
