### ISSUE TITLE
Option to prevent scroll on return focus to dropdown trigger button when menu closed (dropdown menu)

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/headlessui#161]
The page sometimes shifts scroll position when dropdown closes which is less than ideal . There is a preventScroll option that you can provide to the focus method to prevent this. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

**Comment by rsstiglitz** [comment]
Anyone know why this got removed again?
