### ISSUE TITLE
Would you like to create headless components for svelte ? 

### ISSUE THREAD

**Issue by mitya-borodin** [tailwindlabs/headlessui#162]

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are first focusing on React & Vue components, so I can't give you a good answer on this one.
Maybe in the future!

**Comment by shajidhasan** [comment]
Any update?

**Comment by apyredev** [comment]
Support for svelte would be so cool!

**Comment by allochi** [comment]
Tailwind has a lot of love and attention from Svelte developers, couldn't you open some guidelines for us to help you add one?

**Comment by bugproof** [comment]
@chumleesockson 
yup still in beta https://github.com/sveltejs/kit/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0+sort%3Aupdated-desc
someone has started the work https://github.com/mattjennings/headlessui-svelte but it supports only 1 component looking at the readme

**Comment by benmccann** [comment]
A Svelte implementation has been created here: https://github.com/rgossiaux/svelte-headlessui

**Comment by alec-c4** [comment]
@RobinMalfait it would be nice if @tailwindlabs can join their forces with author of https://github.com/rgossiaux/svelte-headlessui

**Comment by eliasdefaria** [comment]
Would love for Svelte support! Currently using -> https://github.com/rgossiaux/svelte-headlessui

**Comment by akbog** [comment]
Has there been any headway in implementing Svelte Support?

**Comment by rohanrajpal** [comment]
A new headless UI library is out with a much more Sveltier way of doing things!
https://github.com/captaincodeman/svelte-headlessui

**Comment by eliasdefaria** [comment]
> A new headless UI library is out with a much more Sveltier way of doing things! https://github.com/captaincodeman/svelte-headlessui

Niiiice. Will give this a go

**Comment by noxware** [comment]
+1 to support Svelte

**Comment by greendesertsnow** [comment]
Svelte support please

**Comment by cupcakearmy** [comment]
I agree with @jiri
Also maybe one could talk to @captaincodeman as they already made the amazing efford to bring it to svelte, so it's just a matter of brining on the package, and then of course the work mantaining it.

**Comment by eliasdefaria** [comment]
I'd also be very willing to contribute to an official Svelte port. Svelte is on the rise :)

**Comment by CaptainCodeman** [comment]
> I agree with @jiri Also maybe one could talk to @CaptainCodeman as they already made the amazing efford to bring it to svelte, so it's just a matter of brining on the package, and then of course the work mantaining it.

My focus was on making the bundle size as small as possible and exploring an alternative "sveltier" approach (stores + actions instead of wrapper components and slots, which help with reducing the bundle size and I find simpler to consume).

I think the approach works but it's really missing thorough unit testing right now which I have on my TODO list (just been busy with work projects). Ideally the testing system would be made less framework specific to make correctness and consistency across all implementations easier.

**Comment by mdkq** [comment]
+1

**Comment by wesharper** [comment]
Just started a new project with SvelteKit and realizing how heavy a lift it is to do certain things using TailwindUI without svelte primitives. I was naive in thinking that the html versions of components would be easily reproducible. It's fine for some things, but for interactive elements like comboboxes and for transitions, finding the right combination of third-party libraries and custom work vs just going down a different road altogether has been a struggle.

**Comment by rohanrajpal** [comment]
> Just started a new project with SvelteKit and realizing how heavy a lift it is to do certain things using TailwindUI without svelte primitives. I was naive in thinking that the html versions of components would be easily reproducible. It's fine for some things, but for interactive elements like comboboxes and for transitions, finding the right combination of third-party libraries and custom work vs just going down a different road altogether has been a struggle.

I have given up on Tailwind UI for Svelte, tho its fair, they have a lot on their plate and might get to this sometime later.

That being said, have really good hopes from Melt UI: https://github.com/melt-ui/melt-ui

It's the closest to a complete headless library

**Comment by wesharper** [comment]
Nice, thanks! I'll take a look.

**Comment by tamaro-skaljic** [comment]
Now that [vanilla javascript support for Tailwind Plus has been released](https://tailwindcss.com/blog/vanilla-js-support-for-tailwind-plus), I'm wondering if this issue should be re-evaluated.

I would like to purchase a Tailwind Plus license, but I am unsure how much work it is to use it in SvelteKit with Svelte 5 or if it would be better to create a Svelte version.
