### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by Manubi** [tailwindlabs/headlessui#1625]
Hi,

@headlessui/react: ^1.6.5
<img width="927" alt="CleanShot 2022-06-28 at 14 38 54@2x" src="https://user-images.githubusercontent.com/20935138/176180514-2b942a38-47a9-40a8-8d40-dcc7ab8911ed.png">

<img width="962" alt="CleanShot 2022-06-28 at 14 33 51@2x" src="https://user-images.githubusercontent.com/20935138/176179616-fb61a4cf-d7a6-422f-93dd-d0fe81215146.png">

I do get this Type Error. I am using turborepo with it. No clue why it doesn't pick up the type anymore. 

Thanks for the help!

**Comment by wking-io** [comment]
@Manubi what did you find out here?

**Comment by Manubi** [comment]
My problem was I am using Tailwind within a monorepo. And somehow the vite version from my ui package was different to the webapp package. So basically it was a version issue. Typescript was checking the types for the older vite version.
