### ISSUE TITLE
[React] `as` prop with typescript requires specifying generic value.

### ISSUE THREAD

**Issue by hailwood** [tailwindlabs/headlessui#1627]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.6.5

**What browser are you using?**
N/A

**Reproduction URL**
https://codesandbox.io/s/nervous-night-mstohd?file=/src/App.tsx

**Describe your issue**
We cannot use the `as` prop on any headless ui elements without manually specifying the generic value.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Adding `"esModuleInterop": true` to your `tsconfig.json` seems to fix your issue. I don't know what other things `react-scripts` is doing behind the scenes, but this resolves it.

Here is an updated CodeSandbox: https://codesandbox.io/s/magical-lumiere-ymwugf?file=/tsconfig.json:494-526
