### ISSUE TITLE
Unmount option not working

### ISSUE THREAD

**Issue by NSpehler** [tailwindlabs/headlessui#163]
Hello there,

It seems like the `unmount` option is not working as documented when using @headlessui/react 0.2.0.

When using the following:
`<Transition show={show} unmount={false}>`

I'm getting this console warning:
`Warning: Received false for a non-boolean attribute unmount.`

And instead of being hidden, the component is removed from the state altogether.

Let me know if you need any further information!

**Comment by roydigerhund** [comment]
I've run into the same problem. 

In my case, the unmount of the component is not waiting for the leave transition to finish. I tried to fix it with the unmount attribute but got the same error.

Maybe these two problems have something in common.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `unmount`, and the "events" for `beforeEnter` and friends do exist, but they the new version has not been published yet.
You can try the dev version `yarn add @headlessui/react@dev`

Will be publishing a new version soon!
