### ISSUE TITLE
[React] `Dialog` closes when I release the mouse click outside of the dialog

### ISSUE THREAD

**Issue by carlwood** [tailwindlabs/headlessui#1646]
**What package within Headless UI are you using?**

 @headlessui/react

**What version of that package are you using?**

v1.6.5

**What browser are you using?**

Chrome, Safari

**Reproduction URL**

https://headlessui.com/react/dialog

**Describe your issue**

When I start selecting text and dragging my cursor (left click down) inside the dialog but then I release it (left click up) outside the dialog, the dialog closes. I expect the dialog to stay open because I didn't left-click (or tap) outside the modal. See video below

https://user-images.githubusercontent.com/596820/177365818-393238e0-584c-458f-94da-99b301a560c9.mov

**Comment by agusterodin** [comment]
I thought I was going crazy when I recently started noticing this. This is definitely new, uninntended behavior.

It is also present on the Popover component.

**Comment by thecrypticace** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should have already been fixed by #1667, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by Voyager-Two** [comment]
This is a pretty serious bug, when will the next release be?
Kind of ridiculous that we have to wait months for this fix or use "insiders" version.

**Comment by Aravinda93** [comment]
@carlwood @Voyager-Two 

I am facing similar issue when I access `DialogPanel2.vue` via `DialogPanel1.vue` then it for some reason automatically closes the `DialogPanel1.vue`.

Issue recreation: [Codesandbox](https://codesandbox.io/p/devbox/headlessui-dialog-multiple-modals-bugs-forked-o2ykb?file=%2Fpages%2Findex.js)
Issue posting: https://github.com/tailwindlabs/headlessui/discussions/3199

Can you please once have a look and provide some suggestions or workarounds?
