### ISSUE TITLE
Vue Dialog does not have a fade in effect while the React example does

### ISSUE THREAD

**Issue by AdamT** [tailwindlabs/headlessui#1655]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

I'm guessing you're using latest?

**What browser are you using?**

Chrome 103

**Reproduction URL**

Visit https://headlessui.com/vue/dialog and view the modal fade in effect. Notice there's a fade out, but no fade in. The react version has both fade in and fade out. 

**Describe your issue**

The Vue Dialog example does not seem to have a fade in while the React example does

https://user-images.githubusercontent.com/641502/178130231-176a8433-ca2e-4a05-961e-3d2b0214e3c5.mov

**Comment by thecrypticace** [comment]
Reproducible: Chrome/Edge/FF
Not Reproducible: Safari

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1664, and is available in the latest release 1.6.7.

You can already try it using `npm install @headlessui/vue@latest`.
