### ISSUE TITLE
Possible bug: Dialog click outside won't work if nested

### ISSUE THREAD

**Issue by osddeitf** [tailwindlabs/headlessui#1657]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome

**Describe your issue**

I created a custom Modal component with Tailwindcss:
```ts
import { PropsWithChildren } from 'react'
import { Dialog } from '@headlessui/react'

interface ModalProps {
  open: boolean
  onClose: () => void
}

export default function Modal(props: PropsWithChildren<ModalProps>) {
  const { open, onClose, children } = props

  return (
    <Dialog open={open} onClose={onClose}>
      {open && (
        <>
          {/* The backdrop, rendered as a fixed sibling to the panel container */}
          <div className="fixed inset-0 bg-black/30" aria-hidden="true" />

          {/* Full-screen container to center the panel */}
          <div className="fixed inset-0 flex items-center justify-center">
            {/* The actual dialog panel. TODO: custom width, height */}
            <Dialog.Panel className="mx-auto w-full max-w-lg rounded overflow-hidden">
              <div className='overflow-auto max-h-screen md:max-h-[80vh] bg-white'>
                {children}
              </div>
            </Dialog.Panel>
          </div>
        </>
      )}
    </Dialog>
  )
}
```
Then tried something like this:
```jsx
<Modal open={open} onClose={() => setOpen(false)}>
  <div className='w-64 h-32 bg-white'/>
  <Modal open={false} onClose={() => {}} />
</Modal>
```
Problem: click outside the modal won't close it. The nested modal (if opened) can still click outside to close.
I think it because the click outside events are conflicted somehow.

**Comment by shasank2** [comment]
Here is what I did... I added a their Transition wrapper in your Dialog and passed the open prop to the Transition wrapper.

 <Transition appear show={open} as={Fragment}>
        <Dialog onClose={onClose}>
          {open && (
            <>
              {/* The backdrop, rendered as a fixed sibling to the panel container */}
              <div className="fixed inset-0 bg-black/30" aria-hidden="true" />

              {/* Full-screen container to center the panel */}
              <div className="fixed inset-0 flex items-center justify-center">
                {/* The actual dialog panel. TODO: custom width, height */}
                <Dialog.Panel className="mx-auto w-full max-w-lg rounded overflow-hidden">
                  <div className='overflow-auto max-h-screen md:max-h-[80vh] bg-white'>
                    {children}
                  </div>
                </Dialog.Panel>
              </div>
            </>
          )}
        </Dialog>
      </Transition>

**Comment by shasank2** [comment]
Here is what i did.. Wrapped your dialog with a Transition and passed your open state to its show prop.

      <Transition appear show={open} as={Fragment}>
        <Dialog onClose={onClose}>
            <>
              <div className="fixed inset-0 bg-black/30" aria-hidden="true" />
              <div className="fixed inset-0 flex items-center justify-center">
                <Dialog.Panel className="mx-auto w-full max-w-lg rounded overflow-hidden">
                  <div className='overflow-auto max-h-screen md:max-h-[80vh] bg-white'>
                    {children}
                  </div>
                </Dialog.Panel>
              </div>
            </>
        </Dialog>
      </Transition>

**Comment by osddeitf** [comment]
@thecrypticace I tried the new package and saw it fixed now. Thank you for your hard work.
