### ISSUE TITLE
[ReactJs] - Dialog - html style overflow:"hidden" not removed when Dialog is closed

### ISSUE THREAD

**Issue by bde-maze** [tailwindlabs/headlessui#1658]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**

"^1.6.6"

**What browser are you using?**

Chrome

**Reproduction URL**

---

**Describe your issue**

When a Dialog is opened, <html/> tag get style attribute set to "overflow:'hidden';" so the scroll is disabled in the background. However, it is not set back to auto when the Dialog is closed and thus prevent user from scrolling normally in the page after. Needing a page full reload to reset style attribute.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/15313830/178271144-e280cb40-46fc-4d94-80a7-9a506b41df3c.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
