### ISSUE TITLE
1.6.6 breaks tabbing for a datetime field in a modal

### ISSUE THREAD

**Issue by davecarlson** [tailwindlabs/headlessui#1665]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.6.6

**What browser are you using?**
Chrome

**Describe your issue**

In 1.6.5 and below, if you had a datetime field, like below in a modal
```
<input type="datetime-local" />
```
Then when you clicked in and pressed tab, it would tab between the different parts of the date as expected. Since 1.6.6, pressing tab skips to the next field.

I suspect it is something to do with the changes in https://github.com/tailwindlabs/headlessui/pull/1440 to resolve https://github.com/tailwindlabs/headlessui/issues/467

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I can't seem to reproduce this: https://ci3hks.csb.app/

Please open an issue with a minimal reproduction repo attached or a CodeSandbox.
