### ISSUE TITLE
Prevent Image redownload in <Transition>

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/headlessui#168]
Hi, I am using <Transition>, it work fine. But the image inside <Transition> will be redownloaded. 
I don't know how to fix, I tried with React.memo but look like it not work. Is there any solution? 
In production, image will get delay show time.

**Comment by mattgreenfield** [comment]
I would expect this to be served from the browser cache. Do you have a demo link to share?

**Comment by matthieudou** [comment]
From my understanding, you could use the `unmount` prop. This will prevent the re-rendering of the image and thus the download. 
https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#props

**Comment by IRediTOTO** [comment]
![cYZ56JSMta](https://user-images.githubusercontent.com/15695252/101473538-867d0400-397c-11eb-9d0a-d7559f3013d8.gif)
Hi here is demo. I remove Transition component and use show hide class, it's fine now, just not have animation.

**Comment by IRediTOTO** [comment]
@matthieudou let's me try

**Comment by IRediTOTO** [comment]
@matthieudou it worked, thank you. But what is the keyword for this problem? I think missed knowledge about this.

**Comment by matthieudou** [comment]
What the transition component is doing by default is removing the elements inside the transition from the dom after the transition finished. So when you transition back, the elements are added again to the dom. If you have an image inside, the browser will see it as an image and download the image.

By setting the `unmount` prop to `false` you're basically saying to the `<Transition>` component to not "remove" the content from the dom but just putting an attribute `hidden` on the element.

Both approaches have their advantages and disadvantages.
Hope it answers your question

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

What @matthieudou describes is entirely correct. By default we have an `unmount` strategy that destroys the DOM completely. But if you have a form inside with some state or you have images like what you are experiencing, then it might be better to use the `hidden` strategy by setting `unmount={false}`.

Note: This currently exists in the `dev` build on npm, not yet on the latest version. I'll try my best to release this asap. But for now you would have to use `npm install @headlessui/react@dev`.
