### ISSUE TITLE
[React] `Combobox.Input` missing `disabled` prop

### ISSUE THREAD

**Issue by 0kzh** [tailwindlabs/headlessui#1697]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome

**Issue**

There's no way to disable a `Combobox.Input` - the component accepts a `disabled` prop due to extending the type here

<img width="425" alt="Screen Shot 2022-07-18 at 10 41 31 PM" src="https://user-images.githubusercontent.com/9621004/179652660-5898dc39-9b30-4cfa-bb94-9181bfaea831.png">

but this doesn't actually disable the input component. If you disable it via inspect element it works as expected.

This is probably to the prop not being passed down to the original `<input/>` component?

**Comment by JesusTheHun** [comment]
The parent `Combobox` accepts the property `disabled` and will disable the input by itself.
If this does not solve your issue, can you please describe your use case ?

**Comment by 0kzh** [comment]
This worked! Could use some more documentation on this though 👍
