### ISSUE TITLE
[React] Button in Menu.Item won't fire click events if not wrapped

### ISSUE THREAD

**Issue by impulse** [tailwindlabs/headlessui#17]
![image](https://user-images.githubusercontent.com/8146736/94397628-85ea1500-0164-11eb-8a9b-74db4f13dee6.png)

Sandbox: https://codesandbox.io/s/headlessuireact-menu-example-forked-c8fjs?file=/src/App.js:2732-2747

**Comment by RobinMalfait** [comment]
Hey, thank you for your bug report!
This has already been fixed in version `0.1.2`: https://codesandbox.io/s/headlessuireact-menu-example-forked-l91ve
