### ISSUE TITLE
Support for nested Menus

### ISSUE THREAD

**Issue by mrodrigues95** [tailwindlabs/headlessui#170]
Hi,

This is somewhat related to #152 

Are there any plans for supporting nested menus? My current use case is that when you select a menu item I need to re-render the list of items in the menu and show them without closing it. This is pretty straight forward but the issue is the menu closes on the first click.

I'm aware I can handle the open state manually but then I need to deal with handling outside clicks, etc. which is already managed by Headless UI.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This is something we want to support, but I can't give you an ETA on this.
We will first focus on other components, but we will get back to this.

**Comment by benknight** [comment]
+1

**Comment by benknight** [comment]
I think this would be rather easy to implement manually if you just provided a way to open a menu programmatically. As of now it can only be opened by clicking on Menu.Button. Just provide an `open` prop on the Menu component, then we can just render another Menu inside Menu.Item and pass the `active` render prop to the Menu's  `open` prop.  Wouldn't that work?
