### ISSUE TITLE
Click Outside broken on iOS

### ISSUE THREAD

**Issue by kevinmlong** [tailwindlabs/headlessui#1707]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.67

**What browser are you using?**

Safari Mobil on iOS 15

**Reproduction URL**

https://github.com/kevinmlong/headlessui-dialog-bug

**Describe your issue**

Clicking outside a dialog does not close the dialog. Functionality works fine on a desktop browser, but on iOS the touch event outside of the dialog (on the backdrop) does not close the dialog.

Steps to Reproduce:

> - Clone repo
> - Run `npm install`
> - Run `npm run dev`
> - Test functionality in a desktop
> - Test functionality on a device by visiting {{IP-ADDRESS}}:{{PORT}} provided by Vite in terminal

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1712, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
