### ISSUE TITLE
Clicking between sibling menus

### ISSUE THREAD

**Issue by pikeas** [tailwindlabs/headlessui#171]
https://codesandbox.io/s/headlessuireact-menu-example-forked-60ohj

Alternate clicking between the two menus and you'll see that the focus highlighting gets confused. This may be related to how each instance of the component handles clicking away?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you test if it still happens with `yarn add @headlessui/react@dev`?

Duplicate of: https://github.com/tailwindlabs/headlessui/issues/166

**Comment by pikeas** [comment]
Sorry for the dupe, and yes, confirmed fixed!
