### ISSUE TITLE
[React, Combobox, Multiple] InputValue disappear when select an option.

### ISSUE THREAD

**Issue by byunghun-jake** [tailwindlabs/headlessui#1720]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.6.6

**What browser are you using?**
Chrome

**Reproduction URL**
https://codesandbox.io/s/combobox-d0pbl6?file=/src/App.tsx

**Describe your issue**
When i select an option, Combobox.Input's value has gone.

``` jsx
<Combobox value={selectedSources} onChange={setSelectedSources} multiple>
  <ul>
    {selectedSources.map((source) => (
      <li key={source.id}>{source.name}</li>
    ))}
  </ul>
  <Combobox.Input
    onChange={(event) => {
      setSourceQuery(event.target.value);
    }}
  />
  <Combobox.Options>
    {filteredData.map((source) => (
      <Combobox.Option key={source.id} value={source}>
        {source.name}
      </Combobox.Option>
    ))}
  </Combobox.Options>
</Combobox>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You want to make sure to provide a `displayValue` prop to control the contents of the input: https://headlessui.com/react/combobox#selecting-multiple-values
