### ISSUE TITLE
Dialog/Modal: Highlighting some text is prone to close the modal accidentally

### ISSUE THREAD

**Issue by PhilippSchoenauer** [tailwindlabs/headlessui#1724]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

 v1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

This happens on the official example on your website too:
https://headlessui.com/examples/react-dialog-hero

**Describe your issue**

If the dialog is open, and i want to highligh some text but accidentaly drag the mouse outside of the modal, it closes automatically.
This is especially cumbersome if the modal includes a form, where in this case the complete user provided input is lost.

![Animation](https://user-images.githubusercontent.com/56018578/181698538-e0715644-8916-4743-aa07-ea2128224837.gif)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should already have been fixes by https://github.com/tailwindlabs/headlessui/pull/1667, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
