### ISSUE TITLE
[DOCS]: FocusTrap is not documented anywhere except the initial pull request

### ISSUE THREAD

**Issue by msdrigg** [tailwindlabs/headlessui#1727]
I see FocusTrap is an exported component, but it isn't documented anywhere except in the initial pr #220 where it was created

Should this be documented, or is the lack of documentation intentional

**Comment by adamwathan** [comment]
Hey! It’s only exported so we can reuse it internally, it’s not public API and not subject to semver which is why it’s not documented.
