### ISSUE TITLE
Listbox (React) not working (Safari)

### ISSUE THREAD

**Issue by saratonite** [tailwindlabs/headlessui#173]
Listbox (react) not working on safari 12.1 Mojave

**Comment by pmualaba** [comment]
Same here on iPhone 6 iOS 12
The option list does not open when clicking on the select box

**Comment by ebuckthal** [comment]
I'm guessing this is because of those browsers [lack of support for PointerEvents](https://caniuse.com/?search=pointer%20events). See https://github.com/tailwindlabs/headlessui/issues/167

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed related to pointer events, I implemented fallbacks thus this should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
