### ISSUE TITLE
Calling Menu.Button via ref doesn't show the menu

### ISSUE THREAD

**Issue by mrodrigues95** [tailwindlabs/headlessui#174]
I'm trying to persist the menu state and keep the menu open when an item is selected so I can show different items.
To do this, I've attached a ref to `Menu.Button` and I am calling `menuRef.current?.click()` to show the second set of items as so:
```
 useEffect(() => {
    if (showDiscussionsMenu) menuRef.current?.click();
  }, [showDiscussionsMenu]);
```
The problem is after calling `menuRef.current?.click()` the second menu will not show despite the button being clicked. I've also logged the `onClick` event for `Menu.Button` and it is being hit.

Here is the rest of the code I am working with:
```
      <Menu>
        {({ open }) => (
          <>
            {/* @ts-ignore */}
            <Menu.Button ref={menuRef} onClick={() => console.log('Menu button clicked!')}>
              {showDiscussionsMenu ? 'Discussions' : 'Classrooms'}
            </Menu.Button>
            <Menu.Items>
              <Menu.Item>
                {({ active }) => (
                  <span
                    className={`${
                      active ? 'bg-gray-100 text-gray-900' : 'text-gray-700'
                    } flex justify-between w-full px-4 py-2 text-sm leading-5 text-left`}
                    onClick={() => handleOnClick(open)}
                  >
                    {showDiscussionsMenu ? 'Discussion 1' : 'Account settings'}
                  </span>
                )}
              </Menu.Item>
              <Menu.Item>
                {({ active }) => (
                  <span
                    className={`${
                      active ? 'bg-gray-100 text-gray-900' : 'text-gray-700'
                    } flex justify-between w-full px-4 py-2 text-sm leading-5 text-left`}
                    onClick={() => handleOnClick(open)}
                  >
                    {showDiscussionsMenu ? 'Discussion 2' : 'New page'}
                  </span>
                )}
              </Menu.Item>
            </Menu.Items>
          </>
        )}
      </Menu>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

I wonder what your exact use case is. What do you mean with "so I can show different items"?
This menu is intended to not have state and act like a menu dropdown with a bunch of links.
So typically you would navigate away or something similar.

**Comment by mrodrigues95** [comment]
Your point about the menu makes more sense now because I was trying to implement a dynamic menu. I decided to make my own menu for this specific use case and will continue to use headless ui for stateless dropdown menus.

Thanks!

**Comment by RobinMalfait** [comment]
Perfect!
