### ISSUE TITLE
`aria-controls` removed from `Disclosure.Button` when using `static` on `Disclosure.Panel`

### ISSUE THREAD

**Issue by Bjodol** [tailwindlabs/headlessui#1741]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Edge, Chrome

**Reproduction URL**

https://github.com/Bjodol/headless-ui-disclosure-bug

**Describe your issue**

When using the `<Disclosure>` component along with `<Disclosure.Panel static>` - _Note the `static`_ - The `aria-controls`  attribute is removed from the `<Disclosure.Button>` element. This is relevant in cases where you want to animate the content entry and exit without being able to do so with the `Transition` component. Example of this is you want to use animate height with `react-animate-height`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1747, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
