### ISSUE TITLE
Combobox Input is not disabled when passing disabled prop

### ISSUE THREAD

**Issue by judicaelandria** [tailwindlabs/headlessui#1746]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**

v1.6.4

**What browser are you using?**

Chrome

**Reproduction URL**

[Codesandbox](https://codesandbox.io/s/condescending-haslett-dz147k?file=/pages/index.tsx)

**Describe your issue**

When passing the props ***disabled*** to the Combobox.Input it should be disabled like other input but it's not

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We consider the Combobox as 1 big component, so if you move the `disabled` prop to the `Combobox` itself then you will get the expected result: https://headlessui.com/react/combobox#combobox

Updated CodeSandbox: https://codesandbox.io/s/upbeat-sutherland-jtqfc6?file=/pages/index.tsx

**Comment by judicaelandria** [comment]
Hey @RobinMalfait , thank you very much!
