### ISSUE TITLE
Duplicated id's on multiple Disclosure.button elements: accessibility problem

### ISSUE THREAD

**Issue by Badlapje** [tailwindlabs/headlessui#1749]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0, but also exists on v1.6.6 (see repo below)

**What browser are you using?**

Firefox & Chrome

**Reproduction URL**

[Repo on stackblitz](https://react-ts-uykpwh.stackblitz.io)

**Describe your issue**

When there are multiple buttons inside a disclosure, all those buttons receive the same id.  Eg in the linked repo this is the generated html:
```html
<div id="root">
  <button class="py-2" id="headlessui-disclosure-button-:r2:" type="button" aria-expanded="false">Button 1</button>
  <button class="py-2" id="headlessui-disclosure-button-:r2:" type="button" aria-expanded="false">Button 2</button>
</div>
```

Both have the id `headlessui-disclosure-button-:r2:`.  Ids on a page should be unique to comply with the html-standard.

I couldn't find a way to override the id.

Ideally the solution would be three-prongued:
1. the id can be overridden on a case by case basis
2. the basis for the id (before adding 1/2/... at the end) can be overriden per disclosure)
3. the auto-generated id is unique, even if there are multiple disclosures on the page  (for me this suffices atm, but for versatility the above two are likely needed in some use cases).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because we don't support multiple `Disclosure.Button`s for the same `Disclosure`. 

What you can do is use an additional `Disclosure.Button` inside the `Disclosure.Panel` to close it again as explained here: https://headlessui.com/react/disclosure#closing-disclosures-manually
