### ISSUE TITLE
disable dialog closing when click outside of dialog

### ISSUE THREAD

**Issue by oliverkan** [tailwindlabs/headlessui#1751]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1700

<div type='discussions-op-text'>

<sup>Originally posted by **oliverkan** July 21, 2022</sup>
Hi, I am trying to find a way to make dialog persistent on screen. I mean I need to disable the closing feature of dialog when the user clicks somewhere outside of the dialog. I tried the `static` prop but it didn't help. I read the solution alternatives in this discussion. They mention about a tailwind class for pointer events but in new version Dialog.Overlay is deprecated. And also I don't want to loose `esc` key functionality if I have an empty `onclose` function. Is there any new, better way to solve this problem or should I have an empty onClose function and implement `esc` keydown event listener?

Thanks and regards.</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Right now the `Dialog` doesn't have a way to differentiate between a click outside or an `esc`. We might introduce a new `onDismiss` in the future where we provide this information but right now this is not supported.

**Comment by oliverkan** [comment]
@RobinMalfait thanks for your quick answer. Is there any workaround or alternative way to disable outside click?

**Comment by eddievlagea** [comment]
I'm also interested in a workound for disabling outside click.

**Comment by zipme** [comment]
Same situation here

**Comment by lfaudreejr** [comment]
Hi, also very interested in preventing this action, but keeping it when pressing escape. Right now you pass a boolean from the close event. Would you be willing to pass the event as a second argument for those who want to disable the close on outside click and keep the close on escape?

**Comment by drichar** [comment]
Here is how I'm doing it in React

```tsx
import { useState } from 'react'
import { Dialog } from '@headlessui/react'

function MyDialog() {
  const [isOpen, setIsOpen] = useState<boolean>(false)

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        setIsOpen(false)
      }
    };

    window.addEventListener('keydown', handleKeyDown)
    return () => {
      window.removeEventListener('keydown', handleKeyDown)
    };
  }, [isOpen])

  return (
    <Dialog open={isOpen} onClose={() => {}}>
      <Dialog.Panel>

        {/* ... */}

        <button onClick={() => setIsOpen(false)}>Close</button>
      </Dialog.Panel>
    </Dialog>
  )
}
```

**Comment by drichar** [comment]
Here is how I'm doing it in React

```tsx
import { useState, useEffect } from 'react'
import { Dialog } from '@headlessui/react'

function MyDialog() {
  const [isOpen, setIsOpen] = useState<boolean>(false)

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        setIsOpen(false)
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => {
      window.removeEventListener('keydown', handleKeyDown)
    }
  }, [isOpen])

  return (
    <Dialog open={isOpen} onClose={() => {}}>
      <Dialog.Panel>

        {/* ... */}

        <button onClick={() => setIsOpen(false)}>Close</button>
      </Dialog.Panel>
    </Dialog>
  )
}
```

**Comment by xsjcTony** [comment]
@RobinMalfait Sorry for pinging in a closed issue, but is there any plan for this feature?

This is a common use case in my opinion, e.g.
When you don't want users to accidentally close the modal (e,g. when you have a form in the modal), but keep the accessibility that keyboard users can still dismiss the modal by `Esc` key.

**Comment by geekcubed** [comment]
*Bump* on this issue.  Just inherited a project using Headless UI and top of the to-do is to stop customers accidentally abandoning their carts by clicking outside the modal dialog.

Proposed fix is in place - https://github.com/tailwindlabs/headlessui/pull/1968 - seems that it's 100% backwards compatible as api changes have defaults which are the current behaviour.

Current options for me are to build out some hack-y interceptors that inject event listeners into the top-level window object, or rip out headlessui in favour of something that supports this behaviour out the box

**Comment by kulapoo** [comment]
Im not sure if this will work for u guys,  please check if u find any cons. That will help me as well or issue that I might face

what I did is something like this


```js
import { Dialog as Dialog Base } from ''

// using styledComponent in my case or can use any class manipulation
const DialogRoot = styled(DialogBase)`
  z-index: 99999;
  position: relative
  display: ${props => props.isOpen ? 'block' : 'none'};

`
function CustomDialog(props) {
   const {
     open,
     onClose,
     ...otherProps
   } = props
   
   const closeWorkAround = useCallback(() => {}, []) // do nothing
   return (
     <DialogRoot 
       static // this is will do the trick
       isOpen={open}
       open={open}
       onClose={closeWorkAround}
     >
       
        // rest of the requiredComponents
     </DialogRoot>
   )
}
`
```

**Comment by ianizaguirre** [comment]
Bumping this, as I am in the same situation, I would like a built-in way for disabling outside click.

**Comment by abolajibisiriyu** [comment]
Need a way to disable outside click. disabled `Esc` like this 

```
<Dialog
      onKeyDown={(e) => {
        switch (e.key) {
          case "Escape": {
            e.preventDefault();

            break;
          }
        }
      }}
/>
```

**Comment by niels-numbers** [comment]
I’m facing the same issue:
I'm using a <Dialog> component that contains a form, and I want the dialog to close when pressing ESC, but not when clicking outside.

Currently, the @close event is triggered in both cases, but there's no way to distinguish why it was triggered.

It would be great if Headless UI emitted more specific events, such as:

- @dismiss-esc (or @close-esc)
- @dismiss-outside (or @close-click-outside)

That way, developers could decide whether to close the dialog depending on the dismissal reason.

**Current workaround in Vue**:

Here's what I'm doing now:

```
const escPressed = ref(false)

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    escPressed.value = true
  }
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onUnmounted(() => window.removeEventListener('keydown', onKeydown))

function handleClose() {
  if (escPressed.value) {
    escPressed.value = false
    emit('update:open', false)
  }
}
```

```
<Dialog :open="open" @close="handleClose">...</Dialog>
```
