### ISSUE TITLE
Can I open Popover by default not clicking button?

### ISSUE THREAD

**Issue by haodev007** [tailwindlabs/headlessui#1753]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1752

<div type='discussions-op-text'>

<sup>Originally posted by **haodev007** August 10, 2022</sup>
Hello, I would love to see and write opened Popover by default. 
Is it possible now?</div>

**Comment by haodev007** [comment]
Can you plz put merged PR, here?

**Comment by haodev007** [comment]
Have you implemented such an idea? :https://github.com/tailwindlabs/headlessui/discussions/727

**Comment by adamwathan** [comment]
I closed it because it’s a feature request not an issue, you already opened a discussion for it 👍🏻 Please don’t convert discussions into issues.

**Comment by haodev007** [comment]
> I closed it because it’s a feature request not an issue, you already opened a discussion for it 👍🏻 Please don’t convert discussions into issues.

hope this feature can be implemented asap.
