### ISSUE TITLE
Function components cannot be given refs ... `yarn react playground`

### ISSUE THREAD

**Issue by Hillsie** [tailwindlabs/headlessui#1757]
While looking at the `menu` implementations, noticed this console log happening on the first time click of `menu-with-framer-motion`.  Thereafter, a page refresh is need to re-create the console log ... image 👇️

Had a look to see if I could track it down and run out of time so thought I might log an issue. This is where I got up to. 

[ playground-react -> pages/menu/menu-with-framer-motion.tsx#L28 ](https://github.com/tailwindlabs/headlessui/blob/b28d177a95d45aa101cc959385ca9d019e13616f/packages/playground-react/pages/menu/menu-with-framer-motion.tsx#L28)  🤷‍♂️️

![image](https://user-images.githubusercontent.com/17975287/184065329-3e429afa-c96f-4ade-89de-6123b4195909.png)

side note: 🙏️ Really happy to have found these implementation examples, thanks. Go Tailwind! 💖

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The playground examples are there to play with various components and combinations of those components. While the warning is not ideal I also don't consider this a bug. Whenever I have to work in that file again I will make sure to update the code to reflect reality better.

Thanks for notifying!
