### ISSUE TITLE
Hidden inputs aren't created unless an initial value is defined

### ISSUE THREAD

**Issue by kevlened** [tailwindlabs/headlessui#1771]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/react-czye19?file=src/App.js

**Describe your issue**

[The docs show how a component will generate a hidden form input](https://headlessui.com/react/radio-group#using-with-html-forms) if `name` is provided. The hidden input is created if a default value is provided, but not if the default value is `undefined` or `null`.

Is this unexpected behavior?

**Comment by adamwathan** [comment]
This is intended yeah — values for inputs have to be strings so there's no real way to represent `null` or `undefined` other than to have no value at all.

This is consistent with how checkboxes work by default in HTML for example — when a checkbox is unchecked, `formData.has('my-checkbox')` returns `false` as if the checkbox input isn't present at all, and the field will not be present when submitting the form to your backend.
