### ISSUE TITLE
Popover.Button stops propagation of drag events

### ISSUE THREAD

**Issue by vcarel** [tailwindlabs/headlessui#1785]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

**Describe your issue**

`<Popover.Button>` stops propagation of click and mouseDown events, which I presume blocks drag events too.

**Comment by erayakgunn** [comment]
i have the same issue with nuxt3 and headlessui/vue@insiders

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
