### ISSUE TITLE
Dialog scrolls page body to bottom when focus trap loops back to first element

### ISSUE THREAD

**Issue by codemzy** [tailwindlabs/headlessui#1787]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

[CodePen](https://codepen.io/codemzy/pen/vYRwXdX)

**Describe your issue**

When you tab through (with keyboard) focusable elements within the Dialog, once the last focusable element is tabbed away from and the focus goes back to the first element, the page behind the Dialog (e.g. document body) scrolls to the bottom. See example codepen above. 

Open the Dialog with the button and then use tab on your keyboard, you will see the background change and when you close the Dialog you will no longer be at the top of the page anymore - you'll be at the bottom.

Finding it really hard to explain it but hopefully with the example CodePen you will see the issue!

**Comment by thecrypticace** [comment]
It appears that this happens in Chrome and Firefox but _not_ Safari for some reason.

**Comment by thecrypticace** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1789, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `npm install @headlessui/vue@insiders`.

**Comment by codemzy** [comment]
That's great! Thanks for such a speedy response! Awesome 🤩
