### ISSUE TITLE
React - unmount prop on transition doesnt work

### ISSUE THREAD

**Issue by TomasSestak** [tailwindlabs/headlessui#179]
and it still unmounts, is it possible to get it fixed? I already implemented your library and I don't wanna swap to different :( 

![Screenshot 2020-12-20 at 20 54 09](https://user-images.githubusercontent.com/27310585/102723057-c1c8ec80-4305-11eb-89b1-2d957def4ac7.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `unmount` prop is not released yet, but you can use it using a dev version: `npm install @headlessui/react@dev`
