### ISSUE TITLE
Menu button click propagates to parent and triggers parent click

### ISSUE THREAD

**Issue by mjcadz** [tailwindlabs/headlessui#1795]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

1.6.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/github-gdgttl-3kbtft?file=src/views/Home.vue

**Describe your issue**

When a MenuButton is inside a parent that has a click event, clicking the menu button will propagate the click to the parent and trigger the parents event as well. This is normally stopped with the .stop modifier eg. @click.stop="event"
I have a card in my ui where the whole thing (image, text, white space) needs to be clickable, except a menu button. headlessui's default propagation behaviour is preventing me from using it. I think the default behaviour should be to stop click propagation. As a work around It can be done with a custom component and the stop modifier.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

We don't want to build in too many assumptions about what your code looks like. You can still add `@click.stop="() => {}"` to the `MenuButton` to stop the propagation.

https://stackblitz.com/edit/github-gdgttl-dtwtot?file=src%2Fviews%2FHome.vue

**Comment by mjcadz** [comment]
@RobinMalfait thank you for the quick reply! that solves it

**Comment by lelabo-m** [comment]
I have the same problem in react. Any ideas how to stop the propagation from the `MenuButton` to a parent `Link` ?
I have tried to use ` stopPropagation` and `preventDefault` on the `MenuButton.onClick` props without success...

**Comment by lelabo-m** [comment]
Workaround for React :
I managed to avoid navigation by refactoring my component tree.
I am making sure that `Menu` is not a child of `Link` anymore in order to avoid event propagation and triggering navigation.

**Comment by rshekhtm** [comment]
For React (and probably any other framework), a cleaner workaround was adding a container around the menu and adding `onClick={event => event.stopPropagation()}` to it. This effectively stops event propagation as soon as it exits the menu.
