### ISSUE TITLE
Dialog with Transition component is flickering when animated

### ISSUE THREAD

**Issue by Mangor1no** [tailwindlabs/headlessui#1800]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome, Safari, both on MacOS and iOS. Tested on MacMini M1 and iPhone 11 Pro Max.
Chrome on Android. Tested on Redmi Note 5.

**Reproduction URL**

[GithubRepo]
[CodeSandbox]

**Describe your issue**

When I toggle the modal, the modal start flickering and jumping up and down instead of being transitioned smoothly. The problem will go away if I remove the button inside the <Dialog.Panel /> component.

[GithubRepo]: https://github.com/Mangor1no/demo-transition-flicker-headlessui
[CodeSandbox]: https://codesandbox.io/s/demo-transition-flicker-headlessui-9olxni

**Comment by Mangor1no** [comment]
@RobinMalfait please take a look, the issue is making UI janky and becomes unusable

**Comment by Mangor1no** [comment]
Update: I think the reason is related to browsers focus behavior. Tested with a <div> tag as below, the problem will happens when the <div> tag is behave as a button.

`
<div
  className="bg-pink-500 rounded-lg p-2 cursor-pointer"
  tabindex="0"
  role="button"
  aria-pressed="false"
  onClick={handleClick}
>
  Click me
</div>`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I think you've changed your CodeSandbox after you've posted it here, however there are a few things to keep in mind. I think the `mt-auto` is doing some odd things while transitioning, the "glitch" you see is because you translate the dialog down and then we unmount it but there is still a moment in time where it reverts back to the original position.

Here is an updated CodeSandbox that makes sure that the Dialog by default is centered, then for the transition we transition from the bottom to the center (meaning that if the transition is done it is at its end position) and for the leave transition we do the same. However, we also transition to `opacity-0` to properly fade it out completely: https://codesandbox.io/s/demo-transition-flicker-headlessui-forked-7o0q8h?file=/src/App.js

---

```html
<div
  className="bg-pink-500 rounded-lg p-2 cursor-pointer"
  tabindex="0"
  role="button"
  aria-pressed="false"
  onClick={handleClick}
>
  Click me
</div>
```

I don't know what this is, but please use a `<button>` 🥺

**Comment by Mangor1no** [comment]
@RobinMalfait thanks for the fast reply. I was testing the button with a `div` tag as I was described above. However I don't think `mt-auto` class is the root cause of the problem. Let me explain it in detail. The expected behavior is, when I click the button, the modal will be mounted into the DOM. When it has been mounted, the transition start taking effect, move the modal up within 1 second. You can increase the duration to observe this effect more clearly. 

To be sure, this is the URL to CodeSandbox: https://codesandbox.io/s/demo-transition-flicker-headlessui-9olxni?file=/src/App.js

Now back to the reality, when we click the `Open dialog` button, the modal will appear almost immediately, skipping all the transition animation and start jumping. If you comment these button, the modal will slide up and down beautifully without any jank effect. That's the reason why I start thinking about browser focus behavior and start testing, leading to the weird `div` tag you've mentioned above. When replace the button with the `div`, this problem happens again. Only if you remove `tabindex="0"` - that means the dialog does not have any button to be focused - the problem goes away.

![Screen Shot 2022-08-31 at 16 55 57](https://user-images.githubusercontent.com/39774481/187652064-beed7333-1244-4525-bfa7-a0396784d2a3.png)

**Comment by Mangor1no** [comment]
And even when open the dialog in your [codesandbox], you can still see the jumping effect. Please take a look again 😄 

[codesandbox]: https://codesandbox.io/s/demo-transition-flicker-headlessui-forked-7o0q8h?file=/src/App.js

**Comment by Mangor1no** [comment]
To be more clear, I've create a small video to demonstrate the situation, including expected effect and unexpected effect with buttons inside modal. https://www.awesomescreenshot.com/video/10808946?key=30a0a80b3f6db98d2624c8b8b9a0bb84

**Comment by mcgrealife** [comment]
Hey @Mangor1no! I was experiencing similar "bunny hop" behavior (nice term 😁) on bottom sheet dialogs and found another solution here: [https://github.com/mcgrealife/bunny-hop-fix_headless-ui-dialog_russ-dev/pull/1/files?diff=split&w=1](https://github.com/mcgrealife/bunny-hop-fix_headless-ui-dialog_russ-dev/pull/1/files?diff=split&w=1).
