### ISSUE TITLE
RadioGroup is not disabled when inside a disabled fieldset

### ISSUE THREAD

**Issue by ragulka** [tailwindlabs/headlessui#1802]
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

For example: v1.6.7

**What browser are you using?**

For example: Chrome

**Reproduction URL**

https://codesandbox.io/s/headlessui-vue-radiogroup-example-ld00r2?file=/src/App.vue

**Describe your issue**

When using a `FormGroup` inside a disabled fieldset, the FormGroup is not automatically disabled.

From [W3C Recommendations for HTML5](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-fieldset-element): "The disabled attribute, when specified, causes all the form control descendants of the [fieldset](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-fieldset-element) element, excluding those that are descendants of the [fieldset](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-fieldset-element) element's first [legend](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-legend-element) element child, if any, to be [disabled](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#concept-fe-disabled)." 

A [similar issue was reported for `Switch`](https://github.com/tailwindlabs/headlessui/issues/194) and it was fixed a while ago. However, this seems to be a separate issue, and it could possibly apply to other form elements provided by HeadlessUI as well (I have not tested them, yet).

**Comment by thecrypticace** [comment]
The default element for a `RadioGroupOption` is a div. Unfortunately changing this to a button would be a breaking change. However, I did notice that you are customizing your set up anyway and rendering it with `as="template"` and a child `<div>`. If you change this <div> to a button and add the classes `w-full text-left` to the button it'll look the same but inherit the correct behavior of disabling the option which is the behavior your after.

We'll add a note to the code to revisit this when we're able to make a breaking change.
