### ISSUE TITLE
support modern version of JS

### ISSUE THREAD

**Issue by twop** [tailwindlabs/headlessui#182]
First of all: thanks a lot for this effort! It is a great resource <3

I noticed that the compilation target is es5, and on top of that the transpired helpers are inlined:
from https://unpkg.com/browse/@headlessui/react@0.2.0/dist/headlessui.esm.js
<img width="655" alt="image" src="https://user-images.githubusercontent.com/6633216/102963236-70ebfc00-449d-11eb-9947-c925341bf547.png">

Is it possible to ship at least es6 version for esm output? Is there a particular reason to target es5?

**Comment by twop** [comment]
One other thing to note is usage of `(...args)`
Original source (in js form):
```js
export function match(value, lookup, ...args) {
    if (value in lookup) {
        const returnValue = lookup[value];
        return typeof returnValue === 'function' ? returnValue(...args) : returnValue;
    }
   // rest of the body
}

```

transpiled:
```js
function match(value, lookup) {
  if (value in lookup) {
    var returnValue = lookup[value];

    for (var _len = arguments.length, args = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++) {
      args[_key - 2] = arguments[_key];
    }

    return typeof returnValue === 'function' ? returnValue.apply(void 0, args) : returnValue;
  }

 // rest of the body
}
```

Not only it is more code but native `...args` is significantly faster :) 

Hope that context helps.

**Comment by samdaniel24** [comment]
In order to write *ES6* code, we need to install something that can compile
it to ES5. ... To clarify, JS is object-oriented, but is not a class-based
object-oriented language like Java, C++, C#, etc, until the release of *ES6*
.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We use `tsdx` under the hood and I would like to keep it that way. However if we can configure it to be a bit more modern, then I think it is a nice benefit. However, when I change the `target` in the `tsconfig` it doesn't seem to output modern syntax. (I didn't put too much time into it yet).

If you want to hack on it and provide a PR that would be cool. Going to close it for now and put it on my personal backlog!
