### ISSUE TITLE
Dialog's children doesn't scroll anymore (React)

### ISSUE THREAD

**Issue by rphlmr** [tailwindlabs/headlessui#1831]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.0

**What browser are you using?**

Safari iOS latest (15)

**Reproduction URL**

https://codesandbox.io/s/tailwind-test-6qqv40

You can directly test on a simulator / iOS with https://6qqv40.csb.app/

**Describe your issue**

Since the latest version, scroll lock on iOS (https://github.com/tailwindlabs/headlessui/pull/1824) seems to have side effects.

If `Dialog` has some scrollable content in its children, it no more scrolls.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1830, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
