### ISSUE TITLE
Newly added tabs in the beginning appear in the wrong order

### ISSUE THREAD

**Issue by wyozi** [tailwindlabs/headlessui#1834]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.0

**What browser are you using?**

Firefox

**Reproduction URL**

https://codesandbox.io/s/sweet-albattani-zyqvll

1. Press "Insert" button on the insert new tab
2. Open the first newly added tab
3. The "Insertion" tab opens up instead of the newly added tab panel

**Describe your issue**

When dynamically adding new tabs to the tab list, the panels in `Tab.Panels` correspond to different tabs as the ones in `Tab.List`, even though they appear in the same order in the JSX.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1837, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by wyozi** [comment]
Thanks for the quick fix 🙇
