### ISSUE TITLE
Scrollable dialog component not scrolling on touch devices

### ISSUE THREAD

**Issue by juliantroeps** [tailwindlabs/headlessui#1845]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.0

**What browser are you using?**

Tested on Chrome and Safari, macOS as well as iOS.

**Reproduction URL**

Live: https://headless-ui-dialog-bug.vercel.app/
Repo: https://github.com/juliantroeps/headless-ui-dialog-bug

Open with your touch device of choice or Chrome DevTools (select an iOS or Android device from the list and reload).

**Describe your issue**

On desktop the dialog box scrolls just fine. On touch devices it just freezes and nothing happens.

**Comment by t-lochhead** [comment]
Came here with the same issue. I fixed this by downgrading to v1.6.0.

**Comment by juliantroeps** [comment]
Seems to be fixed with #1830
