### ISSUE TITLE
`checked` state is resetted on rerender when using inline array of options (missing referential equality) (Radio Group)

### ISSUE THREAD

**Issue by bennettdams** [tailwindlabs/headlessui#1847]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.1

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/beautiful-grass-vt6qnt?file=/src/App.tsx

**Describe your issue**

When using `RadioGroup` with a given array of its options, the `checked` state is reset to `false` on a rerender.
This does not happen when a) the array is coming from external (e.g. outside of React component) or b) when memoizing it (via `useMemo`), so my guess is that it has something to do with referential equality.

If you look at the reproduction, both variants show the selected option initially (blue background = `checked`):

![image](https://user-images.githubusercontent.com/29319414/190015026-0c2b7e7d-daa2-4953-a4fc-837b406d0ad9.png)

When clicking on the button to trigger a simple rerender, the `checked` state of the second variant is reset:

![image](https://user-images.githubusercontent.com/29319414/190015090-e522896f-2afc-418a-a97c-8f3668a61f57.png)

The only difference is how the array is provided to the component:

```tsx
<div>
  <Radio variant="1" plans={plansExternal} />

  <Radio
    variant="2"
    plans={[
      { name: "Startup" },
      {
        name: "Business",
      },
    ]}
  />
</div>;

```

```tsx
// Radio component
export function Radio({
  variant,
  plans
}: {
  variant: "1" | "2";
  plans: Plan[];
}) {
  const [plan, setPlan] = useState(plans[0]);

  return (
    <RadioGroup value={plan} onChange={setPlan} className="space-y-6">
      {plans.map((plan) => (
        <RadioGroup.Option key={plan.name} value={plan}>
          {({ checked }) => {
            console.log(
              `Variant ${variant}'s plan "checked": ${plan.name} ${checked}`
            );
            return (
              <p className={`m-4 p-4 ${checked && " bg-blue-300"}`}>
                {plan.name}
              </p>
            );
          }}
        </RadioGroup.Option>
      ))}
    </RadioGroup>
  );
}
```
---

Notes: I also checked this behavior vor v1.6.6, where the error also occurs.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

Checkout the `by` documentation to compare objects by a certain property within your object if you can't guarantee object equality: https://headlessui.com/react/radio-group#binding-objects-as-values

**Comment by bennettdams** [comment]
The `by` feature was released a week ago, just in time 😅

Thanks and great job.

Have you seen that TypeScript does not like a string for the `by` value?

![image](https://user-images.githubusercontent.com/29319414/190016702-36cffb76-7aa4-4f4e-bd54-6870bba545ae.png)

**Comment by RobinMalfait** [comment]
Yeah hmm odd, I think it has to do with TypeScript not being able to infer the `value` type properly. If you use `onChange={(value) => setPlan(value)}` instead of `onChange={setPlan}`, it starts working (That's what you see in the `SetStateAction<Plan>`). I think the main reason is that it tries to resolve `value` but `onChange` now also is able to call a function (`setPlan`) but with an actual updater function `onPlan((old) => new)`.
