### ISSUE TITLE
[Vue] ComboboxInput should not trigger selecting option and closing combobox when `isComposing` is true

### ISSUE THREAD

**Issue by iendeavor** [tailwindlabs/headlessui#1849]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.1

**What browser are you using?**

Chrome 105.0.5195.102

**Reproduction URL**

https://stackblitz.com/edit/github-gdgttl-adfjpj?file=src/views/Home.vue

**Describe your issue**

ComboboxInput should not trigger selecting option and closing combobox when [isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) is `true`.

https://github.com/tailwindlabs/headlessui/blob/e926d693c5611759af074385636213a5f886821a/packages/%40headlessui-vue/src/components/combobox/combobox.ts#L675-L690

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1850, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
