### ISSUE TITLE
Type Error in @headlessui/react

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/headlessui#187]
I am trying to use Headless UI Select component in a Chrome extension & it gives error: `ReferenceError: process is not defined` as `process.nextTick` is used.

Is there anyway I can bypass that as `process` is not available in Chrome extensions I think? Or maybe can you guys polyfill it? Or I am just a minority.

**Edit:** I couldn't find `process.nextTick` being used :)

**Comment by deadcoder0904** [comment]
Nvm, this worked.

I don't know why the example in `ListBox` that had `const person = [{id: 1, name: 'John'}]` didn't work but `const person = ['John']` did.

Weird but I'll close this for now :)

**Comment by deadcoder0904** [comment]
Here's my `Select` component that doesn't work:

# Select.tsx

```tsx
interface IProps {
	label?: string
	options: Array<{
		id: number
		name: string
	}>
}

export const Select = ({ label, options }: IProps) => {
	const [selectedOption, setSelectedOption] = React.useState(options[0])

	return (
		<Listbox value={selectedOption} onChange={setSelectedOption}>
			<Listbox.Button>{selectedOption.name}</Listbox.Button>
			<Listbox.Options>
				{options.map((option) => (
					<Listbox.Option key={option.id} value={option}>
						{option.name}
					</Listbox.Option>
				))}
			</Listbox.Options>
		</Listbox>
	)
}
```

I get this error (red-squiggly line) on `value` of `value={option}`:

> Type '{ id: number; name: string; }' is not assignable to type '(string & { id: number; name: string; }) | (number & { id: number; name: string; }) | (readonly string[] & { id: number; name: string; })'.
  Type '{ id: number; name: string; }' is not assignable to type 'readonly string[] & { id: number; name: string; }'.
    Type '{ id: number; name: string; }' is missing the following properties from type 'readonly string[]': length, concat, join, slice, and 16 more.

I even tried doing `value={option.name}` but then the select element gets removed from DOM.

# App.tsx

```ts
const shapes = [
	{
		id: 1,
		name: 'Circle',
	},
	{
		id: 2,
		name: 'Square',
	},
]

<Select label="Shape" options={shapes} />
```

And the one that works has `const shapes = ['Circle', 'Square']` & respective changes in `Select.tsx` :)

**Comment by deadcoder0904** [comment]
It is a Type Error in `@headlessui/react` package → https://stackoverflow.com/questions/65529098/typescript-error-ts2322-type-option-is-not-assignable-to-type-string-opti#comment115854012_65529098

**Comment by deadcoder0904** [comment]
Oh so the `process.nextTick` error was not of `@headlessui/react` but another library `react-listbox` haha. I kept the code in there while trying to run it with `@headlessui/react`

https://github.com/mitchbne/react-listbox/blob/135ce10d14fbcccdd63c656e4afcfa5c6d2e91dc/src/Listbox.tsx#L104

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The TypeScript error that you are receiving is a known issue that has been fixed but not fully released yet. However, if you do want to make use of the fix, try using the dev build: `yarn add @headlessui/react@dev` or `npm install @headlessui/react@dev`.

Yeah the `process` issue can't be ours, because we don't use `process` inside the components 😅

**Comment by deadcoder0904** [comment]
Any clues on when it will be released as there's not a lot of activity going on here?
