### ISSUE TITLE
combobox.input value gets out of sync with search term state

### ISSUE THREAD

**Issue by stefanprobst** [tailwindlabs/headlessui#1875]
**What package within Headless UI are you using?**

`@headlessui/react` - `Combobox`

**What version of that package are you using?**

1.7.2

**What browser are you using?**

firefox

**Reproduction URL**

https://github.com/stefanprobst/headlessui-combobox

**Describe your issue**

in a `multiple` combobox, the combobox.input value is [set to an empty string when clicking outside ](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/combobox/combobox.tsx#L669-L691) without selecting anything. however, since this is set directly on the ref, no `input`/`change` event is fired, so the searchterm `useState` will not get notified. in this example, you can see that when focusing the combobox input again, the searchTerm is still set to the previously entered phrase, even though the input is empty:

https://user-images.githubusercontent.com/20753323/192467884-e2070dd2-70f9-4b07-b80c-cc1ba04f1679.mp4

**Comment by robertkern** [comment]
Just fyi, I updated to 1.7.3 and this issue exists there too

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this!

This should be fixed by #1916, and will be available in the next release.

You can already try it using (may take a few minutes to publish to npm):
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by frankleng** [comment]
@thecrypticace still running into this via `@headlessui/react@insiders`
we set empty input when user types in special char, ie `>`
`Combox.Input` is calling `onChange` with the char even with input state was set to empty

**Comment by eexmellie** [comment]
We wanted to include Combobox component into our app, but ran into the same issue on version 1.7.16 of @headlessui/vue.

I saw the comment for the last commit linked to this issue with the suggestion of "Use the `onBlur` on the input to reset the `query` value to filter options". 

Unfortunately, this does not look feasible. We're using `multiple` prop and the issues are:
* `blur` event is fired on each click while selecting/deselecting an option, so we can't just reset filter query on any blur event.
* in case of clicking outside, `blur` is fired before the value is actually cleared and the `open` slot prop is set to `false`. Correct me if I'm wrong, but there is no straightforward and non-hacky way to know that this `blur` event is the one that we need to use to reset the filter query.

So I was wondering if there are any plans for fixing and/or improving this particular behaviour in the forseeable future?
