### ISSUE TITLE
Multiple dialog popups in the portal 

### ISSUE THREAD

**Issue by JoeriTheGreat** [tailwindlabs/headlessui#1880]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.7.2

**What browser are you using?**
Chrome, Safari, FireFox

**Describe your issue**
Using[ LinusBorg's Portal-Vue (vue3) ](https://next.portal-vue.linusb.org/)is causing interference with the Dialog (modal) component.

Im using LinusBorg portal-vue in my Inertia app using different layouts (hence why i can't use <teleport> because of the limitations). 
In this layout i'm using portal-vue to display a back button.
Having this back button is making the dialog showing multiple times in the "headlessui-portal-root"

![image](https://user-images.githubusercontent.com/37139936/192747818-939e5a71-2b32-4a36-bb7f-204ca212ad2a.png)

By removing the portal-vue button in my layout the dialog only shows once.

I tried changing the default component names of portal-vue but nothing seem to work. 
I'm not sure what built-in portal functionality headlessui is using but it somehow interfere with the portal-vue package

Edit:
Found out after removing the package the problem still persists, are you guys using the same logic as the package ? When i use the vue devtools i see multiple <App> instances are created causing this problem

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you attach a reproduction repo so that we can take a look?

Fwiw, the Dialog already has a Portal built-in so there is no need to use another Portal on top when using the Dialog component.

**Comment by JoeriTheGreat** [comment]
Hi @RobinMalfait. It was a problem caused by inertia and the way it duplicated components using nested layouts. Fixing that also 'fixes' this problem so it had nothing to do with headlessui
