### ISSUE TITLE
HeadlessUI doesn't work with nuxt 3

### ISSUE THREAD

**Issue by david4bou** [tailwindlabs/headlessui#1884]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.2

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/nuxt-starter-7p1bis?file=app.vue

**Describe your issue**

When I import a headless ui component like Menu in my vue file I have `TypeError: Cannot read properties of undefined (reading 'flatMap')`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You are just rendering a `<Menu></Menu>` with nothing in it. While this error should not happen, please start with one of the documentation examples that uses all of the necessary sub-components: https://headlessui.com/vue/menu
