### ISSUE TITLE
`Maximum update depth exceeded` when using `Fragment` on `Popover.Button`

### ISSUE THREAD

**Issue by andreasremdt** [tailwindlabs/headlessui#1888]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.2

**What browser are you using?**
Firefox, Chromium

**Reproduction URL**
https://codesandbox.io/s/suspicious-dew-pemsx1?file=/src/App.tsx

**Describe your issue**
I am trying to use a custom `Button` component from a design system within `Popover.Button`. However, the app crashes  saying `Maximum update depth exceeded`.

Similar to what the [docs recommend](https://headlessui.com/react/menu#rendering-a-different-element-for-a-component) for `Menu.Button`, I used `as={Fragment}`, but while this works on menus, it fails on popovers. I would assume that the API is equal, as it's the same scenario. Hence I opened this bug report in case you consider it as such.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1889, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by awkale** [comment]
I'm seeing the same issue with `Disclosure.Panel` when used as a fragment
