### ISSUE TITLE
Combobox `multiple`:  `Type 'boolean' is not assignable to type 'true'.`

### ISSUE THREAD

**Issue by francofantini** [tailwindlabs/headlessui#1895]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

I'm using: v1.7.3
Issue first seen in: v1.7.0
Last version without this issue: v1.6.6

**What browser are you using?**

N/A

**Reproduction URL**

https://github.com/francofantini/HeadlessUICombobox

**Describe your issue**

To reproduce the error:
1. Clone the repo
2. `npm i`
3. `npm run build`

The 3rd step will first check types and you'll see the type error `Type error: No overload matches this call.` on the `multiple` prop.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/11973156/193586860-17cc8a73-6006-4d9e-a930-628c1c8ee8de.png">

I hope this helps.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It looks like your repo is not public, can you make it public so that we can take a look?

**Comment by francofantini** [comment]
@RobinMalfait sorry about that, its public now.

**Comment by RobinMalfait** [comment]
Hey! So we've spent some time trying to figure out what's going on here. The short story is that TypeScript isn't good at Schrödingers Types. And you are trying to create a Combobox that is both `multiple` and not-`multiple` at the same time.

Here is a simplified example of what the Combobox is doing behind the scenes:
```ts
type MyProps<
  TType extends "nullable" | "multiple" | "potato",
  TValue
> = Extract<
  | {
      type: "potato";
      value: TValue;
      onChange(input: TValue): void;
    }
  | {
      type: "nullable";
      value: TValue | null;
      onChange(input: TValue | null): void;
    }
  | {
      type: "multiple";
      value: TValue[];
      onChange(input: TValue[]): void;
    },
  { type: TType }
>;

export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never

type F = MyProps<"nullable" | "multiple", string>
type F1 = F["type"]                // correct: "nullable" | "multiple"
type F2 = F["value"]               // correct: string | string[] | null
type F3 = F["onChange"]            // "correct" but unusable: ((input: string | null) => void) | ((input: string[]) => void)
type F3P = Parameters<F3>[0]       // incorrect: string | string[] | null (should be any)

type F4 = UnionToIntersection<F3>  // "correct" but unusable: ((input: string | null) => void) & ((input: string[]) => void)
type F4P = Parameters<F4>[0]       // incorrect: string[]

let f3: F3 = (x) => {}             // unusable: x is any
let f4: F4 = (x) => {}             // usuable:  x is string | string[] | null
```

Unfortunately, I don't think we can solve this problem in Headless UI right now until TypeScript can handle this case better.

One solution you can try is to either ignore TypeScript altogether, or another solutions is to split up your combobox into 2 where you handle the case for `multiple` and the case for non `multiple` data:
```tsx
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Combobox } from '@headlessui/react'
import { useState, useCallback } from 'react'

const Home: NextPage = () => {
  const [isMultiple, setIsMultiple] = useState<boolean>(false)
  const [selectedOption, setSelectedOption] = useState<string | string[]>('example')

  const onChange = useCallback((e: typeof selectedOption) => {
    console.log(e)
    setSelectedOption(e)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isMultiple ? (
          <Combobox value={selectedOption as string[]} onChange={(e) => onChange(e)} multiple>
            {({ open, activeIndex }) => {
              return <div>test</div>
            }}
          </Combobox>
        ) : (
          <Combobox value={selectedOption} onChange={(e) => onChange(e)}>
            {({ open, activeIndex }) => {
              return <div>test</div>
            }}
          </Combobox>
        )}
      </main>
    </div>
  )
}

export default Home
```

I hope that helps!
