### ISSUE TITLE
Combobox multiple crashes when <Combobox.Options> is set to be displayed

### ISSUE THREAD

**Issue by ahmadnsam** [tailwindlabs/headlessui#1904]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Edge

**Reproduction URL**

https://github.com/ahmadnsam/powerapps-modals/tree/multi-choices-fix

steps to reproduce:
copy repo
npm install
npm run dev

**Describe your issue**

When setting the combo box as multiple combo box, the <Combobox.Option> is causing a problem, when you open the combo box, the app crashes and give the below error in the console
![image](https://user-images.githubusercontent.com/83499142/194281611-45774721-1640-4c9b-837a-19db2894164a.png)

if you replace the <Combobox.Option> with <span> for example it works fine, and the list is displayed.

**Note**: its only happening when setting the combobox as multiple

**Comment by ahmadnsam** [comment]
Thanks Robin for the help you're providing, much appreciated 

I created a branch where it has a sample data, the link in the bug report is https://github.com/ahmadnsam/powerapps-modals/tree/multi-choices-fix which has it.
![image](https://user-images.githubusercontent.com/83499142/194375147-174963b2-62f4-47ef-a7bd-367c28e3aad4.png)

If you check in App.tsx you'll notice that I commented out the getDataParam and I added the sample function which has the data there.

    //setModal(getDataParam());
    setModal(sample());

and once I hit `npm run dev` I see this  

![image](https://user-images.githubusercontent.com/83499142/194375029-8569fb84-e304-445f-9d4a-f0a0d86084f8.png)


I hope this will work.

Thanks again Robin!

**Comment by thecrypticace** [comment]
This is happening because the combobox is changing from an uncontrolled combobox to a controlled one. We're likely going to add a warning for this as React itself warns when this happens for input, select, etc…

If you default the combobox value to `[]` instead of `undefined` this problem goes away.

**Comment by ahmadnsam** [comment]
That works @thecrypticace Thanks a lot!
