### ISSUE TITLE
Navigating through Menu using Tab key

### ISSUE THREAD

**Issue by l0gicgate** [tailwindlabs/headlessui#191]
Would there be a way to enable both Tab and Arrow Up/Down keys for navigation or make it an option?

I am fully aware that the W3C WAI spec states that navigation within menu items should be done via arrow keys only however it is a nice touch to support both.

I’ve looked at multiple websites and this is the behavior:
- Google: Tabbed nav only
- YouTube: Tabbed nav only
- AWS: Arrow keys nav only
- Github: Tab + Arrow keys nav

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

A lot of those menu's on Google, YouTube, GitHub, ... are not using menu's but more like navigations. It's all pretty vague, but I don't think it is a good idea to allow multiple types of navigation. I believe that sticking as close to a spec that makes sense is better than 100 packages/websites that implement it *slightly* different and will annoy end-users. Especially people that rely heavily on those accessible keyboard navigation movements.

I am also a firm believer of keeping the API as small as possible, meaning, keeping the amount of options as low as possible.
