### ISSUE TITLE
Tab.Panel of @headlessui/react does not obey tabIndex prop (e.g. tabIndex={-1}) compromising a11y

### ISSUE THREAD

**Issue by firxworx** [tailwindlabs/headlessui#1917]
**Package**: `@headlessui/react` (Tab)
**Version**: v1.7.3
**Browser Version**: issue present in all browsers

**Reference**: See discussion https://github.com/tailwindlabs/headlessui/discussions/1433 and comment that provides replication steps: https://github.com/tailwindlabs/headlessui/discussions/1433#discussioncomment-3793144

It has been confirmed that only the React library is impacted and that `@headlessui/vue` works correctly. In the discussion thread, @mitar [links to a example](https://wikipedia.peerdb.org/d/3kVWF14ywhUVFaCoTzhhFs) implemented in Vue that demonstrates the desired behaviour (refer to discussion for more details).

**Issue Summary**

@headlessui/react `Tab.Panel` erroneously overrides/ignores the `tabIndex` prop. The implementation always overrides the `tabIndex` on the current `Tab.Panel` to `0`.

The library should _not_ override developer and any `tabIndex` they explicitly set should be applied to the underlying element.

**Issue Description**

Tab Panels themselves do not need to be focusable if the first elements within any Tab Panels are focusable elements. This is covered in the discussion linked above and can be confirmed with a careful reading of: <https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html>.

The W3 link only provides an example where the Tab Panels contain prose (i.e. no focusable elements), and in that particular case, the Tab Panels themselves generally _should_ be focusable.

However if tabs are being used to switch between Tab Panels that contain forms or other focusable UI elements, it may not make sense for the Tab Panels themselves to be focusable. In such cases, focus should move from a given Tab in a Tab List to the first focusable element _within_ the current Tab Panel, avoiding the Tab Panel itself.

An example of a broken use-case is setting `tabIndex={-1}` on `Tab.Panel` in JSX/TSX to remove the tab panel from keyboard navigation because Headless will override the prop value set by the developer.

_Related Issue_

A related TypeScript issue is if `tabIndex` or any other prop is not supported by a given component (for example: it will be overridden or ignored by headlessui) then the types should be specific enough to discourage devs from using that prop. This is a recurring pain point with HeadlessUI where liberal typing and/or lacking generics can signal to developers that certain props are accepted/supported by HeadlessUI components when in fact they are not.

The types are not in-scope for this particular tab index issue however I am throwing it out there to put on the radar of the maintainers :)

**Comment by adamwathan** [comment]
Going to close this in favor of the existing discussion since this is more of a feature request than an issue. I think it would be a good thing to support though 👍

I don't agree that the current behavior "compromises a11y" — it works the way it works because we are trying our best to _make_ it accessible. Not being focusable at all would be compromising accessibility. Having to hit tab once to focus the panel and then again the focus an input or something inside of the panel does not make it inaccessible. I appreciate that you want this change in the library but adding language like that to the issue title to make it sound like a scary catastrophic problem to pressure us into doing what you want is not the right strategy.

**Comment by mitar** [comment]
Maybe the existing discussion could be moved into an issue?

I think there are two realistic bugs here:
* React overrides tabIndex while Vue does not.
* Types do not signal that tabIndex is accepted.

**Comment by firxworx** [comment]
I will remove "compromising a11y" from the title if you read some sort of pressure or catastrophic thing in that (!?). It's your project to triage issues + set roadmap + title issues as you see fit. I have no strategy here other than improve the library long-term: even if you were going to add a fix in the next release that offers nothing of value to my project right now.

No amount of renaming or closing issues will make either of the two issues disappear.

I agree with the default behaviour of tab panels being focusable: most devs never think about tab order or focusable elements and honestly most of the time e.g. internal line-of-business apps, it isn't a concern. The current default works well to improve things in the most likely case where the dev isn't thinking about it.

However by blocking customization Headless is preventing thoughtful design choices by devs that are trying to create something bespoke that perfectly fits the context of their UI.

Unnecessary focus targets that don't make sense are a UX fail because they break the axiom of _do what the user expects_ and requiring additional physical effort of a user _is_ an a11y issue. 

Users are finding the focus highlight on the tab panel confusing to the point I am going to reimplement tabs anyway.

**Food for Thought**

The project was using HeadlessUI tabs for supports a user with spastic quadriplegia.

While the tabbed interface I am using HeadlessUI for is not for her use (it is for caregivers; her interface is custom and involves hardware that interacts via HTML5 gamepad API), she represents a _perfect_ example of a real-world human user where _every single interaction_ is laborious and requires high-effort focus and sometimes _multiple attempts_.

Knock on wood -- we're all a car accident or stroke (or whatever) away from having to struggle through UI's with pointless focus elements in the tab order. Multiply that by a bunch of elements on a page and it can really add up.
