### ISSUE TITLE
Combobox.Input "disabled" prop not working

### ISSUE THREAD

**Issue by agustints** [tailwindlabs/headlessui#1924]
**What package within Headless UI are you using?**

 @headlessui/react

**What version of that package are you using?**

 v1.7.3

**What browser are you using?**

Chrome

**Describe your issue**

The "disabled" property that appears in the documentation does not disable the combobox search.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/20648944/196012522-d731aff4-ae2f-4df4-a272-38e3ad3004c2.png">

![image](https://user-images.githubusercontent.com/20648944/196012505-934261d5-728e-4185-ac72-4c4aeb580080.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We consider the `Combobox` and all of its sub-components as 1 compound component. You have to put the `disabled` prop on the `Combobox` itself, not the `Combobox.Input`.

The `disabled` section you highlighted in your screenshot is a value that is exposed via the `Render Prop`. This allows you to create dedicated (styled) combobox input components while still accessing that information just in case you don't have direct access to the `disabled` state.

**Comment by HerrBertling** [comment]
I found this through a quick search. Quick shoutout @RobinMalfait for this great answer. Now I can wonder how this `disabled` attribute both on the `Combobox.Input` and the `Combobox.Button` ever survived for a few weeks in our codebase :joy:
