### ISSUE TITLE
feat(Menu): Add `onClose` prop and `@close` event

### ISSUE THREAD

**Issue by phegman** [tailwindlabs/headlessui#1948]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1947

<div type='discussions-op-text'>

<sup>Originally posted by **phegman** October 22, 2022</sup>
I am building a filter component and I want to be able to reset the options if a user closes the dropdown without selecting a filter option. Currently it doesn't seem like there is a way to detect when the Menu component is closed. 

**Example use case**

https://user-images.githubusercontent.com/4230489/197367787-c45fe7b5-bc16-4835-bf03-860bbfa3dfcd.mov

I would like the dropdown to reset after the user selects `Filter 3` and then closes the dropdown but there is currently no way to detect that the dropdown was closed.</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

We are aware of this and will implement this in the future, but for now going to close it in favor of the feature request discussion so that we can keep issues for bugs. 👍
