### ISSUE TITLE
It will make the `strategy` always be `RenderStrategy.Unmount`?

### ISSUE THREAD

**Issue by jellykaiser** [tailwindlabs/headlessui#195]
https://github.com/tailwindlabs/headlessui/blob/17a853501de4d30dd9681244b76c5aad64b015fb/packages/%40headlessui-vue/src/utils/render.ts#L51

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Notice that we are using the `??` operator (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). Which means that only `undefined` and `null` will be defaulted to `true`.

This means that:

```js
true ?? true ? 'Unmount' : 'Hidden';       // This results in 'Unmount'
undefined ?? true ? 'Unmount' : 'Hidden';  // This results in 'Unmount'
false ?? true ? 'Unmount' : 'Hidden';      // This results in 'Hidden'
```

If we had used the `||` operator, then your statement would be correct:

```js
true || true ? 'Unmount' : 'Hidden';       // This results in 'Unmount'
undefined || true ? 'Unmount' : 'Hidden';  // This results in 'Unmount'
false || true ? 'Unmount' : 'Hidden';      // This results in 'Unmount'
```

So long story short, if you want to get to `Hidden` you have to explicitly passthrough the `unmount={false}` prop.
