### ISSUE TITLE
Multiple Popover buttons not able to close panel

### ISSUE THREAD

**Issue by jadenmazzone** [tailwindlabs/headlessui#1955]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Chrome and Firefox

**Reproduction URL**

https://codesandbox.io/s/sad-swartz-2peq1d?file=/src/App.js

**Describe your issue**

When you click on the "Other" `Popover.Button` the `Popover.Panel` opens and closes as expected. But if you try to close the `Popover.Panel` with the "Solutions" button you will notice it does not close, however, it is able to open it.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently not really a bug, but it is functionality that we don't support right now. I've added a warning in #2007 to help other developers running into this issue as well.

Going to close this as a won't fix for now.

Note: it _is_ possible to render Button A or Button B conditionally but just not at the same time. 
Note: it is also still possible to render `<Popover.Button />` components inside the `<Popover.Panel />` to close it as explained here: https://headlessui.com/react/popover#closing-popovers-manually
