### ISSUE TITLE
Transitions not working in Chrome iOS

### ISSUE THREAD

**Issue by Publicker** [tailwindlabs/headlessui#1969]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.3

**What browser are you using?**
Browser: Chrome v105.0.5195.147
OS: iOS v16.0 (20A362)
Device: iPhone Xs

**Reproduction URL**
https://headlessui.com/react/transition

**Describe your issue**
Transitions aren't working (and believe never worked) in Chrome iOS as I've experienced this issue for quite long time by now _- sorry I didn't report it before -_.

I've attached two videos showing doing the same actions (just using different browsers, Safari and Chrome) which consists in tapping the button "Click to transition" on the official Headless UI website. And as a result, you'd be able to see how the transition is not being shown (and the final user won't even imagine that the transition was there).

### Safari - iOS 16.0 (20A362)
https://user-images.githubusercontent.com/52673485/198837950-1b4c3756-15ff-4a42-85d0-3bc201ba573a.MP4

### ❌ Chrome v105.0.5195.147 - iOS 16 (20A362) ❌
https://user-images.githubusercontent.com/52673485/198837989-ed26062c-b8d7-473e-8ece-3f63c1402942.MP4

### Results of every video:
| Browser | Version | OS | Animation works |
| ---- | ---- | ----------- |  ----------- |
| Chrome | 106.0.5249.119 | macOS 13.0 (22A380) | ✅
| Safari | same as OS | iOS 16.0 (20A362) | ✅
| Chrome | 105.0.5195.147 | iOS 16.0 (20A362) | ❌

---

Please do not hesitate to ask anything as I'm more than open to give as much help as needed.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We rely on the native `transitionrun`, `transitionend` and `transitioncancel` events. These existed for a while but weren't working for quite some time. 
I can't seem to find in which version they are properly implemented, but testing it on Chrome iOS Version 107.0.5304.66 it works as expected.

So hopefully this issue resolves itself after updating your Chrome version 👍
