### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by sumanthratna** [tailwindlabs/headlessui#197]
it would be great if Headless UI had a table component, featuring sorting, selecting rows, etc. 

linking this, which may be a starting point to make sure the component scales to many rows + columns: https://github.com/schrodinger/fixed-data-table-2

**Comment by ahmedosama5200** [comment]
Are you kidding ? They didn't yet implement modals which are trivial compared to data tables!!
They should really spend more time on this project.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are currently focusing on components we need for Tailwind UI.
But I will put this on my backlog list!

**Comment by ahmedosama5200** [comment]
@RobinMalfait When do you expect you will release modals, tooltips and accordions. Those are main components every project needs.

**Comment by RobinMalfait** [comment]
Hey @ahmedosama5200, we will release those if we implement them and if they are ready.

**Comment by ahmedosama5200** [comment]
@RobinMalfait I am sorry If I was rude. I only asked about what you expect not when they will exactly be released.

**Comment by fanckush** [comment]
Hey @RobinMalfait, are there any plans for adding a table component? I see that Tailwind UI has a table component so I was wondering wether it's planned or not.
Thanks!
