### ISSUE TITLE
Keyboard navigation focus

### ISSUE THREAD

**Issue by kicksnarehat** [tailwindlabs/headlessui#1971]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Chrome 107.0.5304.62 (OSX)

[Reproduction URL](https://codesandbox.io/s/white-bash-jtgbj9?file=/src/App.js)

**Describe your issue**

Keyboard navigation using arrow keys does not follow documentation when using anchor tags as child of Menu.Item

I added a comment to [this discussion](https://github.com/tailwindlabs/headlessui/discussions/1944), but thought a proper issue report would be valuable.

Thanks, I applaud the work this team is doing!

**Comment by adamwathan** [comment]
Hey! Can you be more clear about the actual issue? After adding the missing `bg-blue-500` class you were using but hadn't defined to `styles.css` you can see that the items are being properly selected when using the keyboard:

https://codesandbox.io/s/nameless-bash-jentn6?file=/src/App.js

**Comment by kicksnarehat** [comment]
Thanks for the clarification. I think simply misunderstood headlessui's goal, as your CSS example clearly works.  I had expected items themselves to be focusable -- and am not sure what's actually appropriate for accessibility -- but I see now that this [is working as documented](https://headlessui.com/react/menu#focus-management), placing focus on the items container.

Here's a slightly-modified example showing how I was expecting to style using :focus 

https://codesandbox.io/s/romantic-elbakyan-5p6kpe?file=/src/styles.css:145-275

Your example, though, resolves this issue as reported. Now I've got some homework to do re: my focus question above...
