### ISSUE TITLE
Hydration children mismatch in `<div>: `server rendered element contains fewer child nodes than client vdom. 

### ISSUE THREAD

**Issue by MuhammadKhizar7** [tailwindlabs/headlessui#1982]
Hydration children mismatch in `<div>: `server rendered element contains fewer child nodes than client vdom. 

I am using Nuxt 3 with tailwind css and headless you 

This error cause and also flicker when using tabs when using this module and also when using raw headless UI module 

If we wrap client only <ClientOnly> 
```
 <ClientOnly>
  <TabGroup>
    .....
  </TabGroup>
</ClientOnly
```
or use transpile in config 

```
  build: {
     transpile: ['@headlessui/vue'],
   },
```
but flicker effect remain same it because of client rendering

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
