### ISSUE TITLE
Error when value starts as `undefined` on a controlled ListBox

### ISSUE THREAD

**Issue by will-stone** [tailwindlabs/headlessui#1983]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.4

**What browser are you using?**

Firefox 

**Reproduction URL**

https://codesandbox.io/s/error-when-value-starts-as-undefined-on-a-controlled-listbox-lqe19r

**Describe your issue**

Prior to v1.7.4 it was possible to use `undefined` as the `value`. Now, when selecting an option, the console shows the error:

```
A component is changing from uncontrolled to controlled. This may be caused by the value changing from undefined to a defined value, which should not happen. 
```

Allowing `undefined` is useful as it means the component can start off in a non-selected state.

How about using `null` for when it's controlled but no option should be selected? This way the user is making a conscious decision that they want to control the component but they don't want it to have a value.

Keep up the great work guys! Absolutely love this library 😊

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We fixed this as a bug fix to be more inline with how React itself handles this behaviour. I would recommend you to change your useState hook call just to what you described by using `null`:
```diff
- useState()
+ useState(null)
```

Which gets rid of the warning: https://codesandbox.io/s/error-when-value-starts-as-undefined-on-a-controlled-listbox-forked-7h2wb4?file=/src/App.js

I know this was different in older version, but the sad part is that every single bug fix in any software project is in theory a breaking change if you are/were relying on the "broken" behaviour.

**Comment by will-stone** [comment]
Thanks @RobinMalfait! I didn't realise `null` worked; I tried it and got some TypeScript errors but that was a problem on my side 🙂
