### ISSUE TITLE
(destructured parameter) is undefined with Vue 3.2.42

### ISSUE THREAD

**Issue by innocenzi** [tailwindlabs/headlessui#1995]
Using the recently-released `vue@3.2.42` and `@headlessui/vue@1.7.4`, the Combobox component doesn't seem to work anymore. No clue if it's a Vue bug or a Headless UI one, I assume it's a Vue one or Headless UI was relying on a Vue bug previously.

**Reproduction URL**

https://stackblitz.com/edit/vue-o1z7k1?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue

**Describe your issue**

The Combobox component crashes due to an undefined destructured parameter in its code. The issue is potentially similar to https://github.com/tailwindlabs/headlessui/issues/1994.

**Comment by luabraggion** [comment]
> Usando o recém-lançado `vue@3.2.42`e `@headlessui/vue@1.7.4`, o componente Combobox parece não funcionar mais. Não tenho ideia se é um bug do Vue ou uma interface do usuário sem cabeça, suponho que seja um Vue ou a interface do usuário sem cabeça estava confiando em um bug do Vue anteriormente.
> 
> **URL de reprodução**
> 
> https://stackblitz.com/edit/vue-o1z7k1?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue
> 
> **descreva seu problema**
> 
> O componente Combobox trava devido a um parâmetro desestruturado indefinido em seu código. O problema é potencialmente semelhante ao #1994 .

I had the same problem here I changed ComboboxInput for input there it solved, here the problem is in ComboboxInput

**Comment by luabraggion** [comment]
I had the same problem here I changed ComboboxInput for input there it solved, here the problem is in ComboboxInput

**Comment by luabraggion** [comment]
@innocenzi 

I had the same problem here I changed ComboboxInput for input there it solved, here the problem is in ComboboxInput

**Comment by innocenzi** [comment]
Fixed by https://github.com/vuejs/core/issues/7070
