### ISSUE TITLE
Would this be able to support Phoenix Live View as well?

### ISSUE THREAD

**Issue by ryanwinchester** [tailwindlabs/headlessui#2]
I think I see what you're doing here.

If so, I wouldn't mind making some PRs in the future for [Phoenix Live View](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html) versions.

I'm not sure if it would be possible to easily distribute this sort of thing as [a hex package](https://hex.pm/) though (maybe), and maybe just example files for copypasta if that is the case.

**Comment by RobinMalfait** [comment]
For now we are focusing on JavaScript libraries like React, Vue, Alpine, ... I am not sure if this would be a good fit for this library itself. Maybe we can look into this in the future but not right away.

**Comment by profsmallpine** [comment]
@RobinMalfait Question, is Alpine still in the roadmap?
