### ISSUE TITLE
[URGENT] My company depends on this project but does not support it financially

### ISSUE THREAD

**Issue by kesne** [tailwindlabs/headlessui#200]
@RobinMalfait Is this project still happening????!

Please respond.

**Comment by RobinMalfait** [comment]
No.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

For people reading this and thinking "what is going on here?!", this happened live on stream as a joke. Jordan (@kesne) streams live React, GraphQL and Tailwind CSS development, check them out! https://www.twitch.tv/vapejuicejordan

To be clear, we are still supporting Headless UI! ✌️❤️
