### ISSUE TITLE
click sometimes doesn't register?

### ISSUE THREAD

**Issue by alainbelez** [tailwindlabs/headlessui#201]
i noticed, that if you set the navbar as fixed (from tailwindui) sometimes click doesn't register. i added the option menu from the demo is the docs, to test out if its a bug on my code or not

variant: vue
browser: chrome and safari
device: iphone

https://user-images.githubusercontent.com/6648110/105498476-38894900-5cfb-11eb-88d9-b76477bfae61.MP4

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a minimal reproduction repository or a minimal codesandbox that showcases this issue?

**Comment by alainbelez** [comment]
hello @RobinMalfait i have recreated it on a sample vue project
https://github.com/alainbelez/test

**Comment by RobinMalfait** [comment]
Thanks for the info. Unfortunately I can't reproduce it on my iPhone given your reproduction repository. I am on the latest Safari and I feel like this might be related to pointer events.

Could you try to use the latest `dev` version `@headlessui/vue@dev`, and see if that fixes things?

**Comment by alainbelez** [comment]
Hello @RobinMalfait dev version seems to fixed the issue. thank you
