### ISSUE TITLE
Transition with appear={true} using Next.js

### ISSUE THREAD

**Issue by adjsky** [tailwindlabs/headlessui#2012]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.4

**What browser are you using?**

Google Chrome Version 107.0.5304.87 (Official Build) (64-bit)

**Reproduction URL**

repo: https://github.com/adjsky/headlessui-transition
URL: https://headlessui-transition.vercel.app/

**Describe your issue**

The problem is described in this discussion: https://github.com/tailwindlabs/headlessui/discussions/2010
Transition on mount not working as expected using nextjs

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2059, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
