### ISSUE TITLE
Can not import and use Tab component within React Server Component on Next.js 13

### ISSUE THREAD

**Issue by judewang** [tailwindlabs/headlessui#2021]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.4

**What browser are you using?**

Safari

**Reproduction URL**

https://github.com/judewang/headlessui-rsc

With commands to start dev server:

```
pnpm install
pnpm dev
```

**Describe your issue**

I've read #1981 and thought we could import components from headlessui and use it right in the server component, but it failed to compile.

I've tried some approaches to use Tab component as sample code within server component, like wrapping the exporting within a client component:

```javascript
import { Tab } from "@headlessui/react"

export { Tab }
```

And it still failed.

Then I found 2 ways to make it work, one is wrapping all of the component that using Tab component as a big client component:

```javascript
"use client"

import { Tab } from "@headlessui/react";

export const Content = () => {
	return (
		<Tab.Group>
			<Tab.List>
				<Tab>Tab 1</Tab>
				<Tab>Tab 2</Tab>
				<Tab>Tab 3</Tab>
			</Tab.List>
			<Tab.Panels>
				<Tab.Panel>
					<p>Tab 1 content</p>
				</Tab.Panel>
				<Tab.Panel>
					<p>Tab 2 content</p>
				</Tab.Panel>
				<Tab.Panel>
					<p>Tab 3 content</p>
				</Tab.Panel>
			</Tab.Panels>
		</Tab.Group>
	);
};
```

This approach can result to a big client component since it's hard to pass several server components through the client component's props, this makes all child components within this big client component become client components, too.

The other way is re-exporting Tab components individually and using it right in the Server Component:

```javascript
// Tab.tsx

"use client"

import { Tab } from "@headlessui/react";

export const Group = Tab.Group;
export const List = Tab.List;
export const Panels = Tab.Panels;
export const Panel = Tab.Panel;
export { Tab };
```

```javascript
// Any other components

import { Group, List, Panel, Panels, Tab } from "./Tab";

export const Content = () => {
	return (
		<div className="py-20">
			<Container as="section">
				<Group>
					<List>
						<Tab>Tab 1</Tab>
						<Tab>Tab 2</Tab>
						<Tab>Tab 3</Tab>
					</List>
					<Panels>
						<Panel>
							<p>Tab 1 content</p>
						</Panel>
						<Panel>
							<p>Tab 2 content</p>
						</Panel>
						<Panel>
							<p>Tab 3 content</p>
						</Panel>
					</Panels>
				</Group>
			</Container>
		</div>
	);
};
```

In my opinion, the second way may has better performance but the usage is different than described in documentation. Not sure is this need to be noticed in the usage section of the documentation or should the exporting structure need some revise?

**Comment by judewang** [comment]
@thecrypticace Thank you for replying. When Vercel introduced the different between RSC and Client components, they said `You can pass a Server Component as a child or prop of a Client Component.` (but we cannot import a RSC directly within a Client component). In my case, most of the children of `Tab` and `Tab.Panel` components which I create can be rendered as RSC rather than a SSR component which still need the hydration progress on the client. I would keep using `Tab` with my workaround described above to pre render the children components on server.

![CleanShot 2022-11-19 at 13 14 48](https://user-images.githubusercontent.com/1559819/202833665-f9b2e994-d104-4e4b-b7d8-76bf9aae045b.png)

**Comment by suhaibmujahid** [comment]
In context of https://github.com/tailwindlabs/headlessui/issues/2021#issuecomment-1319951256:

> Unfortunately, the only thing that using `client-only` does is give you a better build error when compiling. I do not believe there is a way for 3rd party packages to automatically be treated as client-only in the same manner that adding `"use client;"` to your build does. Basically because it's a marker that a build tool looks for when compiling. Most of the time when including dependencies your build isn't _necessarily_ traversing an entire AST (there may be minimal versions of this for ESM _specifically_ for tree-shaking.. This is just a limitation of how RSCs work. I'm unsure if that will change in the future.

Thank you for the detailed reply, @thecrypticace! It seems that things have been changed and libraries are expected to use `"use client;"`. See https://nextjs.org/docs/getting-started/react-essentials#library-authors:

> ### Library Authors
> - In a similar fashion, library authors creating packages to be consumed by other developers can use the "use client" directive to mark client entry points of their package. This allows users of the package to import package components directly into their Server Components without having to create a wrapping boundary.
> - You can optimize your package by using ['use client' deeper in the tree](https://nextjs.org/docs/getting-started/react-essentials#moving-client-components-to-the-leaves), allowing the imported modules to be part of the Server Component module graph.
> - It's worth noting some bundlers might strip out "use client" directives. You can find an example of how to configure esbuild to include the "use client" directive in the [React Wrap Balancer](https://github.com/shuding/react-wrap-balancer/blob/main/tsup.config.ts#L10-L13) and [Vercel Analytics](https://github.com/vercel/analytics/blob/main/packages/web/tsup.config.js#L26-L30) repositories.


Adding `"use client;"` in all react components should solve the problem.
