### ISSUE TITLE
Nuxt: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom

### ISSUE THREAD

**Issue by DouglasCalora** [tailwindlabs/headlessui#2038]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.7.4

**What browser are you using?**
Chrome

**Reproduction URL**
https://stackblitz.com/edit/github-ah6srl?file=components%2FAppDialog.vue

**Describe your issue**
I'm using headless with Nuxt, i'm trying to use Dialog with example from docs but it throws an warning:
![image](https://user-images.githubusercontent.com/32134017/203221258-200c1431-396e-4ef1-8c90-c1d4972c6210.png)

When i click in the button "Got it, thanks!" it throws an error:
![image](https://user-images.githubusercontent.com/32134017/203221468-fb3a998f-b7d3-4cb9-8652-b2b0dd763cdf.png)

**Comment by morloderex** [comment]
@DouglasCalora you might need to wrap the `Dialog` within a `<ClientOnly>` component. So that it will not do prerendering.

**Comment by DouglasCalora** [comment]
> @DouglasCalora you might need to wrap the `Dialog` within a `<ClientOnly>` component. So that it will not do prerendering.

It worked, thanks!

**Comment by dustinleblanc** [comment]
Also ran into this issue using Nuxt 3. Component had been copied in from Tailwind UI. Spent a decent amount of time troubleshooting, but this did work, thanks!
