### ISSUE TITLE
`tailwindcss` insiders used as a dependency of `@headlessui/tailwindcss`

### ISSUE THREAD

**Issue by DamianGlowala** [tailwindlabs/headlessui#2039]
**What package within Headless UI are you using?**

@headlessui/tailwindcss

**What version of that package are you using?**

0.1.1

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/formkit/formkit/issues/482

**Describe your issue**

Why is insiders version used rather than the latest stable in the following `package.json`? It breaks other packages.

https://github.com/tailwindlabs/headlessui/blob/8b4363d7a474448078c4a996c8a97b35003767b0/packages/%40headlessui-tailwindcss/package.json#L42

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2040, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/tailwindcss@insiders`.
