### ISSUE TITLE
Combobox component error: undefined is not iterable

### ISSUE THREAD

**Issue by olinoles** [tailwindlabs/headlessui#2041]
**What package within Headless UI are you using?**

@headlessui/vue 1.7.4

**What version of that package are you using?**

1.7.4

**What browser are you using?**

Chrome

**Describe your issue**

When using the combobox component and any of the example snippets, I get the following devtools error

Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at watch.immediate (combobox.js:1:8249)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at job (runtime-core.esm-bundler.js:1798:17)
    at doWatch (runtime-core.esm-bundler.js:1840:13)
    at watch (runtime-core.esm-bundler.js:1675:12)
    at combobox.js:1:8223
    at runtime-core.esm-bundler.js:2743:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)

I'm using the example code from https://headlessui.com/vue/combobox in a new empty component.

Vue 3.2.41

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
