### ISSUE TITLE
[Listbox] Listbox throws an error when using multi-select select without providing a value

### ISSUE THREAD

**Issue by nwesthoff** [tailwindlabs/headlessui#2057]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

v1.7.4

**What browser are you using?**

Chrome & Safari

**Reproduction URL**

https://codesandbox.io/s/musing-cherry-y86t8u

[![Image from Gyazo](https://i.gyazo.com/9ab0b4271c5cdd460b0ef619403d766f.gif)](https://gyazo.com/9ab0b4271c5cdd460b0ef619403d766f)

**Describe your issue**

When using Listbox with `multiple` prop, without providing a value (eg. when using it in uncontrolled manner), it throws after clicking the trigger/button: 
```
Cannot read properties of undefined (reading 'some')
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We will make sure that it doesn't crash, however in `multiple` mode, you should always provide an array. If nothing is selected an empty array should be used.

**Comment by RobinMalfait** [comment]
This should be fixed by #2058, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
