### ISSUE TITLE
OpenClosedProvider Expected server HTML to contain a matching <nav> in <body>.

### ISSUE THREAD

**Issue by meliborn** [tailwindlabs/headlessui#2061]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: ^0.0.0-dev.0ce63d8

**What browser are you using?**

Chrome

**Describe your issue**

I have a NextJS 13 app. Here is a <Header /> component:

```javascript
function Header() {
	return (
		<Disclosure as="nav" className="bg-white shadow mb-10">
					<h1>test</h1>
		</Disclosure>
	);
}

```

Here is a warning with a stacktrace:
![Снимок экрана 2022-12-03 в 20 59 41](https://user-images.githubusercontent.com/735194/205455134-9aa7354e-e0b6-4ce1-8d95-4f33d5242610.png)

**Comment by givenloyiso** [comment]
I have the same problem, seems like it's not compatible with Next js 13.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This seems to work as expected for me: https://codesandbox.io/s/gifted-meadow-gwy58s?file=/pages/index.js

If this is still an issue for you, then please open a new issue with a minimal reproduction repo attached.

**Comment by meliborn** [comment]
@RobinMalfait no no, please use https://beta.nextjs.org/docs/routing/fundamentals
