### ISSUE TITLE
Update headline in docs to "Integrating with Next _12 and older"

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/headlessui#2072]
The docs on https://headlessui.com/react/menu#integrating-with-next-js state, that Next.js requires a special treatment.

However, my understand is, that from Next.JS 13 on the problematic behavior is not applied anymore (by default).

* https://blog.bitsrc.io/next-js-13-what-do-the-new-bleeding-edge-features-actually-do-d3e5fd418563#77ea 
  > The new Next.js `<Link>` component. Far more intuitive to use now, without needing that pesky nested <a> tag as a child. 

* https://nextjs.org/docs/api-reference/next/link

---

I suggest updating the subheadline to reference the Next.JS version. 

(I could not find the content of the docs in a public repos, so it's just an issue, not a PR… :))

**Comment by thecrypticace** [comment]
@tordans Thanks for the tip. @reinink and I tweaked the docs to clarify this behavior is no longer required for v13: https://headlessui.com/react/menu#integrating-with-next-js

Thanks! ✨
