### ISSUE TITLE
unmount prop doesn't work (Vue)

### ISSUE THREAD

**Issue by BartekZienkiewicz** [tailwindlabs/headlessui#208]
I know the unmount prop is not released yet, so I tried to use `@headlessui/vue@dev` but it still doesn't work. Any help?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Our releases to NPM are not automated, I published a new version onto the `dev` tag.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
