### ISSUE TITLE
Dialog, clicking outside to dismiss is letting the click go to the view below, need to stop propagation

### ISSUE THREAD

**Issue by sgehrman** [tailwindlabs/headlessui#2085]
Dialog, clicking outside to dismiss is letting the click go to the view below, need to stop propagation

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently done by design, if you don't want this behaviour, then you can render a `Dialog.Backdrop` that sits between the page and the `Dialog.Panel`.

E.g.: https://headlessui.com/react/dialog#adding-a-backdrop

**Comment by sgehrman** [comment]
ok, thanks for the 'fix' but I still think that is a bug. If someone clicks to dismiss a dialog, they don't want a random button to be clicked when clearly they didn't mean to click anything.
