### ISSUE TITLE
Enable/Disable Scroll Events Order Issue

### ISSUE THREAD

**Issue by nmorice** [tailwindlabs/headlessui#2105]
### What package within Headless UI are you using?
@headlessui/vue

### What version of that package are you using?
1.7.3
also tested with version 1.7.6 and  still happens

### What browser are you using?
Chrome

### Reproduction repository
none

### Describe your issue
If there is a Modal using a Dialog and inside that modal, there is a button to open a new modal (using also a Dialog). 
When I click the button, I close the first modal first and then open the second modal.
The `overflow: hidden `addition/removal don't work as expected.  It seems that the order of the events are incorrect.

Steps to reproduce issue:
-Open modal 1
-Open modal 2 (logic close modal 1 and then open modal 2)
-First error: Modal 2 don't have the `overflow: hidden` on the html tag
-Close modal 2
-Second error:  there is `overflow: hidden `on the html tag, preventing scroll on the page

Related issue: https://github.com/tailwindlabs/headlessui/issues/881

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Currently we don't support multiple Dialogs open at the same time, unless they are nested.

This problem can occur if you are opening and closing 2 dialogs consecutively BUT you are also using some `Transition` components. If you use the `Transition` component then one is still open (transitioning out) and the other is showing already (transitioning in) therefore multiple Dialogs are open on the same page.

Some workarounds can be found here: https://github.com/tailwindlabs/headlessui/issues/1744#issuecomment-1208079384

Once we have support for multiple Dialogs, then this problem should naturally go away.

Hope this helps!
