### ISSUE TITLE
[DOCS]: unmount and static props are not documented for Vue tabs component

### ISSUE THREAD

**Issue by mitar** [tailwindlabs/headlessui#2106]
Maybe also other components have them.

See #740, #743, #1048.

**Comment by jblachly** [comment]
In the case of `unmount`, it is documented for e.g. Dialog, but it does not do anything despite this

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed and the docs have been added:
- https://headlessui.com/react/tabs#tab-panel
- https://headlessui.com/vue/tabs#tab-panel

---

@jblachly it should work, if it doesn't then please create a minimal reproduction repo and open a new issue with the reproduction attached.
