### ISSUE TITLE
Using button element with Listbox.Button `as` prevents closing listbox from button

### ISSUE THREAD

**Issue by johnathanludwig** [tailwindlabs/headlessui#2113]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.7.4

**What browser are you using?**

For example: Chrome & Firefox

**Reproduction URL**

Codesandbox reproduction: https://codesandbox.io/s/headlessui-listbox-button-bug-m5rmkz?file=/index.js

**Describe your issue**

When passing a custom component that renders a `button` element via `as` prop to a Listbox.Button, clicking on the button does not close the Listbox. The button works fine for opening the listbox, and closing via clicking outside. However a click on the button itself will keep the listbox open. 

If you render a div element or don't use `as` then it closes properly.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'll make sure to update the documentation, but the key is that you always spread all incoming props _including_ the ref.

In your case, `Button` can be defined as:
```js
const Button = React.forwardRef((props, ref) => (
  <button ref={ref} {...props} />
));
```

I've updated the CodeSandbox for you: https://codesandbox.io/s/headlessui-listbox-button-bug-forked-xxmxdm?file=/index.js

Hope this helps!
