### ISSUE TITLE
Combobox shouldn't select the first option while searching. And we can add an event to the "enter" hotkey.

### ISSUE THREAD

**Issue by meotimdihia** [tailwindlabs/headlessui#2122]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

any

**Reproduction URL**

https://headlessui.com/react/combobox

**Describe your issue**
I want to use Combobox to build search input like Github's for the example.

But there is no way to press "enter" and trigger an event redirect to a search page.

**Comment by adamwathan** [comment]
Hey! Use the `onChange` event to trigger the redirect, that’s what runs when an option is selected 👍🏻

**Comment by meotimdihia** [comment]
@adamwathan thanks for the fast reply. But I mean this: 

<img width="705" alt="image" src="https://user-images.githubusercontent.com/300961/209442631-74722209-44b4-4a08-ba74-27757b3871fe.png">

Try to search for something then press enter: https://www.reddit.com/

I don't think onChange will do it.

**Comment by RobinMalfait** [comment]
Hey! You can use this pattern for that behaviour: https://headlessui.com/react/combobox#allowing-custom-values

**Comment by meotimdihia** [comment]
@RobinMalfait thanks, I didn't think it could be implemented like this.
