### ISSUE TITLE
Vue: MenuItem adds `disabled="false"` by default, triggering `disabled` CSS styles

### ISSUE THREAD

**Issue by Kagigz** [tailwindlabs/headlessui#2134]
# Details

Package: @headlessui/vue v1.7.7
Browser: Chrome
Reproduction URL: https://github.com/Kagigz/repro-tailwind-ui

# Issue 

I'm using sample code from Tailwind UI to add a Menu Button with Menu Items appearing in a dropdown when clicking it (cf image)

<img width="226" alt="image" src="https://user-images.githubusercontent.com/16519462/210118723-d0e11432-9c92-4a2e-ab5a-4736b7e21d49.png">

This is the sample code I'm using:

```html
<Menu as="div" class="relative ml-5 flex-shrink-0">
    <div>
      <MenuButton class="flex rounded-full bg-white focus:outline-none focus:ring-2 focus:ring-redorange-500 focus:ring-offset-2">
        <span class="sr-only">Open user menu</span>
        <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
      </MenuButton>
    </div>
    <transition enter-active-class="transition ease-out duration-100" enter-from-class="transform opacity-0 scale-95" enter-to-class="transform opacity-100 scale-100" leave-active-class="transition ease-in duration-75" leave-from-class="transform opacity-100 scale-100" leave-to-class="transform opacity-0 scale-95">
      <MenuItems class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
        <MenuItem v-for="item in userNavigation" :key="item.name" v-slot="{ active }">
          <a :href="item.href" class="block py-2 px-4 text-sm text-gray-700" :class="[active ? 'bg-gray-100' : '']">{{ item.name }}</a>
        </MenuItem>
      </MenuItems>
    </transition>
</Menu>
```

I don't understand why, but all the items appear as disabled.

# Reproduction steps

1. Clone the reproduction repo
2. Install dependencies with `pnpm i`
3. Run the app: `pnpm dev`
4. The code related to the header specifically is in `src/components/layout-ui/HeaderMenu`

Note: I'm using Tailwind via UnoCSS, the config is in `unocss.config.ts`

**Comment by adamwathan** [comment]
Thanks, I've looked at the reproduction and narrowed down the issue. Basically you have this CSS rule in your project coming from Ant Design:

**Comment by Kagigz** [comment]
Thanks!
