### ISSUE TITLE
[DOCS]: Sidebar scroll on component details page is overflowing header

### ISSUE THREAD

**Issue by Abdullah-Sajjad026** [tailwindlabs/headlessui#2139]
![image](https://user-images.githubusercontent.com/70557122/210331742-cfc9b9dd-be9d-469f-9300-ebda52f96e2f.png)

**Comment by reinink** [comment]
Hey! Thanks for sharing this, but this is the intended behavior as the site content and page navigation are designed to fall behind the top header — which includes the page navigation scrollbar if it's required. It admittedly does look a bit weird, but from a usability perspective it should work fine 👍
