### ISSUE TITLE
problem when use google pagespeed insights

### ISSUE THREAD

**Issue by webtinax** [tailwindlabs/headlessui#214]
https://developers.google.com/speed/pagespeed/insights

![Image of Yaktocat](https://user-images.githubusercontent.com/17506890/86462844-e84a9980-bd5e-11ea-8e6a-00d86b5219d0.png)

when use this package in nextjs

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issues!
Much appreciated! 🙏

What does this have to do with Headless UI? It's complaining about "A preload <link> was found ...", we don't have `<link>`'s in Headless UI?
Could you elaborate what you mean?

**Comment by webtinax** [comment]
thank for fast response 
no issue
The problem was from another part
