### ISSUE TITLE
Warning in console when using more than one Popover.Button inside Popover.Panel

### ISSUE THREAD

**Issue by twittkopf** [tailwindlabs/headlessui#2143]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/gracious-sinoussi-nlzl6e?file=/src/App.js

**Describe your issue**

When using more than one `<Popover.Button />` inside `<Popover.Panel />` to close the panel after click, I see the following warning in the console:

```
You are already using a <Popover.Button /> but only 1 <Popover.Button /> is supported.
```
Since using multiple `<Popover.Button />` _inside_ `<Popover.Panel />` is a supported use case according to the docs, this seems to be an error. I'd expect the warning is only shown when using more than one `<Popover.Button />` _outside_ of `<Popover.Panel />` because that use case is not supported.

After a [check-in in Discord,](https://discord.com/channels/486935104384532500/758325031163002921/1060124581010092032) it appears the current behaviour is indeed not as intended.

Related [GitHub Discussion Thread](https://github.com/tailwindlabs/headlessui/discussions/2133)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2146, and will be available in the next release.

You can already try it (in a few minutes) using `npm install @headlessui/react@insiders`.

**Comment by michaelcais** [comment]
This false positive warning of multiple `<Popover.Button>` is happening again in `@headlessui/react@1.7.12`. I reverted back to previous version `@headlessui/react@1.7.11` and the warning disappears. All my app's `<Popover.Button>` components are inside a `<Popover.Panel>`.

**Comment by RobinMalfait** [comment]
@michaelcais thank you, I'll take care of that!

**Comment by RobinMalfait** [comment]
This PR should fix that, sorry about this! https://github.com/tailwindlabs/headlessui/pull/2333
