### ISSUE TITLE
Combobox options remain filtered after selecting an option with Enter

### ISSUE THREAD

**Issue by ragulka** [tailwindlabs/headlessui#2171]
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

For example: v1.7.7

**What browser are you using?**

For example: Brave

**Reproduction URL**

* https://headlessui.com/vue/combobox (buggy)
* https://headlessui.com/react/combobox (works as expected)

**Describe your issue**

1. Type `Devon` into the Combobox input
2. Press `Enter` to select `Devon Webb`
3. Click on the combobox button
4. Options show only a single option: `Devon Webb` (selected) 
<img width="320" alt="CleanShot 2023-01-10 at 12 12 08@2x" src="https://user-images.githubusercontent.com/593267/211523255-538836f5-8396-4c5f-a642-9ff4978f4607.png">
5. Click anywhere outside the combobox and its options
6. Click on the combobox button, again
7. Options now show all available options, with `Devon Webb` as selected 
<img width="326" alt="CleanShot 2023-01-10 at 12 12 28@2x" src="https://user-images.githubusercontent.com/593267/211523300-adaa4fdf-d94c-4972-b9b0-637b1ac27318.png">

**Expected result**
I would expect to see _all_ options in step 4. This is true for the React version of combobox, which works as expected.

**Synopsis**
It looks like the Vue version changes the `ComboboxInput` value when the input briefly loses focus as the user clicks on the `ComboboxButton`. It sets the value to the display value of the currently selected option. This triggers the `onChange` handler, which is used to filter the list of options.

Note that this issue does not happen when:
* selecting the option by clicking on it
* when selecting the option by pressing Enter, and then opening the list of options by pressing down arrow key
* when selecting the option by pressing Tab (actually, it does, but the query is reset to an empty string due to `@after-leave="query = ''"` on `TransitionRoot`

Unfortunately, I'm not sure what exactly causes the ComboboxInput value to change on blur. It seems like the component may be re-rendered?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2296, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/vue@insiders`.
