### ISSUE TITLE
Transition breaks Popover Panel focus management

### ISSUE THREAD

**Issue by RyanClementsHax** [tailwindlabs/headlessui#2186]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/RyanClementsHax/ryanclements.dev/tree/popper-focus-bug

**Describe your issue**

Steps to reproduce
1. `yarn install`
2. `yarn dev`
3. Open browser to find two usages of popover, one uses transitions (doesn't work) and the other doesn't use transitions (works)

The issue is when the popover is closed, focus should return back to the button that opened it, but using transitions breaks this. It seems to be related to the following warning that is printed into the console when opening the popover panel `You are already using a <Popover.Button /> but only 1 <Popover.Button /> is supported.` as when the popover panel closes with transitions, it seems the last button in the panel receives that focus before being unmounted thus preventing focus from returning to the button that opened the panel.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should already have been fixed in the insiders version and it will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by RyanClementsHax** [comment]
out of curiosity, was there an open issue already created for this? I looked for one and didn't find any.

**Comment by RyanClementsHax** [comment]
Also this worked for me thanks :)

**Comment by RobinMalfait** [comment]
Yep, 2 related issues in fact! Easiest way to find (unreleased) fixes is by checking the changelog files. E.g.: https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-react/CHANGELOG.md

- First one:
  - Issue: https://github.com/tailwindlabs/headlessui/issues/2143
  - PR: https://github.com/tailwindlabs/headlessui/pull/2146
- Second one:
  - Issue: https://github.com/tailwindlabs/headlessui/issues/2154
  - PR: https://github.com/tailwindlabs/headlessui/pull/2163

Glad it worked for you!
