### ISSUE TITLE
bug with @next/font modal displays Times New Roman

### ISSUE THREAD

**Issue by DanielDerma** [tailwindlabs/headlessui#2189]
"@headlessui/react": "^1.7.7",
    "@next/font": "13.1.2",
    "next": "13.1.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",

```
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "eslint-config-prettier": "^8.6.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.2",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "tailwindcss": "^3.2.4"
  }
```

**What browser are you using?**

Chrome

[**Reproduction URL**](https://github.com/DanielDerma/-next-font-bug-headless-react)

Open the repo and you can use **codespaces**, **npm i** and then **npm run dev**

**Describe your issue**
when i use the modal example of the page this https://headlessui.com/react/dialog and the configuration in 

**_app.tsx**
**tailwind.config.js**

 works great but with headlessui uses Times New Roman, even  in important:true

**Comment by adamwathan** [comment]
Hey! You need to make sure you are adding the class name that sets the font variable on either the body or HTML elements, not main. The modal dialog is rendered outside of main in a portal, so main isn’t a parent which means the style isn’t being applied.

**Comment by RobinMalfait** [comment]
Hey!

As Adam mentioned this is because the `Dialog` is rendered in the body. So if you followed this:
- https://nextjs.org/docs/basic-features/font-optimization#with-tailwind-css

Then you can keep most of it, but instead of applying that variable to the `main` tag, you can inject it into the `html` itself. You could use this approach:
- https://nextjs.org/docs/basic-features/font-optimization#apply-the-font-in-head

To combine it all, it looks like this:
```js
// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      md: "550px",
      lg: "900px",
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-montserrat)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
```

```js
// pages/_app.js
import { Montserrat } from "@next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <style jsx global>{`
        :root {
          --font-montserrat: ${montserrat.style.fontFamily};
        }
      `}</style>
      <Component {...pageProps} />
    </>
  )
}
```
