### ISSUE TITLE
Popover Button Warning Displayed on React 17

### ISSUE THREAD

**Issue by JoseRFelix** [tailwindlabs/headlessui#2204]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/priceless-black-1qen8e?file=/src/index.js

**Describe your issue**

I am receiving the warning `"You are already using a <Popover.Button /> but only 1 <Popover.Button /> is supported."` on React 17 when `Popover.Button` is rendered as a `Fragment`. The warning should not be displayed as only one button is being created.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2163, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.
