### ISSUE TITLE
Broken fonts when using Headless UI Dialog (Modal) with Nextjs @next/font

### ISSUE THREAD

**Issue by nyedidikeke** [tailwindlabs/headlessui#2225]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v2.0.13

**What browser are you using?**
Chrome, Brave, Safari, Edge, and Firefox

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.
https://github.com/nyedidikeke/next-font-with-headless-ui-dialog.git

**Describe your issue**
When using [@next/font](https://nextjs.org/docs/basic-features/font-optimization) from Nextjs with [Headless UI Dialog (Modal)](https://headlessui.com/react/dialog), the fonts do not apply to the modal.

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.
Please find below steps to reproduce.
1. Run `npx create-next-app@latest` to create a new Nextjs project.
2. Run `npm install @next/font @headlessui/react` to install npm install the Nextjs font optimisation as well as the Headless UI packages for react.
3. Add a custom font in all pages by editing [_app.js file](https://nextjs.org/docs/advanced-features/custom-app) under the `/pages` folder as shown below.
```js
// pages/_app.js
import { Inter } from '@next/font/google'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export default function MyApp({ Component, pageProps }) {
  return (
    <main className={inter.className}>
      <Component {...pageProps} />
    </main>
  )
}
```
4. Create a new page as `dialog.js` under the `/pages` folder, and paste into it the code from the very first sample dialog (modal) available at https://headlessui.com/react/dialog.
5. Run `npm run dev` to start the development server on [`http://localhost:3000`](http://localhost:3000).
6. Visit [`http://localhost:3000`](http://localhost:3000) to view the default Nextjs page and take note of the font family in use.
7. Then, visit [`http://localhost:3000/dialog`](http://localhost:3000/dialog) to view the Headless UI Dialog (modal) page and compare the font family in use on the page itself (same as the default Nextjs page) as against the one in use on the rendered Headless UI Dialog (modal) - it actually other than the [`Inter`](https://fonts.google.com/specimen/Inter) font family intended.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because the `Dialog` renders in a `Portal` inside of the `body` directly. That means that it is rendered _outside_ of the `main` element.

Instead, I would recommend you to inject the css as a css variable for example into the `head`: https://nextjs.org/docs/basic-features/font-optimization#apply-the-font-in-head

Here is an example on how you can achieve that: https://github.com/tailwindlabs/headlessui/issues/2189#issuecomment-1385379554

Hope this helps!
