### ISSUE TITLE
Combobox not closing on ESC

### ISSUE THREAD

**Issue by nicoorfi** [tailwindlabs/headlessui#2239]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Chrome

**Reproduction URL**

https://headlessui.com/react/combobox#using-as-an-uncontrolled-component
https://tailwindui.com/components/application-ui/forms/comboboxes

**Describe your issue**

The ESC button isn't closing the **Combobox**. It isn't working on the HeadlessUI docs, and TailwindUI examples.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you double check in incognito mode and/or in another browser?
I can't reproduce this in any browser, so my guess is that you have some extension installed that is fighting against the intended behaviour.

**Comment by nicoorfi** [comment]
Oh, it was (Vimium)[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en] that was causing this.

Sorry for wasting your time.

Thank you for this awesome work on Headless UI much appreciated!

**Comment by RobinMalfait** [comment]
Perfect, glad it's working now (or at least happy you found the root cause!)

Thanks for the kind words! 🤝
