### ISSUE TITLE
[Vue] <Switch /> doesn't support `true-value`/`false-value`

### ISSUE THREAD

**Issue by CasperEngl** [tailwindlabs/headlessui#2241]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Chrome

**Reproduction URL**

[Codesandbox](https://codesandbox.io/s/wispy-glitter-64nj02?file=/src/App.vue)

**Describe your issue**

When working with native input checkboxes, Vue can change the v-model value with the `true-value` and `false-value` props. This doesn't seem to work for HeadlessUI Switches.

In my reproduction, if you click the Switch button, it toggles the value from `false | true`, and the native input toggles the value to `0 | 1`.

Vue's documentation on the behavior: https://vuejs.org/guide/essentials/forms.html#checkbox-1

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `true-value` and `false-value` Vue has are non-native properties and only work for the native `input[type="checkbox"]`. Our component is a `Switch` implementation to make it styleable while keeping it accessible but without using the native `input[type="checkbox"]`.

We are not planning on adding those APIs and your workaround is fine if you want to use `0 | 1` values 👍

**Comment by CasperEngl** [comment]
Got it. Thanks for the prompt response.
