### ISSUE TITLE
default selected is not working for tabs on @headlessui/react v1.7.8

### ISSUE THREAD

**Issue by josetom** [tailwindlabs/headlessui#2245]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.8

**What browser are you using?**
Chrome

**Reproduction URL**
v1.7.8 with bug - https://stackblitz.com/edit/react-vvrzmq?file=src%2FApp.js
v1.7.7 as expected - https://stackblitz.com/edit/react-eprbkg?file=src%2FApp.js

**Describe your issue**
In v1.7.8 react tabs, default selected is not working as expected if the underlying data changes.
You can notice in the example that the first tab gets selected in v1.7.7, however, in 1.7.8 no tabs are selected by default.
I have not given a defaultSelected prop in the example (expecting default 0). But even if you give one it doesn't seem to be respected.

**Comment by thecrypticace** [comment]
Hey thanks for the report. This should be fixed, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`

Appreciate it! ✨
