### ISSUE TITLE
Dialog Scrollbar doesn't work properly on Mobile Devices

### ISSUE THREAD

**Issue by jagustin** [tailwindlabs/headlessui#2246]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.7

**What browser are you using?**

Chrome and Safari on iPhone 13 Pro

**Reproduction URL**

[Bug url](https://drive.google.com/file/d/13HAZQb1VectwQ4rLSKqz4lDt_ESFUNVM/view?usp=share_link)

**Describe your issue**

When the Dialog Modal is opened and the body has been scrolled before, the scroll event works for the body scroll but not for the Dialog Modal. That only happens on mobile devices. I am including a video to help you understand the issue.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
