### ISSUE TITLE
Combobox: tag-picker-like combobox multiselect after one pick and then another pick without unfocus navigation starts from second element

### ISSUE THREAD

**Issue by RIP21** [tailwindlabs/headlessui#2269]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.10

**What browser are you using?**
Chrome

**Reproduction URL**

[Video recording](https://share.cleanshot.com/vbNzmbVh)
[Codesandbox](https://codesandbox.io/s/headless-bugs-ci0fb2?file=/src/index.tsx)

**Describe your issue**

If you try to build a tag picker (so multi-select combobox) so the selected item disappears from the options once selected, it messes up options selection causing selection to happen from the second option and not the first and there is no way to work around it as selection logic is hidden. It works fine for regular multi-select.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2274, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by RIP21** [comment]
Wow! That was quick! Thank you!
