### ISSUE TITLE
umount=true causes all tab panels to be loaded immediately; panels are loaded twice for unmount=true|false

### ISSUE THREAD

**Issue by waynebrantley** [tailwindlabs/headlessui#2276]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.9

**What browser are you using?**
Chrome

**Reproduction URL**
https://stackblitz.com/edit/vitejs-vite-pwdb1w?file=src%2FApp.tsx&terminal=dev

**Describe your issue**
## unmount=true (the default)
- the component correctly mounts each tab as necessary (clicked/activated).  It also unmounts them as necessary.

## unmount=false
- the component correctly does not unmount each tab
- the component mounts each tab on initial render.  While we indicated not to unmount, still would like to mount only as necessary (clicked/activated).

## unmount=true|false
- the component mounts and then unmounts and then mounts again as each tab is activated (or all tabs when false)

## summary of issues
- Each tab should only be mounted as necessary and unmount=false should only control if it is unmounted - not change when it is mounted.
- Each tab should only be mounted once when necessary.  So if you click a tab - it should mount once (where it does a mount/unmount/mount now)

Full example above based on the headlessui.com example code.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a side effect of the `React.StrictMode` component in your `main.tsx` file. This is not something _we_ have control over. This will also not happen in production. You can get rid of this if you don't want that behaviour.

```diff
  ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
-   <React.StrictMode>
      <App />
-   </React.StrictMode>,
  )
```

But, the goal of `StrictMode` is to discover bugs that would occur in future versions of React with Suspense. More info: https://reactjs.org/docs/strict-mode.html more explicitly this part: https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state

If you get rid of this, then you will see that the mounting / unmounting only happens once.

Hope this helps!

**Comment by waynebrantley** [comment]
@RobinMalfait I KNEW I should not have expanded this ticket to have both items in it.  I totally forgot about the development double load.   

However, the reason I opened this ticket was the first item - where each tab should only be mounted as necesssary.

- Each tab should only be mounted as necessary and unmount=false should only control if it is unmounted - not change when it is mounted.

I updated the example to remove talking about double mount issue (and removed the StrictMode so it would not do it) - but other than that example is still the same, showing all tabs 'preload'

https://stackblitz.com/edit/vitejs-vite-pwdb1w?file=src%2FApp.tsx&terminal=dev

**Comment by RobinMalfait** [comment]
Gotcha, the current behaviour is the behaviour we chose as a default for all our components. It is a generic render strategy and we currently expose those 2 strategies. Either mount/unmount (`unmount={true}`) based on internal state or keep everything in the DOM (`unmount={false}`). 

You are correct that this means that they are "preloaded". The advantage of this is that this means that they can be server rendered with the necessary information in the tabs and that they could be used for SEO if you wish.

I don't see this as a bug, but what you want in this case is a new feature to control this behaviour. But I don't think we will add support for such feature in the near future. However, that doesn't solve your problem. What you _can_ do, is use the exposed information like the selected index to build on top of this component to do the lazy loading if you want. 

Something like this could work: https://stackblitz.com/edit/vitejs-vite-xztue8?file=src/App.tsx

Hope this makes sense!

**Comment by waynebrantley** [comment]
Even in your example it loads all tabs ahead of time.  

I understand you consider this to be a feature and not a bug.  I just fail to see why a "do not unmount when tab changes" flag would change what is mounted when component loads!  

While I see the possible advantage on server side - same is true on server side - dont want to load 6 expensive tabs when we only show one - and they only need one.

I would suggest you consider a feature such as 'preloadAllContent' flag that would control that part of it - seems you could just keep track of if the content was loaded or not in much the same way you keep it for unmounting.

Understand if you still do not see this a issue/feature/problem you want to solve.   Your components are great and I really appreciate the conversation.

**Comment by waynebrantley** [comment]
@RobinMalfait - Any additional thoughts?

**Comment by WesleyKapow** [comment]
I hit this same issue. I want the tabs to not be unmounted but I do not want them to also be pre-mounted. The reason is that I'm working with FE components (no SSR) and each tab fetches data. Pre-mounting means that all tabs will fetch all data even if they are never clicked on -- BAD!

@waynebrantley I came up with the following work around, hope it helps!

The trick is to use `unmount={false}` to get the "keep alive"/caching of the component. Then keep track of which tabs have been clicked on (below via `shown`) and guard rendering of the tab content by whether it has been shown or not.

```ts
function MyTabComponent({tabs}) {
  const [selectedTabIndex, setSelectedTabIndex] = useState(0);
  const [shown, setShown] = useState<Record<number, boolean>>({ 0: true }); // Set default tab to be shown = true

  const handleOnChange = (index: number) => {
    setSelectedTabIndex(index);
    setShown({ ...shown, [index]: true });
  };

  return (
      <Tab.Group selectedIndex={selectedTabIndex} onChange={handleOnChange}>
        <Tab.List>
          {tabs.map(({ key, name, content }) => (
            <Tab key={key}>{name}</Tab>
          ))}
        </Tab.List>

        <Tab.Panels>
          {tabs.map((key, content) => (
            <Tab.Panel key={key} unmount={false}>
              {shown[index] && content}
            </Tab.Panel>
          ))}
        </Tab.Panels>
      </Tab.Group>
    </div>
  );
}
```

**Comment by waynebrantley** [comment]
@WesleyKapow Nice fix on this.  (well I consider it a fix - they consider it working :-) ) 
Will likely just roll that into ours!
