### ISSUE TITLE
close is not provided as a render prop

### ISSUE THREAD

**Issue by filipenevola** [tailwindlabs/headlessui#2307]
As the docs says here https://headlessui.com/react/menu#closing-menus-manually a `close` function should be provided as a render prop to `Menu` and `MenuItem` components.
 
```
import { Menu } from '@headlessui/react';

...

    <Menu as="div" className="relative inline-block text-left">
      {({ close }) => {
        console.log(`close`, close);

...

```

This log results in `close undefined`, the same happens for `MenuItem`.

I checked [both](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L273-L299) [code](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L649-L713) and it seems they are not passing the close function as a prop indeed and I'm not able to get it in any other way.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Make sure you are on a version that exposes this. For example on the latest version they are exposed: https://codesandbox.io/s/serene-taussig-p0xtjq?file=/src/App.js

Both links you shared expose the `close` functionality:
- First one: https://github.com/tailwindlabs/headlessui/blob/7794d563e181787e995db1f877cd26c460e385ee/packages/%40headlessui-react/src/components/menu/menu.tsx#L687-L690 & https://github.com/tailwindlabs/headlessui/blob/7794d563e181787e995db1f877cd26c460e385ee/packages/%40headlessui-react/src/components/menu/menu.tsx#L711
- Second one: https://github.com/tailwindlabs/headlessui/blob/7794d563e181787e995db1f877cd26c460e385ee/packages/%40headlessui-react/src/components/menu/menu.tsx#L277-L280 & https://github.com/tailwindlabs/headlessui/blob/7794d563e181787e995db1f877cd26c460e385ee/packages/%40headlessui-react/src/components/menu/menu.tsx#L296

If this is not the case for you:
1. Make sure you are on the latest version
2. Open a new issue with a minimal reproduction repo attached that shows the issue

Hope this helps!

**Comment by filipenevola** [comment]
Oh, you were right, the latest minor included this and now it's working, sorry
