### ISSUE TITLE
Press and hold "Space" bar may lead to error for Listbox/Select with transition

### ISSUE THREAD

**Issue by horans** [tailwindlabs/headlessui#2316]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.11

**What browser are you using?**

Chrome v110 on Win10

**Describe your issue**

I totally undertand why `Space` bar is supported, and I am totally ok with it, in normal cases.
However, when dealing with a complex `Listbox` plus `transition`, things might get tricky.

![image](https://user-images.githubusercontent.com/12060804/221816080-7dee6a32-a149-4fa9-b1c7-0bd330674720.png)

This happens when we click the `ListboxButton`, then press and hold `Space`.
Then the `ListboxOptions` started to blink, and the error came up in few seconds.

It works fine when:
- simple `ListboxOptions` **with** transition
- complex `ListboxOptions` **without** transtion

Can we still keep the keyboard event handlings, but adding an `event.repeat` check to avoid this kind of error?

related issues:
- <https://github.com/tailwindlabs/headlessui/issues/1554>
- <https://github.com/tailwindlabs/headlessui/discussions/820>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you please attach a minimal reproduction repo that shows the issue?

**Comment by reinink** [comment]
Hey! Going to close this issue since we haven't heard back. Feel free to still provide a minimal reproduction and a Git repo and we can have another look, as per the new issue template:

> **Reproduction URL**
> 
> A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.
