### ISSUE TITLE
headless UI 1.7.8 Tab + react router 6.8.1 NavLink + function in className broken on 1.7.8

### ISSUE THREAD

**Issue by wmitsuda** [tailwindlabs/headlessui#2317]
Please see that minimal component: https://github.com/wmitsuda/otterscan/blob/develop/src/components/NavTab.tsx#L13

It works on 1.7.7, but the styling is broken on 1.7.8 or later.

It seems the function on className that NavLink accepts does not work well with headlessui Tab anymore, the function gets serialized in the class field instead of executed.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a _minimal_ reproduction repo that showcases the issue?

<img width="591" alt="image" src="https://user-images.githubusercontent.com/1834413/221832374-f18cb9b7-ea58-4d84-a505-4f0ba4f5fae1.png">

**Comment by reinink** [comment]
Hey! Going to close this issue since we haven't heard back. Feel free to still provide a minimal reproduction and a Git repo and we can have another look, as per the new issue template:

> **Reproduction URL**
> 
> A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.
