### ISSUE TITLE
Typescript errors after upgrading to 0.3.0

### ISSUE THREAD

**Issue by anark** [tailwindlabs/headlessui#233]
After upgrading from 0.2.0 to 0.3.0 I am seeing the following typescript errors.

`Expression produces a union type that is too complex to represent` on 

```
    <Menu.Item>
      Test
    </Menu.Item>
```
And
```
    <Switch
      checked={true}
    >
      <span css={tw`sr-only`}>test</span>
      <span></span>
    </Switch>
```

Also seeing `Binding element 'open' implicitly has an 'any' type.` on the following

```
      <Menu>
        {({ open }) => <>{open}</>}
      </Menu>
```

I am currently using typescript `4.1.3`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I did some fixes to the TypeScript types and released them in [@headlessui/react@v0.3.1](https://github.com/tailwindlabs/headlessui/releases/tag/@headlessui/react@v0.3.1).

Can you verify that the errors are gone? If not, can you provide a reproduction repository/codesandbox that showcases this issue?

**Comment by anark** [comment]
I am still seeing this error after upgrading to `0.3.1`, however I have narrowed it down to a conflict with @emotion/styled.

I have the following lines in my `tsconfig.json`
```
    "jsx": "react-jsxdev",
    "jsxImportSource": "@emotion/react",
```

And if I remove 
```
    "jsxImportSource": "@emotion/react",
```

The warning is gone, however I can no longer use @emotion to add styling via the css prop.  This worked find in version `0.2.0`.   Any idea what change was made in `0.3.0` that would lead to this issue?

**Comment by devrsi0n** [comment]
For someone still need emotion jsx import like me, you can add `/// <reference types="@emotion/react/types/css-prop" />` to the top of a global type module. Here is the details: https://emotion.sh/docs/typescript .

**Comment by PeterlitsZo** [comment]
Well, I am not sure why we should remove this line... I still need the `jsx` function from `@emotion/react`...

**Comment by jabczyk** [comment]
I encountered the same issue with `Dialog`. Couldn't remove the `jsxImportSource` line because it breaks the css prop, so I used `@ts-expect-error` as a workaround:
```ts
const Modal: React.FC = () => {
  return (
    // @ts-expect-error
    <Dialog />
  )
}
```
