### ISSUE TITLE
Popover and Dialog cant start as open

### ISSUE THREAD

**Issue by drexxdk** [tailwindlabs/headlessui#2349]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.4

**What browser are you using?**

Chrome

**Describe your issue**

```typescript
import { Dialog } from '@headlessui/react';
import { useState } from 'react';

const Modal = () => {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <Dialog open={isOpen} onClose={() => setIsOpen(false)}>
      <Dialog.Panel>
        <Dialog.Title>Deactivate account</Dialog.Title>
        <Dialog.Description>This will permanently deactivate your account</Dialog.Description>
        <p>
          Are you sure you want to deactivate your account? All of your data will be permanently removed. This action
          cannot be undone.
        </p>
        <button onClick={() => setIsOpen(false)}>Deactivate</button>
        <button onClick={() => setIsOpen(false)}>Cancel</button>
      </Dialog.Panel>
    </Dialog>
  );
};
export default Modal;
```

It results in this
```
<div id="headlessui-portal-root">
```
rendering the child 
```
<div data-headlessui-portal>
```
 21 times.

If I add a timeout before setting it to true, then it correctly only renders 1 time

```typescript
useEffect(() => {
    const timer = setTimeout(() => {
      setIsOpen(true);
    }, 250);
    return () => clearTimeout(timer);
  }, []);
```

For Popover the logic breaks if it starts as open. Then it cant handle browser window resize or scroll correctly

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up. For example, copying your first snippet in CodeSandbox works as expected: https://codesandbox.io/s/recursing-vaughan-3idfor?file=/src/App.js

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
