### ISSUE TITLE
Keyboard enum

### ISSUE THREAD

**Issue by CTOJoe** [tailwindlabs/headlessui#235]
I am so excited for a project like this to exist. My company loves TailwindCSS, TailwindUI, and Refactoring UI. While looking at the react source, I was curious why the choice of writing out a custom keyboard enum was chosen over the installation of a package such as [ts-key-enum](https://www.npmjs.com/package/ts-key-enum). I know these enums will almost never change, but why not leave the concern to a project that exclusively maintains and tests this enum?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

There are multiple reasons:

- I don't want/need dependencies if they are not a perfect fit.
- I only need a handful of keyboard keys, there is no need to include *all* of it.
- Bundle size, this enum is massive... https://unpkg.com/browse/ts-key-enum@2.0.7/dist/js/Key.enum.js
- It may be possible to load the ts version directly to make use of tree-shaking, but this sounds like too much hassle in my opinion.
- My very first key is `Space = ' '` and I can't seem to find it in the list above.

In my personal opinion, I feel like we use too many dependencies in the JavaScript/Node community. Sure I am not going to build my own React, but for things like this it's a bit overkill. 

Hope this answers your question!
