### ISSUE TITLE
Listbox keyboard events with NVDA

### ISSUE THREAD

**Issue by sethiyark** [tailwindlabs/headlessui#2351]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

For example: Chrome

**Reproduction URL**

https://codesandbox.io/s/sharp-banach-ik2qid?file=/src/App.js

**Describe your issue**

While using NVDA keyboard events are not working as expected for select.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Going to close this issue for now, wrote more about why on the PR you provided:
https://github.com/tailwindlabs/headlessui/pull/2352#issuecomment-1468055650
