### ISSUE TITLE
eslint vue/no-unused-components false positive

### ISSUE THREAD

**Issue by Troncoso** [tailwindlabs/headlessui#236]
Just curious if anyone knows why this is happening. For the `Menu` and `Switch` components specifically, eslint warns that the components are not being used if I use the lowercase version:

```vue
<template>
    <switch-group>
        <switch-label>{{}}</switch-label>
        <switch />
    <!-- ^ when this is lowercase -->
    </switch-group>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Switch, SwitchGroup, SwitchLabel } from '@headlessui/vue';

export default defineComponent({
    components: { Switch, SwitchGroup, SwitchLabel }
    //            ^ this is flagged by eslint
});
</script>
```

```
The "Switch" component has been registered but not used. eslint(vue/no-unused-components)
```

The other components such as `SwitchGroup` and `SwitchLabel` don't have this issue.

**Comment by adamwathan** [comment]
I'm guessing it thinks you are just writing regular HTML elements (there actually is a real `menu` element in HTML for example).

This is probably related to how Vue recommends always using two words in custom component names if you are going to use the dash case versions. Personally I would just recommend using the uppercase names, even Evan writes his Vue stuff this way from what I've seen 👍🏻

**Comment by Troncoso** [comment]
Yep. Now that you say that, I found that there is a `<switch>` element as well (related to SVG). I switched my eslint to use `PascalCase`, so that fixed that. Thanks!
