### ISSUE TITLE
Accessing ui-*: css modifier from within Switch element

### ISSUE THREAD

**Issue by TheVaan** [tailwindlabs/headlessui#2361]
**What package within Headless UI are you using?**

`@headlessui/vue`

**What version of that package are you using?**

[v1.7.11](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Fvue%40v1.7.11)

**What browser are you using?**

Chrome, Safari

**Reproduction URL**

```vue
<script setup lang="ts">
import { ref } from 'vue'
import { Switch, SwitchGroup } from '@headlessui/vue'

const enabled = ref(false)
</script>

<template>
  <SwitchGroup>
    <div class="flex items-center justify-between">
      <Switch
        v-model="enabled"
        class="relative inline-flex items-center h-6 transition-colors rounded-full w-11 ui-checked:bg-indigo-600 ui-not-checked:bg-gray-200"
      >
        <span
          class="inline-block w-4 h-4 transition-transform transform bg-white rounded-full ui-checked:translate-x-6 ui-not-checked:translate-x-1"
        />
      </Switch>
    </div>
  </SwitchGroup>
</template>
```

**Describe your issue**

`ui-checked:` and `ui-not-checked` don't have any effect on the span element while using them in the Switch component is possible. Would be nice exposing checked state from Switch to the child element.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Here is a working CodeSandbox: https://codesandbox.io/s/fancy-river-vno8s9?file=/src/App.vue
Make sure that you are using `@headlessui/tailwindcss` as a Tailwind plugin as well.

---

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
