### ISSUE TITLE
vue: @change not emitted on Switch

### ISSUE THREAD

**Issue by jiblett1000** [tailwindlabs/headlessui#2369]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.12

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/jiblett1000/switch-test

**Describe your issue**

As per the Switch documentation:

```
Any @change prop you provide will still be called when the component's value changes in case you need to run any side effects, but you won't need to use it to track the component's state yourself.
```

The above is not true. Change event is not getting called.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Trying to run your reproduction seems to result in an error:
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/1834413/225607146-2dc0d53f-c57c-4f1e-9570-54f768e0ca87.png">

However, this is a documentation bug that has been fixed. When the `v-model` is used, then this is a shorthand for:

```vue
<CustomInput
  :modelValue="searchText"
  @update:modelValue="newValue => searchText = newValue"
/>
```
https://vuejs.org/guide/components/v-model.html

This means that you should be able to apply the following diff:
```diff
- @change="something"
+ @update:modelValue="something"
```

Hope this helps!
