### ISSUE TITLE
with headleesui, With full-width flyouts Components could not run well

### ISSUE THREAD

**Issue by singleseeker** [tailwindlabs/headlessui#237]
As tailwindui.com and this headlessui plugin from the same team.

I think they should run well with each other.

Well, when using With full-width flyouts Header, in case of showing the dropdown menu, we are using headleesui, then we must change the code structure.

After that, the menu shows not good. 

![image](https://user-images.githubusercontent.com/520698/107836843-73057380-6dd9-11eb-9ec5-c930b1fdfc81.png)

Here is the link, any suggestion?

Thank you.

https://codesandbox.io/s/little-feather-1sssv?file=/src/App.js

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The menu component is not intended to be used for a flyout menu, its mainly used for dropdowns or your native menubar like situation. We have a new component in the `develop` branch, called a `Popover` that can be used for this very use case:

- PR: https://github.com/tailwindlabs/headlessui/pull/220
- Docs: https://github.com/tailwindlabs/headlessui/tree/develop/packages/@headlessui-react#popover

Note: this version is not released yet, however we do have it published under the `dev` tag.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
