### ISSUE TITLE
Demo `Dialog` component produces a `no-op` error on unmount

### ISSUE THREAD

**Issue by b3nk3** [tailwindlabs/headlessui#2373]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.13
React v17

**What browser are you using?**

For example: Arc, Chrome, Safari

**Reproduction URL**

[CodeSandbox](https://codesandbox.io/s/react-17-forked-7chk7p?file=/src/App.js)

**Describe your issue**

Transition generates the following error when closed the first time. Only reproducible on React 17, but I am unable to upgrade my codebase to 18 just yet.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

**Comment by dev-bjoern** [comment]
Related https://github.com/reactwg/react-18/discussions/82
