### ISSUE TITLE
Menu button id inconsistent when server rendered with Next.js

### ISSUE THREAD

**Issue by joshmanders** [tailwindlabs/headlessui#24]
Great work so far. I've noticed a weird warning happening when I use the dropdown menu in Next.js, I get 
```
Warning: Prop `id` did not match. Server: "headlessui-menu-button-2" Client: "headlessui-menu-button-1"
```

And if I refresh the page, it just keeps going up more and more. 

```
Warning: Prop `id` did not match. Server: "headlessui-menu-button-4" Client: "headlessui-menu-button-1"
```

**Comment by RobinMalfait** [comment]
Hey, thank you for the bug report! This is already fixed and will be available the next version we release! 🙏

**Comment by joshmanders** [comment]
Excellent! Thanks @RobinMalfait!

**Comment by lailo** [comment]
I'm getting this error again with the newest version `1.4.0`.  Did something change in this version which could have reintroduced this bug? @RobinMalfait
