### ISSUE TITLE
Type error on Switch

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [tailwindlabs/headlessui#240]
Hello 👋
I'm using the @headlessui/react in 0.3.1 package with typescript 4.1.5
And when i'm trying to use the application with "tsc --noEmit" i have the following error: 

```js
Error: node_modules/@headlessui/react/dist/components/switch/switch.d.ts(16,32): error TS1335: 'unique symbol' types are not allowed here.
```

This is the output in my node_modules ...
```ts
export declare namespace Switch {
    var Group: <TTag extends React.ElementType<any> = React.ExoticComponent<{
        children?: React.ReactNode;
    }>>(props: Props<TTag, {}, unique symbol>) => JSX.Element;
    var Label: <TTag extends React.ElementType<any> = "label">(props: Props<TTag, LabelRenderPropArg, LabelPropsWeControl>) => React.ReactElement<any, string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)> | null;
}
```

i can help you if you have any questions
Have a nice day :) 👋

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Is this only happening while using `tsc --noEmit` or in all use cases?
Can you create a reproduction repository that showcases this issue?

**Comment by targos** [comment]
Hello, here's a reproduction: https://github.com/targos/headlessui-switch-bug

**Comment by RobinMalfait** [comment]
@targos thanks for the repro! I'll take a look now!

**Comment by Sebastien-Ahkrin** [comment]
Thanks @targos :)

**Comment by RobinMalfait** [comment]
This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.

**Comment by Sebastien-Ahkrin** [comment]
i will try that thanks :)

**Comment by Toub** [comment]
Thanks @RobinMalfait

Do you consider to release a patch to have a clean fix before the next version is released?

Or should we install an older version of headlessui ?
