### ISSUE TITLE
Combobox: Input of full-width characters is confirmed after the first character on initial input

### ISSUE THREAD

**Issue by mrsekut** [tailwindlabs/headlessui#2409]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/react-ts-kilsd9?file=App.tsx

**Describe your issue**

I'm encountering an issue with the Headless UI Combobox when entering full-width characters using an IME (Input Method Editor). On the initial input, the full-width character is confirmed after entering just the first character. However, after the first occurrence, the component works as expected.

For example, when I try to input the full-width character "わ" by typing "wa", it gets confirmed as soon as I type "ｗ". This issue only happens once after mounting, and subsequent inputs work correctly.

I've included the code for the Combobox.Input in the reproduction URL. 
![6ec377f648d865a0347d3a77958c2353](https://user-images.githubusercontent.com/24796587/229448221-d8adc4f9-398d-498e-b538-1e66544e6171.gif)

**Comment by thecrypticace** [comment]
@RobinMalfait Did a bit of checking around. This is "Japanese - Romaji".　It's reproducible in Chrome and Firefox. Safari does not seem to be affected by this for some reason.

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this one. I've merged a fix for this in #2426 which will be available in the next release. ✨ 

Until then, you can try it using our insiders build:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
