### ISSUE TITLE
Autosizing textarea

### ISSUE THREAD

**Issue by medihack** [tailwindlabs/headlessui#241]
Hi there. Thanks for this cool project! I guess it will have a bright future.

By the way, a little feature request ... an autosizing text area. A good implementation can be found for example [at Ant Design](https://ant.design/components/input/).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are focusing on accessible components for our needs on tailwindui.com first. I'll put this suggestion on my personal backlog, thanks!
