### ISSUE TITLE
Opening a Dialog makes scrollbars of an overflow element appear on Chrome

### ISSUE THREAD

**Issue by shi-rudo** [tailwindlabs/headlessui#2410]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Chrome 111.0.5563.110

**Reproduction URL**

minimal example [Sandbox](https://codesandbox.io/p/sandbox/react-vite-tailwind-yvsys0?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A21%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A21%7D%5D)

**Describe your issue**

When a dialog / modal is opened the scrollbars of the overflow elements appear. I can only reproduce this behavior in Chrome, the behavior does not appear in Safari. 

![Screenshot](https://i.imgur.com/vN6c5hV.jpg)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is a side effect of the `inert` attribute that gets added. If you don't want this, then you can explicitly add the following css:
```css
[inert] ::-webkit-scrollbar {
  display: none;
}
```

Here is an updated CodeSandbox link with this change applied: https://codesandbox.io/p/sandbox/react-vite-tailwind-yvsys0?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A37%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A37%2C%22startLineNumber%22%3A15%7D%5D

**Comment by shi-rudo** [comment]
Phenomenal! Thanks for the quick help!
