### ISSUE TITLE
Passing additional listeners to DOM events of Listbox

### ISSUE THREAD

**Issue by nick-flood** [tailwindlabs/headlessui#242]
I have a use case where I need to know if the Listbox itself is focused, something like

```typescript
<Listbox>
  <Listbox.Label>{listboxFocus ? 'focused': 'not focused'}</Listbox.Label>
</Listbox>
```

The render props of `Listbox` don't expose these values, nor can I pass an `onFocus` handler to `Listbox`.

Is there plans to add this functionality, or is there an alternative way to do this I'm missing?

Thanks :)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

Can you tell me a bit more about your use case?
If your question is literally to know when the `Listbox.Button` is focused, then you can put an `onFocus` on the `Listbox.Button`. If your question is to know wether the Listbox is "open" and the `Listbox.Options` are focused, then you should be able to destructure the `open` prop from the `Listbox`:

```js
function Example() {
  return (
    <Listbox>
      {({ open }) => (
        <>
          <span>Listbox is currently {open ? 'open' : 'closed'}</span>
          <Listbox.Button />
          <Listbox.Options />
        </>
      )}
    </Listbox>
  )
}
```

**Comment by nick-flood** [comment]
Hey Robin, 

I was trying to listen to whether the component rendered by `Listbox` is focused, but have just realised by default it renders a `Fragment`. My specific use case was something like 

```TSX
<Listbox as={<Component />}>
</Listbox>
```

But now I realise I can just have `<Component />` as the root child of `<Listbox />`. Also, what you have pointed out is an alternative to what I was after that I think makes more sense.

Thankyou!
