### ISSUE TITLE
`Tab` closes Combobox

### ISSUE THREAD

**Issue by bolivier** [tailwindlabs/headlessui#2425]
**What package within Headless UI are you using?**

I'm using `@headlessui/react`

**What version of that package are you using?**

I'm using `v1.7.13`

**What browser are you using?**

I'm using Firefox

**Reproduction URL**

> **Note** 
> Will provide one if it's considered a bug.

**Describe your issue**

The combobox component assumes that `TAB` should close the combobox, but I don't see that in the a11y specs for combobox that I've read online  ([for example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/)).  

The reason this seems like a bug to me is that it removes the ability for a user to `Tab` to the next focusable element.

**Comment by Futureblur** [comment]
I tried replicating this on the headlessui homepage and it indeed closes the combobox. The problem is that pressing the tab key multiple times actually focuses the address bar on Safari, so not quite sure how that could be fixed.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

You are right that this isn't explicitly mentioned. A lot of the time when certain parts are not mentioned we look at the native OS like macOS or other libraries to see what the behaviour is there to try and make the web more consistent regardless of the library you are using. However, if you look at the example you linked it also has this behaviour where you can open it, press tab, and it goes to the next link and the combobox is closed again.

> The reason this seems like a bug to me is that it removes the ability for a user to Tab to the next focusable element.

This shouldn't be the case, it should close _and_ go to the next focusable item (or the previous one if you used shift+tab). Here is a little CodeSandbox that showcases this behaviour: https://codesandbox.io/s/dreamy-chihiro-wm9ebh?file=/src/App.js or if you want to open the preview itself directly: https://wm9ebh.csb.app/

If you are not seeing this behaviour in your own application(s) then I think something else is going on but not 100% sure what yet. Could you open a new issue with a minimal reproduction repo attached? Would love to get to the bottom of this!
