### ISSUE TITLE
Transition: Unable to set Transition div to opacity-75 after animation

### ISSUE THREAD

**Issue by josh-hobnob** [tailwindlabs/headlessui#243]
@headlessui/react: 0.3.0

I am using Transition to animate in an overlay behind a Modal. The goal was to have a 75% opacity background behind the modal which could be clicked on to dismiss, pretty standard practice.

The issue is that I want the div to stay at opacity-75. Currently it does the animation then once finished sets the opacity to default i.e. 100%. I tried putting opacity-75 on the class itself but this didn't help. 

I am using the following code, but for the same reproduction you can open up this https://codesandbox.io/s/headlessuireact-menu-example-b6xje?file=/src/App.js and adjust the opacity to 75% (and maybe make the transition longer to see the effect.
```
<Transition
  show={isOpen}
  enter="transition-opacity duration-1000"
  enterFrom="opacity-0"
  enterTo="opacity-75"
  leave="transition-opacity duration-1000"
  leaveFrom="opacity-75"
  leaveTo="opacity-0"
  className="fixed inset-0 bg-gray-900 flex flex-row items-center justify-center z-50" />
```

I have a hack which is to put a 75% opacity div inside this one and use opacity-100 on the transition instead, however this isn't exactly desired. More importantly, I just don't think the current behavior feels correct so I spent quite a bit of time debugging.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The transition component is mainly used for transitioning itself, meaning once the transition is done no classes (from the enter, leave props) are applied. To implement the behaviour you want, you can do something like this:

```jsx
<Transition
  show={isOpen}
  enter="transition-opacity duration-1000"
  enterFrom="opacity-0"
  enterTo="opacity-100"
  leave="transition-opacity duration-1000"
  leaveFrom="opacity-100"
  leaveTo="opacity-0"
  className="fixed inset-0"
>
  <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
</Transition>
```

Essentially what I did here, is transition to 100%, but the contents contains a div that has an opacity of 75%. Hope this helps you!
