### ISSUE TITLE
Unable to subscribe to the changes of the Popover/Menu open state

### ISSUE THREAD

**Issue by Saul-BT** [tailwindlabs/headlessui#2436]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2435

<div type='discussions-op-text'>

<sup>Originally posted by **Saul-BT** April 14, 2023</sup>
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

^1.7.12

**What browser are you using?**

Firefox & Chrome

**Reproduction URL**
https://codesandbox.io/s/use-case-3ly5ed?file=/src/App.vue
Note: I the example above I cannot change the z-order of the parent element to prevent overlapping.

**Describe your feat request**

Add an event or some thing to be able to handle this weird situations.

My desired API for Popover/Menu (and maybe other components) look like this:

```html
<Popover v-slot="{ open }" @openChange="emitToParentToBeAbleToChangeTheZIndex">
    <PopoverButton>
          ...
    </PopoverButton>
    <PopoverPanel>
          ...
    </PopoverPanel>
</Popover>
```
</div>

**Comment by stevendprinsloo** [comment]
I really feel events need to be added to this component and other components. There are a lot times this functionality would be super useful, not sure why you are still deliberating?

But thanks for the "Dummy" component approach, works well.
