### ISSUE TITLE
Combobox active index styling not resetting correctly

### ISSUE THREAD

**Issue by JamesNuttall** [tailwindlabs/headlessui#2447]
Package Version: @headlessui/vue v1.7.13
Reproduction URL: https://stackblitz.com/edit/combobox-issue?file=src/App.vue

**Issue**

As can be seen in the video below, when the results are changed the active styling isn't being updated and set onto the correct index, its staying on index 1 despite the activeIndex being 0.

https://user-images.githubusercontent.com/22011451/233621169-81d9beca-6c59-4033-9661-41e9374d9d28.mov

In the next clip you can see (at about 10s) that because of the above when I press the down arrow key nothing seems to happen as the styling is incorrectly assigned to the option at index 1 instead of being reset back to index 0, therefor it takes two arrow key press to get any feedback.

https://user-images.githubusercontent.com/22011451/233621586-ea88b6d3-f070-46d6-8f85-b069270d7f62.mov

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #2463, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/vue@insiders`.
