### ISSUE TITLE
Cannot Toggle Popover.Button when custom component is used

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/headlessui#2450]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.14

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/nextjs-ht5rw4?file=pages%2Findex.js

**Describe your issue**

When using default `<Popover.Button>` it toggles on each click. But when using a custom component using `<Popover.Button as={Button}>`, the toggle only opens but not closing. Isn't it expected to behave like a toggle?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Make sure to forward all the props and the `ref` to the `Button` component. Here is an updated StackBlitz with the necessary change: https://stackblitz.com/edit/nextjs-qtcb4j?file=pages/myButton.js

```js
import { forwardRef } from 'react';

const Button = forwardRef(function Button({ children, ...rest }, ref) {
  return (
    <button ref={ref} className="bg-gray-200" {...rest}>
      {children}
    </button>
  );
});

export default Button;
```

**Comment by surjithctly** [comment]
Thank you. I checked the docs many times but couldn't find this. or did I overlooked it?

**Comment by milos5593** [comment]
> Hey, thank you for this bug report! 🙏
> 
> Make sure to forward all the props and the `ref` to the `Button` component. Here is an updated StackBlitz with the necessary change: https://stackblitz.com/edit/nextjs-qtcb4j?file=pages/myButton.js
> 
> ```js
> import { forwardRef } from 'react';
> 
> const Button = forwardRef(function Button({ children, ...rest }, ref) {
>   return (
>     <button ref={ref} className="bg-gray-200" {...rest}>
>       {children}
>     </button>
>   );
> });
> 
> export default Button;
> ```

How to achieve the same in Vue, I am having the same issue?
