### ISSUE TITLE
handle-ios-locking.ts does not restore the scrolling position correctly

### ISSUE THREAD

**Issue by judewang** [tailwindlabs/headlessui#2453]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2388

<div type='discussions-op-text'>

<sup>Originally posted by **chrisjansky** March 21, 2023</sup>
Hi, I have an issue with Dialog on iOS screens.

For some reason <body> gets negative margin-top on Dialog open, making the page jump erratically. To make matters worse, the page doesn‘t return to the same position when Dialog is closed, resulting in terrible UX. Please see video.

Anyone experienced the same problem? 🙏 

https://user-images.githubusercontent.com/5342612/226640450-f8d3622a-3308-4251-a010-12e48bd93afa.mov

</div>

Here's the source code about this issue.

[https://github.com/tailwindlabs/headlessui/blob/0276231c31/packages/%40headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts](https://github.com/tailwindlabs/headlessui/blob/0276231c31/packages/%40headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts)

I'm not sure is this a feature for specific iOS version or not, but in my situation, while we store the `window.pageYOffset` before we open the Dialog, even after executing `window.scrollTo(0,0)`, the `window.pageYOffset` still remained the value which we stored. After closing the Dialog, the `window.scrollTo(0, window.pageYOffset + scrollPosition)` supposed to bring us to the scrolling position that we stored before, but we ended up a scrolling position which has been doubled.

**Comment by thecrypticace** [comment]
Hey! So this feature isn't for a specific iOS version. They all exhibit the same behavior — or have in our testing at least. It's possible that something has recently changed but I'll need to do some testing to verify. I'm going to close this in favor of the discussion for now — I've left a comment there asking for a few things to see if we can help track down what's causing this for you.
