### ISSUE TITLE
Typescript error on <Transition /> Element

### ISSUE THREAD

**Issue by sgwrangler** [tailwindlabs/headlessui#2468]
**What package within Headless UI are you using?**

@headlessui/react v1.7.14
tailwindcss v3.3.2
typescript v5.0.4 (same bug on 4.9.5

**What browser are you using?**
Chrome

**Description:**

When using the transiton element from headless UI with popovers, as provided and copied from the tailwindUI library, I get the following Typescript error: `Expression produces a union type that is too complex to represent.ts(2590)`

I get the error on each of the three `<Transition>` elements down below. The error has nothing to do with children I suppose, as the I get the same error when I provide something like this: 

`<Transition> Foo </Transition>`

**Code:** 

            `<Popover.Group as='nav' className='flex space-x-10'>
              <Popover className='relative'>
                {({ open }) => (
                  <>
                    <Popover.Button
                      className={classNames(
                        open ? 'text-indigo-600' : 'text-indigo-500',
                        'group inline-flex items-center rounded-md text-base font-medium hover:text-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2',
                      )}
                    >
                      <span>#</span>
                      <ChevronDownIcon
                        className={classNames(
                          open ? 'text-indigo-600' : 'text-indigo-500',
                          'ml-2 h-5 w-5 group-hover:text-indigo-500',
                        )}
                        aria-hidden='true'
                      />
                    </Popover.Button>

                    <Transition
                      as={Fragment}
                      enter='transition ease-out duration-200'
                      enterFrom='opacity-0 translate-y-1'
                      enterTo='opacity-100 translate-y-0'
                      leave='transition ease-in duration-150'
                      leaveFrom='opacity-100 translate-y-0'
                      leaveTo='opacity-0 translate-y-1'
                    >
                      <Popover.Panel className='absolute z-10 -ml-4 mt-3 w-screen max-w-md transform lg:max-w-3xl'>
                        <div className='overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5'>
                          <div className='relative grid gap-6 bg-white px-5 pt-6 sm:gap-8 lg:pt-8 lg:px-8 lg:grid-cols-2'>
                            {solutions.map((item) => (
                              <Link
                                key={item.name}
                                href={item.href}
                                className='-m-3 flex items-start rounded-lg p-3 hover:bg-gray-50'
                              >
                                <div className='flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-md bg-indigo-500 text-white sm:h-12 sm:w-12'>
                                  {item.icon}
                                </div>
                                <div className='ml-4'>
                                  <p className='text-base font-medium text-gray-900'>
                                    {item.name}
                                    {item.comingsoon == true && (
                                      <span className='ml-3 inline-flex items-center rounded-full bg-indigo-100 px-3 py-0.5 text-xs font-medium leading-5 text-indigo-800'>
                                        Coming soon
                                      </span>
                                    )}
                                  </p>

                                  <p className='mt-1 text-sm text-gray-500'>{item.description}</p>
                                </div>
                              </Link>
                            ))}
                          </div>
                          <div className='bg-gray-50 p-5 sm:p-8'>
                            <Link
                              href='#'
                              className='-m-3 flow-root rounded-md p-3 hover:bg-gray-100'
                            >
                              <div className='flex items-center'>
                                <div className='text-base font-medium text-gray-900'>
                                  <span>Rekentool</span>
                                </div>
                                <span className='ml-3 inline-flex items-center rounded-full bg-indigo-100 px-3 py-0.5 text-xs font-medium leading-5 text-indigo-800'>
                                  New
                                </span>
                              </div>
                              <p className='mt-1 text-sm text-gray-500'>
                                Bereken eenvoudig wat zonnepanelen voor jou kunnen opleveren
                              </p>
                            </Link>
                          </div>
                        </div>
                      </Popover.Panel>
                    </Transition>
                  </>
                )}
              </Popover>

              <Popover className='relative'>
                {({ open }) => (
                  <>
                    <Popover.Button
                      className={classNames(
                        open ? 'text-indigo-600' : 'text-indigo-500',
                        'group inline-flex items-center rounded-md text-base font-medium hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2',
                      )}
                    >
                      <span className='text-base font-medium text-indigo-500 hover:text-indigo-600'>
                        More
                      </span>
                      <ChevronDownIcon
                        className={classNames(
                          open ? 'text-indigo-600' : 'text-indigo-500',
                          'ml-2 h-5 w-5 group-hover:text-indigo-500',
                        )}
                        aria-hidden='true'
                      />
                    </Popover.Button>

                    <Transition
                      as={Fragment}
                      enter='transition ease-out duration-200'
                      enterFrom='opacity-0 translate-y-1'
                      enterTo='opacity-100 translate-y-0'
                      leave='transition ease-in duration-150'
                      leaveFrom='opacity-100 translate-y-0'
                      leaveTo='opacity-0 translate-y-1'
                    >
                      <Popover.Panel className='absolute left-1/2 z-10 mt-3 w-screen max-w-xs -translate-x-1/2 transform px-2 sm:px-0'>
                        <div className='overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5'>
                          <div className='relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8'>
                            {resources.map((item) => (
                              <Link
                                key={item.name}
                                href={item.href}
                                className='-m-3 block rounded-md p-3 hover:bg-gray-50'
                              >
                                <p className='text-base font-medium text-gray-900'>
                                  {item.name}
                                  {item.comingsoon == true && (
                                    <span className='ml-3 inline-flex items-center rounded-full bg-indigo-100 px-3 py-0.5 text-xs font-medium leading-5 text-indigo-800'>
                                      Coming soon
                                    </span>
                                  )}
                                </p>
                                <p className='mt-1 text-sm text-gray-500'>{item.description}</p>
                              </Link>
                            ))}
                          </div>
                        </div>
                      </Popover.Panel>
                    </Transition>
                  </>
                )}
              </Popover>
            </Popover.Group>`
          
**Please take a look at this when you find the time  @thecrypticace @RobinMalfait**

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Can you attach a minimal reproduction repo that showcases this issue? This is likely an error in your setup / configuration of tsconfig.json so the given code snippet is not enough to debug this.

Once you provided a minimal reproduction repo I'm more than happy to help you out and get to the bottom of this!
