### ISSUE TITLE
type error when using `id` after patch upgrade (1.7.8 -> 1.7.14)

### ISSUE THREAD

**Issue by szamanr** [tailwindlabs/headlessui#2473]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

N/A

**Reproduction URL**

```
<Combobox
  key={defaultItems?.map((u) => u.id).join(",")}
  by="id"
  multiple
  name={name}
  onChange={handleChange}
  value={selectedItems}
>
  {({ open }) => (
    <>
      {isFunction(children) ? children({ ...comboBag, open }) : children}
    </>
  )}
</Combobox>
```

types:

```
type Item = {
  disabled?: boolean;
  id: string;
  label?: string;
  name: string;
};

type Props = {
  defaultItems?: Item[];
}
```

**Describe your issue**

this fails type checks in v1.7.14, but not in v1.7.8. it's a patch upgrade so breaking API changes should not happen.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
