### ISSUE TITLE
provide a reproduction starting template for issues

### ISSUE THREAD

**Issue by szamanr** [tailwindlabs/headlessui#2474]
you have a hard requirement that all issues include a reproduction URL, and if an issue doesn't included it gets closed. for most people this creates an obvious barrier, as the cost of figuring out how to set up a working example is too high.

please include a link to a starter codesandbox project inside of your issue template. this should help people create reproductions.

**Comment by RobinMalfait** [comment]
Hey, thanks so much for this suggestion! 🙏

I've added some CodeSandbox links in the issue template such that you have a starting point for both a React and a Vue version.
