### ISSUE TITLE
Listbox: cannot tab into elements inside dropdown

### ISSUE THREAD

**Issue by szamanr** [tailwindlabs/headlessui#2475]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Firefox

**Reproduction URL**

https://codesandbox.io/s/frosty-snow-5bpuu9?file=/src/App.js

to reproduce:

- click on the button to open lisbtbox options
- press TAB

expected result:
- search box is focused

actual result:
- the container element (`Listbox.Options`) is still focused

**Describe your issue**

i have a listbox, where inside of the dropdown i render a search box and the list of options. i want to be able to tab into the search box and toggle between the search and options.

i have added a `tabIndex` property to the relevant elements, and i also added a `onKeyDown` handler to suppress default TAB key behaviour. this allows me to tab between search and list once in focus.

however, i am unable to get the search box in focus in the first place. when the dropdown is open, pressing TAB doesn't do anything.

related issue: #2476

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The Listbox component is created as an alternative to the native `select` and `option` html tags but with the ability to completely style them. Adding an `input` field as on of the children would make it an invalid (a11y) tree, similar to how adding an `input` as a child of `<select>` is also not allowed. 

If you do want an `input` of some sorts, then I would recommend you to use the [`Combobox`](https://headlessui.com/react/combobox) component which is a combination of a `Listbox` and an `input` field.

Hope this helps!

**Comment by szamanr** [comment]
> Hey, thank you for this bug report! pray
> 
> The Listbox component is created as an alternative to the native `select` and `option` html tags but with the ability to completely style them. Adding an `input` field as on of the children would make it an invalid (a11y) tree, similar to how adding an `input` as a child of `<select>` is also not allowed.
> 
> If you do want an `input` of some sorts, then I would recommend you to use the [`Combobox`](https://headlessui.com/react/combobox) component which is a combination of a `Listbox` and an `input` field.
> 
> Hope this helps!

@RobinMalfait Combobox servers a different use case. we want a separate value and search fields. here's one use case:

a user has 0 or 1 managers. you should be able to click on the value to bring up the dropdown with possible options. you should be able to search for a user within these options. only when you actually select, should the value change.

![select + search](https://user-images.githubusercontent.com/2622838/236466434-4f9d7b3b-a172-4aed-9795-5edef19b91f6.png)

i don't think this can be achieved using Combobox, can it?

furthermore, AFAIK there are is no actual `<select>` element being rendered, so not sure what invalid a11y syntax has to do with it. the way i see it, there is some custom logic in headless UI that prevents the normal TAB behaviour, and i believe this should be fixed on your side.

**Comment by szamanr** [comment]
for posterity, my current workaround is maintaining a ref to the first element i want to focus (search box in my case), and manually focusing it. like this:

```
const handleKeyDown = (e: React.KeyboardEvent<HTMLUListElement>) => {
  // workaround for https://github.com/tailwindlabs/headlessui/issues/2475
  if (e.key === "Tab") {
    searchRef?.focus();
  }
};

...

<Listbox.Options ... onKeyDown={handleKeyDown> 
  ...
</Listbox.Options
```

i still believe this is a bug in headless UI which should be fixed, though.
