### ISSUE TITLE
Listbox: autoFocus doesn't work inside dropdown

### ISSUE THREAD

**Issue by szamanr** [tailwindlabs/headlessui#2476]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Firefox

**Reproduction URL**

https://codesandbox.io/s/frosty-snow-5bpuu9?file=/src/App.js

to reproduce:

- click on the button to open lisbtbox options

expected result:
- search box is focused

actual result:
- the container element (`Listbox.Options`) is focused

**Describe your issue**

i have a listbox, where inside of the dropdown i render a search box and the list of options. i want the search to be in focus when the dropdown is open.

i have added the `autoFocus` property on my input element. however, it's not getting focus. when the dropdown is open, it keeps the container in focus.

related issue: #2475

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The Listbox component is created as an alternative to the native `select` and `option` html tags but with the ability to completely style them. Adding an `input` field as on of the children would make it an invalid (a11y) tree. 

If you do want an `input` of some sorts, then I would recommend you to use the [`Combobox`](https://headlessui.com/react/combobox) component which is a combination of a `Listbox` and an `input` field.

Hope this helps!

**Comment by szamanr** [comment]
thread continued in the related issue here: https://github.com/tailwindlabs/headlessui/issues/2475#issuecomment-1536242897

**Comment by Gamote** [comment]
@szamanr The way we dealt with is to create a component for the input and use the input's ref to focus whenever the refs is updated. But that wasn't enough. The `ref` had to be created in the render method of `Menu.Item`. This our code:
```tsx

const InputWithAutoFocus: FC<{
  placeholder?: string;
  value: string;
  onChange: ChangeEventHandler<HTMLInputElement>;
}> = ({ placeholder, value, onChange }) => {
  const inputId = useId();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(
    () => {
      if (inputRef.current) {
        inputRef.current.focus();
      }
    },
    // It says that inputRef.current is not a dependency, but it is
    // if we remove it, the input will not be focused
    [inputRef.current],
  );

  return (
    <input
      type="text"
      id={inputId}
      value={value}
      ref={inputRef}
      onChange={onChange}
      placeholder={placeholder}
    />
  );
};

/**
 * We have created this component, so we can focus an input when used inside a
 * {@link Menu.Item} whenever the menu is opened.
 *
 * If we put the input directly inside the `Menu.Item`, it will not be focused
 * even though we have set it through the ref. What did the trick was to create
 * a new component that can be returned from the {@link Menu.Item}'s render function.
 *
 * @see https://github.com/tailwindlabs/headlessui/issues/2476#issuecomment-1536059590
 */
const SearchBarMenuItem: FC<{
  placeholder?: string;
  value: string;
  onChange: ChangeEventHandler<HTMLInputElement>;
}> = ({ placeholder, value, onChange }) => (
  <Menu.Item as={'div'} disabled>
    {() => (
      <InputWithAutoFocus
        value={value}
        onChange={onChange}
        placeholder={placeholder}
      />
    )}
  </Menu.Item>
);
```

Now `SearchBarMenuItem` can be used inside `Menu.Items` and it will be auto focused. Notes:
- I recommend the `disabled` flag on `Menu.Item` so the input menu item is skipped on arrow navigations and to avoid closing the menu when the consumer is clicking in the input.
- I have tried `autoFocus` on the `input` and it didn't work.

I am pretty sure is not the best way to do it, but for now it does the trick. @RobinMalfait, maybe you have some recommendations?
