### ISSUE TITLE
Switch not submitting form with type="submit"

### ISSUE THREAD

**Issue by michaelgmcd** [tailwindlabs/headlessui#2482]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Chrome

**Reproduction URL**
Added an example: packages/playground-react/pages/switch/switch-form-submit.tsx
https://github.com/michaelgmcd/headlessui

**Describe your issue**

I'm essentially re-opening https://github.com/tailwindlabs/headlessui/issues/2341 with an example. It took me waaayy to long to realize that `<Switch />` is calling `event.preventDefault()`. This should either be clearly documented in the docs or I'm happy to open a PR to fix. Ideally for a switch of type submit, the form would be submitted.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #2625, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
