### ISSUE TITLE
Menu (Dropdown) doesn't close when clicking an iframe element

### ISSUE THREAD

**Issue by ukaj808** [tailwindlabs/headlessui#2484]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2462

<div type='discussions-op-text'>

<sup>Originally posted by **ukaj808** April 28, 2023</sup>
Hey!

I've got an iframe on my page and when I click it to interact with it, the menu dropdown doesnt close. If I click anywhere outside the iframe the dropdown closes as expected. Is this expected behavior?

I created a quick vue3 project to recreate the "_issue_": https://github.com/ukaj808/headlessui-iframe-issue

Thanks, 
Fiz</div>

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this one — it's definitely not the expected behavior. I've merged in #2485 that fixes this. The fix will be available in our next tagged release. You can test it via our insiders build which will be ready shortly (in a few minutes):

```
npm install @headlessui/vue@insiders
```
