### ISSUE TITLE
`scroll-behavior: smooth` causes auto background scrolling on smaller screens

### ISSUE THREAD

**Issue by SincerelyFaust** [tailwindlabs/headlessui#2494]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2472

<div type='discussions-op-text'>

<sup>Originally posted by **SincerelyFaust** May  2, 2023</sup>
Basically when opening the dialog on bigger screens it works as usual but on smaller screens it opens the dialog as it should but in the background you can see the rest of the website scrolling to the top.</div>

In my case, removing `scroll-behavior: smooth` from `html {}` in my .css file fixed this but that's not really ideal because I'd like to keep the scroll behavior.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by SincerelyFaust** [comment]
The reproduction would be using any of the examples on your page.
