### ISSUE TITLE
ReferenceError: React is not defined using Disclosure with `as='div'` prop

### ISSUE THREAD

**Issue by fernandordev** [tailwindlabs/headlessui#2498]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1788

<div type='discussions-op-text'>

<sup>Originally posted by **fernandordev** August 25, 2022</sup>
I'm using  Disclosure with `as='div'` prop:

```
function QuestionsComponent({ title, answer }) {
  return (
    <Disclosure as={'div'} className="group rounded-lg bg-graySurface p-8 shadow-sm">
      {({ open }) => (
        <>
          <Disclosure.Button className="flex w-full items-center justify-between text-start">
            <h1 className="font-semibold  text-white">{title}</h1>

            <ChevronDownIcon
              className={`${
                open && '-rotate-180'
              } ml-1.5 h-5 w-5 flex-shrink-0 transition duration-300`}
            />
          </Disclosure.Button>
          <Transition
            show={open}
            enter="transition ease-out duration-200"
            enterFrom="transform opacity-0 scale-95"
            enterTo="transform opacity-100 scale-100"
            leave="transition ease-in duration-75"
            leaveFrom="transform opacity-100 scale-100"
            leaveTo="transform opacity-0 scale-95"
          >
            <Disclosure.Panel static>
              <p className="mt-6 text-gray-400">{answer}</p>
            </Disclosure.Panel>
          </Transition>
        </>
      )}
    </Disclosure>
  );
}
```

When building for pruduction, I'm gettings this on console log:

`ReferenceError: React is not defined`

If I remove the as='div' prop, things work correctly. 

Any reasons why this happens?

`Using @headlessui/react v1.6.6 with Vite`
</div>

**Comment by fernandordev** [comment]
The repo is private, but this old code is fine to share. The error occurs only on build in the /about page.

https://drive.google.com/file/d/1oVP-H065TiBbo_jYxLMNN-0x0JmErcKO/view?usp=share_link

**Comment by thecrypticace** [comment]
That helped! Thanks! I think this is/was an incompatibility with the ESM build of Headless UI v1.6 and Vite. If you upgrade to v1.7.x the error disappears. Is there a reason you're still on v1.6?

**Comment by fernandordev** [comment]
This is an old code, you know? I posted on the discussion page back in August 2022, but I didn't receive any answers. I was curious to know what happened. Thanks anyway!

**Comment by thecrypticace** [comment]
Ah I see. No worries. Thanks!
