### ISSUE TITLE
Double apply transition

### ISSUE THREAD

**Issue by maccman** [tailwindlabs/headlessui#25]
I'm seeing an issue that is causing a double toggle of the transition classes (even though `show` is continually `true`), ultimately resulting in a flash.

The issue looks like it's being caused by the `initial` variable changing, causing `useIsoMorphicEffect` to be re-triggered.

It goes like this:

1. First render of the component (initial = true)
2. Second render of the component (initial = false)

I'm curious why `initial` is a dependency on this useEffect?

```typescript
useIsoMorphicEffect(() => {
    const node = container.current

    if (!node) return

    // Skipping initial transition
    if (initial && !appear) return

   ....
  }, [
    id,
    isTransitioning,
    unregister,
    nesting,
    container,
    initial,
```

Let me know if that doesn't make sense and I'll put together an example.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'll look into it!
