### ISSUE TITLE
Scrollbars become visible on all elements when dialog open

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/headlessui#2500]
**What package within Headless UI are you using?**

@headlessui/react dialog component

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Chrome MacOS Version 113.0.5672.92 (arm64)

**Reproduction URL**

https://github.com/agusterodin/headless-ui-scrollbar-behind-dialog-visible-reproduction

**Describe your issue**

On latest version of Headless UI, scrollbars in all elements (excluding body itself) immediately become visible once a dialog is opened. This regression was introduced in version 1.7.12. Version 1.7.11 does not have this issue.

Current behavior (present in @headlessui/react 1.7.12+)

https://github.com/tailwindlabs/headlessui/assets/10248395/e1bc63e2-fdb3-4f2b-97ce-a7c839edba5c

Desired behavior (don't make irrelevant scrollbars visible when dialog opened)

https://github.com/tailwindlabs/headlessui/assets/10248395/e3adbaaa-fbe6-4b30-beff-7b18765467b9

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is a side effect of the `inert` attribute that we apply. You can get rid of it by applying the following CSS:

```css
[inert] ::-webkit-scrollbar {
  visibility: hidden;
}
```

We will also be doing some research to see if we can enable this by default in the `@base` layer of Tailwind CSS if you are using Tailwind CSS. If we can't do it for whatever reason, then we will document this behaviour.

Either way, I hope this helps!

**Comment by agusterodin** [comment]
Thanks for the quick response!

https://github.com/tailwindlabs/headlessui/assets/10248395/c6f22bf9-d9a8-4bf6-9786-7de107d3831f

One thing about the above CSS solution is that if you have overlay scrollbars (on MacOS), the layout will shift when visibility gets set to hidden (notice layout behind dialog shifting in second part of attached video). Alternatively, if you have scrollbars set to "always" in MacOS settings, the layout doesn't shift. Not sure how to smooth out this behavior.

My first intuition is to use [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) but I couldn't seem to get it to help.
