### ISSUE TITLE
Space character prevented on key down when rendering a form inside a Dialog inside a Menu

### ISSUE THREAD

**Issue by Aebrathia** [tailwindlabs/headlessui#2504]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

`"@headlessui/react": "^1.7.14"`

**What browser are you using?**

Bug happens in Chrome, Firefox and Safari and most likely all browsers.

**Reproduction URL**

See `src/App.tsx` in https://github.com/Aebrathia/headlessui-form-in-dialog-in-menu

**Describe your issue**

When I open the dropdown (Headless UI `<Menu>` component)
And I click "Open dialog" (Headless UI `<Dialog>` component)
And I type "I love spaces" in the input
Then I see "Ilovespaces"
However I should see "I love spaces"

I found a workaround using `onKeyDown={(event) => event.stopPropagation()}` either on the input or the Dialog itself. It is not ideal since I work with a Server Driven UI and it may lead to unexpected problems later.

I think the issue is related to the fact that React Portal propagates events and the Menu component likely calls `event.preventDefault()` on space characters for keyboard navigation.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The trick is to render the `Dialog` as a sibling and only trigger the action from the `Menu` itself. A good mental model for this is an `<a>` tag. If you click on an `<a>` tag then a new page opens, but it is not rendered _inside_ the `<a>` tag.

The updated code looks like this:
```js
function App() {
  const [open, setOpen] = useState(false);

  return (
    <div className="App">
      <Menu>
        <Menu.Button>Open dropdown</Menu.Button>
        <Menu.Items unmount={false}>
          <Menu.Item as="div">
            <button type="button" onClick={() => setOpen(true)}>
              Open dialog
            </button>
          </Menu.Item>
        </Menu.Items>
      </Menu>

      <Dialog
        open={open}
        onClose={() => setOpen(false)}
        // onKeyDown={(event) => event.stopPropagation()}
      >
        <Dialog.Panel>
          <form action="#">
            <label htmlFor="input">Broken input</label>
            <input
              id="input"
              name="input"
              type="text"
              placeholder="Type space characters"
              // onKeyDown={(event) => event.stopPropagation()}
            />
            <button type="submit">Submit</button>
          </form>
        </Dialog.Panel>
      </Dialog>
    </div>
  );
}
```

You can then even further simplify this:

```diff
  function App() {
    const [open, setOpen] = useState(false);

    return (
      <div className="App">
        <Menu>
          <Menu.Button>Open dropdown</Menu.Button>
          <Menu.Items>
-           <Menu.Item as="div">
-             <button type="button" onClick={() => setOpen(true)}>
-               Open dialog
-             </button>
-           </Menu.Item>
+           <Menu.Item as="button" onClick={() => setOpen(true)}>Open dialog</Menu.Item>
          </Menu.Items>
        </Menu>

        <Dialog
          open={open}
          onClose={() => setOpen(false)}
          // onKeyDown={(event) => event.stopPropagation()}
        >
          <Dialog.Panel>
            <form action="#">
              <label htmlFor="input">Broken input</label>
              <input
                id="input"
                name="input"
                type="text"
                placeholder="Type space characters"
                // onKeyDown={(event) => event.stopPropagation()}
              />
              <button type="submit">Submit</button>
            </form>
          </Dialog.Panel>
        </Dialog>
      </div>
    );
  }
```

Hope this helps!
