### ISSUE TITLE
Vue MenuItem router-link causes full reload

### ISSUE THREAD

**Issue by alainbelez** [tailwindlabs/headlessui#251]
```
<MenuItem>
  <router-link
    :to="{ name: 'Logout' }"
    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 cursor-pointer focus:outline-none"
    role="menuitem"
  >
    Sign out
  </router-link>
</MenuItem>
```

any idea why this router link causes a full reload?

**Comment by ryzr** [comment]
https://github.com/tailwindlabs/headlessui/issues/143#issuecomment-781010632

**Comment by Sauer-201** [comment]
This method replaces the URL and causes the page to do a full request (refresh) rather than relying on Vue.router. $router.go does not work t

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The router-link doesn't forward everything correctly, flipping things around like this might help you: https://codesandbox.io/s/headlessuivue-menu-example-forked-31t3b?file=/src/components/Menu.vue

**Comment by CalebKester** [comment]
@RobinMalfait Thanks for fix. It would be good to have this in the docs or try and contact the vue team to "fix" router-link if it really isn't working correctly as you say. Considering router-links are 1st class plugins for vue I'm guessing most of your vue user base will be running into this issue.

Do you take PRs for the documentation site? I'd be happy to help out as I'm really enjoying headlessui and tailwindui.

**Comment by ryanpwaldon** [comment]
Had the same issue, thanks for the fix @RobinMalfait!

**Comment by alejandrolsca** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> The router-link doesn't forward everything correctly, flipping things around like this might help you: https://codesandbox.io/s/headlessuivue-menu-example-forked-31t3b?file=/src/components/Menu.vue

Thank you for the fix @RobinMalfait

**Comment by RobinMalfait** [comment]
Hey! Doing a big GitHub clean-up this week so going to take note to document this, but if you stumble upon this issue, please look at the answer here: https://github.com/tailwindlabs/headlessui/issues/251#issuecomment-791671290
