### ISSUE TITLE
Transition element does not take into account reduced motion preferences

### ISSUE THREAD

**Issue by nathan-at-tes** [tailwindlabs/headlessui#2510]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.7.14

**What browser are you using?**

Chrome

**Describe your issue**

Apologies if I've put this in the wrong category, I wasn't sure if this was a bug or a feature request. Feel free to delete.

Essentially we have the following component:

```
function NavbarFlyoutMenu(props: NavbarFlyoutMenuFlyoutMenuProps) {
  return (
    <Popover className="relative">
      <Popover.Button className="flex items-center gap-x-2 rounded-lg p-2 font-bold text-greyscale-600 transition-all duration-200 ease-in hover:border-greyscale-0-hover hover:bg-greyscale-0-hover hover:text-greyscale-700 motion-reduce:transition-none">
        <span>{props.title}</span>
        <ArrowDownward className="fill-greyscale-700" />
      </Popover.Button>

      <Transition
        as={Fragment}
        enter="transition ease-out duration-200 motion-reduce:transition-none"
        enterFrom="opacity-0 translate-y-1 motion-reduce:transition-none"
        enterTo="opacity-100 translate-y-0 motion-reduce:transition-none"
        leave="transition ease-in duration-150 motion-reduce:transition-none"
        leaveFrom="opacity-100 translate-y-0 motion-reduce:transition-none"
        leaveTo="opacity-0 translate-y-1 motion-reduce:transition-none"
      >
        <Popover.Panel className="absolute z-10 mt-2 flex w-screen max-w-min">
          <div className="w-56 shrink rounded-lg bg-white py-2 shadow-material-shadow">
            {props.links.map((link) => (
              <Link
                key={link.title}
                href={link.href}
                className="block p-4 pr-0 text-greyscale-700 transition-all duration-200 ease-in hover:border-greyscale-0-hover hover:bg-greyscale-0-hover hover:text-greyscale-700 motion-reduce:transition-none"
              >
                {link.title}
              </Link>
            ))}
          </div>
        </Popover.Panel>
      </Transition>
    </Popover>
  );
}
```

Note, that I've manually added `motion-reduce:transition-none` to each prop in `Transition`. Would it perhaps be preferable for this to be handled within the `Transition` component itself, or even provide an option prop, i.e `checkForReducedMotion`.

Also, just to note, I'm not that I **need** `motion-reduce:transition-none` in **all** of these props, but I added it anyway. All I know is that I need it in some.

**Comment by thecrypticace** [comment]
Hey! So, I would say that this is something that is best handled on a case-by-case basis — like you've done with `motion-reduce:transition-none`. In many cases reduced motion doesn't necessarily mean **no transition** but that the transition itself should be different.

Reduced motion is generally about [vestibular motion disorders](https://www.a11yproject.com/posts/understanding-vestibular-disorders/) in which apparent movement can cause dizziness or disorientation. Many times transitions that involve scaling or translations will be turned into an opacity/fade animations. In other cases, like rotation, the transition may be omitted entirely.

So, all that to say, I think doing this automatically or even adding a prop is the wrong thing to do here. All we can do is say "the animation won't happen" but that may not be the best choice in all scenarios. Hope that helps! ✨

**Comment by nathan-at-tes** [comment]
That's perfect, thank you for the response! I wonder if it's worth mentioning `motion-reduce` in the docs. I know where I currently work this is an accessibility feature that is overlooked quite a bit
