### ISSUE TITLE
`w-11` used in codepen toggle demo

### ISSUE THREAD

**Issue by mike-seekwell** [tailwindlabs/headlessui#252]
First off, headlessui is awesome! 

`w-11` is used for the button here, which is a bit confusing to troubleshoot

https://codesandbox.io/s/headlessuivue-switch-example-8ycp6?file=/src/App.vue:69-106

**Comment by alexanderbluhm** [comment]
@mike-seekwell Why do you think this is confusing?
Anyway, this is just an example. In general, HeadlessUI provides no styles so you can style it in any way you want.
In this example, TailwindCSS 2.x is used.

**Comment by mike-seekwell** [comment]
Sorry, meant to close this. For some reason when I upgraded to Tailwind 2.x, `w-11` didn't show up the first time.
