### ISSUE TITLE
`appear={true}` stopped working in v1.7.15

### ISSUE THREAD

**Issue by felex0982** [tailwindlabs/headlessui#2526]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.15

**What browser are you using?**

Chrome

**Reproduction URL**

[reproduction of the issue - codesandbox with v1.7.15](https://codesandbox.io/s/winter-lake-1m4d5u)
[working example - codesandbox with v1.7.14](https://codesandbox.io/s/stoic-bhabha-n2f01l)

**Describe your issue**

I would expect `appear` to trigger the enter-animation every time the component is getting mounted. Since `v1.7.15` this doesn't seem to be the case anymore. I think the [issue is originated within this PR](https://github.com/tailwindlabs/headlessui/pull/2457#issuecomment-1556166983) and is already mentioned by [WangJM001](https://github.com/WangJM001).

**Comment by jlangner-hubble** [comment]
Bump.

**Comment by xsjcTony** [comment]
Any update on this?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #2646, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
