### ISSUE TITLE
Dialog - When using Radix Select inside of HeadlessUI Dialog, interacting with the Select closes the Dialog

### ISSUE THREAD

**Issue by dungle-scrubs** [tailwindlabs/headlessui#2533]
**What package within Headless UI are you using?**

@headlessui/react ^1.7.14

**What browser are you using?**

For example: Chrome, Safari, or N/A

Firefox - There is no issue
Chrome & Safari - The issue exists

**Describe your issue**

I'm having difficulty setting up a demo to view the issue, so I'll do my best to describe it. 

When I have a HeadlessUI Modal component with a Radix Select component inside, after interacting with the Select - Choosing an item - and then interacting with it a second time, that second interaction closes the Modal immediately upon clicking on the Select.

This seems to be happening only in Chrome and Safari, while in Firefox the problem doesn't exist. 

Cheers

**Comment by thecrypticace** [comment]
Hey! Thanks for reporting this one.

The ultimate problem was a timing issue. The elements in the Radix select were being removed from the DOM just before our handler was fired for outside clicks — but apparently only in certain situations. This tripped up our handler — which ended up considering the element to be an outside click. We'll now ignore "disconnected" elements for this case.

The fix will be available in our next tagged release. In the meantime, for testing, it'll also be available via our insiders build shortly:
```
npm install @headlessui/react@insiders
```

**Comment by dungle-scrubs** [comment]
Hey @thecrypticace thanks for that, looking forward to the fix.  In the meantime, I used an additional prop `onClose={() => !ignoreOutsideClick && setIsOpen(false)}` that disables closing the modal via an outside click, which also did the trick.

**Comment by veeti-k** [comment]
Hi! Upgraded to the `@headlessui/react@insiders`, it did remove the issue op was having, but another pretty similar issue persists

1. Open the select menu with items in it
2. Don't select an item, instead, close the menu by pressing the `Select.Trigger` component. Note: this is only possible if the `Select.Content`'s `position` prop is set to `"popper"`. Because in this case the opened select menu won't block the `Select.Trigger` component
3. Both the select menu and the headlessui modal closes

**Comment by everettglovier** [comment]
hello there! this is still an issue in v2. any recommendations for fixing?

**Comment by alexfarrill** [comment]
I am also experiencing this issue on 2.1.2

Posting a workaround in case it's helpful to anyone else:

```
const [dialogCloseable, setDialogCloseable] = useState(false);

const onClose = ... your onClose method

const headlessUiDialogOnClose = useCallback(() => {
    if (dialogCloseable) {
      onClose();
    } else {
      setDialogCloseable(true);
    }
  }, [dialogCloseable, onClose]);

const cancelSelectOnPointerDownOutside = useCallback(() => {
    setDialogCloseable(false);
  }, []);

<Dialog onClose={headlessUiDialogOnClose}>
...
</Dialog>

<Select>
   ...
   <SelectContent onPointerDownOutside={cancelSelectOnPointerDownOutside}>
</Select>
```
