### ISSUE TITLE
Dialog - The closable background of the first Dialog appears above the second Dialog

### ISSUE THREAD

**Issue by Eweeen** [tailwindlabs/headlessui#2534]
**What package within Headless UI are you using?**
@headlessui/vue^1.7.14

**What browser are you using?**
Chrome / Firefox

**Describe your issue**
When I open 2 Dialogs, the closable background of the first Dialog appears above the second Dialog. This means that when I click inside the content of the second Dialog, it closes the first Dialog.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
