### ISSUE TITLE
Dialog closes on first open even when clicked inside the panel

### ISSUE THREAD

**Issue by leolorenzoluis** [tailwindlabs/headlessui#2535]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.17.15

**What browser are you using?**

Chrome and Safari

**Describe your issue**

Dialog bug does not occur in 1.7.2 but with 1.7.15 it closes the dialog. When I put a breakpoint what's causing the modal closure... the useClickOutside is getting triggered the first time, so not sure if any succeeding updates between versions broke something.

**Comment by catdoglt** [comment]
Facing the same issue, had to downgrade the previous version. How did you find out that useClickOutside is getting triggered? Where is that hook, I cant even find it

**Comment by Howard86** [comment]
I've got the same issue and downgrading to 1.7.11 seems to fix

**Comment by leolorenzoluis** [comment]
Lol, it hasn’t even been 24 hours and yet you already closed the issue. Basically no chance to edit the issue as a first timer to report an issue. 😵‍💫

**Comment by adamwathan** [comment]
@leolorenzoluis Hey! Sorry for any surprises here, we try to be very clear in the issue template about what is required when opening an issue, and we explain that issues that don't provide all of the necessary information will be closed:

![image](https://github.com/tailwindlabs/headlessui/assets/4323180/3cd7ba3e-f9ce-474c-80ca-56cb8f5bfce9)

That's the only way we've found it's possible to effectively manage busy projects like this with a small team. More than happy to help but need to set the bar for detail at a certain level or things would get out of control here.

**Comment by lukasvice** [comment]
I also have this problem and have created a reproduction.

I have two examples: One that works and one where you can test the bug by opening the dialog for the first time and clicking inside, it closes.

I have found 3 things that need to be met to reproduce this behavior:
1. Version 1.7.15+
2. The Dialog must be opened with a JSX condition and not with the `open` prop
3. (And this is the weird part:) No `Dialog.Title`

Working: https://codesandbox.io/s/dialog-working-6wxrfc?file=/src/App.tsx
Bug: https://codesandbox.io/s/dialog-closing-on-first-click-vx4ftt

Could you reopen this issue?

**Comment by jorgebastida** [comment]
I have this same issue with `1.7.15`. Any click inside or outside the Dialog.Panel closes it. Adding a `Dialog.Title` fixes the issue.

In my case, contrary to @lukasvice 2nd condition, my Dialog is opened with the `open` prop.

Thank you very much for the hint @lukasvice about the `Dialog.Title` you saved my day!

**Comment by daiveedb** [comment]
I had the same issue with `1.7.17` . Any click inside or outside the `Dialog.Panel` closes it. Adding a `Dialog.Title `fixes the issue.

**Comment by IanPhilips** [comment]
Seeing this issue as well with any version above `1.7.11` on mobile safari.

**Comment by Emiliano-Bucci** [comment]
@adamwathan The issue is still present here!

**Comment by adamwathan** [comment]
@Emiliano-Bucci Yep it's been fixed just need to tag a release 👍 

https://github.com/tailwindlabs/headlessui/issues/2800#issuecomment-1761515495

**Comment by nick-tw** [comment]
Issue is still present.

**Comment by adamwathan** [comment]
Please open a new issue with a reproduction if you're still running into this problem 👍

**Comment by abhishekmulik** [comment]
I am on version v-1.7.18 and the issue is still present. Irrespective where you click inside or outside the Dialog.Panel it closes.

**Comment by jeremy0x** [comment]
As @leolorenzoluis pointed out, the `useClickOutside` function is triggered initially. Here’s a simple solution to this problem:

1. Prevent the dialog from closing when clicked outside. You can make the onClose event do nothing and instead:

```javascript
<Dialog open={isOpen} onClose={() => {}}>
```

> If you want the dialog to close when you click outside it, proceed with the next steps:

2. Add an overlay to your dialog using `<Dialog.Overlay />`.

3. Close the dialog when the overlay is clicked by adding an `onClick` event handler to the `Dialog.Overlay`:

```javascript
<Dialog.Overlay onClick={() => closeModal()} />
```

- Here’s how you can define the `closeModal` function:

```javascript
const closeModal = () => {
  setIsOpen(false);
};
```

Hope that helps!

**Comment by alexis-jonuro** [comment]
still present. I have to downgrade to  "1.7.11"

**Comment by halilhanbadem** [comment]
The problem still continues. I had to downgrade to solve the problem (1.7.11). To summarize the problem, click anywhere inside the panel and you will see that the panel is closed. This is not normal behavior. The normal thing is that it closes on any area clicked outside.

**Comment by abhishekmulik** [comment]
One of the issue could be the component that is opening the Dialog or it's parent is getting re-rendered this was the issue I faced and eventually my Dialog got closed whenever I clicked inside the Panel

**Comment by Aravinda93** [comment]
@lukasvice @leolorenzoluis 

I am facing similar issue when I access `DialogPanel2.vue` via `DialogPanel1.vue` then it for some reason automatically closes the `DialogPanel1.vue`.

Issue recreation: [Codesandbox](https://codesandbox.io/p/devbox/headlessui-dialog-multiple-modals-bugs-forked-o2ykb?file=%2Fpages%2Findex.js)
Issue posting: https://github.com/tailwindlabs/headlessui/discussions/3199

Can you please once have a look and provide some suggestions or workarounds?
