### ISSUE TITLE
Dialog - The closable background of the first Dialog appears above the second Dialog

### ISSUE THREAD

**Issue by Eweeen** [tailwindlabs/headlessui#2538]
**What package within Headless UI are you using?**
@headlessui/vue^1.7.14

**What browser are you using?**
Chrome / Firefox

**Reproduction URL**
[Code Sandbox](https://codesandbox.io/p/github/Eweeen/Vue-Vite-TS-Tailwind-HeadlessUI/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cliu11ks2000b2v6ojo8m94th%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cliu11ks2000d2v6o99gxpocv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cliu11ks2000b2v6ojo8m94th%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cliu11ks2000a2v6oku2fhfc7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cliu11ks2000b2v6ojo8m94th%2522%252C%2522activeTabId%2522%253A%2522cliu11ks2000a2v6oku2fhfc7%2522%257D%252C%2522cliu11ks2000d2v6o99gxpocv%2522%253A%257B%2522id%2522%253A%2522cliu11ks2000d2v6o99gxpocv%2522%252C%2522activeTabId%2522%253A%2522cliu11ndq00672v6oxmqnoq2g%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cliu11ndq00672v6oxmqnoq2g%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cliu11ols00bf2v6o16rya7rk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**
When I open 2 Dialogs, the closable background of the first Dialog appears above the second Dialog. This means that when I click inside the content of the second Dialog, it closes the first Dialog.

**Comment by thecrypticace** [comment]
Hey! So what's actually happening here is that, since the two dialogs are not nested, when you click inside the second dialog it considers this an "outside click" relative to the first dialog and thus closes it. You can see this behavior if you open both dialogs and then click the content area inside the second dialog but not the close button. The background elements are not stacked incorrectly (and you can verify this using dev tools and element selection).

Headless UI doesn't officially support having multiple dialogs open at the the same time when they are not nested.

In your case you can probably write your code like this instead which gives you the behavior you want:

```vue
<!-- First Modal -->
  <Modal :isOpen="isOpen" @close="closeModal">
    <!-- Second Modal -->
    <Modal :isOpen="isOpenSecond" @close="closeSecondModal">
      <div class="flex justify-center p-3">
        <button class="bg-gray-300 py-3 px-6 rounded-lg" @click="closeSecondModal">Close modal</button>
      </div>
    </Modal>

    <div class="flex justify-center gap-6 p-6">
      <button class="bg-gray-300 py-3 px-6 rounded-lg" @click="openSecondModal">Open modal</button>
      <button class="bg-gray-300 py-3 px-6 rounded-lg" @click="closeModal">Close modal</button>
    </div>
  </Modal>
```

If this isn't feasible then we'd suggest only showing one dialog at a time. Hope that helps!

**Comment by roneyrao** [comment]
Not true. It works as expected in version `1.6.5`, but breaks with version '1.7.15`. It's an inadvertent breaking change. Is it possible to restore this important capability? @thecrypticace

**Comment by Emiliano-Bucci** [comment]
@thecrypticace What @roneyrao is saying is true; how can we restore this capability? Is silly to have to nest dialogs which they're not supposed to be nested. If I have 2 global dialogs they should stay global.
