### ISSUE TITLE
Dynamic Transition classes do not change instantly

### ISSUE THREAD

**Issue by ycs77** [tailwindlabs/headlessui#2550]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/vite-headlessui-transition-with-floatingui-flip-update-placement-bug-hjujot?file=%2Fsrc%2FApp.jsx

Open the codesandbox above and scroll to the bottom and click the "Button" twice, then scroll back to the top and click the "Button" once, here the transition is expected from bottom to top, but actually is top to bottom.

**Describe your issue**

Here I use Headless UI Popover with Floating UI and enable `flip` to automatically change the placement when the window scrolls, so that the Popover will appear as much as possible.

```jsx
<Transition
  enter="transition duration-200 ease-out"
  enterFrom={`opacity-0 ${
    placement.startsWith("top") ? "translate-y-4" : "-translate-y-4"
  }`}
  enterTo="opacity-100 translate-y-0"
  leave="transition duration-150 ease-in"
  leaveFrom="opacity-100 translate-y-0"
  leaveTo={`opacity-0 ${
    placement.startsWith("top") ? "translate-y-4" : "-translate-y-4"
  }`}
>
```

My expected transition direction is: if the placement is top/top-start, it will transition from bottom to top when it is turned on; if it is bottom/bottom-start, it will transition from top to bottom when it is turned on. But when the switch is finished and the scroll window switches directions, the transition direction of opening again will not be the expected one.

Is there any way to achieve this while keeping the Headless UI usage?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

For this example I think you want to bypass JavaScript as much as possible. One thing you can do is purely rely on CSS. I noticed that you have a `data-placement` already, we can make use of this in our Transition component. This way the classes will always be the same and the `Transition` component doesn't have to re-render.

Let's break it down a little bit.

First, let's look at the `Popover` itself. If you add a `group` class to this one, then we can make use of the `group-data` variants (https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes):
```diff
- <Popover className="group popover" data-placement={placement}>
+ <Popover className="popover" data-placement={placement}>
```

Next, instead of relying on JS to switch the classes in the `Transition` component, you can rely on the CSS:
```diff
- enterFrom={`opacity-0 ${placement.startsWith("top") ? "translate-y-4" : "-translate-y-4"}`}
+ enterFrom={`opacity-0 group-data-[placement^=top]:translate-y-4 group-data-[placement^=bottom]:-translate-y-4`}
```

If we break these classes down, then we can analyze it in the following way:
```txt

    ┌─[./app.jsx]
    │
∙ 1 │   enterFrom={`opacity-0 group-data-[placement^=top]:translate-y-4 group-data-[placement^=bottom]:-translate-y-4`}
    ·                         ────┬─────  ────┬────┬─     ──────┬──────
    ·                             │           │    │            ╰──────── then apply the follow utility
    ·                             │           │    ╰───────────────────── and the placement value starts with `top`
    ·                             │           ╰────────────────────────── and the data attribute has a name of `placement`
    ·                             ╰────────────────────────────────────── when the "group" (the `Popover`) has a data attribute
    │
    └─
```

Now you only have to rely on the library that does the positioning to set the correct `placement` value at the correct time.

If I apply the same logic but with background colors, then you will see something like this:

https://github.com/tailwindlabs/headlessui/assets/1834413/5e15590d-f267-431f-986b-e790905e65d3

Hope this helps!

**Comment by ycs77** [comment]
@RobinMalfait Thank your reply. But I think this issue is still not resolved. I have made the changes based on your suggestions, but the bug is still present.

Below is the updated repo URL:

https://codesandbox.io/p/sandbox/headlessui-transition-with-floatingui-update-placement-bug-updated-y2hhrj?file=%2Fsrc%2FApp.jsx

And follow the reproduction steps will see the bug is still present.

**Comment by ycs77** [comment]
I found a solution. Using the `useTransitionStatus()` hook from Floating UI can make the transition direction and placement consistent. Here is an example:

https://codesandbox.io/p/sandbox/floatingui-flip-update-placement-bug-with-usetransition-ym78qk?file=%2Fsrc%2FApp.jsx

```jsx
import { useState, useRef } from "react";
import { Popover } from "@headlessui/react";
import {
  useFloating,
  useTransitionStatus,
  flip,
  autoUpdate,
} from "@floating-ui/react";

export default function App() {
  const [show, setShow] = useState(false);
  const boxRef = useRef(null);
  const { context, x, y, strategy, placement, refs } = useFloating({
    open: show,
    placement: "bottom-start",
    middleware: [flip()],
    whileElementsMounted: autoUpdate,
  });
  const { isMounted, status } = useTransitionStatus(context);

  return (
    <div className="box" ref={boxRef}>
      <Popover className="popover">
        <Popover.Button
          ref={refs.setReference}
          onClick={() => setShow((show) => !show)}
        >
          Button
        </Popover.Button>
        {isMounted && (
          <Popover.Panel
            static
            className="
              popover-panel
              data-[status=open]:transition data-[status=open]:duration-200
              data-[status=initial]:opacity-0
              data-[status=initial]:data-[placement^=top]:translate-y-4
              data-[status=initial]:data-[placement^=bottom]:-translate-y-4
              data-[status=close]:transition data-[status=close]:duration-200
              data-[status=close]:opacity-0
              data-[status=close]:data-[placement^=top]:translate-y-4
              data-[status=close]:data-[placement^=bottom]:-translate-y-4
            "
            ref={refs.setFloating}
            style={{
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
            }}
            data-placement={placement}
            data-status={status}
          >
            content...
          </Popover.Panel>
        )}
      </Popover>
    </div>
  );
}
```

* useTransitionStatus docs: https://floating-ui.com/docs/useTransition#usetransitionstatus
* useTransitionStatus source: https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useTransition.ts#L121-L210

This is the solution I found so far, but I don't know how to achieve the same goal using only the Transition component of Headless UI. Is there any chance that Headless UI can solve this problem?
