### ISSUE TITLE
Dialog is not unmounting

### ISSUE THREAD

**Issue by OmkoBass** [tailwindlabs/headlessui#2552]
I'm using: `@headlessui/react": "^1.7.15`

I'm using: `Chrome (Brave Browser)`

The modal is not unmounting at all. There is nothing I can do to make it unmount except render it conditionally which of course is bad because transitions wouldn't work.

To reproduce this just create a basic modal component, change the state inside of it, close it and reopen it and the state will stay the same.

The state is not being reset and if you run a useEffect and run a function on unmount nothing happens.

Link: https://codesandbox.io/s/tailwind-css-and-react-forked-pyg673?file=%2Fsrc%2FApp.js

1. Open the modal,
2. Update the name with the button
3. Close the modal
4. Open it again and the name will be updated one, the modal is not unmounting. If the modal was unmounting then the name would be the default one used as the initial useState value.

**Comment by iamjoshua** [comment]
You are setting your state outside of the Transition so why would the closing of the Transition reset your Modal state? You would need to nest your state within the Transition for it to behave as you want.  See: https://codesandbox.io/s/tailwind-css-and-react-forked-cx9zfh?file=/src/App.js

**Comment by OmkoBass** [comment]
Yes i see, I figured that was the problem. There would be no reason for the state to reset since the `useState` hook is outside of the `Transition`. A dumb mistake on my part.

Thanks for the quick reply by the way!

**Comment by iamjoshua** [comment]
You're welcome. State and hooks are tricky to reason about.
