### ISSUE TITLE
[Vue] Wrong `aria-controls` attribute value in `Disclosure` component

### ISSUE THREAD

**Issue by alexandru-albici-ptt** [tailwindlabs/headlessui#2554]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

1.7.14

**What browser are you using?**

Chrome

**Describe your issue**

The `aria-controls` attribute value present in the `DisclosureButton` does not match the `id` value of `DisclosurePanel`. On page load they seem to match, but after a page change or a couple of refreshes they are not matching anymore.

<img width="1065" alt="Screen Shot 2023-06-23 at 1 43 50 PM" src="https://github.com/tailwindlabs/headlessui/assets/106742322/3de73bd3-a48e-4960-a31e-6efb92ccbf79">

**Comment by 8enSmith** [comment]
I'm getting the same error with '@headlessui/react'.

I noticed this issue when doing a Lighthouse scan in Chrome  114.0.5735.133. This issue got reported under 'Accessibility' and the warning message is '[aria-*] attributes do not match their roles`.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by Muetze42** [comment]
Same issue with 1.7.16
