### ISSUE TITLE
Inner element ui-* classes aren't working in Vite + twin.macro config  

### ISSUE THREAD

**Issue by gbirman** [tailwindlabs/headlessui#2556]
**What package within Headless UI are you using?**

@headlessui/react
@headlessui/tailwindcss

**What version of that package are you using?**

React package: 1.7.15
TailwindCSS plugin: 0.1.3

**What browser are you using?**

codesandbox.io settings:
Version: 5338f8c
Environment: production
Sandbox: cqkfjx
Pitcher: 0.293.0
Manager: 1.23.2
Cluster: fc-us-0

I initially saw this issue in an Electron app (v20.3.0 corresponding to Chromium 104.0.5112.124)

**Reproduction URL**
https://codesandbox.io/p/sandbox/vite-twin-macro-headlessui-tailwindcss-cqkfjx

**Describe your issue**
Using the `@headlessui/tailwindcss` example from https://headlessui.com/react/switch, I'm unable to get the `ui-*` classes working on inner elements (i.e. the `span` element). 

I'm using the `tw` prop from `twin.macro` to render the component. However, this is causing some sort of interference. Don't think this is a bug per se in the sense that this is a third party package to support but it would be a nice-to-have. Possibly related: https://github.com/tailwindlabs/headlessui/issues/2524.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This looks like a bug in `twin.macro` itself where the selectors are converted incorrectly. The definition of `ui-checked` and `ui-not-checked` look like this within our codebase:
https://github.com/tailwindlabs/headlessui/blob/11157a80247af85a82ce076f61420b32666eb6d5/packages/%40headlessui-tailwindcss/src/index.ts#L25-L33

Looking at the generated output, the selectors now look like this:
```css
.hGtbpf[data-headlessui-state~="checked"] {}
.hGtbpf[data-headlessui-state]:not([data-headlessui-state~="checked"]) {}
```

Notice that the other `:not` and `:where` are just missing. I don't think there is anything within our library that we can do to solve it, but I would recommend to open an issue on the `twin.macro` repo instead.

Another thing you can do in the meantime, is to not use `twin.macro` for these cases. Or stick with the dynamic solution you have as well.

Sorry for not being more useful right now. But I hope this helps!
