### ISSUE TITLE
Abstracted Dialog doesn't show different content in slots

### ISSUE THREAD

**Issue by kespaldon** [tailwindlabs/headlessui#2559]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2555

<div type='discussions-op-text'>

<sup>Originally posted by **kespaldon** June 23, 2023</sup>
Hi! Awesome framework btw 🔥

So, I'm using `nuxt-headlessui` and I have abstracted the Dialog code (including the transition components) into `Modal.vue`.

I've setup two slots, one default and one for footer.

Now I have two `<Modal />` components in my header (for profile and authentication) and another in my gallery (for showing details).

header dialog
```vue
<Modal key="header" :trigger="modal" @on-close="modal = false">
  hiaaaaasdfasdf
  <template #footer>footer!</template>
</Modal>
```

gallery dialog
```vue
<Modal key="poster" :trigger="modal" @on-close="modal = false">
  poster! {{ selectedPoster }}
  <template #footer> footer for poster modal</template>
</Modal>
```

The problem now is that when I click any of the triggers to show my dialog, it only shows the latter (gallery) content!

I don't know what I'm doing wrong here... I've tried adding keys to differentiate the usages but no dice.

SOS. Thanks!

---

Edit: Thinking of a fix, I created two abstracted modals that would serve these two use cases. Weirdly enough it's still showing the same content. Sometimes the first, sometimes the second

---

Edit 2: I've pasted the Modal.vue code in directly into my header and it's still the same scenario! What's going ooooonnnn</div>

--- 

After looking around it's similar to [this issue](https://github.com/tailwindlabs/headlessui/issues/1880) but I'm not using Portal Vue or any usage of teleport whatsoever

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Let's keep the conversation in the discussions 👍
