### ISSUE TITLE
Combobox does a patch for every ComboboxItem

### ISSUE THREAD

**Issue by tomhooijenga** [tailwindlabs/headlessui#2571]
**What package within Headless UI are you using?**

`@headlessui/vue`

**What version of that package are you using?**

 1.7.14

**What browser are you using?**

Chrome 114.0.5735.199 

**Reproduction URL**

https://stackblitz.com/edit/vue3-script-setup-with-vite-flvsip?file=src%2FApp.vue

**Describe your issue**

The combobox seems to do a patch for every combobox item it has, when opening. This in turn causes a patch/render for every child of the combobox item. This is taking a huge toll on performance. The Listbox does not have the same behaviour.

![image](https://github.com/tailwindlabs/headlessui/assets/1853235/05b36ec7-301b-48f0-a008-354688cfbcf3)

This screenshot is of the vue devtools, after opening the combobox of the examples, which has 6 items.

**Comment by janthurau** [comment]
experiencing it as well, I rolled back to 1.7.12 for now.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be improved by #2574, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
