### ISSUE TITLE
Combobox completely broken on Android chrome on the latest version

### ISSUE THREAD

**Issue by travelarrow** [tailwindlabs/headlessui#2575]
1.7.15

@headlessui/react

Android Chrome

The combobox component is COMPLETELY broken on the latest headlessui react version. When you type on the keyboard, the onChange event does not fire. We had to downgrade to previous version to make it work. This is a critical site breaking issue that completely broke our site for 2 weeks.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report, and sorry about the `Combobox` being unusable for you. Let's see if we can help you out here.

Can you tell me a bit more about what you mean that it is completely broken? That we can gather some information and find a solution for the issues you are having. The latest release should not contain any breaking changes from an API perspective.

- Do you see any errors in the console?
- Can you share a minimal reproduction repo that shows the issue you are having? (Either a repo or a CodeSandbox or similar)

I just tried to reproduce this using this example (https://headlessui-react.vercel.app/combobox/combobox-with-pure-tailwind) on an older Android (Nexus 6P from ~2015, Android 8.1.0) device using Chrome (114.0.5735.196) and this is what I see:


https://github.com/tailwindlabs/headlessui/assets/1834413/a93fbbde-126c-484c-8d89-261ee9cfa07b

**Comment by JarrodLodge** [comment]
I'm experiencing the same issue as well. It looks like the onchange event is not firing on android anymore.
Work around is that the back button seems to trigger the list items to load. And once it loads it seems to work as intended.

This is using Vue 3. headlessui/vue: 1.7.13

https://github.com/tailwindlabs/headlessui/assets/26698916/0ac826c8-885b-4275-b8de-533acef15c98

**Comment by RobinMalfait** [comment]
Thanks for the video @JarrodLodge, I see what you mean now.

/cc @thecrypticace when you type on Android you are always in a composition mode until you press <kbd>enter</kbd> or <kbd>space</kbd>... because they are using the IME APIs for entering text. That's also why I think the text in the video is using an underline.

I have a fix incoming!

**Comment by RobinMalfait** [comment]
@travelarrow can you confirm that the issue you see is the same issue as @JarrodLodge is showing?

**Comment by RobinMalfait** [comment]
Alright here is what I'm going to do:

I know that there are bugs that #2580 solves. So I'm going to merge this and get a release out either later today or by the end of the week (tomorrow).

Assuming this is the same issue, then we should be good. If not, then once there is more information available we will fix that in a separate PR.

**Comment by RobinMalfait** [comment]
This should hopefully be fixed by #2580, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
