### ISSUE TITLE
Dialog (Modal) - slide-in full screen modal - position "shifts up", renders above the top of the screen

### ISSUE THREAD

**Issue by jonathanrstern** [tailwindlabs/headlessui#2579]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v1.7.2

**What browser are you using?**

For example: iOS Chrome - mobile

Example of the modal being positioned incorrectly -- the page shifts up for a reason I cannot figure out:

https://github.com/tailwindlabs/headlessui/assets/51684334/30237a02-9e90-46c4-979c-ce8bcb3d5cc0

Example of the modal sliding in correctly -- this happens 8 or 9 times out of 10. I'm trying to figure out what it going on when it doesn't work!

https://github.com/tailwindlabs/headlessui/assets/51684334/167eef45-b3a5-4c2c-a1f0-7f4efeef2f23

**Comment by syradar** [comment]
Happening to me too. Happens only when it is too small and it is scrollable for me.
"@headlessui/react": "^1.7.15",
Firefox 114.0.2
macOS Ventura 13.4.1 M1

Normal height
![image](https://github.com/tailwindlabs/headlessui/assets/10453338/3cddb004-6e98-4c84-b8ca-8aea4de04afc)

Bottom is fine (some padding)
![image](https://github.com/tailwindlabs/headlessui/assets/10453338/d5f8ad9b-cabb-40d0-9ec4-e8173180cc37)

Top gets cut off
![image](https://github.com/tailwindlabs/headlessui/assets/10453338/daeca269-e3a9-47a7-8935-ab8687cb05ea)

**Comment by jonathanrstern** [comment]
I’m really not sure how I might do that.On Jul 6, 2023, at 8:47 AM, Robin Malfait ***@***.***> wrote:﻿
Hey, thank you for this bug report! 🙏
Can you attach a minimal reproduction repo that has this behaviour?

**Comment by jonathanrstern** [comment]
@RobinMalfait Not able to attach a reproduction repo but I've done several hours of debugging and am 90% sure it's related to iOS's 100vh bug.

Do you know to what degree HeadlessUI modals are affected by the iOS 100vh bug ("[feature](https://nicolas-hoizey.com/articles/2015/02/18/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers/)")?
