### ISSUE TITLE
Unable to start vue playground

### ISSUE THREAD

**Issue by ThomasKientz** [tailwindlabs/headlessui#258]
Hi, 

Sorry for the noob question.

I am doing `yarn` in root folder, then `yarn vue playground` and then open localhost:3000 but the vue app doesn't start and got the following error :

> GET http://localhost:3000/@modules/@headlessui/vue/dist/headlessui.esm.js net::ERR_ABORTED 404 (Not Found)

What I am missing ?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You are missing a `npm run build` in the vue folder, or a symlink. The code is not inside the vite project itself, but it's a dependency of the project.
