### ISSUE TITLE
Tab Indexes of listboxes are wrong

### ISSUE THREAD

**Issue by samuelreichor** [tailwindlabs/headlessui#2582]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.7.14

**What browser are you using?**
Chrome

[**Reproduction URL**](https://gregarious-flan-7ffaa3.netlify.app/)

https://github.com/samuelreichor/HeadlessUI-Bug

So I think not much explanition is needed. When I use the listbox with the keyboard the tab index are wrong. As a keyboard user I don't know where I am. For my understanding i should be able to tab on the li elements.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Navigating items in the `Listbox` is done using the `arrow keys`, using the `home`/`end` keys or just by typing the first characters of an option and it will jump to the first matching option in the list. Checkout the table in the documentation for more information about accessibility and the keyboard shortcuts: https://headlessui.com/react/listbox#accessibility-notes

We definitely don't want to use the `tab` key for each item for a few reasons. Here is a little example: let's imagine you are filling in a form for your address.

1. You type your street and press tab to go to the next field
2. You type your zip code and press tab to go to the next field
3. You open a `Listbox` for your country selection and press tab to go to the next field. But instead you are going to the next 200 countries before going to the next field.

Another reason is a native `<select>` element. You can also use your arrow keys or just start typing the first characters of an option, but you won't be able to use your <kbd>tab</kbd> to jump to the next `option`.

I hope this explanation helped!

**Comment by samuelreichor** [comment]
@RobinMalfait Sorry but when I navigate with the arrow keys I get no indicator where I am. That can't be accessible. Or do I have to style the focus state somehow to indicate where I am?
