### ISSUE TITLE
Active State Not Correctly Passed to Menu Items When Extracted as a Separate Component in @headlessui/react

### ISSUE THREAD

**Issue by mrsekut** [tailwindlabs/headlessui#2609]
**What package within Headless UI are you using?**

@headlessui/react.

**What version of that package are you using?**

v1.7.15 of @headlessui/react.

**What browser are you using?**

Chrome v 114.0.5735.198

**Reproduction URL**

https://stackblitz.com/edit/stackblitz-starters-vdphu5?file=src%2FApp.tsx

```jsx
function MyDropdown() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          {({ active }) => {
            console.log(`1: ${active}`);
            return (
              <a
                className={`${active && 'bg-blue-500'}`}
                href="/account-settings"
              >
                Account settings
              </a>
            );
          }}
        </Menu.Item>
        <Menu.Item>{({ active }) => <Item active={active} />}</Menu.Item>
      </Menu.Items>
    </Menu>
  );
}

const Item: React.FC<{ active: boolean }> = ({ active }) => {
  console.log(`2: ${active}`);
  return (
    <a className={`${active && 'bg-blue-500'}`} href="/documentation">
      Documentation
    </a>
  );
};
```

**Describe your issue**

I've encountered an issue with the `Menu.Item` component of the `@headlessui/react` package. The issue is specifically with the `active` property within the render prop function. The `active` state does not seem to be correctly passed to all of my menu items. This issue is noticeable both from the console logs and the UI behavior.

When I hover over the "Account Settings" item, its background color changes as expected due to the `active` state being `true`. However, when hovering over the "Documentation" item, its background color does not change, indicating that the `active` state isn't `true` as it should be.

Here are the corresponding console logs:

Hovering over "Account Settings":
```
1: true
2: false
```

Stop hovering over "Account Settings":
```
1: false
2: false
```

Hovering over "Documentation":
```
1: false
2: false
```

Stop hovering over "Documentation":
```
1: false
2: false
```

This suggests that the `active` state is not being updated or correctly passed to the `Item` component when it is used within `Menu.Item`. My expectation is for the `active` state to be `true` when the "Documentation" item is hovered over, changing its background color similar to how it behaves for the "Account Settings" item.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The issue is that you have to forward _all_ props to the underlying DOM element, if you do that then it works as expected: https://stackblitz.com/edit/stackblitz-starters-vndrfs?file=src%2FApp.tsx

Right now the `Item` component receives a bunch of props, but it doesn't do anything with them. These prop include a handful of attributes and event listeners required to make it all work. The reason it works when using a simple `<a>` is because internally they are forwarding all the props/listeners to the actual DOM node.

Hope this helps!

**Comment by mrsekut** [comment]
thank you for your reply.

Now I understand and was able to solve the problem. Given your explanation, I rewrote the code as follows and now it works as expected.

https://stackblitz.com/edit/stackblitz-starters-7fy1ad?file=src%2FApp.tsx
```jsx
<Menu.Item>
  {({ active }) => (
    // Insert a div
    <div>
      <Item active={active} />
    </div>
  )}
</Menu.Item>

const Item = ({ active }: { active: boolean }) => {
  // Keeping the original implementation
};

```


I haven't dug deep enough into headlessui's inner workings, so I might be doing something wrong, but I also feel like `Menu.Item` can contain divs etc. inside to avoid this kind of behavior.

Thanks again for your help.
