### ISSUE TITLE
Pressing ```Enter``` for form submit in```Combobox``` did not work properly

### ISSUE THREAD

**Issue by meruyert93** [tailwindlabs/headlessui#2611]
**What package within Headless UI are you using?**
 @headlessui/react

**What version of that package are you using?**
1.7.14

**What browser are you using?**
Chrome

**Reproduction URL**
https://codesandbox.io/s/combobox-in-form-v5k6km?file=/src/Autocomplete.js:4105-4202

**Describe your issue**
I have seen you have implemented allowing Enter for form submit in this PR https://github.com/tailwindlabs/headlessui/pull/1285 
However, it did not work, when I have Combobox and another input in the form. 
If I remove another input, `Enter` submission works, but I need to add another input as well to my form.
The workaround was to add `<button type='submit' className='hidden' />` hidden button to make it work. 
You can test it in the codesandbox and play with it.

However, it would be great if you can improve this and make it work without adding hidden button. 
Thanks a lot in advance!

**Comment by RobinMalfait** [comment]
TODO: complete this
