### ISSUE TITLE
@headlessui/react 

### ISSUE THREAD

**Issue by welschmoor** [tailwindlabs/headlessui#2619]
@headlessui/react

Updating from **"@headlessui/react": "1.7.14"** to **"@headlessui/react": "1.7.15"** stops animations on mount when using import { Transition } from '@headlessui/react'

Chrome

Downgrading to 1.7.14 brought the on-mount animations back on.

This was our animation, which only worked when we toggled the **show** boolean and no longer worked on mount of the component:
```                  
                  <Transition
                    show={transition}
                    appear={true}
                    enter="transform [transition:transform_1800ms_ease-in-out_300ms,opacity_1900ms_ease-in-out_500ms]"
                    enterFrom="-translate-y-full opacity-0"
                    enterTo="translate-y-0 opacity-100"
                  >
```

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
