### ISSUE TITLE
Create a property to disabled toggle

### ISSUE THREAD

**Issue by afgoulart** [tailwindlabs/headlessui#2647]
in This line, Can we to include a validation in property 'disableToggle', as did on react lib?

https://github.com/tailwindlabs/headlessui/blob/cc163ea458845889019667108e61005a58430669/packages/%40headlessui-vue/src/components/switch/switch.ts#L96C7-L96C20

**Comment by RobinMalfait** [comment]
Hey, thank you for your question! 🙏

The `Switch` component renders a button behind the scenes. This means that you can already pass a `:disabled="true"` prop if you want to disable the `Switch` component entirely.

Here is an example on how you can do that: https://codesandbox.io/p/sandbox/admiring-sutherland-5f3pnh?file=%2Fsrc%2FApp.vue%3A12%2C8

Hope this helps!
