### ISSUE TITLE
ReferenceError: Can't find variable: ResizeObserver in old versions of Safari

### ISSUE THREAD

**Issue by Jiert** [tailwindlabs/headlessui#2661]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.16

**What browser are you using?**

Older versions of iOS < 13.4

**Reproduction URL**

N/A

**Describe your issue**

Thanks for making a great library! One small issue we ran into today: When a user with an older version of Safari uses our app, they get an error `ReferenceError: Can't find variable: ResizeObserver` that ends up crashing the browser. I realize this error probably has a small surface area, but one suggestion might be to silently ignore ResizeObserver for production builds and provide a warning message for development if ResizeObserver doesn't exist. This is what the react wrap balancer folks did: https://github.com/shuding/react-wrap-balancer/commit/e10ede1a80b4c5e84f6125b904e0e8189e9bb245

Feel free to ignore / close if not useful. I thought I'd point it out just in case! Thanks!

**Comment by RobinMalfait** [comment]
Hey!

I think silently ignoring the error and showing a warning in the console will not be super discoverable especially on mobile devices. 

The ResizeObserver is used in the Dialog component to see when a Dialog becomes hidden, if it does then it will close the Dialog. This in turn will ensure that all the focus locking behaviour from the Dialog will be turned off. If we silently ignore the ResizeObserver, then this step won't happen anymore if the Dialog becomes hidden and therefore it will result in a completely broken page, which is also not ideal.

I think the best solution would be to include some polyfills. For the ResizeObserver specifically you can use this package: https://www.npmjs.com/package/resize-observer-polyfill

Hope this helps!
