### ISSUE TITLE
Got undefined error from Dialog

### ISSUE THREAD

**Issue by ChristoRibeiro** [tailwindlabs/headlessui#268]
Hi @RobinMalfait,

I'm using `headlessui/react@dev` and I'm going through an error with the Dialog component:

```
TypeError: Cannot read property 'Overlay' of undefined
```

Here the code, copy/pasted from the documentation:

```js
<Dialog open={showForm} onClose={setShowForm}>
  <Dialog.Overlay />

  <Dialog.Title>Deactivate account</Dialog.Title>
  <Dialog.Description>This will permanently deactivate your account</Dialog.Description>

  <p>
      Are you sure you want to deactivate your account? All of your data will be permanently
      removed. This action cannot be undone.
  </p>

  <button onClick={() => setShowForm(false)}>Deactivate</button>
  <button onClick={() => setShowForm(false)}>Cancel</button>
</Dialog>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Do you have your imports at the top? Can you share the *full* code?

**Comment by ChristoRibeiro** [comment]
Yes 

```import { Dialog } from "@headlessui/react"```

**Comment by RobinMalfait** [comment]
Could you Verify that you are on the latest version?

**Comment by ChristoRibeiro** [comment]
when I did `yarn add @headlessui/react` I got this one: `"@headlessui/react": "^0.3.1-d519f7d"`.

Is it the last version?

**Comment by ft-current** [comment]
I got the same problem

**Comment by Brouilles** [comment]
Same problem here.

**Comment by RobinMalfait** [comment]
@ChristoRibeiro make it a pinned version like `"@headlessui/react": "0.3.1-d519f7d"` (without the caret). Also nuke your node_modules just in case! See this reply: https://github.com/tailwindlabs/headlessui/issues/269#issuecomment-791333952
