### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by abdfnx** [tailwindlabs/headlessui#2680]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Edge

**Describe your issue**

```
Module not found: Can't resolve '/node_modules/.pnpm/@headlessui+react@1.7.17_react-dom@18.2.0_react@18.2.0/node_modules/@headlessui/react/dist/components/transition/transition'
```

**Comment by ben519** [comment]
This has already been addressed [here](https://github.com/tailwindlabs/headlessui/issues/2677)

**Comment by abdfnx** [comment]
> This has already been addressed [here](https://github.com/tailwindlabs/headlessui/issues/2677)

Ok @ben519, Thank you
