### ISSUE TITLE
`s` missing in @headlessui/react transition component resolver path

### ISSUE THREAD

**Issue by LartyHD** [tailwindlabs/headlessui#2681]
node_modules/.pnpm/@headlessui+react@1.7.17_react-dom@18.2.0_react@18.2.0/node_modules/@headlessui/react/dist/headlessui.esm.js:2:0
  Module not found: Can't resolve `'{projectPath}/node_modules/.pnpm/@headlessui+react@1.7.17_react-dom@18.2.0_react@18.2.0/node_modules/@headlessui/react/dist/components/transition/transition'`

The problem is a missing `s` in the path.
It tries to get to `**/transition/transition` but the only path that exisits is`**/transitions/transition`.

**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v1.7.17

**Comment by jberry93** [comment]
Just in case anyone gets this error while working on a `next` project, I ran into this same error when updating the `next` version from v13.4.17 to v13.4.18. Reverting back to v13.4.17 stops the error. Not a solution but thought it would be useful to mention.

**Comment by LartyHD** [comment]
My `NODE_ENV=development`


> Just in case anyone gets this error while working on a `next` project, I ran into this same error when updating the `next` version from v13.4.17 to v13.4.18. Reverting back to v13.4.17 stops the error. Not a solution but thought it would be useful to mention.

I was on next v13.4.18. Downgrading to v13.4.17 fixed it.

The bug also only accurse on next builds.
Building with `tsc` works fine.

**Comment by VladimirMikulic** [comment]
Same issue.

**Comment by jberry93** [comment]
Ah looks like a PR was merged on NextJS's side that triggered these errors to pop up from headless ui: https://github.com/vercel/next.js/pull/54188. Yep the solution is to downgrade `next` to v13.4.17 until they push out a fix for now👍

**Comment by LartyHD** [comment]
Fix is out.
https://github.com/vercel/next.js/releases/tag/v13.4.19-canary.0
https://www.npmjs.com/package/next/v/13.4.19-canary.0

I will close the issue after my test succeed

**Comment by LartyHD** [comment]
# Successfully tested with `v13.4.19`

https://www.npmjs.com/package/next/v/13.4.19
https://github.com/vercel/next.js/releases/tag/v13.4.19
