### ISSUE TITLE
Dialog (Modal) headlessui.com docs are missing "Disclaimer" about lack of multiple-modal support (sibling vs nested) 

### ISSUE THREAD

**Issue by sgarcia-dev** [tailwindlabs/headlessui#2689]
**Describe your issue**

It's been stated before Headless UI does NOT support multiple modals as siblings (requiring users to _nest_ multiple modals instead). And has no plans to add support for this:
https://github.com/tailwindlabs/headlessui/issues/825#issuecomment-1058981268

In response to this, the [headlessui.com docs on Dialog (Modal)](https://headlessui.com/react/dialog) should be updated with a **large disclaimer** summarizing this large architectural limitation to users. Ideally, with its own dedicated "_Multiple modal restrictions_" section on the Sidebar to better communicate its importance.

This is especially important to add given the community's largely negative reception of the news. As well as the fact it's largely agreed upon the community that scalable global modal solutions often render them as siblings instead of nested children as Headless UI requires. Which can severely limit Headless UI's Dialog use-cases to smaller web applications where scalability and modal re-use isn't a strong requirement.
https://github.com/tailwindlabs/headlessui/issues/825#issuecomment-1080718005

**Comment by sgarcia-dev** [comment]
Thank you for the comments @reinink! I can totally respect Headless UI's commitment to nested modals for accessibility reasons, and I'm happy this is being documented on the docs.

However, I think we'll have to agree to disagree on this being a "large architectural limitation". As ultimately, I believe there's [enough evidence online](https://tech.ebayinc.com/engineering/rethink-modals-management-in-react/) that global modal systems can sometimes promote code reuse, something many would agree is important for large scale web applications. Not to mention sibling modals help with keeping modals focused on the Single Responsibility Principle, deferring opening other modals to function props. Whereas declaring nested modals forces requires tighter coupling between modal components by handling their state and/or requiring importing them directly. Not saying I don't agree [colocation is sometimes good](https://kentcdodds.com/blog/colocation). But there needs to be a balance. And some things are better left out of the component to avoid component complexity snowballing out of control and avoiding entropy over time.

I liked your final example's slight reduction of this overhead, though it is also less flexible. As it makes the assumption the element triggering a certain modal will always look the same. Something that is not always the case, and limits flexibility further.

Having said that, I agree not every modal needs to be global as that can lead to more problems. Still, it is nice to have that option. Either way, I'm just happy this is being communicated in the docs. As it helps set better set expectations from the start on what can/cannot be achieved with Headless UI.

**Comment by clopezpro** [comment]
I have a global modal in nuxt that I use to confirm an action 
![image](https://github.com/tailwindlabs/headlessui/assets/27446663/52025c73-04f1-40e0-9f47-4b13b7e819e9)
I have a modal that shows a table I have a global modal in nuxt that I use to confirm an action
![image](https://github.com/tailwindlabs/headlessui/assets/27446663/7ac8b027-0311-4508-85f4-c3440caca059)
when Confirm is clicked out all modals are closed
![image](https://github.com/tailwindlabs/headlessui/assets/27446663/3e251a30-5c03-407e-af34-1de6d3831f87)

**Comment by clopezpro** [comment]
I think I can get used to this, to invoke the modal only in the component that is going to use it and not globally since it works correctly there
![image](https://github.com/tailwindlabs/headlessui/assets/27446663/8a9ec4a3-4657-4dce-a9cc-0831148dbb5e)

**Comment by Emiliano-Bucci** [comment]
Sorry guys, but what you're saying is just silly. If I have a global modal that can and **must** be opened from different parts of my application, how the hell should I do this? I mean, should I add that Dialog in ALL places? That's totally insane, and totally not reusable and extendable.

**Comment by sgarcia-dev** [comment]
> Sorry guys, but what you're saying is just silly. If I have a global modal that can and **must** be opened from different parts of my application, how the hell should I do this? I mean, should I add that Dialog in ALL places? That's totally insane, and totally not reusable and extendable.
> 
> @sgarcia-dev Did you found any solution to this? I can't believe this can't be done...

Yes, we stopped using Headless UI 😅 it was an existing large project migration, and refactoring our entire global modal system to accommodate this rather unorthodox modal limitation from Headless UI was just not an option.

**Comment by Emiliano-Bucci** [comment]
@sgarcia-dev Thanks; I feel a bit frustrated thinking that I have to remove headless ui because of this; or I have to do some hack to temporary bypass this limitation. :/

**Comment by sgarcia-dev** [comment]
@reinink, are there still plans to add this important caveat to the docs? Or is there perhaps any way I could help contribute to our docs by adding a dedicated section on how to properly use nested modals? It seems that a lot of unnecessary frustration could have been saved by **communicating something as important as this upfront** before people integrated headless UI into their projects.

**Comment by Emiliano-Bucci** [comment]
All this can be avoided by giving developers the possiblity to disable or manage the focus trap manually. Something to opt-in if needed.

**Comment by sgarcia-dev** [comment]
@Emiliano-Bucci the library authors already explained they don't feel right making this opt-in as it essentially breaks major accessibility rules. And the entire matra/goal behind Headless UI is providing **accessible** headless components. Truth be told, I respect and understand that. And if you don't care about accessibility enough to be willing to remove the focus trap aspect, Headless UI was not the right library for you anyways.

Realistically, I don't think it's ok to ask the maintainers to add for global modal support just because the community doesn't respect accessibility principles. 

But yeah, I agree this restriction alongside a candid explanation behind the accessibility reasoning _should_ have been explained **early** in the modal docs.

**Comment by Emiliano-Bucci** [comment]
@sgarcia-dev But I do concern about accessibility, what I don't understand is why nested modals are ok but sibilings don't. From a dom tree perspective, they're the same thing, is just the internals that change. It would be enough to handle dialogs accessibility by looking the dom tree.

And yes, also the lack of explanation and transparency, because now I probably would have to waste days of refactoring (in the best scenarios)

**Comment by sgarcia-dev** [comment]
> why nested modals are ok but sibilings don't.

I'm pretty sure it's because focus trapping is essential for accessibility, and having sibling modals makes the focus trap of each one fight each other. Whereas nesting them allows focus traps to be nested seamlessly, trapping each other. Again, you and I aren't maintaining this and have no right to demand anything. Specially when we aren't aware of how difficult it is to fix focus trap issues in sibling modals. 

> It would be enough to handle dialogs accessibility by looking the dom tree.

If you're certain of this, you're welcome to browse the source code and come up with a PR of your own on how to fix this yourself while maintaining the focus trap aspect that's essential for accessibility 😉

Anyways, let's try to keep this civil as Headless UI itself is amazing and being maintained + actively developed for free.

**Comment by dmarvasti** [comment]
@sgarcia-dev @Emiliano-Bucci - This has been fixed, @RobinMalfait has addressed https://github.com/tailwindlabs/headlessui/pull/3242 
https://github.com/tailwindlabs/headlessui/issues/2876#issuecomment-2134069416
