### ISSUE TITLE
Angular support?

### ISSUE THREAD

**Issue by matteociasco** [tailwindlabs/headlessui#27]
Hi everyone, 

I'm wondering if there will be angular support in the future.

Regards,
Matteo.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your interest!
Our focus is currently on React, Vue and soon Alpine.

We don't know about other frameworks yet.

**Comment by ilyaryabchinski** [comment]
Do you need some help with Angular support or you don't consider it at all?

**Comment by gobijan** [comment]
Alpine Support would be warmly welcome..

**Comment by drony** [comment]
angular support

**Comment by vinilanzoni** [comment]
+1

**Comment by benjinus** [comment]
+10086
