### ISSUE TITLE
Modal role="alertdialog"

### ISSUE THREAD

**Issue by pkgmain** [tailwindlabs/headlessui#2701]
**What package within Headless UI are you using?**

@headlessui/react and @headlessui/vue

**What version of that package are you using?**

v1.7.16

**What browser are you using?**

Chromium

**Reproduction URL**

https://stackblitz.com/edit/nuxtlabs-ui-6njwbz?file=app.vue

**Describe your issue**

Unable to create a `Modal` with an `alertdialog` role in order to implement the [Alert Dialog](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/) pattern.

**Comment by thecrypticace** [comment]
Hey, thanks for brining this one up. We've added support for this in #2709, and it'll be available in the next release.

You can give this a try already by using our insiders build (it may take a few minutes to publish to NPM):
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
