### ISSUE TITLE
Cannot set autoComplete="off" for Combobox.Input 

### ISSUE THREAD

**Issue by danilofuchs** [tailwindlabs/headlessui#2704]
Chrome

**What package within Headless UI are you using?**

@headlessui/react 

**What version of that package are you using?**

1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/github/tailwindlabs/reproduction-headlessui-react?file=%2Fsrc%2FApp.jsx%3A7%2C9

**Describe your issue**

Cannot set `<input autoComplete="off" />` to disable browser-native auto complete. We prefer to use only our custom autocomplete

**Comment by danilofuchs** [comment]
Actually an issue on our custom input component

**Comment by billreed-dockwa** [comment]
If this is an issue on the custom input component, what's the resolution?
