### ISSUE TITLE
Split repo into one for react and one for vue?

### ISSUE THREAD

**Issue by oofdog** [tailwindlabs/headlessui#271]
NPM doesn't support installing from subdirectories of a git repo.

People who wanted to install specific commits from this repo can't i.e. unpublished changes.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This is a monorepo, which means that a bunch of packages live in the same repository.
This makes managing multiple packages way easier, more info on this topic: https://classic.yarnpkg.com/en/docs/workspaces/, https://monorepo.guide

If you want to install Headless UI for React:

```shellsession
npm install @headlessui/react@latest
```

Or using yarn

```shellsession
yarn add @headlessui/react@latest
```

If you want to install Headless UI for Vue:

```shellsession
npm install @headlessui/vue@latest
```

Or using yarn

```shellsession
yarn add @headlessui/vue@latest
```

---

This is also described in the docs on our README(s):
- https://github.com/tailwindlabs/headlessui/tree/main/packages/%40headlessui-react#--headlessuireact
- https://github.com/tailwindlabs/headlessui/tree/main/packages/%40headlessui-vue#--headlessuivue

**Comment by oofdog** [comment]
thank you. how often is dev published to npm?
