### ISSUE TITLE
<Dialog />'s ref is always undefined

### ISSUE THREAD

**Issue by AEM5299** [tailwindlabs/headlessui#2710]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.16

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/admiring-einstein-l2p3cs?file=%2Fsrc%2FApp.vue%3A9%2C10

**Describe your issue**

The <Dialog /> element `ref` is always undefined. I need to access the underlying internal dialog element, but this bug makes that impossible. As you can see with the above reproduction repo, I've tried to get it at different stages but it's never set for any of them.

**Comment by thecrypticace** [comment]
This should be fixed by #2720, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/vue@insiders`.

**Comment by AEM5299** [comment]
Thanks for fixing that so promptly! Is there a planned ship date for the new release?

**Comment by thecrypticace** [comment]
@luciano-work If you could please open an issue with a reproduction and we'll take a look!
