### ISSUE TITLE
Scrolling dialog with focused input causes overscrolling(?) in Safari on iOS

### ISSUE THREAD

**Issue by himynameisubik** [tailwindlabs/headlessui#2727]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.7.13

**What browser are you using?**
Safari (iOS)

**Reproduction URL**
Codesandbox: https://codesandbox.io/s/ecstatic-hoover-c2jc96

**Reproduction**
- Open https://c2jc96.csb.app/ in Safari on iOS
- Scroll down
- Focus/tap on input
- Scroll down more (this will scroll the <html> element, and will show blank black portion)
- Scroll up on the red part (if waited long enough, this will lead to scrolling of the modal again and thus cutting of the modal content while still showing the black part)

**Describe your issue**
When using Dialog to show a scrollable modal containing a input field, focusing on the input field and scrolling causes an overscroll(?) on the <html>, which then leads a cut off modal. Setting <html> and/or <body> also to `height:100dvh` does not change anything. 

Any help is appreciated if I'm doing something wrong.

Screenshot:
![IMG_134DAC2ACCD4-1](https://github.com/tailwindlabs/headlessui/assets/322449/737d36ee-7ed4-49a9-ac69-a3797e362a4a)

**Comment by RobinMalfait** [comment]
Hey thanks for your question!

This is strange behaviour in the iOS Safari browser, essentially making the page scrollable when the keyboard is visible (https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d)

The black bar even goes beyond the `html` (styling the html with a background color or removing the iOS overscroll behaviour by using `overflow-hidden` will still show it). Even worse, if you tap in the black area, the Dialog won't even close. 

Here is an example with very basic html without Headless UI showing the same result: https://codesandbox.io/s/focused-pond-cst68d?file=/src/Components/MyModal.tsx

The good news is that they are working on the VirtualKeyboard APIs to hopefully get more control over this behaviour (https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard_API#browser_compatibility). 
The bad news is that it's still experimental and iOS doesn't have support for this.

Unfortunately, I also can't think of any way of solving this issue right now until we have some VirtualKeyboard APIs.

I'm going to close this issue for now, but once the VirtualKeyboard lands, or if @thecrypticace has _some_ idea on how to solve this, then I'm more than happy to re-open this and solve this issue. But unfortunately I don't see a solution right now. 

I hope this helps, and sorry about the inconvenience.

**Comment by himynameisubik** [comment]
Thanks for the quick reply. 

I was afraid that was the case. Guess I'll have to live with it for now if nobody else can chime in. Was really hoping `dvh` would be the (obvious) solution, but no matter how it's used even if html and/or body are fixed, overflow: hidden, set height to the actual visualViewport size (which is correctly adjusted after the virtual keyboard is visible, no dice.
