### ISSUE TITLE
[DOCS]: RadioGroup keyboard interactions don't mention left/right arrows

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/headlessui#2733]
In both the [React](https://headlessui.com/react/radio-group#keyboard-interaction) and [Vue](https://headlessui.com/vue/radio-group#keyboard-interaction) docs, the "Keyboard interaction" section for the Radio Group component mentions only the up/down arrows, and not the left/right arrows.

**Comment by reinink** [comment]
Hey thanks for the heads up on this! This has been corrected:  https://github.com/tailwindlabs/headlessui.com/commit/23d7887545f02230abd7605c717f45e4f7496099
