### ISSUE TITLE
[DOCS]: Switch docs have some text about Radio Groups

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/headlessui#2734]
In both the [React](https://headlessui.com/react/switch#using-with-html-forms) and [Vue](https://headlessui.com/vue/switch#using-with-html-forms) docs for the Switch component, there's some text in the "Using with HTML forms" section that I believe wrongly refers to "radio group":

> This lets you use a radio group inside a native HTML `<form>` and make traditional form submissions as if your radio group was a native HTML form control.

**Comment by reinink** [comment]
Hey thanks for catching this too! This has been corrected: https://github.com/tailwindlabs/headlessui.com/commit/101d0b6ec4243e7b1c7f23f838373b14e1d31965
