### ISSUE TITLE
Lazy-loaded components do not show inside disclosure panel the first time it is opened

### ISSUE THREAD

**Issue by akhdefault** [tailwindlabs/headlessui#2757]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.7.17

**What browser are you using?**

Same problem everywhere, eg Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/vigorous-boyd-szywc7?file=%2Fsrc%2Flazy.tsx

**Describe your issue**

Lazy-loaded react components only show inside Disclosure panel after second opening.

**Steps to reproduce**

Click on the second disclosure component ("Section 2 (with lazy component)") - it's empty, neither the lazily loaded component nor fallback; close panel and reopen again - it's there.

**Expected result**

It should be there the first time.

**Comment by thecrypticace** [comment]
This should be fixed by #2760, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`

**Comment by akhdefault** [comment]
I've tried using insiders, but it's missing combobox component, which I was using. Are you planning to drop it?

**Comment by thecrypticace** [comment]
Insiders has combobox but NPM may have picked up an old version if you did an `upgrade` (has to do with the version numbers for insiders using commit hashes).

Try removing it from your package.json, installing, and then running the following:
```
npm install @headlessui/react@insiders --save-exact
```

and see if that works
