### ISSUE TITLE
Type error on `as` prop

### ISSUE THREAD

**Issue by sgup** [tailwindlabs/headlessui#2761]
<img width="994" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/404386/318b27df-c4c5-46f5-9e08-f979045b3ec3">

Error:
```Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type 'ElementType | undefined'.ts(2322)
types.d.ts(12, 5): The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & (TransitionChildProps<ElementType> & { ref?: Ref<HTMLElement> | undefined; })'
```

**What package within Headless UI are you using?**

@headlessui/react@1.7.17
react@18.2.0
@types/react@18.2.22

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/react-typescript-forked-fncj7s?file=/src/App.tsx

**Describe your issue**

Typescript complains about using react `Fragment` being passed into the `as` prop. Was fine before updating to latest react & headlessui versions. Possibly related thread: https://github.com/facebook/react/issues/24304

**Comment by sgup** [comment]
Further error details:

```
Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type 'ElementType | undefined'.
  Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type 'FunctionComponent<any>'.
    Type 'ReactNode' is not assignable to type 'ReactElement<any, any> | null'.
      Type 'undefined' is not assignable to type 'ReactElement<any, any> | null'.ts(2322)
types.d.ts(12, 5): The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & (TransitionChildProps<ElementType> & { ref?: Ref<HTMLElement> | undefined; })'
```

**Comment by sgup** [comment]
After a lot of testing/digging, i was able to get the source of the bug down to this change:

`@types/react` : `18.0.21` works, `18.0.22` throws an error on headless UI `as={Fragment}`.

<img width="761" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/404386/30d55ecb-66bd-4e99-a9b1-6404e150bd4f">

**Comment by thecrypticace** [comment]
Hey, so I can't repro this in a new project. Nor does it reproduce from the codesandbox — though I did notice in my testing that no matter what I did it would not install React 18's version of the types. Chances are, as indicated in the linked issue, you have multiple versions of `@types/react` in your dependency tree (you should be able to check this with `npm ls`).

So overall this is not something we can fix as it's not a Headless UI problem.

As an aside, i'd recommend using something other than `create-react-app` for new projects like Vite, Parcel, or Next.js.

**Comment by Nicolasvegam** [comment]
same error here!
