### ISSUE TITLE
Popover with transition

### ISSUE THREAD

**Issue by rsdrsd** [tailwindlabs/headlessui#277]
I have implemented the popover with the TailwindUI Sidebar layout in Reactjs. It all works fine, but when I close the Sidebar on mobile, it disappears instantly not using the transitionI implemented.

I implemented the following:
```
<div class="h-screen flex overflow-hidden bg-gray-100">
  <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
  <div class="md:hidden">
    <div class="fixed inset-0 flex z-40">
      <!--
        Off-canvas menu overlay, show/hide based on off-canvas menu state.
```
as:
```
<div className='h-screen flex overflow-hidden bg-gray-100'>
            <Popover as={React.Fragment}>
                {({open}) => (
                    <>
                        {open && <div className={`md:hidden`}>
                            <div className='fixed inset-0 flex z-40'>
```
Due to the `{open &&` it removes the `Popover` instantly. I don't see how I can implement this in another way, such that it isn't removed instantly.

Adding a `hidden` class also doesn't have the expected result.

My question is, how should I implement:
```
<div class="h-screen flex overflow-hidden bg-gray-100">
  <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
```
for a TailwindUI Sidebar layout.

**Comment by ianstormtaylor** [comment]
Look for the `static` option in the docs, you'll want that to ensure it's always rendered.

And you'll need to refactor the `open &&` logic to use `<Transition>` instead.

**Comment by rsdrsd** [comment]
Thanks, using `Transition.Child` and the `static` prop did the trick.
