### ISSUE TITLE
[DOCS]: Add Popover example with floating-ui

### ISSUE THREAD

**Issue by wyozi** [tailwindlabs/headlessui#2780]
Floating UI (https://floating-ui.com/) is what seems to be the future of popper, so would be nice to have an example of how to use Popover with it.

**Comment by RobinMalfait** [comment]
Hey!

We have some examples with Floating UI available in our playgrounds.

**React:**
- Code: https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/menu/menu-with-floating-ui.tsx
- Demo: https://headlessui-react-git-main-tailwindlabs.vercel.app/menu/menu-with-floating-ui

**Vue:**
- Code: https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/components/menu/menu-with-floating-ui.vue
- Demo: https://headlessui-vue-git-main-tailwindlabs.vercel.app/menu/menu-with-floating-ui

In the future we might add some examples to the actual docs, but right now the docs are focused on the Headless UI components themselves.

Hope this helps!

**Comment by jamesarosen** [comment]
Note: those files have sinced moved. The React code is now at https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/react/pages/menu/menu-with-floating-ui.tsx and the Vue version at https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/vue/src/components/menu/menu-with-floating-ui.vue.
