### ISSUE TITLE
adjust-scrollbar-padding causing performance degradation when there are many other elements in the page.

### ISSUE THREAD

**Issue by rkdrnf** [tailwindlabs/headlessui#2792]
**What package within Headless UI are you using?**
  "@headlessui/react": "^1.7.17",

**What version of that package are you using?**
v1.7.17

**What browser are you using?**
safari on ios

**Reproduction URL**
if you place 1000 empty divs and [slide-over component sample code in the example page](https://tailwindui.com/components/application-ui/overlays/slide-overs#component-91416d48f50d19d1ad826e5a6c77b1e9),
it introduces lags while opening and closing dialog.

tested on iphone 12 pro and in case of 1000 divs, it cause about 200ms-300ms delay to open and close dialog.

I wonder how elements not related to modal itself can affect on modal performance this much. maybe some costly calculation is done on every element on page.

https://codesandbox.io/p/sandbox/lively-meadow-pf4fw4
 
A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

You can use one of the starting projects on CodeSandbox:

- With React and Tailwind CSS: https://codesandbox.io/s/github/tailwindlabs/reproduction-headlessui-react
- With Vue and Tailwind CSS: https://codesandbox.io/s/github/tailwindlabs/reproduction-headlessui-vue

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by rkdrnf** [comment]
Reproduced on codesandbox. strangely having global css like 
```@layer base {
  * {
    @apply border-black;
  }
}
```
and extending tailwind css theme in config file as below
```
const defaultTheme = require('tailwindcss/defaultTheme')
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Noto Sans KR', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [],
}
```
reproduces the problem.
(NotoSansKR font is embedded in index.html)

**Comment by thecrypticace** [comment]
Hey, so the reason this happens is we calculate the width of the scroll bar so as to prevent layout shifts before/after the dialog opens and closes as best as possible. One step in doing this is querying the current value of `documentElement.clientWidth` which causes a style recalculation. When a document has a large number of DOM nodes and styles exist that apply to every one this can result in a slowdown. Some browsers handle this better than others — Chrome seems to handle this better than safari (well on Desktop — on iOS Chrome and Safari both still use webkit for now).

Normally when you have code that reads from the DOM you do so in batches and avoid doing so in loops. The kicker here is that we have very few reads and generally only one shows up as taking up any significant amount of time.

There's unfortunately not much _we_ can do to optimize this given that it is a single read as it's really down to how well the browser can optimize this situation. Sorry :(

**Comment by rkdrnf** [comment]
Thank you for a detailed explanation. It's a shame that it can't be resolved in this library. Thanks for your great work!
