### ISSUE TITLE
[Bug]: A Dialog is closed when clicking inside for the first time

### ISSUE THREAD

**Issue by JamesKEbert** [tailwindlabs/headlessui#2800]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.15 or newer

**What browser are you using?**

Firefox, reproduced in Chrome

**Reproduction URL**

https://codesandbox.io/s/tailwind-dialog-closing-on-first-click-stjw9m
Additional reproduction by @lukasvice: https://codesandbox.io/s/dialog-closing-on-first-click-vx4ftt

**Describe your issue**

A Dialog is unexpectedly closed when clicking inside the Dialog for the first time, subsequent clicks inside behave as expected. This bug only occurs in Dialogs that do not contain a `Dialog.Title` or `Dialog.Description`. See issue #2535 for more reports and reproductions of the issue.

**Comment by thecrypticace** [comment]
Hey, so this was fixed by #2697 which is available in our insiders build:
```
npm install @headlessui/react@insiders
```

We don't have a a tagged release out but I believe we're aiming to tag a release sometime next week (we have some documentation work to finalize first).
