### ISSUE TITLE
[rfc?] Rendering to Shadow DOM

### ISSUE THREAD

**Issue by alii** [tailwindlabs/headlessui#2806]
Increasingly I've found myself wanting to use Headless UI to render to Shadow DOM. This is especially useful in two scenarios: browser extensions and micro frontends. The main troubles I've had have been with the `Dialog` and `Portal` component, as they explicitly render to an element existing on the document's `body`.

If this could be something Headless might want to have implemented, I'd be thrilled to contribute a PR, however I'd certainly need some guidance as well as some discussion about semantics; which components need to be modified, etc. Additionally, I also have very little Vue experience, so I'd only be able to help out on the React side of things (this could be okay in the interim..?)

I have a fork which adds a `root` prop to the Dialog and Portal component for this very use case https://github.com/alii/headlessui/tree/cf537114b9db0e8ff5071b1963d8b73df7ecdc3e, however my changes are messy and definitely not something shippable. The work done in the fork was half to learn how Headless React works and half to get dialogs working in a chrome extension.

Thanks a lot in advance ❤️

**Comment by alii** [comment]
Others have expressed wanting similar behaviour regarding changing of root element for Dialog and Portal here - https://github.com/tailwindlabs/headlessui/discussions/666

**Comment by thecrypticace** [comment]
Hey so while I understand there is at least some demand for this feature it's a bit more complicated than it seems.

I spent a little time trying to see what supporting this would look like. A `root` prop is just the start of what would be needed. In addition to that we have to consider:
- **Outside clicks:** What if a browser extension adds an element to the DOM — we handle this today as best we can but if it gets mounted inside the Shadow DOM that could cause complications for figuring out where an element is located in relation to the dialog and whether or not it's considered an outside click. It might even be completely ambiguous.
- **Marking elements as `inert`**: When a dialog is open all elements surrounding it must be marked as `inert` to prevent them from being interactive. If you can place the root somewhere else then we have to make sure that ancestors of the root are not `inert` to keep the dialog itself interactive and prevent it from closing when you interact with it.
- **Focus trapping**: This must take into account any quirks of being placed in the Shadow DOM and determing what elements should be focusable.
- Automatic placement into the Shadow DOM is likely not possible — nor would it be desirable in all situations — so a `root` prop  would be absolutely necessary in that case.

In general, this is not something we can prioritize right now. It'll take a good bit of effort for us to properly research, implement, and verify that things work the way they need to if you customize the root container — like placing it inside the Shadow DOM. We generally like to keep issues related to things that are considered to be possible bugs — so I'm going to close this and keep the discussion open.
