### ISSUE TITLE
[Bug] Can't Set defaultValue component resets on mount

### ISSUE THREAD

**Issue by waelnassaf** [tailwindlabs/headlessui#2811]
Using NextJS13.5 and headlessUI for react I am having a problem setting the default value for the <Combobox.Input> component.
I want to set the value of the input to be equal to the search query param `sq` for better UX when the user copies a link of the search. But the input remounts and empties the input after a few milliseconds of showing the text as shown in the following GIF

![ezgif-5-2a95242bff](https://github.com/tailwindlabs/headlessui/assets/18513157/691bac29-7420-4cad-aa7d-25ab09bb75aa)

How can I fix this bug?

 Code:
```
                    <Combobox.Input
                        className="search-text__input"
                        placeholder="Line Counter..."
                        displayValue={(sQuery: string) => sQuery}
                        autoComplete={"off"}
                        defaultValue={getSearchParam("sq")}
                        onChange={(e) => setQuery(e.target.value)}
                    />
```

**Comment by RobinMalfait** [comment]
Hey!

The `Combobox.Input` is synced with the value of the `Combobox`. To have more control over the value, you can use the `displayValue`. If no value is set yet, you can also use the following:

```diff
  <Combobox.Input
    className="search-text__input"
    placeholder="Line Counter..."
-   displayValue={(sQuery: string) => sQuery}
+   displayValue={(sQuery: string) => sQuery || getSearchParam("sq")}
    autoComplete={"off"}
-   defaultValue={getSearchParam("sq")}
    onChange={(e) => setQuery(e.target.value)}
  />
```

If this doesn't behave as expected, please provide a reproduction repo so that we can take a look.

**Comment by waelnassaf** [comment]
> Hey!
> 
> The `Combobox.Input` is synced with the value of the `Combobox`. To have more control over the value, you can use the `displayValue`. If no value is set yet, you can also use the following:
> 
> ```diff
>   <Combobox.Input
>     className="search-text__input"
>     placeholder="Line Counter..."
> -   displayValue={(sQuery: string) => sQuery}
> +   displayValue={(sQuery: string) => sQuery || getSearchParam("sq")}
>     autoComplete={"off"}
> -   defaultValue={getSearchParam("sq")}
>     onChange={(e) => setQuery(e.target.value)}
>   />
> ```
> 
> If this doesn't behave as expected, please provide a reproduction repo so that we can take a look.

It works, thank you very much!
