### ISSUE TITLE
[DOCS]: Update usage of TailwindCSS v2 in examples to v3 

### ISSUE THREAD

**Issue by cjboco** [tailwindlabs/headlessui#2815]
I'm noticing a lot of the examples still are using TailwindCSS v2.

Example: [Menu (Dropdown)](https://headlessui.com/react/menu)

`<Menu.Button className="inline-flex w-full justify-center rounded-md bg-black bg-opacity-20 px-4 py-2 text-sm font-medium text-white hover:bg-opacity-30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75">`

... will result with an ESLint warning: 

`Classname 'bg-opacity-20' should be replaced by an opacity suffix (eg. '/20') eslint[tailwindcss/migration-from-tailwind-2]`

The corrected classes are was follows:

`<Menu.Button className="inline-flex w-full justify-center rounded-md bg-black/20 px-4 py-2 text-sm font-medium text-white hover:bg-black/30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white/75">`

Not a "major" issue, but it is an inconvenience.

**Comment by thecrypticace** [comment]
Updated — thanks!
