### ISSUE TITLE
Accessibility bug: scrollable code blocks on website are not operable with a keyboard

### ISSUE THREAD

**Issue by ashleemboyer** [tailwindlabs/headlessui#2828]
On pages like [Menu (Dropdown)](https://headlessui.com/react/menu) where there are code blocks that can scroll vertically and horizontally, there is no way for keyboard-only users to scroll those areas and view all of the content in them.

This issue falls under [WCAG 2.1 Success Criterion 2.1.1 Keyboard (Level A)](https://www.w3.org/TR/WCAG21/#keyboard). It can be fixed by adding the `tabindex="0"` property to the scrollable regions. This will enable the region to be reachable via keyboard, and then the arrow keys can be used to scroll the content.

Here is a screenshot from the top of the linked page showing a code block that scrolls in both directions:

<img height="500" alt="" src="https://github.com/tailwindlabs/headlessui/assets/43934258/3a827b6b-ee09-4b28-a339-e0fac5e0ae41">

**Comment by reinink** [comment]
Hey thanks for this suggestion as well, I've added `tabindex="0"` to the code block, and now I am able to access it using voiceover on MacOS 👍

<img width="901" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/882133/7805d032-7295-40ee-b135-86249291c12f">
