### ISSUE TITLE
Popover: doesn't close when tab focus leaves, if using `Popover.Button`s `as` prop

### ISSUE THREAD

**Issue by JoshWhiteTTD** [tailwindlabs/headlessui#2837]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

[Repro](https://codesandbox.io/p/sandbox/optimistic-brown-vqrjp9?file=%2Fsrc%2FPopover.jsx%3A32%2C28)

**Describe your issue**

From the [docs](https://headlessui.com/react/popover#accessibility-notes):

> Tabbing out of an open panel will close that panel, and tabbing from one open panel to a sibling Popover's button (within a Popover.Group) closes the first panel

*Expected*
You should be able to use the keyboard to tab to the button, hit enter to open the popover, then when you tab away from the popover, it should close

*Actual*
This works great unless you use the `as` prop on `Popover.Button` (see repro).

In this case, when you tab away from the popover, it doesn't close.

---

I assume there are some refs being passed around here? Let me know if there is something required at the custom button component level...

**Comment by JoshWhiteTTD** [comment]
My colleague pointed out that it works if you use `forwardRef` on the custom button component:
https://codesandbox.io/p/sandbox/wizardly-bardeen-wt2lt8?file=%2Fsrc%2FButton.jsx%3A6%2C1

Do you think this should be (or is)  documented somewhere?

**Comment by thecrypticace** [comment]
Hey, sorry for the late reply. We've updated the docs with information about `forwardRef` on a handful of the pages. But yes, if you're using a component in an `as` prop you have to use `forwardRef` or Headless UI won't be able to work with them correctly.

Example of one of the updated docs pages: https://headlessui.com/react/menu#rendering-as-different-elements

Hope that helps!
