### ISSUE TITLE
Attempted import error: 'Dialog' is not exported from '@headlessui/react'.

### ISSUE THREAD

**Issue by iamrakhmatov** [tailwindlabs/headlessui#284]
Trying to use Dialog for my project and this is what I get :
 **Attempted import error: 'Dialog' is not exported from '@headlessui/react'.**

**Comment by papageno** [comment]
Dialog seems to have not been released yet, and only available in @headlessui/react@dev

https://github.com/tailwindlabs/headlessui/issues/269#issuecomment-791333952

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As @papageno mentioned, this is currently only available via the `dev` channel:
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
