### ISSUE TITLE
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

### ISSUE THREAD

**Issue by megetron** [tailwindlabs/headlessui#2844]
i am getting this error when using Popover:

Failed to compile.

../node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

Import trace for requested module:
../node_modules/@headlessui/react/dist/components/popover/popover.js
__barrel_optimize__?names=Popover!=!../node_modules/@headlessui/react/dist/headlessui.esm.js
./app/search/layout.tsx
../node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fsearch%2Fpage&page=%2Fsearch%2Fpage&pagePath=private-next-app-dir%2Fsearch%2Fpage.tsx&appDir=%2FUsers%2Fguy%2Fproj%2Fcontra%2Fcommerce%2Fapp&appPaths=%2Fsearch%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/search/page.tsx?__next_edge_ssr_entry__

../node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

Import trace for requested module:
../node_modules/@headlessui/react/dist/components/popover/popover.js
__barrel_optimize__?names=Popover!=!../node_modules/@headlessui/react/dist/headlessui.esm.js
./app/search/layout.tsx
../node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fsearch%2Fpage&page=%2Fsearch%2Fpage&pagePath=private-next-app-dir%2Fsearch%2Fpage.tsx&appDir=%2FUsers%2Fguy%2Fproj%2Fcontra%2Fcommerce%2Fapp&appPaths=%2Fsearch%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/search/page.tsx?__next_edge_ssr_entry__

../node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

Import trace for requested module:
../node_modules/@headlessui/react/dist/components/popover/popover.js
__barrel_optimize__?names=Popover!=!../node_modules/@headlessui/react/dist/headlessui.esm.js
./app/search/layout.tsx
../node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fsearch%2Fpage&page=%2Fsearch%2Fpage&pagePath=private-next-app-dir%2Fsearch%2Fpage.tsx&appDir=%2FUsers%2Fguy%2Fproj%2Fcontra%2Fcommerce%2Fapp&appPaths=%2Fsearch%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/search/page.tsx?__next_edge_ssr_entry__

../node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

Import trace for requested module:
../node_modules/@headlessui/react/dist/components/popover/popover.js
__barrel_optimize__?names=Popover!=!../node_modules/@headlessui/react/dist/headlessui.esm.js
./app/search/layout.tsx
../node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fsearch%2Fpage&page=%2Fsearch%2Fpage&pagePath=private-next-app-dir%2Fsearch%2Fpage.tsx&appDir=%2FUsers%2Fguy%2Fproj%2Fcontra%2Fcommerce%2Fapp&appPaths=%2Fsearch%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/search/page.tsx?__next_edge_ssr_entry__

../node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'J').

Import trace for requested module:
../node_modules/@headlessui/react/dist/components/popover/popover.js
__barrel_optimize__?names=Popover!=!../node_modules/@headlessui/react/dist/headlessui.esm.js
./app/search/layout.tsx
../node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fsearch%2Fpage&page=%2Fsearch%2Fpage&pagePath=private-next-app-dir%2Fsearch%2Fpage.tsx&appDir=%2FUsers%2Fguy%2Fproj%2Fcontra%2Fcommerce%2Fapp&appPaths=%2Fsearch%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/search/page.tsx?__next_edge_ssr_entry__

package,json:
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "engines": {
    "node": ">=18"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint-staged": "lint-staged",
    "prettier": "prettier --write --ignore-unknown .",
    "prettier:check": "prettier --check --ignore-unknown .",
    "test": "yarn lint && yarn prettier:check"
  },
  "git": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*": "prettier --write --ignore-unknown"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "@orama/orama": "^1.2.9",
    "clsx": "^2.0.0",
    "geist": "^1.0.0",
    "lodash": "^4.17.21",
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rsuite": "^5.44.0"
  },
  "devDependencies": {
    "@tailwindcss/container-queries": "^0.1.1",
    "@tailwindcss/typography": "^0.5.10",
    "@types/lodash": "^4.14.195",
    "@types/node": "20.8.9",
    "@types/react": "18.2.33",
    "@types/react-dom": "18.2.14",
    "@vercel/git-hooks": "^1.0.0",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.52.0",
    "eslint-config-next": "^14.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-unicorn": "^48.0.1",
    "lint-staged": "^15.0.2",
    "postcss": "^8.4.31",
    "prettier": "3.0.3",
    "prettier-plugin-tailwindcss": "^0.5.6",
    "tailwindcss": "^3.3.5",
    "typescript": "5.2.2"
  }
}

**Comment by ShafiaAnsar** [comment]
Hi man how did you solve this error I am getting the same

**Comment by yogarasu** [comment]
@ShafiaAnsar 
I also faced the same situation, but it was resolved by modifying browserslist in package.json .

**Comment by asiriPiyajanaka** [comment]
> @ShafiaAnsar I also faced the same situation, but it was resolved by modifying browserslist in package.json .

Hay, what is the change you made?
