### ISSUE TITLE
There are no focusable elements inside the <FocusTrap />

### ISSUE THREAD

**Issue by omsali** [tailwindlabs/headlessui#2849]
I'm using { Dialog, Transition } from @headlessui/react to popup the modal to update. It has input fields the also it shows that there are no focusable elements. I'm not using FocusTrap component explicitly.

version : "^1.7.17"

**Comment by DamianGlowala** [comment]
I very much doubt anyone can help you without providing a minimal reproducible example of the issue.

**Comment by omsali** [comment]
its okay I figured it out

**Comment by babycourageous** [comment]
@omsali I'm curious - what was your solution?

**Comment by LittleFishSashie** [comment]
@omsali Would also like to know what the solution was.
