### ISSUE TITLE
Uncontrolled Radio Group and Combobox do not reset hidden inputs when a native form reset happens

### ISSUE THREAD

**Issue by tobeycodes** [tailwindlabs/headlessui#2851]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

latest

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/devbox/pensive-khayyam-h6pytf

**Describe your issue**

Using uncontrolled inputs RadioGroup and Combobox do not reset the hidden inputs values when a native form reset is called. This does work for Switch.

**Comment by RobinMalfait** [comment]
Hey!

Sorry for the delay here. This should be fixed, and will be available in the next release (likely the v2 release).

You can already try it using:
- `npm install @headlessui/react@insiders`.
