### ISSUE TITLE
Popover: cannot close by clicking out-side in a shadow-root

### ISSUE THREAD

**Issue by islxyqwe** [tailwindlabs/headlessui#2856]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/quirky-tharp-4qhcp2

**Describe your issue**

the popover cannot be closed when clicking outside when it's used in a shadow-root.

**Comment by thecrypticace** [comment]
This should be fixed by #2866, and will be available in the next release.

You can try it using our insiders build which should be available in the next few minutes:
- `npm install @headlessui/react@insiders`.

**Comment by georgecoca** [comment]
@thecrypticace I'm having same issue but in vue. I've tried to install (not sure if has the fix included):
```
npm install @headlessui/vue@insiders
```
But still the popover does not close by clicking out-side in the shadow-root.

Thanks
