### ISSUE TITLE
ui-disabled doesn't work for Tabs

### ISSUE THREAD

**Issue by bmulholland** [tailwindlabs/headlessui#2864]
**What package within Headless UI are you using?**

@headlessui/vue, @headlessui/tailwindcss

**What version of that package are you using?**

@headlessui/vue: 1.7.16
@headlessui/tailwindcss: 0.2.0

**What browser are you using?**

Firefox

**Reproduction URL**

Well, I tried to create one, using the linked template and dropping in the literal example from headlessui.com. But that doesn't work, it throws some weird error I don't understand. I'm not going to debug the sandbox provided, so hopefully this is all you need. I added the class that should illustrate the problem but can't confirm this illustrates it because nothing will load. Hopefully the sandbox and sample code on headlessui.com can be made compatible, too, for future repros.

[Attempted repro here](https://codesandbox.io/p/devbox/compassionate-microservice-wrkq2r?file=%2Fsrc%2FApp.vue%3A6%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clprdriew00083b845vresh8g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clprdriew00033b84f69mf7xy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clprdriew00053b84dgla9jk7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clprdriew00073b84inl0tkhe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clprdriew00033b84f69mf7xy%2522%253A%257B%2522id%2522%253A%2522clprdriew00033b84f69mf7xy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpre1ukq00023b83k8wmi6nc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpre1ukq00023b83k8wmi6nc%2522%257D%252C%2522clprdriew00073b84inl0tkhe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprdriew00063b840mdoslvp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clprdriew00073b84inl0tkhe%2522%252C%2522activeTabId%2522%253A%2522clprdriew00063b840mdoslvp%2522%257D%252C%2522clprdriew00053b84dgla9jk7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprdriew00043b844oeftss8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clprdriew00053b84dgla9jk7%2522%252C%2522activeTabId%2522%253A%2522clprdriew00043b844oeftss8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

Tabs can be disabled, and it seems natural that ui-disabled would be applied in that case. Doesn't seem to be, though, and the docs are so light on examples of usage of these that it's left to an exercise to the reader to assume this would work. I'm therefore not really sure if this is intentionally not enabled or what...

**Comment by RobinMalfait** [comment]
This should be fixed by #2918, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
