### ISSUE TITLE
Modal not rendering correctly in web component

### ISSUE THREAD

**Issue by u12206050** [tailwindlabs/headlessui#2872]
We build our web components with vue, and have used headless ui to add functionality such as modal and menu.

However due to it always rendering to a portal on the window root instead of the web component root, it looses all styling.

This could be solved by allowing us to define which portal (root) to use.

**Comment by thecrypticace** [comment]
Hey, I provided a response recently as to why this hasn't been made customizable. See https://github.com/tailwindlabs/headlessui/issues/2806#issuecomment-1814935684 for more info.

tl;dr placing the portal in the Shadow DOM can significantly complicate things

**Comment by u12206050** [comment]
I see, where is this being discussed, and if adding a root prop could solve it could that just simply be added as an advance beta feature? I'm sure if we were able to set it to fixed with z-index to 9999 then it would be fine for most cases.

**Comment by Strangersknowme** [comment]
@u12206050 Did you end up solving this? I am facing the same issue. I have my app wrapped as a web component, the portal is being added to the main DOM instead of the Shadow DOM. How do you end up solving it?
