### ISSUE TITLE
Tabs Component Accessibility - aria-controls Value Issue in React 17

### ISSUE THREAD

**Issue by helmisatria** [tailwindlabs/headlessui#2882]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome, Edge

**Reproduction URL**
- https://stackblitz.com/edit/vitejs-vite-v6gywx?file=src%2FApp.tsx,package.json,src%2Fmain.tsx,src%2FApp.css&terminal=dev

**Steps to Reproduce:**

- Use the Tabs component in a React 17 project.
- Observe the aria-controls attribute of the tab buttons.

**Describe your issue**

I've encountered an issue with the Tabs component from the `@headlessui/react` where the tab's `aria-controls` value is set incorrectly (id is `undefined`) when used with React 17. This issue seems to be specific to React 17 and does not occur in React 18.

**Screenshots:**
<img width="651" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/15356855/2b2ab8c2-e8c2-4fd7-930f-79fc0d3089f0">
<img width="1361" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/15356855/0222b974-4b3f-439e-9a65-43220d9667fe">

**Comment by RobinMalfait** [comment]
Hey!

This has been fixed by #2883 and will be available in the next v1.7 release.
