### ISSUE TITLE
Combobox does not clear when setting value to undefined

### ISSUE THREAD

**Issue by pbrzosko** [tailwindlabs/headlessui#2892]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

1.7.16

**What browser are you using?**

Chrome

**Reproduction URL**

[headlessui-bug.zip](https://github.com/tailwindlabs/headlessui/files/13739818/headlessui-bug.zip)
`npm i` then `npm run dev`

**Describe your issue**

When I want to clear combobox value with a clear button, the value is not cleared. As you can see in the project, when I clear the value, model is clear, but the combobox still displays a value that was previously selected:

Value selected:
![image](https://github.com/tailwindlabs/headlessui/assets/67122459/cfee9a3b-1801-4f08-8239-fe86ec5dc3ca)

Clear button clicked:
![image](https://github.com/tailwindlabs/headlessui/assets/67122459/bfad673e-1ae3-49dd-a1cc-e18057b4884f)

**Comment by pbrzosko** [comment]
Probably the issue is with your useControllable composable, that depends on undefined value? When I change the code to set null to the model, then it works.

**Comment by RobinMalfait** [comment]
Hey!

Setting the `value` to undefined makes the combobox switch from a controlled to an uncontrolled component, similar to how native React components work: https://react.dev/reference/react-dom/components/textarea#im-getting-an-error-a-component-is-changing-an-uncontrolled-input-to-be-controlled

Instead, you can add the `nullable` prop and set the value to `null` instead.

https://headlessui.com/react/combobox#allowing-empty-values
