### ISSUE TITLE
(Vue) Listbox example is not working

### ISSUE THREAD

**Issue by iraklisg** [tailwindlabs/headlessui#290]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

0.2.0

### What browser are you using?

Firefox

### Reproduction repository

https://codesandbox.io/s/headlessuivue-listbox-example-mi67g?file=/src/App.vue

When clicking at listbox component nothing happens

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Vue introduced a breaking change in 3.0.5, we fixed this in the dev channel!

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
