### ISSUE TITLE
 Transition not showing the children if transition is not active 

### ISSUE THREAD

**Issue by Joostdeboer** [tailwindlabs/headlessui#2905]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.13 (lower version needed to make the Popover component disappear properly)

**What browser are you using?**

Firefox v121.0

https://codesandbox.io/p/sandbox/lucid-margulis-zhcytl
To see the issue, click on e.g. "Test1" or "Test4".

**Describe your issue**

I'm running into the following issue. I have a header menu in which I wished to include some items, that appear as a dropdown/popover when clicked. I added a transition to the caret to make it flip over, but instead found something I'm not quite sure of how to fix. Posting in the Discussions tab resulted in no results, and it looks like it should work, so I think it's a bug.
What looks to happen is that, whatever is inside the Transition itself, seems to unmount when the transition is not active. I've tried using the `show` prop, or `appear` or `unmount`, but none of these provided the desired effects.

Perhaps I'm not approaching this correctly. If not, I'd like some advice as to how to properly implement this transition. But it seems like it is bugged. How is the Transition supposed to work here? Are the elements inside the transition supposed to never show its children if not active?

**Comment by adamwathan** [comment]
Hey! The `Transition` component is purely controlling enter/leave transitions, so things that appear and disappear. For animating positions of things that stay on the screen the whole time, you just need simple utility classes:

https://codesandbox.io/p/sandbox/gifted-edison-l4nwnw

```jsx
<Popover.Button className="group w-full h-full focus:outline-none transition-colors hover:bg-red-400 ease-in-out group-first/parent:rounded-l-md group-last/parent:rounded-r-md">
  <span>{name}</span>
  {menuItems ? (
    <span
      className={`${
        open ? "rotate-0" : "rotate-180"
      } transition-transform ease-in-out duration-100 absolute right-5`}
    >
      ^
    </span>
  ) : undefined}
</Popover.Button>
```
