### ISSUE TITLE
ComboboxOptions virtual don't have options

### ISSUE THREAD

**Issue by AnnaYuS** [tailwindlabs/headlessui#2926]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

For example: latest

**What browser are you using?**

Chrome, Firefox

**Reproduction URL**
[codesandbox](https://codesandbox.io/p/devbox/nifty-paper-tys4v6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrexyaxc00072e6789xnmou8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrexyaxb00022e67xew20cni%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrexyaxc00042e67vrw42dyn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrexyaxc00062e67rgk6slzx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrexyaxb00022e67xew20cni%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrexyaxb00012e67kq4do7vd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrexyaxb00022e67xew20cni%2522%252C%2522activeTabId%2522%253A%2522clrexyaxb00012e67kq4do7vd%2522%257D%252C%2522clrexyaxc00062e67rgk6slzx%2522%253A%257B%2522id%2522%253A%2522clrexyaxc00062e67rgk6slzx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrexyaxc00052e67puy99adr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrexyaxc00052e67puy99adr%2522%257D%252C%2522clrexyaxc00042e67vrw42dyn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrexyaxc00032e672upc1sws%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrexyaxc00042e67vrw42dyn%2522%252C%2522activeTabId%2522%253A%2522clrexyaxc00032e672upc1sws%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A22.135416666666657%257D)

**Describe your issue**

When you open the list of options the list is empty. It seems that virtual options are not available to `ComboboxOptions` component

**Comment by RobinMalfait** [comment]
Hey!

The `virtual` feature is currently an unreleased feature and isn't available in the version you are using in the Codesandbox link. To use the virtual feature, you currently have to use the insiders version which you can install using:
```shell
npm install @headlessui/vue@insiders
```

Hope this helps!
