### ISSUE TITLE
Unexpected token . Pages are not getting loaded in older browsers

### ISSUE THREAD

**Issue by imsourajit** [tailwindlabs/headlessui#2927]
Hi Team 

We are getting "unexpected token . and unexpected token ... " in console. We have used headlessui/react dialog for popup. The popups are not getting opened in any of the below browser.  And a blank page is opening. 

1. Google Chrome - version 74.0.3729.185
2. Samsung Internet browser - any version
3. UC Browser - any version

Current package versions 
```
"@headlessui/react": "^1.7.17",
 "tailwindcss": "3.3.3",
```

And also we found these issues happens in devices with Android OS Versions 7,8,9 and 10.

To reproduce the bug you can use any <Dialog></Dialog> component code.  
Below is the sample screenshots of console.

<img width="1430" alt="Screenshot 2024-01-15 at 20 45 48" src="https://github.com/tailwindlabs/headlessui/assets/97603933/028fa108-3b33-41f9-90fd-ddcdf20f6fd2">

<img width="427" alt="Screenshot 2024-01-15 at 20 44 10" src="https://github.com/tailwindlabs/headlessui/assets/97603933/766c7a84-dbca-4f05-a363-9df4d36517d6">

**Comment by reinink** [comment]
Hey! Sorry, we're unable to help without a minimal reproduction of the bug, as per the bug report template:

> **Reproduction URL**
>
> A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

Going to close this issue, but feel free to create a new one with a proper reproduction 👍
