### ISSUE TITLE
I can't uncheck the option. Options: multiple: false and nullable: true

### ISSUE THREAD

**Issue by timoteiNicsoft** [tailwindlabs/headlessui#2928]
@headlessui/vue. v1.7.17

Browser: Chrome

**Reproduction URL**

- With Vue and Tailwind CSS: [Link](https://codesandbox.io/p/devbox/happy-bassi-smkltx?file=%2Fsrc%2FApp.vue%3A6%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrg6urjq00073b6g6pen4st2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrg6urjq00023b6gw5eb2ibj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrg6urjq00043b6ggbgp32tg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrg6urjq00063b6guerbd6nb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.12942496890767%252C49.87057503109233%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrg6urjq00023b6gw5eb2ibj%2522%253A%257B%2522id%2522%253A%2522clrg6urjq00023b6gw5eb2ibj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrg6urjq00013b6gig9aupjn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrg7f9e500023b6gojj7kxpg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A82%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A82%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FFilterCombobox.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrg7j2r400023b6gdyuxhy7s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrg7j2r400023b6gdyuxhy7s%2522%257D%252C%2522clrg6urjq00063b6guerbd6nb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrg6urjq00053b6gutv8p4h6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrg6urjq00063b6guerbd6nb%2522%252C%2522activeTabId%2522%253A%2522clrg6urjq00053b6gutv8p4h6%2522%257D%252C%2522clrg6urjq00043b6ggbgp32tg%2522%253A%257B%2522id%2522%253A%2522clrg6urjq00043b6ggbgp32tg%2522%252C%2522activeTabId%2522%253A%2522clrg6urjq00033b6g5ch30trr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrg6urjq00033b6g5ch30trr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clrg75j70007l3b6gbu5k0zj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrg75jb6000zedi6bnwpdtj8%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

I can't uncheck the option.

**Comment by RobinMalfait** [comment]
Hey!

`nullable` means that the component can be in a `null` state. If you remove all the text from the `ComboboxInput` then nothing will be selected. The `nullable` state currently doesn't mean that you can toggle an option on or off.

Going to keep this open for a bit, because going to see if it makes sense to also toggle or not (and why) in case of `nullable`.

**Comment by timoteiNicsoft** [comment]
Hey @RobinMalfait !

I use this dropdown as a filter and I wanted to implement the same logic as when multiple:true. When it's set to multiple:true, it activates a toggle feature. From my perspective, it would be beneficial to have this functionality even when multiple is set to false.

I am using it in the select logic. The first action to remove a filter is to deselect the previously selected option. It was quite challenging for me to realize that I need to enter the search input and delete its content to remove the filtering.

Thanks.

**Comment by RobinMalfait** [comment]
Hey!

I see what you mean, but for now we are going to keep the current behavior. It mimics the behavior of other libraries and more importantly the behavior of the native `<select>` where you can also not uncheck an option once it's checked. 

Since we don't want to change that behavior right now, I'm going to close this issue and we might revisit this in the future but no promises.
