### ISSUE TITLE
Create Menu from array

### ISSUE THREAD

**Issue by rafcontreras** [tailwindlabs/headlessui#293]
### What package within Headless UI are you using?

 @headlessui/react

### What version of that package are you using?

v0.3.1

### What browser are you using?

Chrome

### Reproduction repository

private

How can I create a Menu with an array of Items? Similar to the ListBox.

**Comment by nathanheffley** [comment]
This seems more like a general React programming question moreso than an issue. If you close this and open a discussion (over here https://github.com/tailwindlabs/headlessui/discussions/categories/help) instead and tag me I think I have a menu component that is based on array like the listbox component that I'll dig up and host on a codepen to show you.
