### ISSUE TITLE
Returning focus after dialog is closed (with a transition)

### ISSUE THREAD

**Issue by widavies** [tailwindlabs/headlessui#2946]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.18

**What browser are you using?**

Electron/Chromium

**Reproduction URL**

[Reproduction URL](https://codesandbox.io/p/devbox/github/tailwindlabs/reproduction-headlessui-react?file=%2Fsrc%2FApp.jsx%3A11%2C2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrtezfss0007356gw3ggn2m4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrtezfss0002356gra6cwidc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrtezfss0004356gso4p8sji%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrtezfss0006356gu358j364%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrtezfss0002356gra6cwidc%2522%253A%257B%2522id%2522%253A%2522clrtezfss0002356gra6cwidc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0001356gr2emobw8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtezfss0001356gr2emobw8%2522%257D%252C%2522clrtezfss0006356gu358j364%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0005356gqajjt56q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrtezfss0006356gu358j364%2522%252C%2522activeTabId%2522%253A%2522clrtezfss0005356gqajjt56q%2522%257D%252C%2522clrtezfss0004356gso4p8sji%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0003356gaxfsw1mr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrtezfss0004356gso4p8sji%2522%252C%2522activeTabId%2522%253A%2522clrtezfss0003356gaxfsw1mr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

In this example, **Open dialog** opens the dialog. After the dialog closes, I'd like the input **Focus me** to regain focus.

![image](https://github.com/tailwindlabs/headlessui/assets/11671115/c9dec2a5-0697-4df8-a515-f7b5f96b5f66)

The dialog itself contains a button called **Click me** that will close the dialog.

I'm trying to use the `afterLeave` property to restore focus, but it doesn't seem to work. My theory is that either  `afterLeave` doesn't wait for the transition to complete & unmount to occur (thus focus is still stolen by the dialog).

It seems like no matter what I do, I can't get focus to return to _any_ component after the dialog closes.

Thanks for the help!

**Comment by RobinMalfait** [comment]
Hey!

The Dialog should already restore focus to the correct element once it closes without you having to do anything special.

The reproduction URL points to our template, can you update your reproduction URL so that we can take a look?

**Comment by widavies** [comment]
Whoops! Try this [link](https://codesandbox.io/p/devbox/funny-galois-r94smv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrtezfss0007356gw3ggn2m4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrtezfss0002356gra6cwidc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrtezfss0004356gso4p8sji%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrtezfss0006356gu358j364%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrtezfss0002356gra6cwidc%2522%253A%257B%2522id%2522%253A%2522clrtezfss0002356gra6cwidc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0001356gr2emobw8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtezfss0001356gr2emobw8%2522%257D%252C%2522clrtezfss0006356gu358j364%2522%253A%257B%2522id%2522%253A%2522clrtezfss0006356gu358j364%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0005356gqajjt56q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtezfss0005356gqajjt56q%2522%257D%252C%2522clrtezfss0004356gso4p8sji%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtezfss0003356gaxfsw1mr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrtezfss0004356gso4p8sji%2522%252C%2522activeTabId%2522%253A%2522clrtezfss0003356gaxfsw1mr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by reinink** [comment]
Hey!

So this is actually intended behavior, as @RobinMalfait suggested. When the dialog is closed and unmounts, Headless UI automatically restores focus to the element that was focused at the point the dialog was opened.

In your particular use-case this focus restoration is happening basically at the exact same time as the code in your `afterLeave` callback, and Headless UI just happens to be winning out. You can fix this by delaying the focus of your input by one macrotask, which you can do using a `setTimeout()`:

```jsx
afterLeave={() => {
  setTimeout(() => inputRef.current.focus())
}}
```

Hope that helps!

**Comment by widavies** [comment]
@reinink Thanks! I had got it working with `setTimeout` having a delay specified, but I didn't realize it had a no-args call for one-macrotask as well, that's useful.

One interesting bit - this is working for me in the web browser (chrome), but not in Electron, any ideas?

**Comment by widavies** [comment]
This seems to be the root issue: https://github.com/electron/electron/issues/28163
