### ISSUE TITLE
[headlessui/react][Menu] - Pass active state to a composant

### ISSUE THREAD

**Issue by guelosuperstart** [tailwindlabs/headlessui#2952]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v1.7.18

**What browser are you using?**

For example: Chrome

**Reproduction URL**

`https://stackblitz.com/edit/remix-run-remix-1hkqyn?file=app%2Froutes%2F_index.tsx`

**Describe your issue**

When I use a component to display a button, the active state doesn't work.
The same button directly in the code works fine 

Thank you

**Comment by RobinMalfait** [comment]
Hey!

You have to make sure that you forward all incoming props and the `ref` as well. This way the `Menu.Item` can add the necessary event listeners to your custom button.

You can update your button to something like this:
```ts
const DeleteButton = forwardRef<
  HTMLButtonElement,
  {
    classification: { name: string };
    active: boolean;
  }
>(
  (
    {
      classification,
      active,
      ...rest // Accept all other props
    },
    ref // Accept the `ref`
  ) => {
    return (
      <button
        {...rest} // Forward the incoming props
        ref={ref} // Forward the ref
        type="button"
        className={`${
          active ? 'bg-gray-100' : ''
        }   flex w-full items-center px-4 py-2 text-sm`}
      >
        {/* <TrashIcon className="mr-2 h-4 w-4 text-gray-400 group-hover:text-gray-500" aria-hidden="true" /> */}
        Remove,{classification.name}
      </button>
    );
  }
);
```

Hope this helps!
