### ISSUE TITLE
[a11y]: Checkbox does not submit form on enter

### ISSUE THREAD

**Issue by hauptrolle** [tailwindlabs/headlessui#2958]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v2.0.0-alpha.4 (but also occurs in latest stable version)

**What browser are you using?**

Chrome

**Describe your issue**

The current <Checkbox /> implementation does not support to submit the form on enter. (The <Switch> components works)
Example from the docs:
```tsx
import { Checkbox } from '@headlessui/react'
import { useState } from 'react'

function Example() {
  const [enabled, setEnabled] = useState(true)

  return (
    <form action="/notification-settings" method="post">
      <Checkbox
        checked={enabled}
        onChange={setEnabled}
        name="notifications"
        className="group block size-4 rounded border bg-white data-[checked]:bg-blue-500"
      >
        <svg className="stroke-white opacity-0 group-data-[checked]:opacity-100" viewBox="0 0 14 14" fill="none">
          <path d="M3 8L6 11L11 3.5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </Checkbox>
      <button>Submit</button>
    </form>
  )
}
```

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #2962, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.

**Comment by hauptrolle** [comment]
@RobinMalfait Wow, thank you very much for fixing this so fast!
Any plans when the next release will be released?

**Comment by reinink** [comment]
Hey just a heads up that we noticed today that our insiders builds were broken. If you now try and install the latest insiders you should get this updated checkbox behavior 👍
