### ISSUE TITLE
Combobox: vue@1.7.17 breaks activeOption

### ISSUE THREAD

**Issue by saibotk** [tailwindlabs/headlessui#2964]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Firefox 122

**Reproduction URL**

https://codesandbox.io/p/sandbox/affectionate-chandrasekhar-nd4shl

**Describe your issue**

The reproduction is basically the "CommandPalette with Preview" from TailwindUI but reduced to only the Combobox.

With v1.7.16 the preview works fine, but since 1.7.17 and the changes to the Combobox, the `activeOption` slot prop is always undefined.

**Comment by sebastiaanluca** [comment]
Can confirm, just upgraded and having the same situation in production in Chrome. Hovering an item does nothing and no error in the console either.

**Comment by reinink** [comment]
Hey folks! Thanks for reporting this issue. We've just merged in a fix (#2973) for this and will get a new release tagged before the end of the day 👍

**Comment by thecrypticace** [comment]
`@headlessui/vue@1.7.19` is out with the fix!

**Comment by saibotk** [comment]
Thank you very much! <3
