### ISSUE TITLE
Switch component cannot stop propagation

### ISSUE THREAD

**Issue by kurt-hardy** [tailwindlabs/headlessui#2970]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.18

**What browser are you using?**

Chrome

**Describe your issue**

When I define a click event on the parent container, the inner switch button click cannot stop propagation. The on change event passes the Boolean value back so there's no access to the event

**Comment by kurt-hardy** [comment]
Code sand box: https://codesandbox.io/p/sandbox/switch-stop-propagation-w8chyd

Thanks

**Comment by reinink** [comment]
Hey! So you're correct, the `onChange` handler doesn't receive the event, but you can use the `onClick` handler to stop propagation:

```jsx
<Switch
  checked={enabled}
  onClick={(event) => event.stopPropagation()}
  /* ... */
```

I've updated your reproduction to do this: https://codesandbox.io/p/devbox/switch-stop-propagation-forked-njzj7y

You can also just do this directly on the `<td>` if you want, that way you don't have to bake this into your `Switch` component. Something like this:

```jsx
<tr onClick={() => setDisplay(!display) }>
  <td>{display ? "value 1" : "Value 2"}</td>
  <td onClick={(event) => event.stopPropagation()}>
    <Toggle />
  </td>
</tr>
```

Also, just an aside, the `onChange` handler in your reproduction was broken, you needed to pass the value through:

```diff
- onChange={() => setEnabled()}
+ onChange={(value) => setEnabled(value)}
```

Hope that helps! 👍
