### ISSUE TITLE
ListboxButtons cause hydration errors in Nuxt

### ISSUE THREAD

**Issue by enemy-senator92** [tailwindlabs/headlessui#2979]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.19

**What browser are you using?**

Chrome, Safari, Firefox

**Reproduction URL**

https://github.com/enemy-senator92/nuxt-headlessui

**Describe your issue**

Using ListboxButton in server-side rendering causes hydration errors.

![image](https://github.com/tailwindlabs/headlessui/assets/24677480/0d724b7f-0c4f-4642-a520-e90c3b8ce4f8)

This is because the id on the server and on the client is generated differently each time

**Comment by theartkod** [comment]
Same issue here

**Comment by thecrypticace** [comment]
Hey! So this is a limitation of Vue + SSR. Vue v3.5 is supposed to provide a proper `useId` function for this that we can use once it's available but until then we've implemented a workaround for Nuxt users using Nuxt v3.10+

See https://github.com/tailwindlabs/headlessui/issues/2913#issuecomment-1924681165 for instructions on how to use this workaround to generate stable IDs on the server and client.

**Comment by enemy-senator92** [comment]
> Hey! So this is a limitation of Vue + SSR. Vue v3.5 is supposed to provide a proper `useId` function for this that we can use once it's available but until then we've implemented a workaround for Nuxt users using Nuxt v3.10+
> 
> See [#2913 (comment)](https://github.com/tailwindlabs/headlessui/issues/2913#issuecomment-1924681165) for instructions on how to use this workaround to generate stable IDs on the server and client.

Thanks, it really works!
