### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by M0hammedImran** [tailwindlabs/headlessui#298]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.3.1

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/M0hammedImran/headlessui-react-type-error-demo

When I build the app I get this error. 
```console
node_modules/@headlessui/react/dist/components/switch/switch.d.ts:16:32 - error TS1335: 'unique symbol' types are not allowed here.

16     }>>(props: Props<TTag, {}, unique symbol>) => JSX.Element;
                                  ~~~~~~~~~~~~~
```

I am using vite to bootstrap a React app. This error never occurred in a CRA app.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed in v0.3.2!
