### ISSUE TITLE
Combobox `disabled` attribute not disabling hidden inputs

### ISSUE THREAD

**Issue by VictorGlindasPaf** [tailwindlabs/headlessui#2988]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.18

**What browser are you using?**

Chrome

**Reproduction URL**

[https://codesandbox.io/p/devbox/relaxed-shtern-vrkmkt?workspaceId=6a20031e-e5fd-43b6[…]ebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](https://codesandbox.io/p/devbox/relaxed-shtern-vrkmkt?workspaceId=6a20031e-e5fd-43b6-a39d-bb9573aadb6b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsoobwst00053b6hzinbxm14%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsoobwst00023b6h3rfoysx8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsoobwst00033b6hmks1vfel%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsoobwst00043b6h1q1edsul%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsoobwst00023b6h3rfoysx8%2522%253A%257B%2522id%2522%253A%2522clsoobwst00023b6h3rfoysx8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsoolxey008v3b6hkgv6vkei%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsoolxey008v3b6hkgv6vkei%2522%257D%252C%2522clsoobwst00043b6h1q1edsul%2522%253A%257B%2522id%2522%253A%2522clsoobwst00043b6h1q1edsul%2522%252C%2522activeTabId%2522%253A%2522clsoocden006a3b6hu8jjq5u7%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsoocden006a3b6hu8jjq5u7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsoobwst00033b6hmks1vfel%2522%253A%257B%2522id%2522%253A%2522clsoobwst00033b6hmks1vfel%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsoocbs8005a3b6hi3k8dk7i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsoocbs8005a3b6hi3k8dk7i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

When passing `disabled` to `Combobox`, the hiden inputs it renders are not disabled, and are still submitted via any parent form.

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3004, and will be available in the next release. This will also be fixed for all the other form-like components.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
