### ISSUE TITLE
Menu in an overflow hidden parent div or at the edge of page

### ISSUE THREAD

**Issue by evangeline** [tailwindlabs/headlessui#30]
Hey, thanks for this great library! I'm a huge fan of Tailwind CSS and am really excited that you guys are releasing a headless component library. There are two cases which I don't see handled in the menu component, which I come across pretty regularly in the wild.

1. Menu button positioned near the edge of a page, which causes the menu items to be rendered off screen.

This may happen when the user resizes their window or when whatever the menu button is positioned in has been scrolled to the edge of the user's window.

Sandbox: https://codesandbox.io/s/headlessuireact-menu-example-forked-8c38x

2. Menu in an overflow hidden div.

The menu button may be fully visible in the overflow hidden parent div, but the menu items are cropped/hidden because of overflow-hidden. This is especially problematic when we need virtualisation, eg when we're rendering an infinitely scrollable table/list of cards with menu buttons.

Sandbox: https://codesandbox.io/s/headlessuireact-menu-example-forked-pg5es

**Comment by RobinMalfait** [comment]
Hey! Thank you for trying Headless UI!

We made the choice to not support this positioning related issue (at least for now, not sure about the future).
We are aware of the issue, and we created an example on how to use this library together with Popper (scenario 1) and a Portal (scenario 2).

https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx

The most interesting parts are:

https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx#L12-L16

and

https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx#L46

The advantage of this is that you can compose multiple components (and its functionality) together. This way we can keep the API service small and to the point. It would be a bit of a bummer to also allow props on our Menu component that are not really related to it but are just for positioning and portals. 

I hope this answers your question!
I'm going to leave the issue open for now while I wait for some feedback.

Much appreciated! 🙏

**Comment by adamwathan** [comment]
Yep as Robin mentioned this is by design and the API has been designed to compose well with Portals which already exist in React and Vue as well as with libraries like Popper which already handle the positioning. We may discover ways to make this integration even easier in the future and add some hooks or props or who knows for this sort of thing, but for now it’s 100% possible to handle in user land by combining Headless UI with existing tools focused specifically on these problems 👍🏻

**Comment by evangeline** [comment]
That makes sense, thank you! 👍

**Comment by tslocke** [comment]
Do you have any pointers for getting this working with Vue?

**Comment by jaletechs** [comment]
Hi @grantholle, both links are currently broken. Could you please update?

**Comment by grantholle** [comment]
Here is the [composition function](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/playground-utils/hooks/use-popper.js). I'm not sure where the example went

**Comment by superuser-chi** [comment]
Hi @RobinMalfait , I could not access the links with popper you included in your comment, can you kindly assist :-)

**Comment by aaronbguerrero** [comment]
Thank goodness for the Wayback Machine :)

[https://web.archive.org/web/20210615073708/https://github.com/tailwindlabs/headlessui/blob/develop/packages/@headlessui-react/pages/menu/menu-with-transition-and-popper.tsx]

**Comment by RobinMalfait** [comment]
@aaronbguerrero @superuser-chi You don't need the Wayback Machine, we just moved those files into a `playground-react` and `playground-vue` package in the same repo. E.g.: https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/menu/menu-with-transition-and-popper.tsx

**Comment by aaronbguerrero** [comment]
@RobinMalfait even better!! thank you so much :)

**Comment by AlejandroAkbal** [comment]
Bless you @OliverRC

**Comment by brtdv** [comment]
Just leaving this here for other people: I did a manual implementation of the above requested behaviour by manually combining [`focus-trap-react`](https://github.com/focus-trap/focus-trap-react) and [`popper.js`](https://popper.js.org/), ... but scrapped it all after discovering that this is actually super easy to do by using [@headlessui-float](https://headlessui-float.vercel.app/). 

Just wrap your `<Menu.Button>` & `<Menu.Items>` in a `<Float>` component and add the [`portal`](https://headlessui-float.vercel.app/react/portal.html#portal) and/or [`autoPlacement`](https://headlessui-float.vercel.app/react/floatingui-options.html#auto-placement) props (autoPlacement even accepts all Popper.js options) and you're basically done.

See also: https://headlessui-float.vercel.app/react/quick-start.html#usage

**Comment by giannifm** [comment]
@brtdv how lucky am I to see your suggestion to use the `<Float/>` component, when you just posted this morning!!!!!!!!!! THANK YOU 🙏 

What ended up working for me was using the [HeadlessUI Float component](https://headlessui-float.vercel.app/react/quick-start.html#usage) with the `portal` prop and then I specified what direction I wanted the dropdown to go in with `placement` prop (as opposed to `autoPlacement`).

**Comment by p19ky** [comment]
I tried some stuff from here: https://headlessui-float.vercel.app/react/adaptive-width.html But I don't have success... :/

**Comment by p19ky** [comment]
I just use useLayoutEffect and put a ref on the container div and get it's width with getBoundingClientRect and set it on the dropdown. 🤷‍♂️

**Comment by shammahk** [comment]
This can be solved with the [HeadlessUI Float Portal](https://headlessui-float.vercel.app/react/portal.html).

You won't need to rewrite so much code and it isn't hacky. [Steps to use](https://headlessui-float.vercel.app/react/quick-start.html)

**Comment by iamvinny** [comment]
> @headlessui-float

That's crazy we need a dedicated library to fix an issue that seems so simple.. Well, not so simple, I guess.
