### ISSUE TITLE
Missing license file in package

### ISSUE THREAD

**Issue by arnekra** [tailwindlabs/headlessui#3010]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2971

<div type='discussions-op-text'>

<sup>Originally posted by **arnekra** February  6, 2024</sup>
We have started using @headlessui/vue (currently 1.7.16) in a project, but we noticed that its license file is missing in the package. All the other npm packages that we use include a license file next to the readme file in the package, but it is missing in @headlessui/vue.

We are using a license utility to collect all the licenses that should be acknowledged, but for @headlessui/vue it pulls in your readme file instead of the license file. Instead of us having to add a hacky build step to download your license file, it would be nice if you could include the license file in the package instead.

Thanks</div>

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3030, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by arnekra** [comment]
Thanks a lot!
