### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by SimeonGriggs** [tailwindlabs/headlessui#303]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss.com

(As mentioned in Discord)

I don't think Tree Shaking is working / fully optimized. You can see this even in the bundle on tailwindcss.com – the only Component in use is `<Switch />` and yet inspecting the (impressive!) coverage of the website's Next.js bundle contains references to `headlessui-menu`, `headlessui-listbox`, etc.

This is more problematic using Components from the dev branch where even more Components are bundled – whether they're in use or not.

(I could be misunderstanding something about the nature/purpose/design of tree shaking in this context I just thought to mention it)

<img width="1440" alt="Screen_Shot_2021-04-03_at_1 35 26_pm" src="https://user-images.githubusercontent.com/9684022/113519257-f1cd9000-9582-11eb-8686-bf1de60587e1.png">

**Comment by henribru** [comment]
I think I'm seeing the same thing with Vue CLI. Here's from webpack-bundle-analyzer: 
![image](https://user-images.githubusercontent.com/6639509/116562979-efe9b900-a903-11eb-9897-17dfd363d1b3.png)

**Comment by Bessonov** [comment]
It seems like some parts are not optimized or can't be optimized. Just installed headlessui and used only one definition:

```typescript
import { Transition } from '@headlessui/react'
```
Now it's second biggest dep:
```
@headlessui+react@1.2.0_react@17.0.2/node_modules/@headlessui/react/dist/headlessui.esm.js • 53.52 KB • 18.3%
```

Looking at the original file:
```
151616 Mai 30 17:32 headlessui.esm.js
```
it's a reduction, but, well, still too big.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This PR that was already merged improves tree shaking a lot: https://github.com/tailwindlabs/headlessui/pull/602

**Comment by deadcoder0904** [comment]
@RobinMalfait do i need to enable anything to make it work? i'm using next.js & only `Dialog` but still getting a lot of unused code in my coverage report.

**Comment by evanfrawley** [comment]
Seeing the same. Locally running with `@headlessui/react` and importing Menu & Listbox, and I'm seeing this when I search the source in Chrome dev tools:
![CleanShot 2022-02-28 at 12 38 14](https://user-images.githubusercontent.com/13992385/156055235-ddcf9b63-71c2-42c9-88b0-8a884588c34c.png)

**Comment by Ojay** [comment]
Hey all, I'm just re-visiting this package as the lack of tree shaking made me opt for another approach a few months ago. Looking to add this to a new project (also Next.js like @deadcoder0904) but want to make sure tree shaking is being fully handled first?

Thanks for all your hard work!

**Comment by TheRusskiy** [comment]
hey guys, maybe something changed and tree shaking got broken along the way.
I can take a look later because right now trying to flee Russia 😬

**Comment by Ojay** [comment]
Yeah well first things first... 😂

Best of luck!

**Comment by deadcoder0904** [comment]
yeah, @TheRusskiy this can wait, take care :)

**Comment by nandorojo** [comment]
Hate to be that guy, but did anyone figure out how to tree shake here?

**Comment by cpakken** [comment]
😢still no treeshaking. I just want to use `<Transition />` my bundle increased by 225kB 😲

**Comment by BasicallyMe** [comment]
has treeshaking been implemented?👀

**Comment by antoniormrzz** [comment]
Seems to be working with vite swc, 11KB when only switch is used.

**Comment by RobinMalfait** [comment]
@BasicallyMe there is not a lot to implement here (sure we can make sure that we don't include everything in every file, or that we don't mess with globals), but typically you don't implement tree shaking in the library. 

We are the tree, you have to shake it.

**Comment by o-pnk-craft** [comment]
> hey guys, maybe something changed and tree shaking got broken along the way. I can take a look later because right now trying to flee Russia 😬

какой ты нахер русский, говноед ты, а не русский.
