### ISSUE TITLE
Can not use the combobox scrollbar in a bootstrap modal

### ISSUE THREAD

**Issue by Swedish-li** [tailwindlabs/headlessui#3033]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.19

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/Swedish-li/headlessui-demo.git

**Describe your issue**
<img width="730" alt="Screenshot 2024-03-14 at 22 35 28" src="https://github.com/tailwindlabs/headlessui/assets/17829108/1f3b6f3c-af99-4124-9212-56161bf293c7">

  I can not use the scrollbar in a bootstrap modal, when I click the scrollbar, the combobox will close.

**Comment by RobinMalfait** [comment]
Hey!

Hmm interesting one, the moment you click inside the scrollbar the `Combobox` is closed because the bootstrap modal moves focus to the modal element itself and therefore blurring the `Combobox` which close the combobox.

I am looking into some ways to see if we can solve it on our end, but it's the bootstrap modal implementation moving the focus unfortunately.

Going to keep this open a little longer to make sure I'm not missing something obvious.

**Comment by Swedish-li** [comment]
https://github.com/tailwindlabs/headlessui/assets/17829108/f87dde5a-9c50-4d74-b599-dd055a657a9e
Hello, RobinMalfait! Thank you for the help!
I find I can use the scrollbar after I do the right-click on the combobox option.

**Comment by Swedish-li** [comment]
> https://github.com/tailwindlabs/headlessui/assets/17829108/f87dde5a-9c50-4d74-b599-dd055a657a9e Hello, @RobinMalfait ! Thank you for the help! I find I can use the scrollbar after I do the right-click on the combobox option.

Now, I use this to fix the scrollbar issue

https://github.com/Swedish-li/headlessui-demo/commit/4e349cec87df29be046e9b3509b9ecc4c5bfa645

**Comment by RobinMalfait** [comment]
Hey!

I looked into it and I'm not sure if there is anything we can do about this besides trying to detect if we are in a bootstrap modal and change the logic accordingly.

I also noticed that you found a solution for your use case, so I'm going to close this issue for now.

**Comment by Swedish-li** [comment]
> the bootstrap modal moves focus to the modal element itself 
I find the really reason for this is the bootstrap modal element has a tabindex attribute
https://github.com/Swedish-li/headlessui-demo/commit/811f426b8a535a799e2a1a57913dd6443f4a6114

**Comment by scottroot** [comment]
I am having this exact same issue when using Combobox within a table.  Using tailwind styled <table> and on each row is a td that includes the combobox -- when trying to scroll the combobox it closes.  I have been experimenting with using Combobox.Options static and hold without luck.

Is there a way to completely override the open/close logic of the combobox?

**Comment by Swedish-li** [comment]
> I am having this exact same issue when using Combobox within a table. Using tailwind styled `<table>` and on each row is a td that includes the combobox -- when trying to scroll the combobox it closes. I have been experimenting with using Combobox.Options static and hold without luck.
> 
> Is there a way to completely override the open/close logic of the combobox?

If the scrollbar is in the ComboboxOptions,I think you can add a tabindex attribute to the ComboboxOptions to fix this issue

**Comment by scottroot** [comment]
> > I am having this exact same issue when using Combobox within a table. Using tailwind styled `<table>` and on each row is a td that includes the combobox -- when trying to scroll the combobox it closes. I have been experimenting with using Combobox.Options static and hold without luck.
> > Is there a way to completely override the open/close logic of the combobox?
> 
> If the scrollbar is in the ComboboxOptions,I think you can add a tabindex attribute to the ComboboxOptions to fix this issue

Hi.  Awesome.  That does it.  Thank you very much for pointing that out @Swedish-li 

```tsx
<Combobox.Options
  id={`dd-${idx}`}
  hold={true}
  tabIndex={-1}
  className="absolute ..."
>
```

**Comment by banushanv** [comment]
Great, that solves it. Thanks a lot for highlighting that, @Swedish-li
