### ISSUE TITLE
Transition hiding behind image below dropdown button

### ISSUE THREAD

**Issue by tvarwig** [tailwindlabs/headlessui#304]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

0.3.2

### What browser are you using?

Chrome

### Reproduction repository

https://www.youtube.com/watch?v=3O_3X7InOw8

When using a Dropdown button transition into a flyout menu the transition is hidden underneath an image until the animation is complete. I am using components from TailwindUI

Start of Transition
![underhero](https://user-images.githubusercontent.com/8144988/113617058-8b488080-961b-11eb-9a66-bbef297a5680.png)

End of Transition
![afteranimation](https://user-images.githubusercontent.com/8144988/113617108-9a2f3300-961b-11eb-893e-569d2e793755.png)

I have placed the z-index to `0` on the image and `40` on the flyout menu. There are no other index in the code

```
// hero image
<div className="mt-4 z-0">
        <main>
          {/* Hero section */}
          <div className="relative">
            <div className="absolute inset-x-0 bottom-0 h-1/2 bg-gray-100" />
            <div className="max-w-7xl mx-auto sm:px-6">
              <div className="relative shadow-xl sm:overflow-hidden">
                <div className="absolute inset-0 z-0">
                  <img className="h-full w-full object-cover z-0" src="/images/hero/warehouse.jpeg" alt="" />
                  <div className="z-0 absolute inset-0 bg-gradient-to-r from-primary-500 to-primary-800" style={{mixBlendMode: 'multiply'}} />
                </div>
...
```

```
// flyout menu
<Transition show={show} enter="transition ease-out duration-300" enterFrom="opacity-0 -translate-y-1" enterTo="opacity-100 translate-y-0" leave="transition ease-in duration-250" leaveFrom="opacity-100 translate-y-0" leaveTo="opacity-0 -translate-y-1">
      <div className="absolute z-40 left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-md sm:px-0">
        <div className="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
          <div className="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8">
...
```

**Comment by ludwig-pro** [comment]
hey ! 

there is a breaking change with transition API => https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v0.3.0

```js
// flyout menu fixed
<Transition 
   show={show} 
   enter="transition ease-out duration-300" 
   enterFrom="opacity-0 -translate-y-1" 
   enterTo="opacity-100 translate-y-0" 
   leave="transition ease-in duration-250" 
   leaveFrom="opacity-100 translate-y-0" 
   leaveTo="opacity-0 -translate-y-1"
   className="absolute z-40 left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-md sm:px-0"
>
        <div className="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
          <div className="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8">
...
```

**Comment by kpaquino2** [comment]
Hey! I also encountered this issue, what worked for me was removing the containing div inside the Transition and moving the classes of that div to the transition.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As @ludwig-pro mentioned, make sure to follow the upgrade guide in the release.
You can also try to follow the suggestion provided by @kpaquino2 

If this is still relevant and still not working, please create a new issue with a minimal reproduction repo attached so that we can take a look 👍
