### ISSUE TITLE
[DOCS]: Website isn't active

### ISSUE THREAD

**Issue by wisdomose** [tailwindlabs/headlessui#3060]
<img width="960" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/35114555/9b8a0786-412e-45fc-a9d7-5c9cb34c6860">

**Comment by RobinMalfait** [comment]
Hey!

Can you try again or switch browsers?
Can't seem to reproduce this here.

**Comment by wisdomose** [comment]
I have tried across Mutiple devices and browsers, but it doesn't load.
