### ISSUE TITLE
Input doesn't capture `aria-invalid` prop to set the invalid state

### ISSUE THREAD

**Issue by depsimon** [tailwindlabs/headlessui#3090]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v2.0.0-alpha.4

**What browser are you using?**

For example: N/A

**Reproduction URL**

[CodeSandBox](https://codesandbox.io/p/devbox/github/tailwindlabs/reproduction-headlessui-react/tree/main/?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluto0doj00073b6gakzysyz0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluto0doj00023b6gw09x1l19%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluto0doj00043b6ge6grx1cj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluto0doj00063b6ghrs2xqcy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluto0doj00023b6gw09x1l19%2522%253A%257B%2522id%2522%253A%2522cluto0doj00023b6gw09x1l19%2522%252C%2522activeTabId%2522%253A%2522cluto33xh00ee3b6g5fqt0na4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cluto33xh00ee3b6g5fqt0na4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cluto0doj00063b6ghrs2xqcy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluto0doj00053b6gthg0svj6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluto0doj00063b6ghrs2xqcy%2522%252C%2522activeTabId%2522%253A%2522cluto0doj00053b6gthg0svj6%2522%257D%252C%2522cluto0doj00043b6ge6grx1cj%2522%253A%257B%2522id%2522%253A%2522cluto0doj00043b6ge6grx1cj%2522%252C%2522activeTabId%2522%253A%2522cluto6dzp01183b6gnp1ibitj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluto5ggt00un3b6gnm41e3e0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluto5gil008ediiqdeug9hz7%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cluto6dzp01183b6gnp1ibitj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

When declaring the input's invalid state through an `aria-invalid` prop instead of the good old `invalid` prop, the Headless Input doesn't set the state to `invalid`.

I am using Conform as a form library, and by default they expose the `aria-invalid` and not the `invalid` props when requesting the input props.

It'd be great if the Headless Input could hook into that aria-invalid prop as well to handle it's invalid state. Is this something you would consider?

**Comment by RobinMalfait** [comment]
Hey!

The CodeSandbox you linked points to the default reproduction URL and not your reproduction. That said, I would recommend to set the `invalid` prop yourself in addition to the `aria-invalid` prop. 

I think setting the `invalid` prop automatically based on `aria-invalid` is a bit too magic. Because if you _don't_ want this behavior, then there is no way to undo this and only set the `aria-invalid` prop. I think it's safer to not do it automatically.

You could also argue that this behaviour should be extended to other properties, for example if you pass `aria-disabled`, that we also set the `disabled` prop. But in that scenario the component will become less accessible because a button with `disabled` can't receive focus.

Hope this makes sense!

**Comment by depsimon** [comment]
Hi!

Indeed I messed up with the Sandbox link, sorry ^^ But I see you got my point!

The reasoning makes sense, I'll add this behavior on my Input component that wraps the Headless Input.
