### ISSUE TITLE
Listbox.Option not changed when Listbox.Options is static

### ISSUE THREAD

**Issue by mohammadhosseinmoradi** [tailwindlabs/headlessui#3098]
**Describe your issue**

Listbox.Option not changed when Listbox.Options is static must be change Listbox.Options key to reflect changes.

**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v2.0.0-alpha.4

**What browser are you using?**

Chrome

**Comment by RobinMalfait** [comment]
Hey!

Can you share a reproduction repo that contains the bug? 

You rarely need the `static` prop so I also wonder what your use case is.

**Comment by RobinMalfait** [comment]
Hey!

So the `static` prop means that the component itself will always be rendered, but that doesn't mean that the state is `open` or `active` yet. The `static` prop should only be used if you want to control the rendering, for example when using transitions using Framer motion.

Going to close this one for now, if you are still running into this issue please open a new issue with a minimal reproduction repo attached.
