### ISSUE TITLE
vue.defineComponent is not a function 

### ISSUE THREAD

**Issue by vmiguellima** [tailwindlabs/headlessui#31]
I tried to use headless ui on nuxtjs and this error is returned `vue.defineComponent is not a function `.

More Details:

*node_modules/@headlessui/vue/dist/headlessui.cjs.development.js*
```js
  }

  return context;
}

var Menu = /*#__PURE__*/vue.defineComponent({
  props: {
    as: {
      type: [Object, String],
      "default": 'template'
    }
```

**Comment by RobinMalfait** [comment]
This library is created for Vue 3. I am not sure that NuxtJS is using Vue 3, I think they are using Vue 2. Can you verify this?

**Comment by adamwathan** [comment]
Yep Nuxt hasn’t released a version on Vue 3 yet but as far as I understand a beta is coming in the near future 👍🏻
