### ISSUE TITLE
[insiders] Error when using `Transition` with an anchored, non-modal `Listbox.Options` inside a `Dialog`

### ISSUE THREAD

**Issue by benface** [tailwindlabs/headlessui#3113]
This is the sequel to #3107 – thanks again for fixing it so quickly. 🫶

**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

0.0.0-insiders.dcbcd79

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/amazing-glitter-forked-cprxyp?file=%2Fsrc%2FApp.tsx

**Describe your issue**

Click on "Open dialog" and then click on "Option 1". This error appears:

> Did you forget to passthrough the `ref` to the actual DOM node?

Notice that the issue does NOT happen if you:
- remove the `anchor` or `modal` props from `Listbox.Options`
- don't wrap the `Listbox.Options` in a `Transition`
- don't wrap the `Listbox` in a `Dialog`

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3124, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
