### ISSUE TITLE
[DOCS]: Add information about the `immediate` property on Combobox

### ISSUE THREAD

**Issue by Riley19280** [tailwindlabs/headlessui#3134]
The `Combobox` component accepts an `immediate` property to display the options as soon as it is focused, however this is not mentioned in the docs. I am running an alpha build of Headless UI with the Catalyst components, so it may just be that its a newer feature. Happy to PR the docs update as well, but i'm not seeing where those are hosted.

**Comment by RobinMalfait** [comment]
Hey!

The `immediate` prop is currently not released in a stable release yet, and we also don't have documentation for alpha releases (because a lot can change in the meantime).

Once we release Headless UI v2 we will publish the new docs accordingly 👍
