### ISSUE TITLE
v2 release breaks catalyst dropdown.tsx

### ISSUE THREAD

**Issue by jlarmstrongiv** [tailwindlabs/headlessui#3174]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v2.0.0

**What browser are you using?**

For example: N/A

**Describe your issue**

```
Property 'to' does not exist on type 'NonNullable<AnchorProps | undefined>'.
```

on line

```ts
export function DropdownMenu({
  anchor = 'bottom',
  ...props
}: { anchor?: NonNullable<HeadlessMenuItemsProps['anchor']>['to'] } & Omit<HeadlessMenuItemsProps, 'anchor'>) {
```

Please note I just downloaded the latest version of catalyst, so it’s not due to an outdated component.

**Comment by jlarmstrongiv** [comment]
You are trying to access `to` on this type specifically:

```ts
export type AnchorProps = false | (`${Placement}` | `${Placement} ${Align}`) | Partial<BaseAnchorProps & {
    /**
     * The `to` value defines which side of the trigger the panel should be placed on and its
     * alignment.
     */
    to: `${Placement}` | `${Placement} ${Align}`;
}>;
```

**Comment by jlarmstrongiv** [comment]
One solution is to use this instead:
```ts
export function DropdownMenu({
  anchor = 'bottom',
  ...props
}: { anchor?: Exclude<NonNullable<HeadlessMenuItemsProps['anchor']>, false | string>["to"] } & Omit<HeadlessMenuItemsProps, 'anchor'>) {
```

**Comment by thecrypticace** [comment]
Hey! Thanks for pointing this out. We'd prepped the necessary changes for the stable release of v2.0 but forgot to publish them. We've been super busy hacking away on Headless UI v2 and Catalyst and this update fell through the cracks when we published Headless UI v2 this morning.

I've pushed the updates to the documentation, the downloaded zip file, and the template details page on Tailwind UI. You can download the updated version on Tailwind UI now 👍
