### ISSUE TITLE
[DOCS]: `DialogPanel` and `DialogTitle` tagged as deprecated

### ISSUE THREAD

**Issue by gustavoteodoro** [tailwindlabs/headlessui#3175]
Hey folks.

First of all, thanks a lot for the version 2. That's a huge and exciting upgrade!! 🎉 

I found that the new `DialogPanel` and `DialogTitle` are currently _(on v2.0.0)_ wrongly tagged as `@deprecated`. I've investigated it and I notice that in a [recent PR removing](https://github.com/tailwindlabs/headlessui/pull/3171) `DialogBackdrop` and `DialogOverlay` the  [deprecated comments](https://github.com/tailwindlabs/headlessui/pull/3171/files#diff-887b16418d08f2a0244dbe2c80593ed1c359205992256b024534f4345be79397R539) were left behind, affecting `DialogPanel` and `DialogTitle`.

I've created a branch resolving this but I don't have access to push it. Can I have access to do it, please?

Thanks a lot!

**Comment by thecrypticace** [comment]
🤦‍♂️ patch release incoming…

**Comment by thecrypticace** [comment]
v2.0.1 is out

**Comment by tchanxx** [comment]
I'm still seeing `DialogBackdrop` and `DialogPanel` in the docs? https://headlessui.com/react/dialog#dialog-backdrop

**Comment by RobinMalfait** [comment]
Hey @tchanxx, we re-introduced it in [v2.0.1](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.1.0), which is useful in combination with the new `transition` prop. See: https://headlessui.com/react/dialog#adding-transitions
