### ISSUE TITLE
Issue after upgrading healdessui to latest version in a react17 project: Uncaught TypeError: (0 , import_react45.useId 

### ISSUE THREAD

**Issue by crissadriana** [tailwindlabs/headlessui#3185]
**What package within Headless UI are you using?**
@headlessui/react v2.0.3

**What version of that package are you using?**
v2.0.3

**What browser are you using?**
Chrome / Safari / FF

**Reproduction URL**
N/A

**Describe your issue**

We've got a project using react 17 currently and we've just upgraded to the v2.0.3 of react headlessui, but we keep getting this error: `Uncaught TypeError: (0 , import_react45.useId `

Are there any requirements in order to upgrade to this version?

**Comment by thecrypticace** [comment]
Hi! Headless UI v2 now **requires React 18** as we're making use of some React 18+ features now. You can see this in our peer dependencies here:
https://github.com/tailwindlabs/headlessui/blob/031b39d52259c81b9906d86ec7118755da6ef916/packages/%40headlessui-react/package.json#L44-L47

You should've seen warnings from NPM when you installed it into a React 17 project. So, if you want to use Headless UI v2 you will need to upgrade your project first.

**Comment by cjoderati** [comment]
I have this same issue but i'm already on React 18...

```
    "react": "^18.2.0",
    "react-color": "^2.19.3",
    "react-dom": "^18.2.0",
```

```
@headlessui_react.js?v=657b1b39:6175 Uncaught TypeError: (0 , import_react45.useId) is not a function
```
