### ISSUE TITLE
Combobox scroll jitter when scrolling long list after an option is selected

### ISSUE THREAD

**Issue by josh3io** [tailwindlabs/headlessui#3189]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v2

**What browser are you using?**

Windows 11 
Google Chrome Version 124.0.6367.119 (Official Build) (64-bit)

**Reproduction URL**

https://tailwindcss.com/blog/headless-ui-v2?utm_source=tldrnewsletter

**Describe your issue**

In the demo, after selecting a user in the "combobox list virtualization" section, there is jitter when trying to scroll the list. With no user selected it scrolls cleanly as expected. See screen recording.

https://github.com/tailwindlabs/headlessui/assets/8906082/439e86b5-c967-450e-af20-18a816eb64ac

**Comment by RobinMalfait** [comment]
This should be fixed by #3190, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
