### ISSUE TITLE
Dropdown components are missing prop "modal"

### ISSUE THREAD

**Issue by areriklq** [tailwindlabs/headlessui#3192]
**What package within Headless UI are you using?**

 @headlessui/react

**What version of that package are you using?**

@headlessui/react 2.0.3

**What browser are you using?**

Edge/Chromium

**Reproduction URL**

N/A

**Describe your issue**
Release notes for 2.x says:
```
Dropdown components are now modal by default
The Menu, Combobox, and Listbox dropdowns are now rendered modal by default. When the dropdown is open the page is scroll-locked and all other page content is made inert.

While this is generally recommended behavior for these components, you can disable this using the modal prop:

- <Combobox ...>
+ <Combobox modal={false} ...>
```

However, I am unable to find the modal prop on the `Listbox` component:
![image](https://github.com/tailwindlabs/headlessui/assets/156663890/e6713bf9-8672-497e-a05a-b3f4b590a99f)

Am I doing something wrong or is this a defect?

(The changed behavior is causing regressions for me as users now need to click twice to toggle a control after they have opened a multi-select Listbox.)

**Comment by areriklq** [comment]
I found the prop now, but on `ListboxOptions` . I did not expect that given the release documentation.

**Comment by RobinMalfait** [comment]
Hey!

That was a mistake on our end, I've updated the release notes. You can also find the available props in the API documentation on the docs website. https://headlessui.com/react/listbox#listbox-options

Sorry about that, and hope it helps!
