### ISSUE TITLE
[DOCS]: ListboxOptions change from v1.7 to v2.0 is missing active

### ISSUE THREAD

**Issue by leonatajeff** [tailwindlabs/headlessui#3198]
I see active is deprecated and `focus` is being used but I wasn't able to see this change as easily as the rest with the v2 release.

Also active is considered as focus**ed**/active. Maybe, using `focused` instead of `focus` might be more clear?

**Comment by reinink** [comment]
Hey! You're right, we forgot to mention this change in our changelog and in our upgrade guide.

I've updated the changelog to include this and added a section to the [upgrade guide](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0#user-content-upgrading-from-v1):

<kbd><img width="718" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/882133/596463c2-b3ae-4f5c-a661-1834289d1611"></kbd>

As for the `focus` prop name, I think we're going to leave that as is for now, but I appreciate the feedback either way 👍
