### ISSUE TITLE
Standard web or Svelte framework support ?

### ISSUE THREAD

**Issue by Peyman-Borhani** [tailwindlabs/headlessui#32]
Hello,
I just saw react and vue frameworks guide in the site, which I prefer not too use.
I wonder if either standard web, web-components or Svelte framework,  are supported ?

Thanks.

**Comment by adamwathan** [comment]
Right now just React and Vue, but we would like to explore other frameworks eventually. Just a lot of work to build a library like this for even one framework, have to start somewhere!

Closing as not an open bug or anything but is something we plan to R&D down the road.

**Comment by trevyn** [comment]
Q: is there shared architecture now between the React and Vue components?

Q2: Would you be open to community work and pull requests on Svelte or vanilla-JS implementations?

(meta: I think it’s a better practice to leave issues like this open to encourage future discussion, only closing when they become implemented or wont-fix. You can use tags and filtering on GitHub to keep the issues list “clean” for everyday work.)

**Comment by RobinMalfait** [comment]
@trevyn If you have specific questions or issues, please open a new issue. However, here are my answers:

Q1: No, we prefer to build the components we require first before we even try to abstract into some shared architecture. There are a lot of similarities already some parts are duplicated, but not shared. I believe in duplication over early abstractions.

Q2: No, not at this moment. We are focusing on React and Vue. This allows us to create components with a certain API. Supporting only a small set of frameworks allows us to move way more quickly especially when we have certain bugs (that have to be applied to all supported frameworks) or if we want to change the API in some way shape or form. This makes everything in the beginning much simpler and easier to move forward. While community work is appreciated in form of bug fixes, reproduction cases with failing tests, typo's... community work for new components / frameworks won't be accepted at this moment.

Q3: Thanks, but we like to manage the project in a way that we like and works for us, therefore this issue will remain closed. I hope you understand.

**Comment by benmccann** [comment]
Someone from the Svelte community created an implementation here: https://github.com/rgossiaux/svelte-headlessui

The most highly upvoted issue of all time in this repo is one requesting Svelte support: https://github.com/tailwindlabs/headlessui/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+

I hope that given the demand for Svelte support that you may reconsider at some point and allow a PR to make these components an official part of this repo. In the meantime, perhaps you could link to community importations for Svelte, etc. from the docs to help discoverability?

**Comment by rohanrajpal** [comment]
> Someone from the Svelte community created an implementation here: https://github.com/rgossiaux/svelte-headlessui
> 
> The most highly upvoted issue of all time in this repo is one requesting Svelte support: https://github.com/tailwindlabs/headlessui/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+
> 
> I hope that given the demand for Svelte support that you may reconsider at some point and allow a PR to make these components an official part of this repo. In the meantime, perhaps you could link to community importations for Svelte, etc. from the docs to help discoverability?

+1 
Official svelte support would be very much appreciated! This is an amazing library and svelte support would allow us to prototype faster.
