### ISSUE TITLE
[DOCS]: Fieldset/Select example styling is off (Chrome)

### ISSUE THREAD

**Issue by tseidler** [tailwindlabs/headlessui#3200]
The options for the selects aren't visible in my **Chrome** browser. It *works fine* in FireFox though..

https://headlessui.com/react/fieldset
https://headlessui.com/react/select

![image](https://github.com/tailwindlabs/headlessui/assets/5659459/60461149-4343-4194-bdc3-ad6718d643fc)

![image](https://github.com/tailwindlabs/headlessui/assets/5659459/7641d1a1-91de-4c28-81aa-efb2cfb5a252)

### Firefox:
![image](https://github.com/tailwindlabs/headlessui/assets/5659459/0ed1a56e-73d7-47fd-9aaa-c5ac5c1409c3)

**Comment by RobinMalfait** [comment]
Hey!

Thanks this should be fixed and will be live shortly. Turns out that adding `color: white` on the `<select>` also applies the `color: white` to the `<option>` elements but only on Windows.
