### ISSUE TITLE
Combobox's `onChange` also fires on no change

### ISSUE THREAD

**Issue by matijs** [tailwindlabs/headlessui#3202]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.0.3

**What browser are you using?**

Safari, Firefox

**Describe your issue**

Acoording to the [docs](https://headlessui.com/react/combobox#combobox), the `onChange` prop of a `Combobox`…
>  …is called when a *new* option is selected’ (emphasis mine).

If a user clicks outside the Combobox without having selected an option, or when the user selects the same option that was already selected, the `onChange` handler also fires.
It's easy enough to work around, but it feels like the handler should only fire on an actual change :)

**Comment by RobinMalfait** [comment]
Hey!

That should definitely not be the case, my guess is that you are defining an array of objects _inside_ your render function and therefore each option is going to be a new instance of the object every time the component rerenders.

Can you share a minimal reproduction repo?

**Comment by RobinMalfait** [comment]
Hey! Going to close this one since we haven't heard back, but feel free to reopen a new issue if you're able to provide a minimal reproduction of this 👍

**Comment by matijs** [comment]
@RobinMalfait ah, will do, I had not found the time just yet. Your guess kind of helped in that indeed each option is a new instance (we use Combobox as a autosuggest) and that would explain firing `onChange`. However, with a fixed array defined outside of the render function reselecting an already selected option does seem to fire an undesired `onChange`.
