### ISSUE TITLE
[DOCS]: PopoverPanel `modal` incorrectly says default=true and makes others inert

### ISSUE THREAD

**Issue by david-crespo** [tailwindlabs/headlessui#3223]
This bit of the docs appears to be incorrect. 

https://headlessui.com/react/popover

<img width="738" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/3612203/0958fe08-4ee5-4b00-a759-43be1ac44c9e">

Based on the description of https://github.com/tailwindlabs/headlessui/pull/3124 both of the following are intentional, so the fix would be to the docs rather than the code.

### `modal` defaults to false

https://github.com/tailwindlabs/headlessui/blob/045f2bc761be3d30ef203ccb3da2c0292c8a5397/packages/%40headlessui-react/src/components/popover/popover.tsx#L815

### `PopoverPanel` does not call `useOthersInert`

https://github.com/tailwindlabs/headlessui/blob/045f2bc761be3d30ef203ccb3da2c0292c8a5397/packages/%40headlessui-react/src/components/popover/popover.tsx#L857-L861

**Comment by RobinMalfait** [comment]
Good catch!

You are right that the `Popover` component doesn't set the `inert` attribute on other elements. We've updated the docs accordingly. Thanks

**Comment by david-crespo** [comment]
Thanks! I don’t want to be pedantic, but it still says `modal` defaults to true and I don’t think it does.

**Comment by vincerubinetti** [comment]
The docs currently say:

> Whether to enable accessibility features like scroll locking and focus trapping.

Looking at the code, it only does scroll locking. It doesn't make anything inert. It doesn't prevent interaction outside the popover. And it definitely doesn't focus trap; you can tab out of the popover to close it.

Calling this option `modal` is very misleading. It doesn't do what is expected, or even what the HUI Dialog component does.
