### ISSUE TITLE
Unable to click scrollbar of combobox options when being displayed inside a Dialog 

### ISSUE THREAD

**Issue by isaacpresidium** [tailwindlabs/headlessui#3230]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v2.0.1

**What browser are you using?**

Chrome

**Reproduction URL**

[Here is a codesandbox link](https://codesandbox.io/p/devbox/happy-fog-3crmms), click the button to open a modal and when you type in the box you will see a list appear. 

**Describe your issue**

You can scroll the list with the scroll wheel, but you cannot click the scrollbar with your left mouse button. This only happens when the combobox is displayed within a Dialog, but is there any way to prevent it? Am I doing something wrong?

**Comment by RobinMalfait** [comment]
Hey!

The linked CodeSandbox link points to the default template, can you update the CodeSandbox to make sure the reproduction is available?

**Comment by isaacpresidium** [comment]
> Hey!
> 
> The linked CodeSandbox link points to the default template, can you update the CodeSandbox to make sure the reproduction is available?

Updated the link: https://codesandbox.io/p/devbox/happy-fog-3crmms

**Comment by isaacpresidium** [comment]
@RobinMalfait hey, can I get the label for this ticket changed at least? I provided more info, with a working link, as requested

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3249, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
