### ISSUE TITLE
Popover panel incorrectly closes when user tabs with keyboard

### ISSUE THREAD

**Issue by joshcairney** [tailwindlabs/headlessui#3231]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
2.0.3

**What browser are you using?**
Chrome, Firefox, Safari on macOS

**Reproduction URL**
https://headlessui.com/react/popover
or
https://codesandbox.io/p/devbox/busy-poitras-877jt5

**Describe your issue**
When a Popover is opened, a user should be allowed to interact via Tab on their keyboard to cycle through the open panel's contents. Currently, the Popover panel will close in this scenario. The issue is even present in the official demo.

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3239, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
