### ISSUE TITLE
Bump `@react-aria` versions to address missing source maps and console spam

### ISSUE THREAD

**Issue by short-dsb** [tailwindlabs/headlessui#3238]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

v2.0.3

**What browser are you using?**

N/A

**Reproduction URL**

See [adobe/react-spectrum#6355](https://github.com/adobe/react-spectrum/issues/6355).

**Describe your issue**

Currently, `@headlessui/react` relies on versions of `@react-aria/focus` and `@react-aria/interactions` that are missing source maps, resulting in console spam like the following:

```
WARNING in ./node_modules/@react-aria/interactions/dist/useInteractOutside.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/@react-aria/interactions/dist/useInteractOutside.mjs.map' file: Error: ENOENT: no such file or directory, open './node_modules/@react-aria/interactions/dist/useInteractOutside.mjs.map'
```

The missing source maps have been restored in the latest release of `@react-aria`. Can the dependencies of this project be updated to address this issue?

**Comment by abel-officener** [comment]
I too am experiencing the same problem.
It does not occur if you run it immediately after installing the module.
I confirmed that turning it off and running it again caused the problem.

**Comment by RobinMalfait** [comment]
Hey! You should be able to just run `npm update` because all the new versions of those packages are within the range specified in our package.json.

That said, we also bumped them anyway via #3247, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
