### ISSUE TITLE
Error closing Dialog when initial state is set with something other than `ref(true)`

### ISSUE THREAD

**Issue by bakerkretzmar** [tailwindlabs/headlessui#327]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

0.3.1-6fa6c45

### What browser are you using?

Firefox

### Reproduction repository

https://codesandbox.io/s/jovial-snowflake-p4s76?file=/src/Modal.vue

### Description

If the value passed in as the `open` prop of a `Dialog` is created with something other than literally `ref(true)` or `ref(false)`, updating it causes this error: `Set operation on key "open" failed: target is readonly.`.

E.g. I'm trying to create a generic `Modal` wrapper component to use in a few places, so I want `open` and `@close` available outside of the component using the `Dialog`. If I try to pass in `open` as a prop though, I can't seem to use it without that 'readonly' error.

Given this component:

```vue
<template>
  <Dialog as="template" :open="open" @close="onClose" static>
    <div>
      <DialogOverlay v-if="open" />

      <div v-if="open">
        <slot />
      </div>
    </div>
  </Dialog>
</template>

<script>
import { toRefs } from "vue";
import { Dialog, DialogOverlay } from "@headlessui/vue";

export default {
  components: { Dialog, DialogOverlay },
  props: { open: Boolean },
  emits: ["close"],
  setup(props, { emit }) {
    const { open } = toRefs(props);

    return {
      open,
      onClose(val) {
        open.value = val;
        emit("close");
      },
    };
  },
};
</script>
```

Changing the `open` prop works (can close the Dialog this way) but produces the error, but clicking outside the Dialog or pressing <kbd>Esc</kbd> produce the error and also don't actually work.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is not a bug with Headless UI, the issue is that you are mutating an incoming prop. 
Instead, add an `@close="modalOpen = false"` to your `Modal` component. 
Also drop the `open.value = value` inside the Modal component, just rely on the `emit('close')` event.

Here is an example: https://codesandbox.io/s/optimistic-driscoll-ou1sb

**Comment by bakerkretzmar** [comment]
Thanks! The Toggle button in that example doesn't work though, it can't close the Dialog. `modalOpen.value` in the Modal component is always `false`, and clicking the Toggle button always sets it to `true`.

Was the issue that my state variable and prop were both called `open`? I previously tried renaming it to `isOpen` like in your example and got the same error.

**Comment by bakerkretzmar** [comment]
Ah never mind, the Toggle button issue is because it's also 'outside' of the Dialog, so clicking it closes the Dialog and then immediately reopens it.

I'm still confused about the prop name--this example produces the original error too, `Set operation on key "open" failed`:

```vue
<template>
  <Dialog as="template" :open="isOpen" @close="onClose" static>
    <div>
      <DialogOverlay v-if="isOpen" />

      <div v-if="isOpen">
        <slot />
      </div>
    </div>
  </Dialog>
</template>

<script>
import { toRefs } from "vue";
import { Dialog, DialogOverlay } from "@headlessui/vue";

export default {
  components: { Dialog, DialogOverlay },
  props: { open: Boolean },
  emits: ["close"],
  setup(props, { emit }) {
    const { open: isOpen } = toRefs(props);

    return {
      isOpen,
      onClose(val) {
        isOpen.value = val;
        emit("close");
      },
    };
  },
};
</script>
```

**Comment by RobinMalfait** [comment]
Yeah, it's not a Headless UI issue. It is just because you are mutating your props. Here is an example in pure Vue with a button and a count value:

https://codesandbox.io/s/elated-darkness-d6wcg?file=/src/components/HelloWorld.vue

**Comment by bakerkretzmar** [comment]
Ah okay I think I was confusing the behaviour of `toRef` and just `ref`. Thanks a lot!
