### ISSUE TITLE
__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED and React 19 RC

### ISSUE THREAD

**Issue by logemann** [tailwindlabs/headlessui#3275]
upon trying to build my Next 15 RC (React 19) with headlessUI, i am getting the following build errors.

```
./node_modules/@headlessui/react/dist/utils/stable-collection.js
Attempted import error: '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED' is not exported from 'react' (imported as 'r').

Import trace for requested module:
./node_modules/@headlessui/react/dist/utils/stable-collection.js
./node_modules/@headlessui/react/dist/components/tabs/tabs.js
```

**What package within Headless UI are you using?**

`    "@headlessui/react": "2.0.4",`

**What browser are you using?**

Chrome latest.

**Reproduction URL**

no public github repo available. 

**Describe your issue**

getting the outlines problem on building.

**Comment by logemann** [comment]
Oh. This is a duplicate. closing

**Comment by RookTKO** [comment]
WILL IT KIL YOU PPL TO LINK TO THE ORIGINAL! lmao

**Comment by XavierGeerinck** [comment]
https://github.com/tailwindlabs/headlessui/issues/3167
