### ISSUE TITLE
Typescript error with <Listbox>. 

### ISSUE THREAD

**Issue by tjshipe** [tailwindlabs/headlessui#330]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.3.2

### What browser are you using?

Chrome

### Issue

The following error shows up with @headlessui/react with Typescript v4.1.3 in a Next.js (v10) app that is also using Emotion. I found a similar issue #233 but neither of the solutions proposed worked for me. I'll update this if I find a work around.

`Expression produces a union type that is too complex to represent. `

![Screen Shot 2021-04-13 at 11 05 33 AM](https://user-images.githubusercontent.com/1254942/114576401-1a235180-9c49-11eb-9a95-0399d31fd03c.png)

**Comment by tjshipe** [comment]
Ok so removing this line from tsconfig.json fixed it for me:
```"jsxImportSource": "@emotion/react",```
The other issue #233 mentioned this but I needed to restart VS Code after removing that line.

**Comment by AnandChowdhary** [comment]
Unfortunately, even after removing this, I see this this error. Any other tips?

**Comment by tjshipe** [comment]
@AnandChowdhary Where are you seeing the error?

**Comment by AnandChowdhary** [comment]
Both in VS Code and in my CI process when running `build`.

**Comment by tjshipe** [comment]
Can you post your tsconfig?

**Comment by AnandChowdhary** [comment]
Sure!

<details><summary>`tsconfig.json`</summary>
<p>

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"],
      "@/lib/*": ["src/lib/*"],
      "@/config/*": ["src/config/*"],
      "@/types/*": ["src/@types/*"],
      "@/hooks/*": ["src/hooks/*"]
    }
  },
  "files": ["src/@types/twin.d.ts", "src/@types/next-pwa.d.ts"],
  "exclude": ["node_modules", ".next", "out"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.js"]
}
```

</p>
</details> 

<details><summary>Error message in CI</summary>
<p>

```
./src/components/Proposal/DurationSelector.tsx:20:9
Type error: Expression produces a union type that is too complex to represent.

  18 |     </p><div tw="relative w-full">
  19 |       <Listbox value="{value}" onchange="{onChange}">
&gt; 20 |         <Listbox.button tw="relative w-full py-2 pl-3 pr-10 text-left bg-white rounded-lg shadow cursor-default focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75 focus-visible:ring-white focus-visible:ring-offset-indigo-300 focus-visible:ring-offset-2 focus-visible:border-indigo-500 border">
     |         ^
  21 |           <span tw="block truncate">{Number(value) / 12} years</span>
```

<p></details>
