### ISSUE TITLE
React Popover v2: warnings when used inside `p`-element

### ISSUE THREAD

**Issue by jmyrland** [tailwindlabs/headlessui#3319]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.0

**What browser are you using?**

Chrome

**Reproduction URL**

See the [sandbox](
https://codesandbox.io/p/devbox/headless-popover-v2-forked-np9frt?workspaceId=d19bb18f-8ddc-4ef7-98a7-7c36159678d2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxsv2gx10009356l3xcts0ha%2522%252C%2522sizes%2522%253A%255B69.00414937759336%252C30.995850622406635%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxsv2gx10003356lh70wadks%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxsv2gx10006356l3oep5va8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxsv2gx10008356l0zh229wn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxsv2gx10003356lh70wadks%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxsv2gx10002356la0ni886o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A51%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A51%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxsv2gx10003356lh70wadks%2522%252C%2522activeTabId%2522%253A%2522clxsv2gx10002356la0ni886o%2522%257D%252C%2522clxsv2gx10008356l0zh229wn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxsv2gx10007356lax8in0zb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxsv2gx10008356l0zh229wn%2522%252C%2522activeTabId%2522%253A%2522clxsv2gx10007356lax8in0zb%2522%257D%252C%2522clxsv2gx10006356l3oep5va8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxsv2gx10004356lg7iiu8ef%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clxsv2gx10005356lc4ky1sgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522format%2522%257D%255D%252C%2522id%2522%253A%2522clxsv2gx10006356l3oep5va8%2522%252C%2522activeTabId%2522%253A%2522clxsv2gx10004356lg7iiu8ef%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

When using `Popover` nested inside a `p`-element, the following warning is logged in the console:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

As you can see in the sandbox, all of the popover components use `as="span"`, but there is an empty `div` rendered within the `Popover` causing this issue:
![image](https://github.com/tailwindlabs/headlessui/assets/837651/ea40e63e-54cf-4512-abdd-5ec3bc2642b3)

Is this empty `div`-element critical for the popover to work, or is there a way to opt out from this element?

**Comment by RobinMalfait** [comment]
This should be fixed by #3362, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
