### ISSUE TITLE
`ComboboxOptions` render prop `option` has unknown type

### ISSUE THREAD

**Issue by jussirantala** [tailwindlabs/headlessui#3326]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v2.1.0

**Describe your issue**

When using the render prop of `ComboboxOptions` for a virtualized list, the `option` property has unknown type.

<img width="638" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/5900968/088dc70b-5656-4cbe-8125-aaf9cb7f12ad">

**Comment by thecrypticace** [comment]
Hey! So this is a [known limitation of TypeScript](https://github.com/microsoft/TypeScript/issues/21699) in how it interprets JSX. Children in JSX/TSX can't be "typesafe" and as a result are not able to infer their types, props, etc… based on the parent component.

Matt Pocock has [an article about this topic](https://www.totaltypescript.com/type-safe-children-in-react-and-typescript) that details some of the problems. But the gist is that we'd need to find a way to design the types such that the "children" of Combobox are only of a certain type — this would then allow us to infer the props type. Sadly this is just not possible today.

This is why the type in the render prop is typed as `unknown` — to push people to type it themselves. I'd suggest typing it explicitly like this:

```tsx
<HeadlessComboboxOptions>
  {({ option } : { option: MyOptionType }) => (
    <HeadlessComboboxOption>…</HeadlessComboboxOption>
  )}
</HeadlessComboboxOptions>
```

Hope that helps 👍

**Comment by jussirantala** [comment]
@thecrypticace I actually tried to type it myself but I get this:
<img width="756" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/5900968/22849418-0f21-4bd3-a335-fb3f95536f50">

**Comment by jussirantala** [comment]
If the type was `any` instead of `unknown`, I think it would work.

**Comment by thecrypticace** [comment]
I swear worked at one point but yeah aliasing to a different type does not in function argument position. Will get a fixed merged in for that.
