### ISSUE TITLE
`Transition` does not respect responsive `display` styles from the parent element

### ISSUE THREAD

**Issue by anniegiang-octave** [tailwindlabs/headlessui#3328]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.0.4

**What browser are you using?**
Chrome Version 126.0.6478.114 (Official Build) (arm64)

**Reproduction URL**
https://kw6kvd-3000.csb.app/

[Sandbox](https://codesandbox.io/p/devbox/gifted-ace-kw6kvd?file=%2Fmy-app%2Fsrc%2Fapp%2Fpage.tsx%3A12%2C17&workspaceId=a76e4b8c-2295-410c-868c-fcbb28d4db1c&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxtnniyv00073b6j63ksk5v3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxtnniyv00023b6jd6130n51%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxtnniyv00043b6j12ri75w4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxtnniyv00063b6jgs3sbrt6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.04597370878528%252C59.95402629121472%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxtnniyv00023b6jd6130n51%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxtnniyu00013b6jxv8yw0il%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxtnpxj4004f3b6j807xmgzm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxum1qe000023b6jqaa5q6t8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxunyxv600023b6j3hrv6ggn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fmy-app%252Fsrc%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxtnniyv00023b6jd6130n51%2522%252C%2522activeTabId%2522%253A%2522clxunyxv600023b6j3hrv6ggn%2522%257D%252C%2522clxtnniyv00063b6jgs3sbrt6%2522%253A%257B%2522id%2522%253A%2522clxtnniyv00063b6jgs3sbrt6%2522%252C%2522activeTabId%2522%253A%2522clxum928500c43b6jb61ljrn2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxum928500c43b6jb61ljrn2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxtnniyv00043b6j12ri75w4%2522%253A%257B%2522id%2522%253A%2522clxtnniyv00043b6j12ri75w4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxum27tq004j3b6jklyowny5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxum27yd0151diiqaxv6ewoc%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxum27tq004j3b6jklyowny5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

1. Open the reproduction URL above. You should see two texts that have colored backgrounds. Only the red one is rendered inside of a Transition.
2. In Chrome, open the inspector and toggle the device toolbar. Set the dimensions to be responsive.
3. Decrease the screen width until you know longer see both texts.
4. Increase the screen width until you see the yellow one.

Expected behavior:
In step 4, the red one should also appear at breakpoints greater than `md` as specified in the parent `div` but it doesn't appear.

It's worth noting that this issue does not happen with the React + Tailwind boilerplate sandbox and versions for the following packages:

"@headlessui/react": "2.0.4",
"react": "18.3.1",
"react-dom": "18.3.1"

https://n5lf4f-5173.csb.app/

[Sandbox](https://codesandbox.io/p/devbox/elegant-hertz-n5lf4f?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxtnniyv00073b6j63ksk5v3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxtnniyv00023b6jd6130n51%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxtnniyv00043b6j12ri75w4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxtnniyv00063b6jgs3sbrt6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.66590043818691%252C39.33409956181309%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxtnniyv00023b6jd6130n51%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxtnniyu00013b6jxv8yw0il%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxtnpxj4004f3b6j807xmgzm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxum1qe000023b6jqaa5q6t8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxtnniyv00023b6jd6130n51%2522%252C%2522activeTabId%2522%253A%2522clxtnpxj4004f3b6j807xmgzm%2522%257D%252C%2522clxtnniyv00063b6jgs3sbrt6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxtnniyv00053b6jd7f04jcz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxtnniyv00063b6jgs3sbrt6%2522%252C%2522activeTabId%2522%253A%2522clxtnniyv00053b6jd7f04jcz%2522%257D%252C%2522clxtnniyv00043b6j12ri75w4%2522%253A%257B%2522id%2522%253A%2522clxtnniyv00043b6j12ri75w4%2522%252C%2522activeTabId%2522%253A%2522clxuno75g002x3b6jpgbx7zih%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxtnniyv00033b6jxe4z9oqn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clxuno75g002x3b6jpgbx7zih%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxuno78w015mdiiqanli29nf%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by thecrypticace** [comment]
I get a "Devbox not found" error and "Unauthorized Preview" from your reproduction(s). Any chance you could update them?

**Comment by anniegiang-octave** [comment]
> Sandbox

@thecrypticace updated the sandbox links

**Comment by RobinMalfait** [comment]
This should be fixed by #3372, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
