### ISSUE TITLE
Popover using anchor prop in PopoverPanel hangs unit test

### ISSUE THREAD

**Issue by restrin-extensis** [tailwindlabs/headlessui#3339]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
2.1

Adding this unit test to popover.test.tsx reproduces the problem

```
describe('Popover', () => {
    it(
      'should open panel with anchor prop',
      suppressConsoleLogs(async () => {
        render(
          <Popover>
            <PopoverButton>Trigger</PopoverButton>
            <PopoverPanel anchor="bottom">Panel open</PopoverPanel>
          </Popover>
        )

        assertPopoverButton({
          state: PopoverState.InvisibleUnmounted,
          attributes: { id: 'headlessui-popover-button-1' },
        })
        assertPopoverPanel({ state: PopoverState.InvisibleUnmounted })

        await click(getPopoverButton())

        assertPopoverButton({
          state: PopoverState.Visible,
          attributes: { id: 'headlessui-popover-button-1' },
        })
        assertPopoverPanel({ state: PopoverState.Visible, textContent: 'Panel open' })
      })
    )
   
```

The problem seems to be within `useFixScrollingPixel` while setting the max height which resolves to NaN and this method is infinitely called.
<img width="580" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/46825740/74fd6174-7df2-4986-8ce5-9aabbac60124">

`maxHeight: "min(var(--anchor-max-height, 100vh), 0px)"`

**Comment by RobinMalfait** [comment]
Hey! First of all, thank you very much for the test that reproduces the issue, this was very helpful, as well as your initial debugging here!

This should be fixed by #3357, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
