### ISSUE TITLE
Combobox virtual feature randomly gives an error: Uncaught Error: Unexpected undefined at notUndefined at Virtualizer.getOffsetForIndex

### ISSUE THREAD

**Issue by JCMais** [tailwindlabs/headlessui#3353]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v2.1.1

**What browser are you using?**

Chrome, but does not matter

**Reproduction URL**

https://codesandbox.io/p/devbox/still-leftpad-xr4zpk?file=%2Fsrc%2FCombobox.jsx&embed=1

Steps to reproduce:
1. click the field
2. clear the input (type "a")
3. press enter
5. error happens

**Describe your issue**
I am randomly getting the error: `Error: Unexpected undefined` when the list is empty.

![image](https://github.com/tailwindlabs/headlessui/assets/1041647/dc68be50-4030-4bf1-b3b3-543ed24ff769)

I think one possible fix here is to bump the `@tanstack/react-virtual` package to the latest version and disable the virtualizer when the list is empty

This is related to this ticket https://github.com/TanStack/virtual/issues/696 and the related link PR: https://github.com/TanStack/virtual/pull/741

**Comment by RobinMalfait** [comment]
This should be fixed by #3356, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
