### ISSUE TITLE
PopoverPanel `focus` prop doesn't work when `transition` prop is set

### ISSUE THREAD

**Issue by oliwheeler** [tailwindlabs/headlessui#3358]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.1

**What browser are you using?**

Chrome

**Reproduction URL**

[Link to repro](https://codesandbox.io/p/devbox/relaxed-nobel-5v9htd?file=%2Fsrc%2FApp.jsx%3A13%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clri93n8k00073b6imtvbqns5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clri93n8j00023b6ig8djbr20%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clri93n8j00043b6iggasfjji%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clri93n8k00063b6iohcq5uts%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clri93n8j00023b6ig8djbr20%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clri93n8j00013b6i7nld8ejr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clri99ffq001z3b6js0cuioub%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clri93n8j00023b6ig8djbr20%2522%252C%2522activeTabId%2522%253A%2522clri99ffq001z3b6js0cuioub%2522%257D%252C%2522clri93n8k00063b6iohcq5uts%2522%253A%257B%2522id%2522%253A%2522clri93n8k00063b6iohcq5uts%2522%252C%2522activeTabId%2522%253A%2522cly5u99ag00ft3b6jm2pse829%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cly5u99ag00ft3b6jm2pse829%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clri93n8j00043b6iggasfjji%2522%253A%257B%2522id%2522%253A%2522clri93n8j00043b6iggasfjji%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cly5u9qy000jv3b6jrv6x5bu8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cly5u9qy000jv3b6jrv6x5bu8%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

The `focus` prop on the `PopoverPanel` component doesn't focus on the panel when the transition prop is also set to true.

**Comment by RobinMalfait** [comment]
This should be fixed by #3361, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.

**Comment by oliwheeler** [comment]
Thank you!
