### ISSUE TITLE
Spacebar toggles React popover twice-ish

### ISSUE THREAD

**Issue by nathanheffley** [tailwindlabs/headlessui#338]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.3.1

### What browser are you using?

Firefox

### Reproduction repository

https://headlessui.dev/react/popover

I noticed this issue on the demo site, viewing the popover element and using the spacebar to toggle it works in Chrome for both Vue and React versions, but in Firefox the React version will flash on the screen and then disappear immediately as if it is being toggled twice. If I hold down the spacebar then it will flash quickly and I am sometimes lucky enough to get it to stay open. The Vue popover works fine in Firefox.

https://user-images.githubusercontent.com/8952123/114762130-60eb7700-9d2f-11eb-938a-bd92c74d7133.mov

**Comment by matt416** [comment]
The same issue occurs on the Disclosure component. React in Firefox 

https://user-images.githubusercontent.com/169192/114796683-8ee8af80-9d5f-11eb-98d4-e847b7c228af.mp4

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is fixed, (the docs were using an older version - oops). Can you verify that this is not happening anymore for you?

**Comment by nathanheffley** [comment]
@RobinMalfait yes both the popover and disclosure elements are working now for me, thanks!
