### ISSUE TITLE
Script to start react and vue

### ISSUE THREAD

**Issue by ThiagoFelippi** [tailwindlabs/headlessui#34]
## Script to start react and vue
I believe a script to start react and vue in Headless directory going to facility development 

### Example
```json
{
 "..."
  "scripts": {
     "react:start" : "yarn workspace @headlessui/react playground",
      "vue:start" : "yarn workspace @headlessui/vue playground",
    "..."
  }
}
```

If you believe that make sense I can do

**Comment by RobinMalfait** [comment]
Hey! Thank you for your contribution!
Much appreciated! 🙏

I don't think this is necessary, you can already run `yarn react playground` or `yarn vue playground`. I don't think `yarn react:start` or `yarn vue:start` will have a lot of benefits here.
