### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by yoeriboven** [tailwindlabs/headlessui#342]
I found some issues in the Headless UI docs. Not sure where to send them, so here they are.

- [Page1](https://headlessui.dev/vue/popover) [Page2](https://headlessui.dev/vue/listbox) [Page3](https://headlessui.dev/vue/menu) The code for the top example still uses the native vue `<transition>` instead of the new component added to Headless UI. Probably other code examples as well.
- [Page](https://headlessui.dev/vue/dialog#transitions) The docs keep mention the `Transition` component. The code however shows a `TransitionRoot` component. `Transition` should be changed to `TransitionRoot`. This issue is multiple times on this page. Possibly on the other pages as well.
- [Page](https://headlessui.dev/vue/dialog#styling-the-overlay) Mentions React instead of Vue. `...component accepts normal React props like class, ...`
- [Page](https://headlessui.dev/vue/popover#positioning-the-panel) There's still a `TODO` here.
- [Page](https://headlessui.dev/vue/menu#transitions) This part talks as if you should use the vue `<transition>`. Maybe I misunderstood but I think this should use the new `Transition` component?

**Comment by yoeriboven** [comment]
@RobinMalfait Sorry about the previous issue. I was still editing the text so it looked empty.

**Comment by samselikoff** [comment]
Thanks so much for this thorough issue!

Yes, the Vue Transition guides are a bit confusing atm but you are correct that we prefer Vue's built-in `<transition />` when it suffices.

You can find more information here: https://headlessui.dev/vue/transition#about-this-component

But, I think we can improve the clarity elsewhere in the docs 👍

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestions!
Much appreciated! 🙏

Those should all be taken care of!
