### ISSUE TITLE
Maximum update depth exceeded when using MenuButton with `as={Fragment}`

### ISSUE THREAD

**Issue by faebeee** [tailwindlabs/headlessui#3439]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.3

**What browser are you using?**

Any

[Minimal Repro Sandbox](https://codesandbox.io/p/sandbox/headlessui-menu-fragment-repro-23kyy2)

You can use one of the starting projects on CodeSandbox:

**Describe your issue**

When using the `MenuButton` with the `as={Fragment}` property, I end up with a "Maximum update depth exceeded" Error

**Comment by serafxxx** [comment]
same for ComboboxInput

**Comment by jcypret** [comment]
We're seeing this as well starting with @headlessui/react v2.1.4 and also in the latest version  v2.1.5:

<img width="952" alt="Screenshot 2024-09-04 at 7 14 33 PM" src="https://github.com/user-attachments/assets/24585b43-57b5-4994-96d9-90bc709cc75c">

Hitting the same error as @faebeee specifically related to `as={Fragment}` on `MenuButton`. If we drop the `as` or change it to something else like `as="div"`, it works.

<img width="505" alt="Screenshot 2024-09-04 at 7 16 50 PM" src="https://github.com/user-attachments/assets/d84d915a-87d0-477b-8438-554734137034">

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3478, and is available in the latest release (2.1.8).

You can already try it using:
- `npm install @headlessui/react@latest`.
