### ISSUE TITLE
Mutiple Portal Order breaks access to top Dialog

### ISSUE THREAD

**Issue by mschipperheyn** [tailwindlabs/headlessui#3443]
**What package within Headless UI are you using?**
@headlessui/react
remix run 2.11.2

**What version of that package are you using?**

2.1.2

**What browser are you using?**

Chrome

**Reproduction URL**
https://sorry.nocando - will do later if I have time

**Describe your issue**

When you have an existing Dialog open and navigate to a new url that also contains an open Dialog, the portal gets appended to the Portal root div and displays normally over the existing dialog. However, the underlying dialog still controls the ui bc the overlaying portal is marked `inert`. A reload fixes this. I assume this is caused by the innovative way remix allows you to create overlays using page routes. I assume the portal counting mechanism gets screwed up somehow

Parent route > contains `<Outlet />
    Child route  > renders in place of the outlet

**Comment by nosovj** [comment]
I ran into this issue this morning, when you have a Modal with a Listbox child, it seems to set the portal to inert for all of the elements, so none of the children are clickable.

Expected:
![image](https://github.com/user-attachments/assets/0b78dbc4-4ef2-4d10-9a9c-d7f0b91c4657)

Actual:
![image](https://github.com/user-attachments/assets/d48eaedf-5130-4a06-a057-6d79b8d3e432)



It seems like this is an issue with headlessui 2.1.3, when I changed the version from `"@headlessui/react": "^2.1.2"` to `"@headlessui/react": "2.1.2"`, it seems to have went away.

**Comment by BobbiSixkiller** [comment]
Well for me it was the same even on all 2.1.x verisons. Decided to revert back to version 1.7.x. Now listbox and select components behave correctly when rendered inside the modal.

**Comment by sollambert** [comment]
Getting this issue as well when using Listbox within a modal, downgrading to 2.1.2 resolved the issue

**Comment by RobinMalfait** [comment]
Hey!

I can't seem to reproduce this issue anymore with the latest version of Headless UI. Can everybody try and upgrade to the latest version:
```
npm install @headlessui/react
```

This is a related issue that also works with the latest version: https://github.com/tailwindlabs/headlessui/issues/3330

If that is not sufficient for your use case, please create a new issue with a minimal reproduction repo attached and I'm happy to take a look!

Hope this helps!

**Comment by gstrobl** [comment]
I also can confirm that this issue, created a quick example here: 

https://codesandbox.io/p/live/a71299e7-f07e-422f-b037-db59c76e58fc

**Comment by RobinMalfait** [comment]
@gstrobl did you delete the sandbox? If not, can you make it public?

<img width="585" alt="image" src="https://github.com/user-attachments/assets/c7ba170f-7b18-4e7d-bd45-1a794cae29d5">

**Comment by gstrobl** [comment]
> @gstrobl did you delete the sandbox? If not, can you make it public?
> 
> <img alt="image" width="585" src="https://private-user-images.githubusercontent.com/1834413/365591973-c7ba170f-7b18-4e7d-bd45-1a794cae29d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTQ3NTAsIm5iZiI6MTcyNjE1NDQ1MCwicGF0aCI6Ii8xODM0NDEzLzM2NTU5MTk3My1jN2JhMTcwZi03YjE4LTRlN2QtYmQ0NS0xYTc5NGNhZTI5ZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTUyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQwZWE3ZGM5ODBlYmE1ZTAxZmFmOTRmNjkwYmFjNDU3YTVkMjU3ZGJiODdlNTBhZjNiNGU2OGI5YmE3MDM1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AIKIavkrwFyIiAKqFLCGMa03IPrPQ_X0p421UbGYuM8">

Sorry, now it's public!

**Comment by sagarchoudhary96** [comment]
@RobinMalfait  i'm also seeing the issue when i'm trying to use a dropdown menu inside a dialog. the dropdown menu items are not clickable.

**Comment by AlexanderFarkas** [comment]
I also experience similar issue when Dialog's position is set to "relative". It breaks ListboxOptions completely
