### ISSUE TITLE
Combobox throws "Maximum recursive updates exceeded" error in Vue

### ISSUE THREAD

**Issue by ajuvonen** [tailwindlabs/headlessui#3455]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

1.7.22

**What browser are you using?**

Firefox 129, Chrome 128

**Reproduction URL**

[Stackblitz.](https://stackblitz.com/edit/vue3-vite-starter-jh3jmb)

**Describe your issue**

With enough data, opening a Combobox takes several seconds to open and eventually errors out with the following error:

`Uncaught (in promise) Maximum recursive updates exceeded in component <Combobox>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

Oddly enough the error doesn't occur if you type in the combobox in certain ways, but when you clear your input, opening the full list again errors.

The Stackblitz fork is a Vite + Vue starter with basically everything else taken off, and the Combobox implementation follows the HeadlessUI example, with the exception of its data generation and it being a nullable multiple selection.

**Comment by ajuvonen** [comment]
This seems to start occurring after Vue 3.5.0, still works with 3.4.38.

**Comment by miguelrk** [comment]
I can confirm I'm having this error as well after upgrading to vue 3.5.0

**Comment by RobinMalfait** [comment]
Hey!

This seems to be an issue with vue itself. If you install the latest version (3.5.2) it starts working again as expected 👍

Hope this helps!

**Comment by miguelrk** [comment]
Hey @RobinMalfait, thanks for your answer! How would I install `vue`  version `"3.5.2"` for `nuxt@3.13.1`? Is it simply `npm install vue@^3.5.2` for nuxt to use that locally installed version?

**Comment by timotheeduran** [comment]
> Hey @RobinMalfait, thanks for your answer! How would I install `vue` version `"3.5.2"` for `nuxt@3.13.1`? Is it simply `npm install vue@^3.5.2` for nuxt to use that locally installed version?

Hey @miguelrk. Did you manage to do this?

**Comment by RobinMalfait** [comment]
@miguelrk @timotheeduran Nuxt relies on `"vue": "^3.5.0",` in the package.json, which means that an `npm install` or `npm update` should do the trick already.

You can run `npm ls vue` to see which version of Vue is installed.

**Comment by patriktoth67** [comment]
Sadly it didn't solve the issue for me, after `npm ls vue` I see that v3.5.6 is installed but still get the error with most popover elements.

**Comment by egoson** [comment]
this is repeated in vue 3.3, it seems this is not normal behavior, passing reactive data to value helped, but this is not at all obvious

**Comment by azulkipli** [comment]
I use nuxt 3.14 still happen

I use with nuxt headless-ui module

```
<HeadlessCombobox
	v-slot="{ open }"
	v-model="selectedCategories"
	multiple
>
	<div class="relative">
		<ul
			v-if="selectedCategories.length > 0"
			class="p-0 rounded-md mb-2 flex flex-wrap justify-start gap-x-2 gap-y-1"
		>
			<li
				v-for="cat in selectedCategories"
				:key="cat._id"
				class="flex items-center py-1 text-xs"
			>
				<div
					class="h-5 font-normal text-[13px] border border-transparent"
				>
					{{ cat.category_name }}
				</div>
				<button
					class="inline-block align-middle text-red-600"
					@click="removeCategory(cat)"
				>
					<IconCarbonClose class="text-red-600" />
				</button>
			</li>
		</ul>
		<div class="relative">
			<HeadlessComboboxInput
				:display-value="
					(cat: any) => cat.category_name
				"
				class="flk-input"
				placeholder="Select Categories (type to search)"
				@change="queryCategory = $event.target.value"
			/>
			<HeadlessComboboxButton
				class="absolute inset-y-0 top-0 right-0 flex items-center pr-2"
			>
				<IconHeroChevronDown
					:class="open ? 'rotate-180' : ''"
				/>
			</HeadlessComboboxButton>
		</div>

		<HeadlessTransitionRoot
			leave="transition ease-in duration-100"
			leave-from="opacity-100"
			leave-to="opacity-0"
			@after-leave="queryCategory = ''"
		>
			<div
				v-if="
					filteredCategories.length === 0 &&
					queryCategory !== ''
				"
				class="shadow cursor-default select-none px-3 py-2 mt-1 text-gray-500 border"
			>
				Category not found.
			</div>
			<HeadlessComboboxOptions
				v-if="filteredCategories.length > 0"
				as="ul"
				class="max-h-32 border overflow-y-scroll shadow mt-1 py-1"
			>
				<HeadlessComboboxOption
					v-for="cat in filteredCategories"
					v-slot="{ selected }"
					:key="cat._id"
					:value="cat"
				>
					<HeadlessComboboxButton
						class="px-2.5 py-1.5 cursor-pointer w-full flex justify-between hover:bg-slate-200"
					>
						<div
							:class="selected ? 'text-blue-600' : ''"
						>
							{{ cat.category_name }}
						</div>
						<span
							v-if="selected"
							class="text-blue-600"
						>
							&check;
						</span>
					</HeadlessComboboxButton>
				</HeadlessComboboxOption>
			</HeadlessComboboxOptions>
		</HeadlessTransitionRoot>
	</div>
</HeadlessCombobox>
```
