### ISSUE TITLE
Cannot read properties of undefined (reading '0') when ussing in Nuxt 3 with nuxt headlessui component

### ISSUE THREAD

**Issue by agracia-foticos** [tailwindlabs/headlessui#3463]
We are ussing [Nuxt](https://github.com/P4sca1/nuxt-headlessui) 
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

"Cannot read properties of undefined (reading '0')

**What browser are you using?**

Chrome

**Describe your issue**

  stack: '<pre><span class="stack internal">at useId (/home/business/var/www/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1447:63)</span>\n' +
    '<span class="stack internal">at setup (/home/business/var/www/node_modules/@headlessui/vue/dist/components/disclosure/disclosure.js:1:1143)</span>\n' +
    '<span class="stack internal">at callWithErrorHandling (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:203:19)</span>\n' +
    '<span class="stack internal">at setupStatefulComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7668:25)</span>\n' +
    '<span class="stack internal">at setupComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7629:36)</span>\n' +
    '<span class="stack internal">at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:636:15)</span>\n' +
    '<span class="stack internal">at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)</span>\n' +
    '<span class="stack">at _sfc_ssrRender (./src/components/Page/Header/Promotion.vue:76:34)</span>\n' +
    '<span class="stack internal">at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:9)</span>\n' +
    '<span class="stack internal">at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:652:25</span></pre>'

**Comment by RobinMalfait** [comment]
Hey!

We rely on the native `useId` hook if it's available. If it's not available, then our implementation of the `useId` hook will be used. It looks like you are using the built-in one.

Can you try and upgrade both `Nuxt` and `Vue` to the latest version and see if that solves the issue for you?

**Comment by agracia-foticos** [comment]
@RobinMalfait I don't know what happened, I tried on another machine, reinstalling all the node_modules and now it works for me. Could it be npm/yarn issue?

**Comment by RobinMalfait** [comment]
@agracia-foticos My guess is that `node_modules` ended up in a weird state. Removing `node_modules` and re-installing typically does the trick. Another potential issue is stale caches. Most of them are stored in `node_modules` as well so a clean install should do the trick.

In case of Nuxt, this might help: https://nuxt.com/docs/api/commands/cleanup

Can you verify if that worked on your main machine?

**Comment by agracia-foticos** [comment]
@RobinMalfait now its all works. Thanks!
