### ISSUE TITLE
"Maximum update depth exceeded" when rendering ComboboxInput as Fragment

### ISSUE THREAD

**Issue by pierrechevaliercf** [tailwindlabs/headlessui#3520]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.9

**What browser are you using?**

 Chrome / Jest

**Reproduction URL**

https://codesandbox.io/p/devbox/strange-murdock-d2s369?workspaceId=a6f3575d-11e2-4d0a-8416-c1b842cb3477

**Describe your issue**

This is exactly like https://github.com/tailwindlabs/headlessui/issues/3507, but for ComboboxInput.

**Comment by thecrypticace** [comment]
This was addressed in #3513 — we'll get a release out soon

**Comment by RobinMalfait** [comment]
Hey! Just got a new release out. You can use `npm install @headlessui/react@latest` to resolve this issue.
