### ISSUE TITLE
Peer dependency error  when upgrading react and react-dom to react 19 (Nextjs 15)

### ISSUE THREAD

**Issue by franckadil** [tailwindlabs/headlessui#3538]
**What package within Headless UI are you using?**

**What version of that package are you using?**

 @headlessui/react: "^2.1.10"

**Describe your issue**

Upgrading to next.js 15 with the minimum version of react and react-dom that is now 19 I get a peer dependency error that breaks the upgrade. headlessui requires react 18.

**Comment by reinink** [comment]
Hey folks! We added React 19 support to Headless UI today (see #3543). You can upgrade to this version by running:

```sh
npm install @headlessui/react@latest
```

Please let us know if you run into any issues! 🙏
