### ISSUE TITLE
Animated slide-overs do not open smoothly

### ISSUE THREAD

**Issue by reczy** [tailwindlabs/headlessui#357]
### What package within Headless UI are you using?

`@headlessui/react`

### What version of that package are you using?

1.0.0 (and `postcss7-compat` version of `tailwindcss`)

### What browser are you using?

Chrome and Safari (Mac)

### Reproduction repository

Tailwind UI Application UI > Overlays > Slide-overs > With background overlay

**Comment by reczy** [comment]
![Tailwind - Headless ui Slide-over animation](https://user-images.githubusercontent.com/1100860/114866633-6db4ad00-9db9-11eb-8d27-d56fff494dfb.gif)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We updated the example on https://tailwindui.com

Can you update the div above the second TransitionChild to have `fixed` instead of `absolute`, and see if that fixes things for you?

```diff
- <div class="absolute inset-y-0 right-0 pl-10 max-w-full flex">
+ <div class="fixed inset-y-0 right-0 pl-10 max-w-full flex">
```

**Comment by reczy** [comment]
Thanks @RobinMalfait - works perfectly now in Chrome and Firefox.

**Comment by RobinMalfait** [comment]
Perfect, thanks!
