### ISSUE TITLE
web: Icon (apple-touch-icon) has red background

### ISSUE THREAD

**Issue by neupauer** [tailwindlabs/headlessui#36]
A little off topic ( I didn't find the repositories for the website https://headlessui.dev so I'm putting it here )

I noticed that apple-touch-icon ( https://headlessui.dev/apple-touch-icon.png ) has a red background, which looks weird and it's probably a mistake.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I also noticed this and it is kinda funny 😄

**Comment by RobinMalfait** [comment]
That should be fixed now!
It could be that your device is still caching some of the favicon files, at least my chrome on iPad did. But Safari and Brave are using the correct fresh icon.
