### ISSUE TITLE
Typescript error on Switch and Listbox v-model in VSCode using Volar

### ISSUE THREAD

**Issue by ananni13** [tailwindlabs/headlessui#368]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.1.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/ananni13/test-headlessui

So this is just an IDE issue, in VSCode (using [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar)), v-model on the Switch component shows this error:

![ts-error](https://user-images.githubusercontent.com/37385837/114935498-8e254b80-9e3b-11eb-802a-08405f831122.jpg)

**Comment by pingustar** [comment]
I have the same issue

**Comment by pingustar** [comment]
@RobinMalfait 

Would you like a PR to fix this?

I think this should fix it:

https://github.com/tailwindlabs/headlessui/blob/0534b2ee6fe38f4bd7ce7a0597747c57df1a5ea9/packages/%40headlessui-vue/src/components/switch/switch.ts#L64

change this:

`modelValue: { type: [Object, Boolean], default: null },`

to:

`modelValue: { type: Boolean, default: false },`

**Comment by RobinMalfait** [comment]
@pingustar that would be awesome, can you create a PR against the `develop` branch?

**Comment by ananni13** [comment]
I also tried `Listbox` and `RadioGroup` (I think those are the only other components that use v-model so far).
I updated the demo repository as well, copying the examples directly from the docs.

`Listbox` shows the same type of error as `Switch`:
![listbox](https://user-images.githubusercontent.com/37385837/116252240-acf6dc80-a76f-11eb-912a-1ad1728f5721.png)

And there's also a problem with `ListboxOption` `value` prop:
![option](https://user-images.githubusercontent.com/37385837/116253023-65248500-a770-11eb-8d0e-fa7d3a9dbd6f.png)

`RadioGroup` and `RadioGroupOption` show no errors but I'm not sure they are correct either, Volar shows `v-model` (on `RadioGroup`) as `modelValue?: unknown` and `value` (on `RadioGroupOption`) as `value?: unknown`.

**Comment by ananni13** [comment]
Looks like the difference between Listbox and RadioGroup is here:
https://github.com/tailwindlabs/headlessui/blob/0534b2ee6fe38f4bd7ce7a0597747c57df1a5ea9/packages/%40headlessui-vue/src/components/radio-group/radio-group.ts#L62-L69
https://github.com/tailwindlabs/headlessui/blob/0534b2ee6fe38f4bd7ce7a0597747c57df1a5ea9/packages/%40headlessui-vue/src/components/radio-group/radio-group.ts#L230-L238
https://github.com/tailwindlabs/headlessui/blob/0534b2ee6fe38f4bd7ce7a0597747c57df1a5ea9/packages/%40headlessui-vue/src/components/listbox/listbox.ts#L75-L82
https://github.com/tailwindlabs/headlessui/blob/0534b2ee6fe38f4bd7ce7a0597747c57df1a5ea9/packages/%40headlessui-vue/src/components/listbox/listbox.ts#L444-L452

RadioGroup doesn't have a default for `modelValue` (and `value`), so in the generated declaration file they are typed as `unknown` instead of `null`.
