### ISSUE TITLE
<Dialog /> / <Portal />  custom root element

### ISSUE THREAD

**Issue by xiaoyu-tamu** [tailwindlabs/headlessui#369]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

chrome

### Reproduction repository

I'm rendering my react app under shadow root and all my css are scoped inside the shadow root.

I want the `<Dialog />` or the `<Portal />` insert inside the shadow root instead of the document.body. It would be nice we can pass custom root element for  `<Dialog />` / `<Portal />`.

![image](https://user-images.githubusercontent.com/33362998/114949370-80a99a80-9e16-11eb-82f2-2b48505e9121.png)

![image](https://user-images.githubusercontent.com/33362998/114949731-370d7f80-9e17-11eb-8f73-e12fdadcbe69.png)

**Comment by SigurdMW** [comment]
Any update on this? This is a feature we would like as well 😄
