### ISSUE TITLE
Modal gives "Intersection Observer not found" error on iOS safari

### ISSUE THREAD

**Issue by 10000multiplier** [tailwindlabs/headlessui#375]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

Safari

### Reproduction repository

https://headlessui.dev/react/dialog

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You will have to install a polyfill for this, this is the official recommended polyfill by w3c: https://github.com/w3c/IntersectionObserver/tree/main/polyfill

**Comment by anark** [comment]
Is it possible to add documentation about this requirement somewhere in headlessui so new users know that this is required for older browser support?

**Comment by epitaphmike** [comment]
This isn't just older browser support. If you do not have Intersection Observer turned on within experimental features in Safari on iOS 14.7.1. It wont work

**Comment by pricklywiggles** [comment]
You really should put this in the documentation, there was no way for me to know I needed this until I got thousands of exceptions in production.
