### ISSUE TITLE
Delay between focus outline and toggled state on Radio Group Option

### ISSUE THREAD

**Issue by kolpav** [tailwindlabs/headlessui#380]
### What package within Headless UI are you using?

both react and vue

### What version of that package are you using?

v0.3.1

### What browser are you using?

Chrome

### Reproduction repository

.

**Comment by kolpav** [comment]
Slowed down recording of the interaction

https://user-images.githubusercontent.com/19467143/115024774-d63a8180-9ec0-11eb-9448-6c1ff286e578.mp4

**Comment by kolpav** [comment]
I tested it just in docs demo not locally

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is sort of expected. The `active` state is based on whether the option has focus or not. However in the browser when you click, the `focus` is already triggered on `mousedown`, but the actual change of the state is triggered when the click event is complete `mouseup`. 

You can also see this effect on native `radio` inputs, click and hold a radio input and you will see that it has a form of active state. But it will only be active (blue on macos) when the click is complete.

https://user-images.githubusercontent.com/1834413/115252387-b6f35c80-a12b-11eb-8f49-e730da4bed8f.mov
