### ISSUE TITLE
Listbox search is case sensitive

### ISSUE THREAD

**Issue by employee451** [tailwindlabs/headlessui#381]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.0.0

### What browser are you using?

Chrome

### Reproduction repository

https://headlessui.dev/react/listbox

### Description

The issue can be experienced on the documentation page for Listbox (which I have linked to).
Try opening the menu, and then type on your keyboard to search for an item. The item can only be found if you exclusively use lowercase letters.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
