### ISSUE TITLE
vue.defineComponent is not a function

### ISSUE THREAD

**Issue by MohammedKhalid96** [tailwindlabs/headlessui#389]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

^1.0.0",

### What browser are you using?

Chrome

### Reproduction repository

no

**Comment by MohammedKhalid96** [comment]
![Screenshot from 2021-04-17 12-55-25](https://user-images.githubusercontent.com/43882433/115110542-3e9a6900-9f7c-11eb-9b75-8f23867436d3.png)

**Comment by MohammedKhalid96** [comment]
Hi, I can't use any of the tailwind vue components it always gives me this error vue.defineComponent is not a function node_modules/@headlessui/vue/dist/headlessui.cjs.development.js

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI only supports Vue 3, not Vue 2. Can you verify that you are on Vue 3?

**Comment by VicGUTT** [comment]
Use seem to be using Nuxt.JS, and as far as I can tell it does not support Vue 3 yet (you'd need Nuxt V3). Therefore none of the Headless UI components will work.

You may try your luck with a library like [vue-demi](https://github.com/vueuse/vue-demi) although I believe it'd need to be integrated into Headless UI in order to be useful.

**Comment by MohammedKhalid96** [comment]
@RobinMalfait @VicGUTT Yeah I am using nuxt.js and unfortunately, it doesn't support Vue 3 yet

**Comment by RobinMalfait** [comment]
We currently do not support Vue 2 - hopefully Nuxt.JS has some Vue 3 compatible code soon!

**Comment by vedmant** [comment]
Any way to make this compatible with Vue 2? None of me projects will use Vue 3 anytime soon.

**Comment by RobinMalfait** [comment]
@vedmant the core API of Headless UI is using the new API's exposed by Vue 3. We have no plans for implementing a Vue 2 compatible version.
