### ISSUE TITLE
Docs Typo; Vue; Disclosure

### ISSUE THREAD

**Issue by jasonlund** [tailwindlabs/headlessui#392]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.0.0

### What browser are you using?

N/A

### Reproduction repository

N/A

I couldn't find a repo for the docs so I figured I'd post this here.

There's a syntax error in the Vue Disclosure docs: https://headlessui.dev/vue/disclosure

The code example is:
```
<template>
  <Disclosure v-slot="{ open }">
    <DisclosureButton class="py-2">
      <span>Is team pricing available?</span>

      <!-- Use the `open` slot prop to rotate the icon when the panel is open -->
      <ChevronRightIcon :class='open ? "transform rotate-90" : ""}' />
    </DisclosureButton>
    <DisclosurePanel>
      <!-- ... -->
    </DisclosurePanel>
  </Disclosure>
</template>
...
```

But should be:
```
<template>
  <Disclosure v-slot="{ open }">
    <DisclosureButton class="py-2">
      <span>Is team pricing available?</span>

      <!-- Use the `open` slot prop to rotate the icon when the panel is open -->
      <ChevronRightIcon :class='open ? "transform rotate-90" : ""' />
    </DisclosureButton>
    <DisclosurePanel>
      <!-- ... -->
    </DisclosurePanel>
  </Disclosure>
</template>
...
```

There is an erroneous `}` in the class of ChevronRightIcon.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed and it is deployed to production, thanks for notifying me! https://headlessui.dev/vue/disclosure
