### ISSUE TITLE
[Bug]: Docs: Listbox: `person.unavilable` should be `person.unavailable`

### ISSUE THREAD

**Issue by TheDutchCoder** [tailwindlabs/headlessui#428]
### What package within Headless UI are you using?

Documentation

### What version of that package are you using?

Documentation

### What browser are you using?

Documentation

### Reproduction repository

https://www.youtube.com/watch?v=KIxq2qyyQh8&ab_channel=Slayer-Topic

### Describe your issue

Just a small typo ;)

Could probably also update the actual code to include that property:
```js
      const people = [
        { name: "Durward Reynolds", unavailable: true },
        { name: "Kenton Towne", unavailable: false },
        { name: "Therese Wunsch", unavailable: false },
        { name: "Benedict Kessler", unavailable: true },
        { name: "Katelyn Rohan", unavailable: false },
      ];
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Should be live! https://headlessui.dev/vue/listbox#disabling-an-option

**Comment by TheDutchCoder** [comment]
Notice!
