### ISSUE TITLE
Elements with Transition not in DOM until show is true

### ISSUE THREAD

**Issue by jorgeramos** [tailwindlabs/headlessui#44]
I'm working on an app that is using Transition for opening the modal menu used for navigation. The menu opens and closes as desired, however, the markup is not visible on the DOM unless it is open. This is problematic for SEO as that content would not be visible to the search engine crawlers. How can I make the component behave visually just as it is now, but just toggle the visibility so that the markup is always there?

You can see the behavior in the example app: https://b6xje.csb.app/

![Screen Shot 2020-10-05 at 9 55 02 AM](https://user-images.githubusercontent.com/611561/95090232-07a4ea00-06f3-11eb-9934-6ecf87062d8b.png)

![Screen Shot 2020-10-05 at 9 55 18 AM](https://user-images.githubusercontent.com/611561/95090255-0e336180-06f3-11eb-8882-90d2d58bcf87.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Both scenarios are true because we unmount the whole tree. I am going to experiment with an idea to make it stay in the DOM.

I'll keep you posted!

**Comment by Tzelon** [comment]
+1 
It will be very useful if we have a prop that toggles that behavior.

**Comment by jorgeramos** [comment]
@RobinMalfait can you share what you have in mind? This is pretty critical so I'd like to give it a shot if you don't have the bandwidth at the moment.

**Comment by jorgeramos** [comment]
> Hey! Thank you for your bug report!
> Much appreciated! 🙏
> 
> Both scenarios are true because we unmount the whole tree. I am going to experiment with an idea to make it stay in the DOM.
> 
> I'll keep you posted!

Hi, do you think you'll have time over the next couple of days for this one? I'd love to jump in and work on it. Can you point me in the right direction with the ideas you had?

**Comment by RobinMalfait** [comment]
@jorgeramos Hey! I'm working on this the next couple of days. I will get back to this very shortly!

**Comment by RobinMalfait** [comment]
Hey! Small update: This should be working in the next version we publish.

### Usage:

Put an `unmount={false}` on all the the `Transition` or `Transition.Child` elements that you want to keep in the DOM. From a visual perspective this should behave exactly the same. From a DOM perspective the components that have `unmount={false}` will get a `hidden` prop and a `style={{ display: 'none' }}`

The default value of `unmount` is `true`, so make sure to put it everywhere where you need it.

```jsx
<Transition unmount={false} />
<Transition.Child unmount={false} />
```

**Comment by jorgeramos** [comment]
@RobinMalfait thanks for working on this. Do you have an expected date for the next release?

**Comment by mansoorkhan96** [comment]
This might help someone using Popovers
https://github.com/tailwindlabs/headlessui/discussions/870#discussioncomment-11804946
