### ISSUE TITLE
[Bug]: RadioGroup Circle gets oval when descriptions is a two liner

### ISSUE THREAD

**Issue by logemann** [tailwindlabs/headlessui#442]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.0.0

### What browser are you using?

Chrome

### Reproduction repository

N/A

### Describe your issue

Issue as in title. See https://github.com/tailwindlabs/tailwindui-issues/issues/588 for details.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI itself doesn't render any children, so this is not an issue with Headless UI itself. A `flex-shrink-0` will probably work.
It looks like that your issue is already resolved, so will close this one.
