### ISSUE TITLE
[Bug]: Menu.Item keyboard selection does not work with Next.js Link components

### ISSUE THREAD

**Issue by lukasbuenger** [tailwindlabs/headlessui#449]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

Chrome 90, Safari 14.0.3

### Reproduction repository

https://codesandbox.io/s/laughing-napier-5i5f4

### Describe your issue

When using a [next/link](https://nextjs.org/docs/api-reference/next/link) `Link` component as a child of `Menu.Item`, keyboard selection (Enter, Space) is not working. Using the mouse still works as expected.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue here is that the `Link` component doesn't forward the props it receives. 
I would recommend to create a `NextLink` component that does this for you: https://codesandbox.io/s/elegant-dirac-tmkc4?file=/pages/index.js
