### ISSUE TITLE
[Bug]: In the dialog form when submitting, it is not submitted

### ISSUE THREAD

**Issue by dacoto97** [tailwindlabs/headlessui#451]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.1.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/dacoto97/broken_headlessui/tree/updated_to_1.1.0

### Describe your issue

When updating to headlessui 1.1.0 the forms do not send with the submint button, see the changes: https://github.com/dacoto97/broken_headlessui/pull/1
You can see how the main branch does work, but when you switch to the update branch dosn't work the submit.
Main: https://github.com/dacoto97/broken_headlessui/tree/main
Update branch: https://github.com/dacoto97/broken_headlessui/tree/updated_to_1.1.0

**Comment by anark** [comment]
I am seeing this issue with @headless-ui/react as well

**Comment by Nazaire** [comment]
Seems similar to an issue i'm having where <a> tags and <input type="file"> clicks aren't working either. Looks like an event listener on the <Dialog> component is consuming the click events. Downgrading back to v1.0.0 for now...

**Comment by hailwood** [comment]
Here's a code sandbox reproduction https://codesandbox.io/s/headless-ui-dialog-forked-fi34g?file=/src/Modal.tsx
Tracing it through these lines appear to be the problem https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L246-L249

**Comment by nickroberts** [comment]
I was wondering what was going on. I just updated to 1.1.0 yesterday, and just tested the form in a dialog today. Ha!

I downgraded to 1.0.0, for now, until a fix is implemented.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Sorry about that! Should be fixed in 1.1.1

**Comment by dacoto97** [comment]
I delete the repository, but I attach the two branches.
MAIN: [broken_headlessui-main.zip](https://github.com/tailwindlabs/headlessui/files/6390397/broken_headlessui-main.zip)
BROKEN: [broken_headlessui-updated_to_1.1.0.zip](https://github.com/tailwindlabs/headlessui/files/6390398/broken_headlessui-updated_to_1.1.0.zip)

**Comment by denu5** [comment]
Thanks for the fix!
Stumbling over this in a next.js project was painful, since the internal nextjs link components work.

just adding some keywords for anyone hitting this issue: 

link modal dialog broken not working click event propagation events swallowed
