### ISSUE TITLE
[Docs]: React Dialog example is missing cancelButtonRef on the actual button

### ISSUE THREAD

**Issue by iamandrewluca** [tailwindlabs/headlessui#454]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

N/A

### What browser are you using?

N/A

### Reproduction repository

N/A

### Describe your issue

When looking at the dialog example we can see that we pass `initialFocus={cancelButtonRef}` to `Dialog`. 
but the actual button is missing this ref `cancelButtonRef`

https://headlessui.dev/react/dialog

ps: are the docs open sourced somewhere? I wanted to make the fix, but couldn't find.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed.

---
Currently the docs are not open sourced. We will likely do that but not sure when yet.
