### ISSUE TITLE
[Bug]: Transition is not working on first mount when using react-focus-lock

### ISSUE THREAD

**Issue by emadabdulrahim** [tailwindlabs/headlessui#455]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.1.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/winter-grass-gk2t1?file=/src/App.js

### Describe your issue

I'm having trouble getting the transition to work on the first time the state changes. I'm using `react-focus-lock` to bring focus inside when a component mounts and keep focus locked inside (My real example is SideSheet and Dialog components). You'll notice it works fine afterwards. 

If I remove `FocusLock` component it works fine, but I've been trying to figure out why it messes up the transition only on the first mount. Any help would be greatly appreciated 🙏🏽

### Update
It looks like this is happening because the `enterFrom` classes are not applied in that first mount. However, I don't know why is that.

[React Focus Lock](https://github.com/theKashey/react-focus-lock)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I updated the Sandbox: https://codesandbox.io/s/vigorous-waterfall-pky6x?file=/src/App.js
Checkout the `FocusTrap` that we expose from Headless UI.

So the issue that is happening here:
When you want to focus an element, then the browser will make sure that the element is in view immediately. The browser will basically cancel all of the transitions that are happening. You can get around this behaviour by doing something like `element.focus({ preventScroll: true })`. That is basically what we are doing in our `FocusTrap`.

Hope this helps!
