### ISSUE TITLE
Apologies for creating a lot of references to my fork

### ISSUE THREAD

**Issue by HonkingGoose** [tailwindlabs/headlessui#46]
I just did something really stupid, and want to notify you and apologize for my actions.

**Intention:**

I wanted to try out the **Depfu** bot for you, as you are not really happy with the Dependabot config that I gave you.
I wanted to revert the Dependabot stuff on my fork so that I could try again with the Depfu bot, and see what the result is.

**What I did:**

I did a `git rebase -i --root` on my fork to drop all commits that relate to the Dependabot config I made for you.
This of course creates new commits, and I force-pushed those to my fork.

I did not realize that by force-pushing I'm creating new references to my fork on your project.... :disappointed: 
See `https://github.com/tailwindlabs/headlessui/pull/29` for an example of what I did.

**What I should have done:**

I should have just done a `git revert` on each commit instead of creating brand-new commits and force pushing those...

**Trying to get this fixed:**

I have contacted GitHub support to try and fix my mistake.

**Apology:**

I feel really bad about this, I only wanted to help, and now I've only created more hassle for you.

I'm really sorry for making such a mess of things. :disappointed:

**Comment by RobinMalfait** [comment]
Hey!
Don't worry about it, it doesn't really affect me. I get "spammed" enough by GitHub because I am a force pusher myself, which results in stuff like this:

![image](https://user-images.githubusercontent.com/1834413/95103497-f381dc80-0734-11eb-9461-4c44e202eb06.png)

PR for this image: https://github.com/tailwindlabs/headlessui/pull/26

---

So really, don't worry about it!

**Comment by HonkingGoose** [comment]
> I  get "spammed" enough by GitHub because I am a force pusher myself, which results in stuff like this:

At least I didn't manage to spam the repository that badly... :zany_face: 

> Don't worry about it, it doesn't really affect me. 

Thank you for your kind words! :+1: :1st_place_medal: 
I feel a lot better now. I was really stressed out about messing things up.
