### ISSUE TITLE
Multiple / Nested Popup tabIndex bug

### ISSUE THREAD

**Issue by DoctorDerek** [tailwindlabs/headlessui#467]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.0.0 (latest?)

### What browser are you using?

Chrome latest 64-bit 89.0.etc Windows 10

### Reproduction repository

https://codesandbox.io/s/headlessui-dialog-multiple-modals-bugs-forked-534xd?file=/pages/index.js:171-187

### Describe your issue

This may be related to #426 (nested Dialogs -- Is it the same for nested Popovers?)

I seem to be seeing a tabIndex bug where nested popovers tab 2 items for focus, including with the new `dev` build. But maybe I'm missing something?

https://codesandbox.io/s/headlessui-dialog-multiple-modals-bugs-forked-534xd?file=/pages/index.js:171-187

`Tab` into the menu works:
![image](https://user-images.githubusercontent.com/761231/116175755-89cc1e80-a6d6-11eb-972d-e01d5dba6478.png)

But `Tab` skips the in-between item:
![image](https://user-images.githubusercontent.com/761231/116175766-8e90d280-a6d6-11eb-9962-404bff420077.png)

And `Esc` closes all the Popovers. Is that the intended effect or a similar bug to the nested dialogs bug?

**Comment by DoctorDerek** [comment]
Per discussion in #426, this looks unrelated -- but I haven't come up with a solution yet. Thoughts?

**Comment by thebuilder** [comment]
Also seeing this behaviour after nesting popover elements. They seem to behave in a logical manner otherwise, like closing when tabbing outside all the popover's.

**Comment by DoctorDerek** [comment]
Thanks Dan @thebuilder for reproducing this issue. I haven't been able to solve it, since I can't figure out how to expose the behavior to override `tabIndex` like I could for overriding the `onclick` handler to make a hover menu (see #239 for #283 for discussion and my code example).

When I manually throw some tabIndexes on willy-nilly, I can't seem to change the behavior.

I'd love to hear what you come up with. It's currently one of the last stumbling blocks for me on a client site that has an accessibility requirement (which I would be concerned about anyway, but it's holding up launch).

**Comment by DoctorDerek** [comment]
Hi, I tried digging into the code to solve the issue, but I couldn't quite make sense of the part generating `tabIndex` values. It might be related to the recently fixed issue #283, but in looking at that fix it doesn't seem to be.

Minimal reproducible case here: https://github.com/tailwindlabs/headlessui/issues/426#issuecomment-827268497

Thanks in advance for any help. I've been working on this issue for over 6 months now, and I'm about ready to give up on @tailwindlabs/headlessui for this particular project so I can finally ship an accessible, nested menu.

**Comment by kloh-fr** [comment]
I'm nesting popover elements for a mobile navigation with 2 level panels and I also identified this issue as I was doing some tabulation tests… This is quite strange and annoying. 🙁

I'm going to experiment a bit, even I think I'm going to be limited pretty fast by my poor technical knowledge. 💩

**Comment by DoctorDerek** [comment]
It would be great if we could figure something out here. I bought Headless
UI to use with a client but was never able to do so because of this issue.

**Comment by blueridger** [comment]
I'm experiencing the every-other tabbing bug inside a popover as well, however we aren't nesting popovers. Just a single popover with a bunch of buttons inside is skipping every other button when tabbing through.

@headlessui/react 1.5.0
MacOS Mojave 10.14.6

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1440, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by kloh-fr** [comment]
Just tried insiders version and I can confirm tab order is fixed in my case! 🙌
