### ISSUE TITLE
[React DOCS ]: Dialog 

### ISSUE THREAD

**Issue by vousys** [tailwindlabs/headlessui#468]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

Chrome

### Reproduction repository

none

### Describe your issue

In the documentation, you use 2 differents variables to handle the "open" state: "isOpen" and "open" but the useState function works with "isOpen"

All the code blocks that uses transitions have the issue:
![image](https://user-images.githubusercontent.com/12813221/116777227-d2bc0400-aa43-11eb-94bc-04c1f07ada7a.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed.
