### ISSUE TITLE
[Bug]:  Hydration mismatch (Expected server HTML to contain a matching <div> in <div> )

### ISSUE THREAD

**Issue by enochndika** [tailwindlabs/headlessui#470]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.1.1

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/enochndika/headless-ui-with-Next.js

### Describe your issue

This warning appears when I use the Dialogue (Modal) component

It only appears if the initial state of open is true.

```jsx
const [open, setOpen] = useState(true);
```

this indicates : ``` Warning: Expected server HTML to contain a matching <div> in <div>.
    at div
    at DescriptionProvider```

To fix that, I first check if the component is mounted on the client side

```jsx
export default function Home() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return <>{mounted && <MyModal />}</>;
}

```
But I think the best solution would be to check if the component is mounted internally, so that we don't have to do it manually

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
