### ISSUE TITLE
[Bug]: Missing default null value for useRef hook

### ISSUE THREAD

**Issue by roydigerhund** [tailwindlabs/headlessui#473]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.1.1

### What browser are you using?

Safari

### Reproduction repository

https://codesandbox.io/s/headless-ui-useref-example-6zuvi?file=/src/App.tsx

### Describe your issue

**Describe the bug**
The correct usage of the useRef hook would include `null` as an initial value.
In a Javascript project, this would possibly don't matter but in a Typescript project this will throw an error because a `ref` attribute would not accept `undefined` as value.

**Current wrong usage**
`const cancelButtonRef = useRef()`

**Correct usage**
`const cancelButtonRef = useRef(null)`

**Headless UI**
The same wrong usage can be found in the Tailwind UI project, the linked issue is: 
https://github.com/tailwindlabs/tailwindui-issues/issues/599

**Comment by carlosmori** [comment]
@roydigerhund Im trying to bypass this bug because I cant get my project to build. Do you know a way to workaround it?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This will be fixed in the next version of the docs.
