### ISSUE TITLE
[Bug]: Performance issues with Select Custom Dropdown on big lists

### ISSUE THREAD

**Issue by khuang7** [tailwindlabs/headlessui#474]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.1.1

### What browser are you using?

Firefox

### Reproduction repository

https://github.com/khuang7/headlessui-listbox-issue (yarn install then yarn start)

### Describe your issue

I am trying to populate a pretty big list (500 elements) into the [Simple Custom](https://tailwindui.com/components/application-ui/forms/select-menus) component found in TailwindUI for my project. The hover behavior when trying to select an option becomes quite slow when you try to move the mouse around on all the options. Also generating the list can sometimes be slow as well.

My workaround this problem is to replace Listbox.Options and Listbox.Option to ul and li html elements so that I can just call 'hover:' on the li elements which improves performance significantly. But I would prefer to keep using the HeadlessUI instead of HTML because I would lose a lot of the ARIA accessibility features.

I was wondering if there is a way to deal with the performance issues in the HeadlessUI. I could only pinpoint the issue being related to ListboxOptions and ListboxOption.

**Comment by mseele** [comment]
Same for **@headlessui/vue**. It takes ~ 5 seconds to open a popup with around 1000 items.

Good solution would be to lazy load entries (like vuetify does), but i don't know if this is possible with "headless"

**Comment by ErickTamayo** [comment]
I managed to virtualize the options by using https://github.com/bvaughn/react-window, but then the accessibility (pressing up and down arrows) gets messed up. 

![hui-virtualized](https://user-images.githubusercontent.com/4788817/118753670-b29d8a80-b822-11eb-8892-dae41651c494.gif)

**Comment by rovansteen** [comment]
Yeah currently all `ListBox.Option` values needs to be mounted because they register themselves within the context. Would be great if that could be changed so they are lazy so it can work together with virtualisation libraries.

**Comment by bezreyhan** [comment]
This is also an issue for ListBox (at least for React). Part of the issue is that all of the options get re-rendered when the user hovers over each option.

But this is a big issue for us since as of now there is no way for us to use ListBox without sacrificing UX. We will probably resort to the native html select tag for now.

**Comment by bezreyhan** [comment]
Yea this is a problem for us as well. It looks like all of the options are re-rendered when the user hovers over each option.

**Comment by adrianrudnik** [comment]
Just experienced the same with a language drop-down of 150 values, getting unusable results on mobile.

**Comment by doutatsu** [comment]
I thought it was an issue on my end, but looks like the component is just not well optimised. I need to render lists up to 1000 entries, which is unusable with this select

**Comment by RomainLanz** [comment]
Bumping this issue.

Having a country list of 240 items makes it nearly unusable.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Currently our components don't implement windowing / virtualisation so the performance issues are currently expected if you throw a lot of items at them. I took note of it to explore using Headless UI with tools like react-window as @ErickTamayo explored and once we have that figured out we will document it.

**Comment by Miladiir** [comment]
I don't quite understand the reasoning behind closing this issue when this issue that is perceived as a bug by developers using headlessui is not remedied. Is there a public roadmap somewhere, where this issue could at least be linked against so we can keep track of progess in any other way than subscribing to this issue?

**Comment by Zertz** [comment]
On the React side at least, most of the slow-ness comes from [`compareDocumentPosition`](https://github.com/tailwindlabs/headlessui/blob/c219d87a6968b84ddb668ee90639e9ca6eea1788/packages/%40headlessui-react/src/utils/focus-management.ts#L116).

This is indirectly used by `<Listbox>` (and others): 
1. [`adjustOrderedState`](https://github.com/tailwindlabs/headlessui/blob/40fee45afe9c105c4bf739c3dd6c2ab9138895aa/packages/%40headlessui-vue/src/components/listbox/listbox.ts#L137)
1. [`sortByDomNode`](https://github.com/tailwindlabs/headlessui/blob/40fee45afe9c105c4bf739c3dd6c2ab9138895aa/packages/%40headlessui-react/src/utils/focus-management.ts#L106)

I'm not an expert with algorithms but I'm pretty sure a lot of expensive, duplicate DOM work is being done here.

**Comment by Miladiir** [comment]
> It took me a while to get it just right but windowing works quite well with [`react-virtual`](https://github.com/TanStack/react-virtual)!
> 
> Once I got everything set up, I was able to overcome most (all?) quirks by being somewhat generous with overscan. For a list of about 2000 items, 25 seems to do the trick.

Last time I tried something similar, keyboard navigation through items broke. I am also interested in your solution. Can you provide a minimal example?

**Comment by Zertz** [comment]
Started putting together an example in the react playground, I'll try to create a PR this evening!

**Comment by briavicenti** [comment]
Just checking in @Zertz, were you still considering sharing a playground with a demo? I am really struggling to get react-virtual to work with the Listbox, would love to see what you did to combine them.

**Comment by Zertz** [comment]
I'm sorry, I got caught up in a million things. I'll try to finish the demo shortly.

**Comment by leoyli-headsup** [comment]
Hitting a similar issue, would like to know if any one knows how to improve the perf issue 🙏

**Comment by aburtsev** [comment]
> 

@leoyli-headsup 
Look at react-virtualized or react-virtualized for that. With one of these tools, you can easily solve the performance problem

**Comment by imrids** [comment]
@Zertz Don't mean to be a bother, but any chance you'll get around to that example anytime soon? Would be highly appreciated.

**Comment by bzbetty** [comment]
here's a quick demo of using it with tanstack react-virtual.  

couple of notes
* react-virtual currently doesn't support react 18 in strict mode
* the virtual list has to be in a separate compoent not directly embedded in the <combobox.options> as it doesn't handle losing it's ref

```
import { Fragment, useRef, useState } from 'react'
import { Combobox, Transition } from '@headlessui/react'
import { ArrowDown, CommentIcon } from '@SvgList'
import classNames from 'classnames'
import { useVirtualizer } from '@tanstack/react-virtual'

type ListItem = {
    value: string | number
    text: string | undefined | null
}

type Props = {
    name?: string
    items?: ListItem[]
    label?: string
    onChange?: (event: { target: any; type?: any; }) => Promise<void | boolean>;
    children?: never
    className: string
};

export default function Select({ name, label, items, className, onChange }: Props) {
    const [selected, setSelected] = useState<ListItem>();
    const [query, setQuery] = useState('');
    const btnRef = useRef<HTMLButtonElement>(null);

    const filteredItems =
        query === ''
            ? items
            : items?.filter((item: ListItem) =>
                (item?.text ?? '')
                    .toLowerCase()
                    .replace(/\s+/g, '')
                    .includes(query.toLowerCase().replace(/\s+/g, ''))
            ) ?? [];


    var classes = classNames(
        "relative w-full cursor-default overflow-hidden text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-teal-300",
        "mt-1 block w-full h-9 bg-background-grey border rounded text-base text-dark-grey shadow-sm placeholder-light-grey focus:bg-white focus:outline-none focus:border-accent-purple focus:ring-2 focus:ring-accent-light disabled:bg-light-grey disabled:text-light-grey disabled:border-light-grey disabled:shadow-none invalid:border-red-100 invalid:text-light-grey focus:invalid:border-red-100 focus:invalid:ring-red-100 leading-none border-light-grey",
        className,
    );

    return (
        <label className="block">
            <span className="block text-sm font-semibold text-dark-grey">{label}</span>
            <div className="relative mt-1">
                <Combobox value={selected} onChange={(v) => { setSelected(v); onChange?.({ target: { name, value: v?.value } }); }}>
                    <div className="relative mt-1">
                        <div className={classes}>
                            <Combobox.Input onFocus={(e: any) => { e.target.select(); if (!e.relatedTarget) { btnRef?.current?.click(); } }} className="w-full border-none py-2 pl-3 pr-10 text-sm leading-5 text-gray-900 focus:ring-0"
                                displayValue={(item: ListItem) => item?.text ?? ''}
                                onChange={(event) => setQuery(event.target.value)}
                            />
                            <Combobox.Button ref={btnRef} className="absolute inset-y-0 right-0 flex items-center pr-2">
                                <ArrowDown />
                            </Combobox.Button>
                        </div>

                        <Combobox.Options>
                            {filteredItems?.length === 0 && query !== '' ? (
                                <div className="relative cursor-default select-none py-2 px-4 text-gray-700">
                                    Nothing found.
                                </div>
                            ) : (
                                <VirtualizedList items={filteredItems ?? []} />
                            )}
                        </Combobox.Options>
                    </div>
                </Combobox>
            </div>
        </label>
    )
}

function VirtualizedList({ items }: { items: ListItem[] }) {
    const parentRef = useRef<HTMLDivElement>(null);

    const rowVirtualizer = useVirtualizer({
        count: items?.length,
        getScrollElement: () => parentRef.current,
        estimateSize: () => 35,
        overscan: 5,
    });

    return (
        <div ref={parentRef} className="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
            <div
                style={{
                    height: `${rowVirtualizer.getTotalSize()}px`,
                    width: '100%',
                    position: 'relative',
                }}
            >
                {rowVirtualizer.getVirtualItems().map((virtualRow: any) => (
                    <Combobox.Option
                        key={virtualRow.index}
                        style={{
                            position: 'absolute',
                            top: 0,
                            left: 0,
                            width: '100%',
                            height: `${virtualRow.size}px`,
                            transform: `translateY(${virtualRow.start}px)`,
                        }}
                        className={({ active }) =>
                            `relative cursor-default select-none py-2 pl-2 pr-4 ${active ? 'bg-dark-grey text-white' : 'text-gray-900'
                            }`
                        }
                        value={items?.[virtualRow.index]}
                    >
                        {({ selected, active }) => (
                            <span className={`block truncate ${selected ? 'font-medium' : 'font-normal'}`}>
                                {items?.[virtualRow.index].text}
                            </span>
                        )}
                    </Combobox.Option>
                ))}
            </div>

        </div>
    );
}
```

**Comment by Dorianslavov** [comment]
Anyone managed to make a workaround for Vue for this performance issue ?

**Comment by zynth17** [comment]
got the some issue with vue, isn't this supposed to be top priority to do?

**Comment by zynth17** [comment]
> got the some issue with vue, isn't this supposed to be top priority to do?

finally i fix this on vue, combining `headlessui` and [UseVirtualListComponent](https://vueuse.org/core/usevirtuallist/#usage) from `vueuse`
works fine. i just hope this get built in since this is important issue.

**Comment by Tinoooo** [comment]
This issue should be reopened as it is not fixed for the Vue variant.

**Comment by RobinMalfait** [comment]
It's also not "fixed" for React. As mentioned in my comment here: https://github.com/tailwindlabs/headlessui/issues/474#issuecomment-1047048101 currently we don't support it and you can use other tools to work together with Headless UI to implement windowing.

It's not a bug, it's just a feature we didn't implement yet.
