### ISSUE TITLE
Disable Menu.Button

### ISSUE THREAD

**Issue by guvenakcoban** [tailwindlabs/headlessui#48]
Sometimes we need to disable Menu.Button but I couldn't see any section on docs about this and also couldn't see docs about contribution. I think it is an essential feature.

I could wish to use it like this

```
{({ open }) => (
  <>
    <Menu.Button disabled={true}>
     ...
    </Menu.Button>

    ...
  </>
)}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

This should work out of the box, however we use pointer events instead of click in a few places. I'll make sure this works for both the `Menu.Button` and the `Listbox.Button`.
