### ISSUE TITLE
[Bug]: `disabled` attribute on ListboxOption component defaults to `false`, which is truthy

### ISSUE THREAD

**Issue by robyedlin** [tailwindlabs/headlessui#483]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.1.1

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/tailwindlabs/headlessui/blob/91007b75efdec6500b1afb27d7946b1488eb80c6/packages/%40headlessui-vue/src/components/listbox/listbox.ts#L449

### Describe your issue

The `disabled` attribute on ListboxOption component defaults to `false`, which is truthy.  Chrome reads `disabled="false"` the same as `disabled="true"` or just `disabled`.

The prop should default to `null`.

I'm happy to submit a PR.

https://github.com/tailwindlabs/headlessui/blob/91007b75efdec6500b1afb27d7946b1488eb80c6/packages/%40headlessui-vue/src/components/listbox/listbox.ts#L449

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Good catch! 

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
