### ISSUE TITLE
[Bug / Website]: Vue Disclosure Example Code is broken

### ISSUE THREAD

**Issue by mseele** [tailwindlabs/headlessui#487]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.1.0

### What browser are you using?

Chrome

### Reproduction repository

https://headlessui.dev/vue/disclosure

### Describe your issue

- Go to [https://headlessui.dev/vue/disclosure](https://headlessui.dev/vue/disclosure)
- Open Code on the first example
- Disclosure is missing the v-slot

How it is: `<Disclosure>`
How it should be: `<Disclosure v-slot="{ open }">`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed!
