### ISSUE TITLE
[Bug]: Unmounted Dialogs crash when mounted and opened again

### ISSUE THREAD

**Issue by gunters63** [tailwindlabs/headlessui#492]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.1.1

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/gunters63/MultipleDialogsUnmountRemountCrash

### Describe your issue

Dialogs within components which get unmounted and mounted again crash when shown.

It seems during unmounting a component the portal gets removed, when a new component is being mounted with another dialog there is maybe a racing condition because there is no new portal created

The simplest example would be something like this:

````
      {enabled && <MyModal />}
      {!enabled && <MyModal />}
````

where MyModal contains a Dialog and the enabled state is flipped with a Switch (see repo)

Open the first Dialog, toggle enable, crash happens when you try to open the second dialog

The errors does not happen if you make the Dialog static and wrap it in a Transition.

**Comment by gunters63** [comment]
The Github repo is created via [CodeSandbox](https://codesandbox.io/s/github/gunters63/MultipleDialogsUnmountRemountCrash)

**Comment by thecrypticace** [comment]
Hey, thanks for the report — this appears to have be fixed in the latest Headless UI releases! 🎉

**Comment by RobinMalfait** [comment]
As an addition to @thecrypticace's comment, here is an updated codesandbox with the latest insiders built: https://codesandbox.io/s/sparkling-cloud-vne44o?file=/src/App.tsx

This will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
