### ISSUE TITLE
[Bug]: Two dialogs - There are no focusable elements inside the <FocusTrap />

### ISSUE THREAD

**Issue by Sugavanas** [tailwindlabs/headlessui#493]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.1.1

### What browser are you using?

Chrome

### Reproduction repository

-

### Describe your issue

I need to show a dialog box while another dialog is open in Vue. Both the dialogs are different components, here is an example of both the dialogs open,

![image](https://i.gyazo.com/428a79d52ccf4d4381a5d01bb5f789ae.png)

The second dialog acts as a confirmation for the first dialog. The first dialog can't be dismissed.

Is there any way to disable the focus trap on the first dialog manually?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you provide a minimal reproduction repo?

Make sure that if you want nested Dialogs that you nest them. Here is an example:
https://codesandbox.io/s/dreamy-archimedes-xxesv?file=/src/App.js

**Comment by Sugavanas** [comment]
Hi, Sure!

Here is a very basic example using two modals similar to the ones I used. 

https://codesandbox.io/s/brave-nightingale-5wczu?file=/src/App.vue

As you can see as soon as you open the second modal this error is thrown.

![image](https://user-images.githubusercontent.com/8426015/117666101-18ac6100-b1d6-11eb-9245-8353e9e9320a.png)

For now I have fixed the issue by implementing a custom Modal component and only using the `TransitionRoot` and `TransitionChild` from HeadlessUI.

**Comment by cubecleveland** [comment]
HI, im having the same issue.
Can u explaing how you exactly solved it.
Mine is a bit different though.

I have 2 modals.

Modal 1 is openable via  mouse click.
The 2nd modal can be opened via a Hot key.

When Modal 1 is open and i press the hot key i get the same error.

A ny input will be appreciated.

**Comment by Sugavanas** [comment]
Here is an example, you can use the `Modal.vue` component. It uses the `TransitionRoot` and `TransitionChild` from Headless UI.

https://gist.github.com/Sugavanas/eabbc3a260c488d4b403321883bbaa4e

You can use [vue-click-away](https://github.com/VinceG/vue-click-away) for the dismiss function but it will not work with two models open as well.

**Comment by arpitjacob** [comment]
had the same issue, I got it when both model were opening up by default when the page loads.

**Comment by RobinMalfait** [comment]
Here is an updated version of the CodeSandbox provided by @Sugavanas: https://6kwdz.csb.app/

The key takeaway here is: If you want multiple Dialog's, make sure that you nest them. We need to know the hierarchy of Dialogs so that we can properly close and restore Dialogs when pressing escape or using outside click.

**Comment by cubecleveland** [comment]
HI Guys, can us end the same sandbox in React ?


CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629

**Comment by Amethystafyy282** [comment]
U can close the first then open the new one with setTimeout 100

**Comment by xfire5000** [comment]
Just change main modal z-index to anything for example:
<Modal1 class="relative z-60">
   <Modal2 class="relative z-50">
</Modal2>
</Modal1>
it works 4 me
