### ISSUE TITLE
Add steps component

### ISSUE THREAD

**Issue by markozxuu** [tailwindlabs/headlessui#5]
Hi @adamwathan @RobinMalfait 👋  I am new to tailwindcss, I would like to collaborate to add a component in `Steps` like this but I still don't know where to start. 

I like this project and I would like it to grow more ❤️ 

<img width="1261" alt="Screen Shot 2020-09-24 at 15 18 19" src="https://user-images.githubusercontent.com/16585386/94195864-2f858980-fe79-11ea-9f93-17bb82927766.png">

**Comment by RobinMalfait** [comment]
Hey! This project has no styles attached, it is headless component library.
