### ISSUE TITLE
[Bug]: Popover does not close whenever navigating between pages

### ISSUE THREAD

**Issue by AdaptCharm** [tailwindlabs/headlessui#506]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://cdn.discordapp.com/attachments/758325031163002921/841656004096688128/Skjermopptak_2021-05-11_kl._14.19.17.mov

### Describe your issue

The problem is that popover does not close automatically whenever navigating between pages.
There simply is no callback to change the `open` boolean in the API documentation.

[https://user-images.githubusercontent.com/17816720/117818042-7ee1c400-b268-11eb-9a5a-5dee27d901c6.mov](https://user-images.githubusercontent.com/17816720/117818042-7ee1c400-b268-11eb-9a5a-5dee27d901c6.mov)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The solution here is to move focus to the new content. Once you do that, the popover will close automatically.
More information on this topic can be found here: https://github.com/tailwindlabs/headlessui/issues/358#issuecomment-822555803 (we will document this as well!)
