### ISSUE TITLE
[Bug]: Headless UI Vue > Listbox: disabled ListOption is focused on click

### ISSUE THREAD

**Issue by simonswiss** [tailwindlabs/headlessui#509]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

^1.2.0

### What browser are you using?

Chrome, Safari

### Reproduction repository

https://github.com/simonswiss/headlessui-vue-listbox-disabled-item-focus

### Describe your issue

When clicking on a disabled `ListboxOption` item, the item enters in focus (with slightly different behaviours in different browsers, see repro README).

The assumption is that an element with a `disabled="true"` attribute should never be focusable/focused.

### Screenshot (from Chrome)

![image](https://user-images.githubusercontent.com/485747/117896439-ec8efe00-b303-11eb-9f5e-26896a1f89f9.png)

The repro README has instructions on how to reproduce the issue.

**Comment by RobinMalfait** [comment]
Yep, good catch! 

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
