### ISSUE TITLE
Listbox multiple selection

### ISSUE THREAD

**Issue by iamohd** [tailwindlabs/headlessui#51]
It would be great to allow the Listbox to select more than one option by passing "multiple" Boolean prop

Example:
```
<Listbox v-model="selectedPerson" multiple>
    <ListboxButton>{{ selectedPerson.name }}</ListboxButton>
    <ListboxOptions>
      <ListboxOption v-for="person in people" :key="person.id" :value="person" :disabled="person.unavailable">
        {{ person.name }}
      </ListboxOption>
    </ListboxOptions>
</Listbox>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature request!
Currently that's not possible but it will be in a future version!

**Comment by ditschedev** [comment]
+ 1 on this one, would be great!

**Comment by tomhrtly** [comment]
Any chance of an update on this one @RobinMalfait?

**Comment by mxdi9i7** [comment]
https://gist.github.com/landorid/f747c49342dd9eac1b89b251cbe39616
https://codesandbox.io/s/headlessuireact-listbox-multiple-mockup-widh4

There are some workarounds posted by others from another issue: https://github.com/tailwindlabs/headlessui/issues/181

**Comment by arivelli** [comment]
any news on this? any estimated time? thanks

**Comment by ajota-admios** [comment]
Any ETA? This is very important :)

**Comment by thien-do** [comment]
Looking at Tailwind UI, I think the recommendation now is to use a list of checkboxes https://tailwindui.com/components/ecommerce/components/category-filters
