### ISSUE TITLE
[Bug]: Popover overlay only appears when the popover is open

### ISSUE THREAD

**Issue by innocenzi** [tailwindlabs/headlessui#519]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.2.0

### What browser are you using?

Latest Firefox developer edition

### Reproduction repository

https://i.imgur.com/aPhnpj3.gif

### Describe your issue

The documentation states that popover overlay is always displayed: 

> In this example, we put the PopoverOverlay before the Panel in the DOM so that it doesn't cover up the panel's contents. Also, since the PopoverOverlay is always rendered (even when the panel is closed), we use the open render prop to only make it full-screen (via fixed and inset-0) when the panel is open.

But [it appears to not be the case](https://i.imgur.com/aPhnpj3.gif). It causes the opacity transition to not be working, since the overlay is only added to the DOM when the popover is displayed.

Here is the full component: 

```html
<template>
	<popover v-slot="{ open }">
		<popover-button
			:class="[
				'px-3 py-2.5 space-x-1 flex items-center justify-center',
				'text-sm font-medium',
				'transition',
				'rounded-md',
				'text-pink-300 bg-pink-300 bg-opacity-15 hover:bg-opacity-20',
				'focus:outline-none focus-visible:bg-opacity-40 focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-gray-800 focus-visible:ring-pink-200 focus-visible:ring-opacity-20'
			]"
		>
			<icon name="uil:keyboard" class="w-5 h-5 mr-2" />
			<span class="font-medium">Shortcuts</span>
		</popover-button>

		<popover-overlay
			class="bg-black transition-opacity z-10"
			:class="open ? 'opacity-60 fixed inset-0' : 'opacity-0'"
		/>

		<transition
			enter-active-class="transition transform origin-top-left duration-200 ease-out"
			enter-from-class="scale-90 opacity-0"
			enter-to-class="scale-100 opacity-100"
			leave-active-class="transition transform origin-top-left duration-150 ease-in"
			leave-from-class="scale-100 opacity-100"
			leave-to-class="scale-90 opacity-0"
		>
			<popover-panel class="z-20 absolute mt-8 p-7 flex flex-col rounded-lg bg-gray-800 border border-gray-700">
				Panel contents
			</popover-panel>
		</transition>
	</popover>
</template>

<script setup lang="ts">
import { Popover, PopoverButton, PopoverPanel, PopoverOverlay } from '@headlessui/vue'
</script>
```

My temporary workaround is to use a `TransitionRoot` component.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a documentation issue. The `PopoverOverlay` is only rendered when the `Popover` is in an open state. If you don't want this behaviour (and thus _always_ show the `PopoverOverlay`), then you can use the `static` prop: `<PopoverOverlay static />`
