### ISSUE TITLE
[Bug]: React 17 support in peerDependecency

### ISSUE THREAD

**Issue by jadbox** [tailwindlabs/headlessui#531]
### What package within Headless UI are you using?

@headlessui-react

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

npm v7.13.0

### Describe your issue

The React peer dependecy doesn't reach Reacy v17.
   
This block:
```
   "peerDependencies": {
    "react": ">=16"
  }
 ```

Should be:
```
   "peerDependencies": {
    "react": "^16.0.0 || ^17.0.0"
  }
 ```
  
  When installing with NPM 7:
  ```
  npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16" from @headlessui/react@1.1.1
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Hmm, I will change it, but according to semver `>=16` should match `17.0.1`. https://semver.npmjs.com
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/1834413/118797771-32683b00-b89d-11eb-8715-16274104720a.png">

**Comment by RobinMalfait** [comment]
This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
