### ISSUE TITLE
[Bug]: Example code for Dialog (Modal) has unexpected scroll on iPhone Chrome and Safari Browser

### ISSUE THREAD

**Issue by pingustar** [tailwindlabs/headlessui#534]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0

### What browser are you using?

Mobile Chrome and Safari

### Reproduction repository

https://codesandbox.io/s/headlessuivue-dialog-example-forked-9mmpx

### Describe your issue

When using the example code from headlessui.dev, the dialog is not centered and has an unexpected vertical scroll.

Chrome and Safari on iPhone is having the issue. Brave and Firefox work fine.

Open this codesandbox reproduction link on mobile Chrome or Safari: https://9mmpx.csb.app/

Video: https://streamable.com/k8xawq

**Comment by nickw** [comment]
I'm experiencing this as well in a production app running in Safari on macOS. @pingustar were you able to track down the source of this? Or figure out a workaround?

**Comment by pingustar** [comment]
I am still in development of the app so I have put it on the side for now. But in about two weeks I will have to revisit this problem. Let me know if you find a fix @nickw  - I'll do the same :)

> I'm experiencing this as well in a production app running in Safari on macOS. @pingustar were you able to track down the source of this? Or figure out a workaround?

**Comment by joshuajung** [comment]
This is likely due to the `min-h-screen` in https://github.com/tailwindlabs/headlessui/blob/345f1b6e6b817ba0872653a6358ba97286f09574/packages/%40headlessui-react/pages/dialog/dialog.tsx#L75, which on mobile doesn't take into account the space occupied by the window chrome. Replacing it with `absolute inset-0` seems to work for the moment, though it may cause issues once there is too much content in the alert.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is more of a styling issue and not a Headless UI bug. The `h-screen` resolves to a `height: 100vh` which has some quirks on mobile Safari.
You can try this postcss plugin that should help you with this: https://github.com/postcss/postcss-100vh-fix

**Comment by nickw** [comment]
@RobinMalfait to be clear, this happens in desktop Safari as well. Although I suppose it's possible the same `100vh` quirk occurs in both versions.
