### ISSUE TITLE
[Bug]: Opening a portal in a Dialog has unexpected focus behaviour

### ISSUE THREAD

**Issue by evangeline** [tailwindlabs/headlessui#540]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headlessuireact-listbox-example-forked-54rx0?file=/src/App.js

### Describe your issue

I use portal (custom implementation as seen in the sandbox) and popper (react-popper + popperjs) to style anything that pops up, including a select component. While this may sound a little overkill, I found that it's resulted in the most consistent UX + DX where we don't have to worry about overflow-hidden or other weird positioning quirks. Happy to debate this if necessary. 

I've just migrated my select component to the Headless' Listbox component in this library and everything works fine, until I tried migrating my modal component to the Headless' Dialog component. There are two issues:

1. Opening the Listbox doesn't trigger the usual Listbox focus behaviour, eg you don't change the focus of a Listbox Option with up and down key press.
2. Selecting an item in the Listbox closes the Dialog when it should not

As I've been portaling my components manually, I am able to tweak the code such that it portals into the same div as the Dialog. Tried replicating the behaviour of nested Dialogs that Robin posted [here](https://codesandbox.io/s/headlessui-dialog-multiple-modals-bugs-forked-o2ykb) but couldn't get anywhere. Is there a workaround for this?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Yep, the Dialog component is very strict in the sense that you are not allowed to interact with content outside of it. We also use `role="modal"` which already marks content outside of the `Dialog` as inert for people that use screenreaders. 

Long story short, we also export a `Portal` component in Headless UI. I've updated your CodeSandbox here where we make use of the built-in `Portal` component.
https://codesandbox.io/s/headlessuireact-listbox-example-forked-ff6l3?file=/src/Select.js

Will this work for you?

**Comment by evangeline** [comment]
Yes it works! Thanks for the quick response :)
