### ISSUE TITLE
[Bug]: Can't contain comments in `template` component

### ISSUE THREAD

**Issue by FujishigeTemma** [tailwindlabs/headlessui#549]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome 90.0.4430.212（Official Build） （x86_64）

### Reproduction repository

https://github.com/FujishigeTemma/headlessui-vue-comment-reproduction

### Describe your issue

I want to write comments in code without worrying about a component's type.
But in Vue,  comments are also treated as a node so that I can't comment in `template` components as mentioned [here](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/utils/render.ts#L106).
I figured I could just filter out the nodes with `type=Symbol(Comment)`, but please let me know if there are any problems.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

My main question would be, why would you want to do this? https://github.com/FujishigeTemma/headlessui-vue-comment-reproduction/blob/main/src/App.vue#L28

If you provide an `as="template"` than you have to provide an actual element as the children.

If you did this, then it would also crash:

```vue
       <ListboxOption
          v-for="person in people"
          :key="person"
          :value="person"
          :disabled="person.unavailable"
          as="template"
        >
          {{ person.name }}
        </ListboxOption>
```

Some options that would work:

```vue
       <ListboxOption
          v-for="person in people"
          :key="person"
          :value="person"
          :disabled="person.unavailable" /* We removed the `as="template"` */
        >
          <!-- some comment -->
          {{ person.name }}
        </ListboxOption>
```

Or use an actual element:

```vue
       <ListboxOption
          v-for="person in people"
          :key="person"
          :value="person"
          :disabled="person.unavailable"
          as="li"
        >
          <!-- some comment -->
          {{ person.name }}
        </ListboxOption>
```

Or use an actual element as children in case of `as="template"`:

```vue
       <ListboxOption
          v-for="person in people"
          :key="person"
          :value="person"
          :disabled="person.unavailable"
          as="template"
        >
          <li>
            <!-- some comment -->
            {{ person.name }}
          </li>
        </ListboxOption>
```

**Comment by FujishigeTemma** [comment]
@RobinMalfait  Thank you for your answer😃 

The sample code was written just for reproduction, not for any particular situation where I would want to use `as="template"`.
The point of the issue I intended is that comments should not affect the behavior of the code. (It is also true that comments are treated as nodes though.)

This is a kind of question, not a strong opinion, so it would be great to hear some more opinions on this point.
