### ISSUE TITLE
[Bug]: Headless UI Docs for Vue

### ISSUE THREAD

**Issue by ninjaparade** [tailwindlabs/headlessui#562]
### What package within Headless UI are you using?

@headless/vue

### What version of that package are you using?

N/a

### What browser are you using?

N/a

### Reproduction repository

N/a

### Describe your issue

The docs show code samples that have incorrect reference to variable names.

[Here](https://headlessui.dev/vue/transition#co-ordinating-multiple-transitions)
`isOpen` is used but not in the actual code.

![image](https://user-images.githubusercontent.com/228899/119385605-302a2600-bc7b-11eb-8415-ebf582a6c37c.png)

[here](https://headlessui.dev/vue/transition#transitioning-on-initial-mount)
The same error is made `isOpen` is used but not referenced in the code below

![image](https://user-images.githubusercontent.com/228899/119385706-636cb500-bc7b-11eb-9f79-1faf19e51718.png)

**Comment by simonswiss** [comment]
Thanks for this! I have fixed those + a third one I found on the same page 👍
