### ISSUE TITLE
[Bug]: Listbox requires an index and not a object for it to work properly

### ISSUE THREAD

**Issue by nimabrownlee** [tailwindlabs/headlessui#585]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://headlessui.dev/react/listbox

### Describe your issue

I've linked to the documentation because I think it's enough to explain the issue. Right now, to choose an active item in the list, you have to use the index.

```
const people = [
  { name: 'Wade Cooper' },
  { name: 'Arlene Mccoy' },
  { name: 'Devon Webb' },
  { name: 'Tom Cook' },
  { name: 'Tanya Fox' },
  { name: 'Hellen Schmidt' },
]
```

Now for me to select the first item, I have to do it like this:

`const [selected, setSelected] = useState(people[0])`

This doesn't work:

 `const [selected, setSelected] = useState({ name: 'Wade Cooper' })`
 
 The problem for me is that I set the active item in another component. Don't know how to solve this.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We don't require an index, but we do require the same identity. Internally we are using `===` to find the selected item in the list. This means that if you do something like this:

```js
const people = [
  { name: 'Wade Cooper' },
  { name: 'Arlene Mccoy' },
  { name: 'Devon Webb' },
  { name: 'Tom Cook' },
  { name: 'Tanya Fox' },
  { name: 'Hellen Schmidt' },
]

// ...

useState({ name: 'Wade Cooper' })
```

That you are comparing 2 objects `{ name: 'Wade Cooper' } === { name: 'Wade Cooper' }` but this is a new object and thus not the same reference.

If you are setting the selected item in another component, just make sure that you are using the same reference. 

You can do something like this that maintains the same reference:

```js
function Component() {
  let [people, setPeople] = useState(...); // This data can come from an API or something
  let [selectedPerson, setSelectedPerson] = useState(null);

  return <MyStyledListbox  value={value} onChange={onChange} />
}

function MyStyledListbox({ value, onChange }) {
  return <Listbox  value={value} onChange={onChange}>{/* ... */}</Listbox>
}
```
