### ISSUE TITLE
[Bug]: Dependency 'react-dom' is not listed

### ISSUE THREAD

**Issue by govizlora** [tailwindlabs/headlessui#595]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

N/A

### Reproduction repository

https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

### Describe your issue

We are using yarn v2 as our package manager, and since it strictly requires dependencies to be listed, we hit this error during build:
```
ERROR in ../../.yarn/__virtual__/@headlessui-react-virtual-d1a940d68d/0/cache/@headlessui-react-npm-1.2.0-f43a69a877-d61e49e135.zip/node_modules/@headlessui/react/dist/headlessui.esm.js 2:0-41
Module not found: Error: Can't resolve 'react-dom' in '/Users/youyang/repos/bclad/.yarn/__virtual__/@headlessui-react-virtual-d1a940d68d/0/cache/@headlessui-react-npm-1.2.0-f43a69a877-d61e49e135.zip/node_modules/@headlessui/react/dist'
```

It's caused by `react-dom` being imported in some files (such as `packages/@headlessui-react/src/components/portal/portal.tsx`), while it's not listed in either dependencies nor peerDependencies. A detailed explanation from Yarn can be found here: https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

Though it's possible for the users to ignore them temporarily by configuring `packageExtensions` in Yarn, it's better to be fixed here so it works out of box

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
