### ISSUE TITLE
Dialog: Unable to disable "outside click" behavior

### ISSUE THREAD

**Issue by paulwongx** [tailwindlabs/headlessui#621]
Is there an option to disable "outside click" behaviour? For example, I'd like to keep the dialog opened when click outside. It would be great if we can have the condition inside the useWindowEvent function.

_Originally posted by @wengtytt in https://github.com/tailwindlabs/headlessui/pull/212#issuecomment-841353081_

There also seems to be multiple feature requests regarding this. Is there a way to override this default behavior currently?

**Comment by molteber** [comment]
You can make it `static` and decide when to show the component yourself by using the close method

a react example could be something like this

```jsx
const foo = () => {
  const [isOpen, setIsOpen] = useState(false);
  
  return (
    <>
      {!isOpen && (
        <button onClick={() => setIsOpen(true)}>Open dialog</button>
      )}
      {isOpen && (
        <Dialog static open={isOpen} onClose={() => setIsOpen(false)}>
          // ...
        </Dialog>
      )}
  );
}
```

> The `open` prop is still used for manage scroll locking and focus trapping, but as long as `static` is present, the actual element will always be rendered regardless of the `open` value, which allows you to control it yourself externally.

You can read more about it under [Transitions](https://headlessui.dev/react/dialog#transitions)
(See the last code example, right before Accessibility notes)

**Comment by dickerstu** [comment]
I only needed to set the onClose to null using the solution from @wengtytt for this to work. Adding the static property kept the custom close events from working.

```
<Dialog
    // ...
    onClose={() => null}>
</Dialog>
```

**Comment by paulwongx** [comment]
> Hi there, I forgot to post my solution for this problem. The trick is not the `static` property. Even you provide the `static` property, the `onClose` is still triggered when user clicks outside. (The ideal solution will be a property to disable the listener for clicking outside)
> 
> To solve the problem, we can provide an empty function as the `onClose` function and use `static` property with custom function to handle open and close for the modal.
> 
> ```js
> <Dialog
>     // ...
>     static
>     onClose={() => null}>
> </Dialog>
> ```

Amazing. This works. Thank you!

**Comment by molteber** [comment]
> Hi there, I forgot to post my solution for this problem. The trick is not the `static` property. Even you provide the `static` property, the `onClose` is still triggered when user clicks outside. (The ideal solution will be a property to disable the listener for clicking outside)
> 
> To solve the problem, we can provide an empty function as the `onClose` function and use `static` property with custom function to handle open and close for the modal.
> 
> ```js
> <Dialog
>     // ...
>     static
>     onClose={() => null}>
> </Dialog>
> ```

Oh 🤦‍♂️ I might've forgotten what i did to solve this.

Maybe i solved this myself by exchanging the overlay component with my own div, setting aria-hidden="true" and using the same classes.

That way you don't loose out on the close on esc etc.
However, not sure if this has other drawbacks (by not using the provided overlay component)

**Comment by iambryanhaney** [comment]
Bypassing `onClose` will require you to set up your own keyboard listener to capture the `esc` key.

If we look in `dialog.tsx`, we can see that there is a mouseDown event listener on the window itself, which closes the Dialog if the event emitter is not a descendant of it.

```
useWindowEvent('mousedown', event => {
    let target = event.target as HTMLElement

    if (dialogState !== DialogStates.Open) return
    if (hasNestedDialogs) return
    if (internalDialogRef.current?.contains(target)) return

    close()
})
```

Simple solution: add `pointer-events: none` to the `Dialog.Overlay`...

Inline: `style={{ pointerEvents: 'none' }}`
Tailwind: `className="pointer-events-none"`

...which will effectively disable click events outside of the Dialog's body.

If you have other interactive elements higher in the z-index, such as a toast notification, you can capture the `mouseDown` event in that element (while still listening for onClick) and prevent it from bubbling to the Dialog's window listener:

```
// In your toast notification component...
{/* eslint-disable-next-line jsx-a11y/no-static-element-interactions */}
<div onMouseDown={(e) => e.stopPropagation()}>
```

Notes on the eslint disable:  https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md#case-the-event-handler-is-only-being-used-to-capture-bubbled-events

**Comment by paulwongx** [comment]
> Bypassing `onClose` will require you to set up your own keyboard listener to capture the `esc` key.
> 
> If we look in `dialog.tsx`, we can see that there is a mouseDown event listener on the window itself, which closes the Dialog if the event emitter is not a descendant of it.
> 
> ```
> useWindowEvent('mousedown', event => {
>     let target = event.target as HTMLElement
> 
>     if (dialogState !== DialogStates.Open) return
>     if (hasNestedDialogs) return
>     if (internalDialogRef.current?.contains(target)) return
> 
>     close()
> })
> ```
> 
> Simple solution: add `pointer-events: none` to the `Dialog.Overlay`...
> 
> Inline: `style={{ pointerEvents: 'none' }}`
> Tailwind: `className="pointer-events-none"`
> 
> ...which will effectively disable click events outside of the Dialog's body.
> 
> If you have other interactive elements higher in the z-index, such as a toast notification, you can capture the `mouseDown` event in that element (while still listening for onClick) and prevent it from bubbling to the Dialog's window listener:
> 
> ```
> // In your toast notification component...
> {/* eslint-disable-next-line jsx-a11y/no-static-element-interactions */}
> <div onMouseDown={(e) => e.stopPropagation()}>
> ```
> 
> Notes on the eslint disable: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md#case-the-event-handler-is-only-being-used-to-capture-bubbled-events

Wow you're absolutely right - esc key not working is an issue with the onclick={()=>null} solution. This should be the accepted answer! Many thanks!

**Comment by sujin-lifology** [comment]
static
    onClose={() => null}> 

this solution doesn't work for me , 
my problem is if i click outside the dialog it never goes away but i can click the outside buttons and it is working when the modal is not even not closed. 

anyone help?

**Comment by sujin-lifology** [comment]
you can also return the empty obj, it prevents the outside click !
 onClose={() => {} }>

**Comment by Rasul1996** [comment]
> Bypassing `onClose` will require you to set up your own keyboard listener to capture the `esc` key.
> 
> If we look in `dialog.tsx`, we can see that there is a mouseDown event listener on the window itself, which closes the Dialog if the event emitter is not a descendant of it.
> 
> ```
> useWindowEvent('mousedown', event => {
>     let target = event.target as HTMLElement
> 
>     if (dialogState !== DialogStates.Open) return
>     if (hasNestedDialogs) return
>     if (internalDialogRef.current?.contains(target)) return
> 
>     close()
> })
> ```
> 
> Simple solution: add `pointer-events: none` to the `Dialog.Overlay`...
> 
> Inline: `style={{ pointerEvents: 'none' }}` Tailwind: `className="pointer-events-none"`
> 
> ...which will effectively disable click events outside of the Dialog's body.
> 
> If you have other interactive elements higher in the z-index, such as a toast notification, you can capture the `mouseDown` event in that element (while still listening for onClick) and prevent it from bubbling to the Dialog's window listener:
> 
> ```
> // In your toast notification component...
> {/* eslint-disable-next-line jsx-a11y/no-static-element-interactions */}
> <div onMouseDown={(e) => e.stopPropagation()}>
> ```
> 
> Notes on the eslint disable: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md#case-the-event-handler-is-only-being-used-to-capture-bubbled-events

This is exactly what i was looking for, many thanks !!!

**Comment by ponnamkarthik** [comment]
I tried the same solution in vue but its not working

**Comment by tolerance-go** [comment]
```tsx
               <Dialog
                  ref={containerRef}
                  as='div'
                  className='relative z-10'
                  onClose={() => {}}
                  onClick={(event) => {
                     /**
                      * disable Close modal when click outside of modal
                      */
                     if (
                        isElementChild(
                           containerRef.current!,
                           event.target as HTMLElement,
                        )
                     ) {
                        closeModal()
                     }
                  }}
               >
```

I use this method to solve the nested modal situation

**Comment by sujin-lifology** [comment]
> ```tsx
>                <Dialog
>                   ref={containerRef}
>                   as='div'
>                   className='relative z-10'
>                   onClose={() => {}}
>                   onClick={(event) => {
>                      /**
>                       * disable Close modal when click outside of modal
>                       */
>                      if (
>                         isElementChild(
>                            containerRef.current!,
>                            event.target as HTMLElement,
>                         )
>                      ) {
>                         closeModal()
>                      }
>                   }}
>                >
> ```
> 
> I want to close the modal on click outside, but I use this method to solve the nested modal situation

That's the solution that worked for me i mentioned above

**Comment by brandalx** [comment]
i had same error so i tried to solve my way and this actually work 
i did this by removing the style of pointer events like so:

`  onClose: () => {
    set({ type: null, isOpen: false });

    // Delay restoring pointer events for 2 seconds
    setTimeout(() => {
      document.body.style.pointerEvents = "auto";
    }, 1000);
  },
}));`

Note, i did it with small timeout to make sure that first all modal scripts are completed and then im manually removing that. Hope it helps!

**Comment by ramialkaro** [comment]
> Bypassing `onClose` will require you to set up your own keyboard listener to capture the `esc` key.
> 
> If we look in `dialog.tsx`, we can see that there is a mouseDown event listener on the window itself, which closes the Dialog if the event emitter is not a descendant of it.
> 
> ```
> useWindowEvent('mousedown', event => {
>     let target = event.target as HTMLElement
> 
>     if (dialogState !== DialogStates.Open) return
>     if (hasNestedDialogs) return
>     if (internalDialogRef.current?.contains(target)) return
> 
>     close()
> })
> ```
> 
> Simple solution: add `pointer-events: none` to the `Dialog.Overlay`...
> 
> Inline: `style={{ pointerEvents: 'none' }}` Tailwind: `className="pointer-events-none"`
> 
> ...which will effectively disable click events outside of the Dialog's body.
> 
> If you have other interactive elements higher in the z-index, such as a toast notification, you can capture the `mouseDown` event in that element (while still listening for onClick) and prevent it from bubbling to the Dialog's window listener:
> 
> ```
> // In your toast notification component...
> {/* eslint-disable-next-line jsx-a11y/no-static-element-interactions */}
> <div onMouseDown={(e) => e.stopPropagation()}>
> ```
> 
> Notes on the eslint disable: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md#case-the-event-handler-is-only-being-used-to-capture-bubbled-events

The version UI 1.6 have been depreacted the Dialog.Overlay.  https://headlessui.com/react/dialog#dialog-overlay

At least with version 1.7.17 the issue it not happen.

**Comment by afterxleep** [comment]
I'm using vue and a clean solution is to put a fixed backdrop that covers the entire screen and make that part of the DialogPanel.

This works for me.

```
<template>
  <TransitionRoot as="template" :show="open">
    <Dialog class="relative z-10" @close="onClose">      
      <DialogPanel>
        <TransitionChild as="template" enter="ease-out duration-300" enter-from="opacity-0" enter-to="opacity-100" leave="ease-in duration-200" leave-from="opacity-100" leave-to="opacity-0">
          <div class="pointer-events-none fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
        </TransitionChild>
        <div id="backdrop" class="fixed inset-0 z-10 w-screen overflow-y-auto">
          <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <TransitionChild as="template" enter="ease-out duration-300" enter-from="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" enter-to="opacity-100 translate-y-0 sm:scale-100" leave="ease-in duration-200" leave-from="opacity-100 translate-y-0 sm:scale-100" leave-to="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
              <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">              
                <div class="bg-white pt-1 px-5 pb-4 border-b">  
                  <img class="h-12" :src="logo" />
                </div>              
                <div class="bg-white px-4 pb-4 pt-2 sm:p-4 sm:pb-4">               
                  <div class="sm:flex sm:items-start">                  
                    <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                      <DialogTitle as="h3" class="text-base font-semibold leading-6 text-red-600">Are you sure?</DialogTitle>
                      <div class="mt-2 pb-2 mr-3">
                        <p class="text-sm text-gray-500">Closing this will cancel your account</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                  <button type="button" class="inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto" @click="onSkip">Skip</button>
                  <button type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto" @click="onExit" ref="cancelButtonRef">Cancel</button>
                </div>
              </div>
            </TransitionChild>
          </div>
        </div>
    </DialogPanel>
    </Dialog>
  </TransitionRoot>
</template>
```

**Comment by afterxleep** [comment]
The `pointer-events-none` did not work for me on 1.7, so I'm just moving the backdrop to be part of the `DialogPanel`.  This way, there are no clicks outside :).

```
<template>
  <TransitionRoot as="template" :show="open">
    <Dialog class="relative z-10" @close="onClose">      
      <DialogPanel>
        <TransitionChild as="template" enter="ease-out duration-300" enter-from="opacity-0" enter-to="opacity-100" leave="ease-in duration-200" leave-from="opacity-100" leave-to="opacity-0">
          <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
        </TransitionChild>
        <-- Fixed backdrop here -->
        <div id="backdrop" class="fixed inset-0 z-10 w-screen overflow-y-auto">          
          ...rest of your dialog content
        </div>
    </DialogPanel>
    </Dialog>
  </TransitionRoot>
</template>
```

If you want to also prevent the ESC key handler, you can add a key listener with capture mode:

With Vue, it'd be something like this.
```
function keyPress(e) {
  if (e.key === "Escape") {
    console.log("Escape key pressed");
    e.stopImmediatePropagation();
  }
}

onMounted(() => {
  console.log("mounted");
  window.addEventListener('keydown', keyPress, true); // 'true' enables capture mode
});

onUnmounted(() => {
  console.log("unmounted");
  window.removeEventListener('keydown', keyPress, true);
});
```

**Comment by sko-kr** [comment]
Just make DialogPanel fullscreen, then add dialog content div as a direct child of DialogPanel and style that as though it is DialogPanel.

**Comment by benfoster** [comment]
What is the solution for this on v2?

**Comment by twhitbeck** [comment]
Indeed, setting `pointer-events: none` on the backdrop no longer works for v2, at least if you're following the recommendation of making the backdrop a sibling of the panel: https://headlessui.com/react/dialog#adding-a-backdrop
Could we please get an option for this in the dialog component? `closeOnOutsideClick?: boolean`?
