### ISSUE TITLE
[Bug]: Switch doesn't "switch" when Enter is pressed

### ISSUE THREAD

**Issue by AnnaYuS** [tailwindlabs/headlessui#629]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://headlessui.dev/vue/switch

### Describe your issue

Switch doesn't "switch" when it's focused and Enter is pressed. It doesn't work in the preview on headlessui site and it doesn't work in my local project.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is by design, it only toggles using the `space` key or on click. 
This is also how native `input[type=checkbox]` works: https://jsfiddle.net/4165xeyb/
