### ISSUE TITLE
Allow to place Listbox.Options above the Listbox.Button

### ISSUE THREAD

**Issue by Mojeer0** [tailwindlabs/headlessui#63]
When the Listbox is at the bottom of the screen it would be nice to be able to place it above Listbox.Button.

It might already be possible, but I didn't find a way to style the div generated by Listbox.Options that contains the ul node (`<div class="absolute mt-1 w-full rounded-md bg-white shadow-lg">`).
Even if possible it would be nice to have headlessui figure out the best positioning (above or below) depending on the ListBox.Button position on the screen.

An other issue of not being able to put Listbox.Options above is that when the Listbox is placed at the bottom of the page, opening it will increase the scrollable area.

https://codesandbox.io/s/headlessuireact-listbox-example-forked-lu7b8?file=/src/App.js:2409-2415

A naive way to detect a good placement could look like:
 ```
function computePlacement(buttonRef) {
    const optionsHeight = optionsRef.current.offsetHeight;

    const bounding = buttonRef.current.getBoundingClientRect();
    const spaceBellow = window.innerHeight - bounding.bottom;
    const spaceAbove = bounding.top;

    return (
        spaceBellow > optionsHeight
        || spaceBellow > spaceAbove
    ) ? "bellow" : "above";
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is similar to your other issue #59 and the same answer applies.

But if you know that it is going to be at the bottom anyway, then you can replace the className on your Transition component: https://codesandbox.io/s/headlessuireact-listbox-example-forked-dmton

```diff
- className="absolute mt-1 w-full rounded-md bg-white shadow-lg"
+ className="absolute mb-1 w-full rounded-md bg-white shadow-lg bottom-full"
```

**Comment by MrEmelianenko** [comment]
I don't know if it'll be helpful to anybody or not, but I've figured out this code to keep original listbox style, and it works like a charm:

```javascript
<Transition
  show={open}
  as={Fragment}
  leave="transition ease-in duration-100"
  leaveFrom="opacity-100"
  leaveTo="opacity-0"
  className={classNames(
    "absolute z-50 w-full bg-white shadow-lg max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm",
    showAbove ? "mb-1 bottom-full" : "mt-1 top-full",
  )}
>
  <Listbox.Options
    ...
```

**Comment by 0radek** [comment]
Not able to add className to Transition.

**Comment by 0radek** [comment]
@MrEmelianenko doesn't seem like I can add className to Transition

**Comment by geyuqiu** [comment]
eslint and tslint ignore works
