### ISSUE TITLE
[Bug]: disclosure broken with naitve details and summary

### ISSUE THREAD

**Issue by NikitaIT** [tailwindlabs/headlessui#631]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0

### What browser are you using?

N/A

### Reproduction repository

gif exemple in body

### Describe your issue

1) Set native html5 controls on any Disclosure:
```
Disclosure as="details"
DisclosureButton as="summary"
```
2) Try Open by click and by Space/Enter with Tabulation
3) Disclosure not works

P.S. `<details open>` but slot is `open===false` and `<details>` but slot is `open===true`.

![45](https://user-images.githubusercontent.com/16810067/122748674-c5c1d100-d28c-11eb-82e7-b26f16a35ff7.gif)

```
 <Disclosure as="details" class="lalala" v-slot="{ open }">
    <DisclosureButton
      as="summary"
      class="lalala"
      :class="{ 'text-primary': open }"
    >
      <span>{{ name }}</span>
      <ChevronUpIcon
        :class="open ? 'transform rotate-180' : ''"
        class="w-5 h-5 text-primary"
      />
    </DisclosureButton>
      <DisclosurePanel class="lalala">
        <slot />
      </DisclosurePanel>
  </Disclosure>
</template>
<script lang="ts">
import { defineComponent } from "vue";
import { Disclosure, DisclosureButton, DisclosurePanel } from "@headlessui/vue";
import { ChevronUpIcon } from "@heroicons/vue/solid";

export default defineComponent({
  name: "MyDisclosure",
  components: {
    Disclosure,
    DisclosureButton,
    DisclosurePanel,
    ChevronUpIcon,
  },
  props: {
    name: {
      type: String,
      required: true,
    },
  },
});
</script>

```

**Comment by NikitaIT** [comment]
Now i use native details and its works fine. 
Why do we even need this element in the library if the native one works the same or better?

**Comment by LoganDark** [comment]
> Now i use native details and its works fine.
> Why do we even need this element in the library if the native one works the same or better?

This is meant as a replacement for the native one where you can add custom styles, a different HTML structure, animations, etc.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Our components are alternatives to native elements where you can apply styling as mentioned by @LoganDark.
details/summary cannot be styled in the same way so this is a good alternative to use.
However, details/summary have their own "state" built in, so it won't work when you want to combine it with this library.

That said, you can think of it as using our `Listbox` with a `<Listbox as="select" />`, which also doesn't really make sense.
