### ISSUE TITLE
[Bug]: RadioGroup with a focusable element within will also be focused, when inner element is focused

### ISSUE THREAD

**Issue by phuhl** [tailwindlabs/headlessui#659]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

Firefox

### Reproduction repository

https://github.com/phuhl/tailwind-bug

### Describe your issue

When I focus the radio group I can navigate with the arrow keys and the focus ring is on the radio knob, as everything should.

But when I tab to the button within the radio group, both, the button and the corresponding radio knob have a focus ring. My expectation is, that only the button is focused, not the radio knob as well. when repeatedly tabbing, the next button and corresponding radio knob will be focused.
![tailwind bug](https://user-images.githubusercontent.com/16835755/124273454-52e41000-db40-11eb-8aad-61a5efea14a1.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I would not recommend to nest form elements like this.
This is similar as putting a `button` inside an `<input>` field.

I would move the button outside of the actual radio group component.

**Comment by phuhl** [comment]
Thank you for the response, I gave it some thought and I can see where the recommendation comes from and it does make sense. But it also makes developing a bit more complex, where you have interactive elements within the radio element, especially when they are not always at a fixed position within the element.

So while generally a good idea to put other interactive elements outside, wouldn't it be better anyways if the active prop given to the radio elements would only be true, if the actual element is active?
