### ISSUE TITLE
[Bug]: Website (headlessui.dev) uses overflow-x-scroll rather than overflow-x-auto on Component API prop tables

### ISSUE THREAD

**Issue by LoganDark** [tailwindlabs/headlessui#661]
I tried to find a repository for your website, but could not, not even an issue tracker.

`overflow-x-scroll` (what you are currently using):
![image](https://user-images.githubusercontent.com/4723091/124345259-af6d1c80-db8c-11eb-9235-9bb25dcb8ec3.png)

`overflow-x-auto`:
![image](https://user-images.githubusercontent.com/4723091/124345268-c14ebf80-db8c-11eb-9105-48baa9b1ebb3.png)
![image](https://user-images.githubusercontent.com/4723091/124345282-d1669f00-db8c-11eb-821c-bba7ff4a7e51.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed now!

**Comment by guaiamum** [comment]
Hey, is the code for headlessui.dev open sourced? I was trying to get a look into the implementation of the [Overlay/Dialog](https://headlessui.dev/examples/react-dialog-hero) with the external trigger :)

**Comment by LoganDark** [comment]
> Hey, is the code for headlessui.dev open sourced? I was trying to get a look into the implementation of the [Overlay/Dialog](https://headlessui.dev/examples/react-dialog-hero) with the external trigger :)

Looks like the exact same example that is provided with source code on [the Dialog page](https://headlessui.dev/react/dialog).

**Comment by guaiamum** [comment]
Indeed! Thanks @LoganDark !
