### ISSUE TITLE
[Bug]: `<Popover>` component does not use forwardRef

### ISSUE THREAD

**Issue by LoganDark** [tailwindlabs/headlessui#664]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.3.0

### What browser are you using?

Chrome

### Reproduction repository

N/A

### Describe your issue

(Censored to protect confidentiality)

![image](https://user-images.githubusercontent.com/4723091/124388221-cac44e80-dc96-11eb-9a9c-860f7ddf8bad.png)

It looks like `Popover.Button` and friends use forwardRef, but not `Popover` itself.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

My question would be what your actual goal is exactly. The `Popover` by default renders a `Fragment` so there is nothing that can be attached to it.
Can you elaborate what your goal is?
There might be a more straightforward solution instead.

**Comment by LoganDark** [comment]
It's been a long time since I posted this issue but I think I was having to deal with a parent component that used `cloneElement` on its children. It tried to helpfully preserve refs, but as Popover was not forwardRef, even setting the ref to null (as it was) triggered an error.

**Comment by RobinMalfait** [comment]
Oops, I was wrong while responding to this issue. Most of the time we have the Root element render a Fragment just so that we can setup context providers and I assumed the same here.

It's true that all components have an `as` prop. I'm going to think about whether there is a downside of using `forwardRef` everywhere 🤔

**Comment by lifedup** [comment]
+1 forwardRef for transition. 

If you set the parent to `as={ Fragment }` it drops the `ref` in the child element. In order for the child to its `ref` you must set the `as` prop  on transition to a HTML element.

Forwarding refs would make this simpler.

**Comment by RobinMalfait** [comment]
This should be fixed by #1116, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.

**Comment by ginnymin** [comment]
> This should be fixed by #1116, and will be available in the next release.
> 
> 
> 
> You can already try it using:
> 
> - `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.

@RobinMalfait I recently ran into this issue at work with Tab - I tried out the fix and it works beautifully. Any idea when the next release is planned? Just need to know if I need to use another solution or if I can wait until the release :)
