### ISSUE TITLE
[Bug]: headlessui-portal-root disappears on navigation

### ISSUE THREAD

**Issue by evangeline** [tailwindlabs/headlessui#672]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.3.0

### What browser are you using?

Chorome

### Reproduction repository

NA

### Describe your issue

I'm currently using React Router for navigation and I noticed that on every other navigation, `headlessui-portal-root` disappears from by `index.html`'s `<body />`. This prevents anything that's being portaled with Headless from appearing. I've been digging into Headless' source code and it looks like if the Portal component doesn't detect any children, it removes the `<div id="headlessui-portal-root" />`. 

My question is, would this ever create a race condition between components being loaded into index.html and Portal checking for children? Or is this some other issue relating to routing? I've not really been able to reproduce this scenario in codesandbox because we have a huge repo and I've not been able to isolate this issue.

My current workaround is to hardcode `<div id="headlessui-portal-root" />` with a empty div child, but obviously this messes up with the ordering of the html elements.

**Comment by revh** [comment]
I'm also experiencing the same issue, it seems related to https://github.com/tailwindlabs/headlessui/issues/505

**Comment by exponent42** [comment]
https://github.com/tailwindlabs/headlessui/issues/505#issuecomment-894657289

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed in the latest version 👍
