### ISSUE TITLE
[Bug]: Headless Vue components break with kebob-case templates

### ISSUE THREAD

**Issue by zdb999** [tailwindlabs/headlessui#676]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0-105068

### What browser are you using?

Chrome

### Reproduction repository

https://www.youtube.com/watch?v=u1ZB_rGFyeU

### Describe your issue

Vue templetes can contain both PascalCase and kebob-case tags. Vue automatically converts PascalCase components to kebob-case, which is a more HTML-esque way to write a template, and I follow this style in my codebase.

However, certain Headless UI components break when converted from PascalCase to kebob-case. For example, when I convert a `<Dialog>` tag to a `<dialog>` tag, I get the following error when I try to render the page.

```
Uncaught (in promise) Error: <DialogOverlay /> is missing a parent <Dialog /> component.
```

This also occurs happens because `<dialog>` and `<menu>` are preexisting HTML tags, causing a naming clash. I think the best solution to this would be to create optional aliases for all Headless Vue components. For example, the `Dialog` component could become a `HeadlessDialog`  component, which would have a kebob-case tag of `<headless-dialog>`. This is in keeping with [Vue Style Guide](https://v3.vuejs.org/style-guide/) as well.

**Comment by adamwathan** [comment]
Hey! In this case we just recommend aliasing the component yourself when exposing it to your template:

```vue
<template>
  <poop-dialog>
    <!-- ... -->
  </poop-dialog>
</template>

<script>
import { Dialog, /* ... */ } from '@headlessui/vue'

export default {
  components: {
    PoopDialog: Dialog,
    // ...
  }
  // ...
}
</script>
```

No plans to change the actual component names or alias them ourselves just because it's so straightforward to do yourself, hope that's understandable — cheers! 💪

**Comment by zdb999** [comment]
Fair enough, you're right that this is an easy fix. It would be helpful to discuss this explicitly in the docs though, it took me quite a while to identify what was causing the problem.

**Comment by adamwathan** [comment]
Yeah that's a great point, I'll make a note to talk about that in the documentation 👍🏻
