### ISSUE TITLE
React 18 compatibility tracking issue

### ISSUE THREAD

**Issue by RobinMalfait** [tailwindlabs/headlessui#681]
### What package within Headless UI are you using?

@headlessui/react

### Describe your issue

Now that React 18 is out, it looks like some people are running into issues. This is because of `StrictMode` in React that does a [few extra things](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode) to ensure that your library works with Suspense.

Currently it looks like all our components work fine with React 18, except for the `Transition` component. It just happens that a lot of people use this component in combination with other components like our `Menu` or `Listbox` components.

We are aware of the issues and are working on fixes.

In the meantime, if you _need_ React 18 support, then you can temporarily disable `StrictMode`. If you are using something like Next.js, then you can disable it like this:

```js
const nextConfig = {
  reactStrictMode: false,
  // ...
};

module.exports = nextConfig;
```

This workaround is a **temporary** solution so that you can move forward with your work. `StrictMode` is a development tool anyway and we are working hard to have compatibility with React 18 really soon.

**Edited:** 5th of April, 2022

**Comment by samselikoff** [comment]
Just ran into this, took me a while to trace down! I was seeing a bug in my app - There are no focusable elements inside the <FocusTrap />.

Here's a repro: https://codesandbox.io/s/headless-ui-react-dialog-react-alpha-pvmd3?file=/src/App.js

Next + react alpha + latest headlessui + strict mode. Clicking the button shows the error - remove strict mode and it works.

**Comment by mellson** [comment]
I'm also seeing this using strict mode and React 18 RC. Can't use the `Menu` component since clicking it doesn't open the menu.

**Comment by matthewlilley** [comment]
Yeah, seems to be an issue with React 18 + strict mode. Disabling strict mode solves the issue for now.

**Comment by bmichotte** [comment]
Now that React 18 is out, I think it's time to bump this issue :D

**Comment by lynnntropy** [comment]
I think it'd be good to pin this issue now that React 18 is out. Maybe also put a note somewhere on https://tailwindui.com/? I spun up a new Next.js project yesterday and just spent a while debugging why some of my Tailwind UI components were broken 😅

**Comment by jlarmstrongiv** [comment]
React 18 seems to have broken npm install with peer dependencies:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @reactjs/example@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2" from @reactjs/example@1.0.0
npm ERR!   packages/reactjs/example
npm ERR!     @reactjs/example@1.0.0
npm ERR!     node_modules/@reactjs/example
npm ERR!       workspace packages/reactjs/example from the root project
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.5.0
npm ERR!   node_modules/@headlessui/react
npm ERR!     peer @headlessui/react@"^1.5.0" from @reactjs/example@1.0.0
npm ERR!     packages/reactjs/example
npm ERR!       @reactjs/example@1.0.0
npm ERR!       node_modules/@reactjs/example
npm ERR!         workspace packages/reactjs/example from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from react-dom@18.0.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^16 || ^17 || ^18" from @headlessui/react@1.5.0
npm ERR!   node_modules/@headlessui/react
npm ERR!     peer @headlessui/react@"^1.5.0" from @reactjs/example@1.0.0
npm ERR!     packages/reactjs/example
npm ERR!       @reactjs/example@1.0.0
npm ERR!       node_modules/@reactjs/example
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-03-31T02_17_07_266Z-debug.log
```

**Comment by bigint** [comment]
It's breaking again, react 18 is out now please make this issue a high priority one 🙏🏻

**Comment by martinnabhan** [comment]
Not sure how this can be circumvented considering it's the default behaviour of Strict Mode since React 18. We decided to disable Strict Mode for now, but would obviously prefer to keep it enabled.

The announcement says the component will have all of its previous state when it gets remounted, so maybe there is some kind of workaround.
>When a component get shown again after being hidden– it’s similar to being mounted again except that it will have all of its previous state.

Also please do keep in mind this only affects development environments, as Strict Mode doesn't run in production mode.

**Comment by maggo** [comment]
Can confirm this is also breaking in `nextjs@12.1.2` with `react@18` and `reactStrictMode: true` setting (which is required to use react 18 features)

**Comment by betomoedano** [comment]
## Work around
- at `next.config.js` change reactStrictMode: false

```
const nextConfig = {
  reactStrictMode: false,
};

module.exports = nextConfig;
```

**Comment by sidwebworks** [comment]
https://github.com/facebook/react/blob/main/CHANGELOG.md#breaking-changes 

Here if we have a look at the Strict Mode section, they talk about 
**"components to be resilient to remounting with existing state" **

**Comment by nenonja** [comment]
Can you also make nextjs 11 compatible with react-18? The reason we are still using nextjs 11 is that the styled components is not fully supported in nextjs 12, but we still would like to upgrade to react 18 on our project. Thanks!

**Comment by MAK-Denis** [comment]
Please comment here when it's update.

**Comment by haf** [comment]
Without strict mode, next js latest in dev mode, the select menu doesn't show all the items.

**Comment by RobinMalfait** [comment]
@samselikoff I've updated your CodeSandbox using the latest insiders build which should fix React 18 issues. https://codesandbox.io/s/headless-ui-react-dialog-react-alpha-forked-feooky Thanks for reporting!

**Comment by msdrigg** [comment]
Any word when we will get a release for this?

**Comment by M1ck0** [comment]
Works for me with react 18 with `insiders` version. Version `1.5.0` fo `headlessui` works only in production and not development.

**Comment by sapphirecity** [comment]
> Works for me with react 18 with `insiders` version. Version `1.5.0` fo `headlessui` works only in production and not development.
> 
> Is this stable enough for production, or should I revert back to `React 17` and `Headlessui 1.5.0`, or perhaps removing `StrictMode`

i think, swtich off StrictMode on dev & prod. and we just wait until headless updates for react v18!

**Comment by timfee** [comment]
+1 please to putting a notification on tailwindui.com -- not a super great experience as a paying member for that product to have something not work out of the box. thanks! :)

**Comment by bigint** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/69431456/164052865-6e76222e-a860-462e-9d68-b59712a4b16f.png">

@RobinMalfait I'm getting this in insiders version 😕

**Comment by RobinMalfait** [comment]
Hey @bigint, it looks like it is erroring on `startTransition` which is not something we have in our code anywhere so I doubt that it is Headless UI related. That said, as mentioned in the original issue if you are experiencing any other issues, then please open a new issue _with_ a minimal reproduction repo or CodeSandbox attached.

**Comment by M1ck0** [comment]
There is a problem with `1.6.0` with React 18. I get this error when opening modal with inputs and selects

```
Uncaught Error: Did you forget to passthrough the `ref` to the actual DOM node?
    at transition.js:1:1
    at commitHookEffectListMount (react-dom.development.js:22969:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24702:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24666:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24653:1)
    at commitPassiveMountEffects (react-dom.development.js:24641:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26848:1)
    at flushPassiveEffects (react-dom.development.js:26801:1)
    at performSyncWorkOnRoot (react-dom.development.js:25915:1)
    at flushSyncCallbacks (react-dom.development.js:11982:1)
```

Reverting back to `1.5.0` fixes the problem.

**Comment by RobinMalfait** [comment]
@M1ck0 can you open a new issue with a reproduction repo / CodeSandbox attached? Hard to debug otherwise.
