### ISSUE TITLE
[Bug]: Invalid Hooks Call when I used a Headless-UI Element

### ISSUE THREAD

**Issue by xiaooubai** [tailwindlabs/headlessui#689]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

7.13.0

### What browser are you using?

Chrome

### Reproduction repository

Unnecessary

### Describe your issue

I am currently trying to implement a React component using headless-ui. When I try the most basic example components off the documentation online, I get an error saying that it is an Invalid Hook Call. I have attached the error and code snippet below. Thank you!

`import { Menu } from '@headlessui/react'

function MyDropdown() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          {({ active }) => (
            <a
              className={`${active && 'bg-blue-500'}`}
              href="/account-settings"
            >
              Account settings
            </a>
          )}
        </Menu.Item>
        <Menu.Item>
          {({ active }) => (
            <a
              className={`${active && 'bg-blue-500'}`}
              href="/account-settings"
            >
              Documentation
            </a>
          )}
        </Menu.Item>
        <Menu.Item disabled>
          <span className="opacity-75">Invite a friend (coming soon!)</span>
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}`

![Screen Shot 2021-07-20 at 12 01 40 AM](https://user-images.githubusercontent.com/31837089/126263912-118ece8f-0d1c-4270-a79f-5385ce28b13f.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You probably have multiple version of React or similar going on.
It could be related to using workspaces, or something.

Without a minimal reproduction repository I can't help you.
