### ISSUE TITLE
Unexpected behavoir for Switch / Toggle on enter?

### ISSUE THREAD

**Issue by molteber** [tailwindlabs/headlessui#69]
Hi,
Things are looking great so far!

I noticed one thing about the switch component which feels like unwanted behavior on both React and Vue.

As a side-note, i compare the Switch component as a checkbox input.

When pressing spacebar on checkbox and switch component, the state toggles, as expected.
Holding it down, only changes state when releasing the space bar, as expected.

While pressing enter, it toggles on the switch component, but not on checkbox input. IMO doesn't really matter that you can toggle it with enter, so that's alright.

However, when holding down enter, it furiously toggles back and forth. If allowing to press enter, it should be considered to work the same way spacebar works (toggle on keyup, not on press/down)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It's a bug I fixed yesterday (https://github.com/tailwindlabs/headlessui/commit/fecd61dff6e08066f5577d7aa698f573736c1dfe) but I didn't release it yet. It will be in the next version!
