### ISSUE TITLE
[Bug]: headless UI TypeError - Vue Typescript project

### ISSUE THREAD

**Issue by elrDevelopment** [tailwindlabs/headlessui#695]
### What package within Headless UI are you using?

@headless/vue

### What version of that package are you using?

1.3.0

### What browser are you using?

firefox

### Reproduction repository

https://github.com/elrDevelopment/vue3-headlessui-test

### Describe your issue

Getting this error in the console - and the UI will not render (firefox or chromium)

![image](https://user-images.githubusercontent.com/38711500/126877553-d44edb9c-fc04-4fd5-b739-e62539eb5055.png)

I have placed the setup process I used for the repro repo in the readme.

Thanks

**Comment by elrDevelopment** [comment]
Everything works fine in a non-typescript vue project. Trying the setup again to see if I missed something.

**Comment by zzhenryquezz** [comment]
I think you not using vue 3 in this project, that was the headless-ui/vue work with

**Comment by elrDevelopment** [comment]
I think the vue3 comment fixes things.
