### ISSUE TITLE
[Docs]: Typo in docs for Tabs component (Vue package)

### ISSUE THREAD

**Issue by kerunix** [tailwindlabs/headlessui#706]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.4.0

### What browser are you using?

Not relevant

### Reproduction repository

Not relevant

### Describe your issue

There is a typo in the code examples for the new Tabs component.

In the live preview example (the one at the very top of the page) you use two `v-for` directives on lines 6 and 27 to loop through the `categories` array but you forgot to add the colon before the `key` attributes for the two loops. I know these attributes are not mandatory but the default eslint config for Vue will throw an error if they are missing so this is still a bit annoying.

```html
<Tab
  v-for="category in Object.keys(categories)"
  as="template"
  key="category" <!-- Missing colon here -->
  v-slot="{ selected }"
>

<TabPanel
  v-for="(posts, idx) in Object.values(categories)"
  key="idx" <!-- Same here -->
  :class="[
    'bg-white rounded-xl p-3',
    'focus:outline-none focus:ring-2 ring-offset-2 ring-offset-blue-400 ring-white ring-opacity-60',
  ]"
>
```

Not a big deal but still an issue I guess.

Would gladly have submitted a PR myself but I was told that this was the place to go to for anything docs related.

Thanks again for the great work !

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed and will be live very soon!
