### ISSUE TITLE
[Bug]: Transition call afterLeave multiple times

### ISSUE THREAD

**Issue by waiwai0308** [tailwindlabs/headlessui#714]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.0

### What browser are you using?

chrome

### Reproduction repository

none

### Describe your issue

Hi,

I use afterLeave function of Transition Component, I think that afterLeave function should be only call once when I add N Transition.child, but this Transition Component will call afterLeave function N+1 times.

For example:
```javascript
<Transition
    beforeLeave={()=>{
      console.log("parent beforeLeave");
    }}
    afterLeave={() => {
      console.log("parent afterLeave");
    }}
>
</Transition>
```
output:
parent beforeLeave
parent afterLeave

```javascript
<Transition
    beforeLeave={()=>{
      console.log("parent beforeLeave");
    }}
    afterLeave={() => {
      console.log("parent afterLeave");
    }}
>
   <Transition.Child
    afterLeave={() => {
      console.log("child 1 afterLeave");
    }}
   ></Transition.Child>
   <Transition.Child
    afterLeave={() => {
      console.log("child 2 afterLeave");
    }}
   ></Transition.Child>
</Transition>
```
output:
parent beforeLeave
child 1 afterLeave
child 2 afterLeave
parent afterLeave
parent afterLeave
parent afterLeave

Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1179, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
