### ISSUE TITLE
Open modal from dropdown menu item - no fade in animation

### ISSUE THREAD

**Issue by raburabur** [tailwindlabs/headlessui#719]
Hello.
I have some issue when I'm using modal with dropdown menu. When I want to open a dialog from standard button, everything works correct (dialog comes with nice fade in animation). But when I do the same from dropdown menu item, dialog comes but without animation. Just appears immediately.

Tested on newest versions of Chrome and Edge.

My dependencies:
- vue: 3.0.5
- headlessui/vue: 1.3.0
- tailwindcss": 2.2.4

Here is example showing the above issue:
https://pastebin.com/R8RrvN1S

**Comment by davidluhr** [comment]
@raburabur Transferring this over to Headless UI, which is where the Vue Dropdown and Modal components come from.

**Comment by prestonholt** [comment]
I'm also experiencing this issue. Please let me know if you find any workarounds

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Closing this in favor of #456.
