### ISSUE TITLE
[Bug]: Can't apply onClick handler to Menu.Button

### ISSUE THREAD

**Issue by shafkathullah** [tailwindlabs/headlessui#725]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.3.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headlessui-button-example-forked-nw288?file=/src/App.js

### Describe your issue

Can't access the onClick event of `Menu.Button` to call `event.stopPropagation`

**Comment by dayvista** [comment]
+1 to this. This is the missing link to making my UI work.

**Comment by shafkathullah** [comment]
I think its by design, one way to work around this is by wrapping a <button> with <Menu.Button as={React.Fragment}> and call stopPropogation from <button>. This is how I use currently

**Comment by shafkathullah** [comment]
I think its by design, one way to work around this is by wrapping a <button onClick={handleBtnClick}> with <Menu.Button as={React.Fragment}> and call stopPropogation from button. This is what I use at the moment.

**Comment by shafkathullah** [comment]
I think its by design, one way to work around this is by wrapping a <button onClick={handleBtnClick} /> with <Menu.Button as={React.Fragment}> and call stopPropogation from button. This is what I use at the moment.

**Comment by shafkathullah** [comment]
I think its by design, one way to work around this is by wrapping a < button onClick={handleBtnClick}> with <Menu.Button as={React.Fragment}> and call stopPropogation from button. This is what I use at the moment.
