### ISSUE TITLE
[Bug]: Focus trap on Popover inside a Dialog not working as expected.

### ISSUE THREAD

**Issue by emdavidmoreno** [tailwindlabs/headlessui#751]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/tailwind-css-and-react-forked-8hd53

### Describe your issue

I have a Dialog and inside that I created a Popover with several links inside . When the popover is open, and you try to navigate through the links using the keyboard (Tab key or Shift+Tab), if you are focused on Element(x),  the next focused element is not Element (x+1) for Tab, or Element(x-1) for Shift+Tab. Actually, the focus goes to Element(x+2) for Tab, and Element(x-2) for Shift+Tab.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This seems to be related to this issue: https://github.com/tailwindlabs/headlessui/issues/467 will close this one in favor of the other bug.
Thanks!
