### ISSUE TITLE
[Bug]: `initialFocus` with Modal and Vue nested slots erroneously triggers Focus Trap error

### ISSUE THREAD

**Issue by Cherry** [tailwindlabs/headlessui#764]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.4.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headlessui-modal-nested-slots-8y6i1?file=/src/components/ModalWrap.vue

### Describe your issue

This is a pretty complex one, but I've tried to illustrate as best as I can in the reproduction. (Please excuse the terrible CSS styles).

We use a _lot_ of reusable components in our UI, with lots of slots for replacing header/footer/content etc., and have been implementing the Modal into this. These reusable components allow us to nest slots from various components to create really complex but standardised UIs.

The example I've provided in the reproduction uses a `ModalWrapper` component, and a `Box` component. The `Box` component is emulating a UI component we use in lots of places, where we have some default styles/classes/colors etc. and then the `ModalWrapper` is emulating our wrapped `Modal` component, which re-uses this `Box` component to create a consistent UI experience.

When using these kind of nested `template` and `slot`s, it seems to cause an issue with the `FocusTrap` when you close the modal, when using the `initialFocus` ref passed through components.

- Page renders, fine.
- Open Modal, fine, and expected element is focused.
- Close Modal, `There are no focusable elements inside the <FocusTrap />` is thrown.

The one quick workaround we've found for this is by setting the `unmount` property to `false` (as can be seen [here](https://codesandbox.io/s/headlessui-modal-nested-slots-unmount-eiwpv?file=/src/components/ModalWrap.vue)), but we're not sure if this is good semantically.

**Comment by Cherry** [comment]
I think the symptom here will be hidden now with #775, though I'm still not sure exactly why it was being triggered with this setup.

**Comment by Chanceux-L** [comment]
If I don't want to get focus, what should I do?
