### ISSUE TITLE
Example links do not point to correct examples

### ISSUE THREAD

**Issue by ChristopherBilg** [tailwindlabs/headlessui#78]
At least on [this](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react), the example links don't point where they need to.

**Comment by adamwathan** [comment]
I just checked all of the example links and they seem fine. Do you mean something different than the CodeSandbox demo links? Each of those goes to the right demo currently.

The "Transition" one links to the same sandbox as Menu but that's deliberate — that example does use the Transition and we haven't made a separate demo for it at this point.

**Comment by ChristopherBilg** [comment]
Alright, I apologize. It must be something on my end then. It was indeed the transition, and then I _thought_ it was happening on all of them. Sorry for the time-waste.
