### ISSUE TITLE
[Bug]: Radio group does not check with a valued object

### ISSUE THREAD

**Issue by YuriFontella** [tailwindlabs/headlessui#789]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome, Firefox

### Reproduction repository

I believe that a repository is not necessary

### Describe your issue

I was passing the _item_ object within the _value_ and everything works perfectly.
I needed to pass a custom object so it is not checked and active when selected.

it works
```
<RadioGroup value={value} onChange={onChange}>
    <div className="relative bg-white rounded-md -space-y-px">
      {player.games.map((item, index) => (
        <RadioGroup.Option
          key={index}
          value={item}
          className={({ checked }) =>  classNames(...)}
        >
          {({ active, checked }) => (...)}
        </RadioGroup.Option>
      ))}
    </div>
  </RadioGroup>
```

does not work
```
<RadioGroup value={value} onChange={onChange}>
    <div className="relative bg-white rounded-md -space-y-px">
      {player.games.map((item, index) => (
        <RadioGroup.Option
          key={index}
          value={{ id: player.id, balance: player.balance, game_id: item.id }}
          className={({ checked }) =>  classNames(...)}
        >
          {({ active, checked }) => (...)}
        </RadioGroup.Option>
      ))}
    </div>
  </RadioGroup>
```

next: 11.1.2
tailwindcss: 2.2.9

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

We use the `===` operator to check equality. The reason it doesn't work for you is that `{ id: player.id, balance: player.balance, game_id: item.id }` is a completely new object and will never exist in your list.

Alternatively, I would recommend either using an object that _does_ exist in your list, or use a primitive value (like an `id`) as the value instead.

**Comment by YuriFontella** [comment]
Thanks for the quick feedback, and thanks so much for the explanation.
