### ISSUE TITLE
[Bug]:  jest react testing-library: TypeError: React.createContext is not a function

### ISSUE THREAD

**Issue by cgcullen** [tailwindlabs/headlessui#792]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/cgcullen/cindycullen

### Describe your issue

Using Next.js with typescript, tailwindui and @headlessui.  Run npm run test and get the error:

TypeError: React.createContext is not a function on the import { Popover, Transition} from "@headlessui/react"

Stack trace:

 at Object.<anonymous> (node_modules/@headlessui/react/src/internal/portal-force-root.tsx:9:30)
      at Object.<anonymous> (node_modules/@headlessui/react/dist/index.js:7:20)
      at Object.<anonymous> (components/MobileHeader.tsx:2:1)
      at Object.<anonymous> (pages/index.tsx:12:1)
      at Object.<anonymous> (__tests__/index.test.jsx:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As far as I can tell, this is not a Headless UI issue. I can run your tests if I do the following tests:
- Bump dependencies to latest versions (probably unnecessary, but did it anyway as a quick fix test)
- Remove the `'.'` in `moduleDirectories: ["node_modules", "."],` in your `jest.config.js`
- Update the imports in your `pages/index.tsx` to be relative:
```diff
diff --git a/pages/index.tsx b/pages/index.tsx
index 2a59d05..1a0d894 100644
--- a/pages/index.tsx
+++ b/pages/index.tsx
@@ -9,9 +9,9 @@ import {
   ServerIcon,
   ShieldCheckIcon,
 } from "@heroicons/react/outline"
-import MobileHeader from "components/MobileHeader"
-import Header from "components/Header"
-import Footer from "components/Footer"
+import MobileHeader from "../components/MobileHeader"
+import Header from "../components/Header"
+import Footer from "../components/Footer"
 
 const Home: NextPage = () => {
   const features = [
```

It seems that this is the culprit: `moduleDirectories: ['.']`, not 100% sure _why_ that is the culprit but doing these changes allows me to run the tests.

Here is a PR that fixes all of that: https://github.com/cgcullen/cindycullen/pull/1
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1834413/157773170-ff833ecf-3780-437e-8a73-ff1735b23c26.png">
