### ISSUE TITLE
[Bug]: Cannot call hooks inside Tab.Panel when panels are rendered using loop (Array.map)

### ISSUE THREAD

**Issue by FourLineCode** [tailwindlabs/headlessui#797]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.1

### What browser are you using?

Firefox developer edition

### Reproduction repository

http://github.com/fourlinecode/wavechat

### Describe your issue

```ts
const tabs = [
	{
		id: 'friends',
		title: 'Friends',
		component: FriendsList,
	},

	{ id: 'requests', title: 'Requests', component: Requestslist },
];

export function FriendsInfo() {
	return (
		<div className='w-64 h-full p-2 xl:w-80 bg-dark-800'>
			<Tab.Group>
				<Tab.List className='flex w-full overflow-hidden rounded-lg'>
					{tabs.map((tab) => (
						<Tab
							className={({ selected }) =>
								clsx(
									'flex-1 p-1.5 flex justify-center items-center bg-dark-700 transition focus:outline-none font-semibold text-lg',
									selected
										? 'bg-brand-500'
										: 'hover:bg-brand-300 hover:bg-opacity-30'
								)
							}
							key={tab.id}
						>
							{tab.title}
						</Tab>
					))}
				</Tab.List>
				<Tab.Panels>
					{tabs.map((tab) => (
						<Tab.Panel key={tab.id}>{tab.component}</Tab.Panel>
					))}
					{/* <Tab.Panel>
						<FriendsList />
					</Tab.Panel>
					<Tab.Panel>
						<Requestslist />
					</Tab.Panel> */}
				</Tab.Panels>
			</Tab.Group>
		</div>
	);
}
```
I am rendering Tab.Panels using Array.map, and each custom component inside is using hooks to make gql requests. but its causing error whenever i use any sort of hooks inside the component.
Resulted error: `Error: Rendered more hooks than during the previous render.`
even using a simple useEffect of useState is causing the error.

but the commented out code later which is manually added each tab panel works just fine.

i am wondering if i am doing something wrong or is this a bug, as i couldn't find any other solution.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You are rendering `{tab.component}`, but `tab.component` is referring to an actual Function/Component, not the resulting JSX. 
To fix this you should render it as:

```js
<Tab.Panel key={tab.id}><tab.component /></Tab.Panel/>
```
