### ISSUE TITLE
react readme has incorrect anchor for Transition

### ISSUE THREAD

**Issue by UmungoBungo** [tailwindlabs/headlessui#8]
lines 30 - 31 of headlessui/packages/@headlessui-react/README.md
`- [Transition](#menu-button-dropdown)`
`- [Menu Button (Dropdown)](#menu-button-dropdown)`

Should be
`- [Transition](#transitions)`
`- [Menu Button (Dropdown)](#menu-button-dropdown)`

With respect🤗

**Comment by simonswiss** [comment]
Hey @UmungoBungo, thanks for this - will fix!

**Comment by RobinMalfait** [comment]
Yep, thank you! Should be fixed now!
