### ISSUE TITLE
Transition not working in NextJs

### ISSUE THREAD

**Issue by puneetverma05** [tailwindlabs/headlessui#80]
It appears like Transition classes are not there initially on any div(`<Transition>`) 
Btw I'm using ( tailwindcss(^1.8.4) , styled-components & twin-macro)

Sample code I'm trying to test on my NextJs WebApp
![image](https://user-images.githubusercontent.com/3938044/95546051-34237380-0a1d-11eb-9432-41754105498b.png)

**Comment by idrisakmal** [comment]
Hi, not sure if its the same issue. I just faced this a minute ago, and the solution was to hoist the classes in the inner div to the `<Transition>`

initial:
```
<Transition
        show={showMenu}
        enter="transition duration-75 ease-in-out"
        enterFrom="transform translate-x-full"
        enterTo="transform translate-x-0"
        leave="transition duration-75 ease-in-out"
        leaveFrom="transform translate-x-0"
        leaveTo="transform translate-x-full"
      >
        <div className="bg-primary absolute right-0 h-screen w-full md:w-1/4 md:rounded-tl-lg shadow-xl">
              .......
        </div>
```

After
```
<Transition
        show={showMenu}
        enter="transition duration-500 ease-in-out"
        enterFrom="transform translate-x-full"
        enterTo="transform translate-x-0"
        leave="transition duration-500 ease-in-out"
        leaveFrom="transform translate-x-0"
        leaveTo="transform translate-x-full"
        className="bg-primary absolute right-0 h-screen w-full md:w-1/4 md:rounded-tl-lg shadow-xl"
      >
        <div className="p-8">
              ..........
        </div>
```

I think this is because the <Transition> component renders the child in another div. so having your classes there might solve it.

**Comment by puneetverma05** [comment]
@idrisakmal  I did try placing class as you mentioned but didn't work :( 
I think, maybe it is related to styled-components?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a reproduction via codesandbox? You can start from this example if you want: https://codesandbox.io/s/headlessuireact-menu-example-b6xje?file=/src/App.js

**Comment by andrewgbliss** [comment]
I am also having issues with the transition not working with NextJS. It works fine when I run it locally but when I push to netlify the transition doesn't work. The div doesn't have any classes on it.

`import { Transition } from '@headlessui/react';

export default function Cover() {
  return (
    <div className="bg-banner-bk text-white text-center md:text-left">
      <section>
        <Transition
          show={true}
          appear={true}
          enter="transition-opacity delay-500 duration-1000"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="transition-opacity duration-150"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="h-32" />
          <h1 className="pady">
            A New Way
            <br />
            To Start Business
          </h1>
          <p className="pady">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora
            dolor adipisci
            <br />
            dicta dolores qui quaerat iure cumque perspiciatis mollitia
            accusamus ex aliquam et.
          </p>
          <div className="pady">
            <button className="btn-primary">Get Started</button>
          </div>
          <div className="h-8 sm:h-16" />
        </Transition>
      </section>
    </div>
  );
}
`

**Comment by puneetverma05** [comment]
> Hey! Thank you for your bug report!
> Much appreciated! 🙏
> 
> Can you create a reproduction via codesandbox? You can start from this example if you want: https://codesandbox.io/s/headlessuireact-menu-example-b6xje?file=/src/App.js

Hey @RobinMalfai , sorry for the delay, busy week 📌 [here](https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-headless-ui-transition-30qrr?file=/pages/index.js) is the repro
you can able to see that Transition class is empty..
https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-headless-ui-transition-30qrr?file=/pages/index.js

**Comment by RobinMalfait** [comment]
@puneetverma05 

The transition currently works by reading the duration from the DOM. So this duration is defined by the `duration-100` class for example. However, when you use `twin.macro` the `duration-100` class doesn't exists, thus the duration will be 0 and immediately mounted/unmounted.

Essentially if you know how to generate a className form the macro then it should work 

```js
function magic(twinput) {} // This function should return a className

<Transition enter={magic(tw`...`)} leave={magic(tw`...`))} />
```

---

@andrewgbliss What do you mean with `The div doesn't have any classes on it.` which div are you referring to? The one `Transition` generates (when it is mounted) or another one?

**Comment by andrewgbliss** [comment]
> @puneetverma05
> 
> The transition currently works by reading the duration from the DOM. So this duration is defined by the `duration-100` class for example. However, when you use `twin.macro` the `duration-100` class doesn't exists, thus the duration will be 0 and immediately mounted/unmounted.
> 
> Essentially if you know how to generate a className form the macro then it should work
> 
> ```js
> function magic(twinput) {} // This function should return a className
> 
> <Transition enter={magic(tw`...`)} leave={magic(tw`...`))} />
> ```
> 
> @andrewgbliss What do you mean with `The div doesn't have any classes on it.` which div are you referring to? The one `Transition` generates (when it is mounted) or another one?

Yes the div that generates from the Transition component. It works fine on my local. But not on Netlify when I build NextJS, which may be an issue with those technologies.

**Comment by puneetverma05** [comment]
@RobinMalfait In future will headlessUI add support for twin macros (may be a headlessui plugin for tw)?

**Comment by RobinMalfait** [comment]
> @RobinMalfait In the future will headlessUI add support for twin macros (maybe a headlessui plugin for tw)?
> Something like this
> `` <Transition enter={tw`...`)} leave={tw`...`))} /> ``

I don't think so, doesn't really make sense to me. It would make more sense that `twin.macro` could generate a className dat you can put in the `enter`, `leave`, ... spots.

**Comment by puneetverma05** [comment]
@RobinMalfait hmm IMHO that will also not make sense either , twin.macro generates css objects from tailwind classes  & shares them styled-components/emotion. there is no need for twin macro in the first place to generate classNames altogether. 
BTW that would be troublesome to manage both classNames & styled-components.

**Comment by RobinMalfait** [comment]
@puneetverma05 It would be very weird that we should support *insert tools here*. That said, if it is not the responsibility of `twin.macro` but rather styled-components / emotion, then it is up to those tools to generate classNames. 

For example, when you use emotion (I don't know if styled-components exposes such an api) than you can do this: https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-headless-ui-transition-forked-p7hbe?file=/pages/index.js:1633-2041

**Comment by puneetverma05** [comment]
@RobinMalfait 100% agree on this, let me check if something similar I can find in styled-components like emotion's `css()`
Btw thanks for your help ✌

> @puneetverma05 It would be very weird that we should support _insert tools here_. That said, if it is not the responsibility of `twin.macro` but rather styled-components / emotion, then it is up to those tools to generate classNames.
> 
> For example, when you use emotion (I don't know if styled-components exposes such an api) than you can do this: https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-headless-ui-transition-forked-p7hbe?file=/pages/index.js:1633-2041

**Comment by ShuttleSantalex** [comment]
Hey there,

We have just decided to migrate our UI lib and are now using `twin.macro`. However, we have encountered the same issue as described above. We are also using styled-components. @puneetverma05  any luck  on your side?

**Comment by lopezjurip** [comment]
Since `twin.macro` is a macro (hence the name), many things happens in build time so you can't use `<Transition enter="transition-opacity delay-500 duration-1000" ...` just like that.

Here is how I fixed it using the default twin.macro setup (`emotion` behind the scenes):

```tsx
import { Transition } from "@headlessui/react";
import { css, cx } from "@emotion/css"; // <- this

// get classnames from style objects
const twClassNames = {
  enter: cx(css(tw`transition ease-out duration-100 transform`)),
  enterFrom: cx(css(tw`opacity-0 scale-95`)),
  enterTo: cx(css(tw`opacity-100 scale-100`)),
  leave: cx(css(tw`transition ease-in duration-75 transform`)),
  leaveFrom: cx(css(tw`opacity-100 scale-100`)),
  leaveTo: cx(css(tw`opacity-0 scale-95`)),
};

function App() {
  const [show, setShow] = useState(false);
  return (
    <Transition show={show} {...twClassNames}>
      {(ref) => ( ... )}
    </Transition>
  )
}
```

I hope headlessui implements function props while keeping support for strings. Eg: 
```tsx
// This is just an idea, do not use this code
<Transition enter={() =>tw`transition ease-out duration-100 transform`} />
```

**Comment by RobinMalfait** [comment]
For now we will only support class names directly instead of objects. Everybody that uses something like `twin.macro` or something that generates objects will have to use the `css` prop from `@emotion` or similar packages to generate the actual class name.

**Comment by dimitarrusev** [comment]
Encountering the same issue with styled components and twin.macro. Would be great if anyone can provide and example.

@puneetverma05 Did you solve this?

**Comment by jeroenv** [comment]
Here's a working example for styled components and twin.macro:
https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-headless-ui-transition-forked-vow27?file=/pages/index.js

 Isn't perfect but works...

**Comment by puneetverma05** [comment]
> Having the same issue with styled components and twin.macro. Would be great if anyone can provide an example.
> 
> @puneetverma05 Did you solve this?

Hi @dimitarrusev , not yet but @jeroenv posted a good solution where creating a styled wrapper over Transition, please have a look 🙂

**Comment by andrasferenczi** [comment]
Based on a quick test it looks like keeping the `appear` property on `true` solves this issue with `NextJS`

**Comment by OnurGvnc** [comment]
I am using twin.macro (tw``) with custom Transition wrapper component.


```tsx
import tw from 'twin.macro'
import { Transition } from './transition'

<Transition
  show={isShowing}
  enter={tw`transition-opacity duration-1000`}
  enterFrom={tw`opacity-0`}
  enterTo={tw`opacity-100`}
  leave={tw`transition-opacity duration-150`}
  leaveFrom={tw`opacity-100`}
  leaveTo={tw`opacity-0`}
>
  I will fade in and out
</Transition>
```

transition.tsx
```tsx
import React, { ElementType, MutableRefObject } from 'react'

import { Transition as TransitionBase } from '@headlessui/react'
import { TransitionEvents } from '@headlessui/react/dist/components/transitions/transition'
import { Props } from '@headlessui/react/dist/types'
import { PropsForFeatures } from '@headlessui/react/dist/utils/render'

import { css } from '@emotion/css'
import { TwStyle } from 'twin.macro'

const DEFAULT_TRANSITION_CHILD_TAG = 'div' as const
type NewType = MutableRefObject<HTMLDivElement>

type TransitionChildRenderPropArg = NewType
const Features = { None: 0, RenderStrategy: 1, Static: 2 }
const TransitionChildRenderFeatures = Features.RenderStrategy

interface TransitionClasses {
  enter?: TwStyle | string
  enterFrom?: TwStyle | string
  enterTo?: TwStyle | string
  entered?: TwStyle | string
  leave?: TwStyle | string
  leaveFrom?: TwStyle | string
  leaveTo?: TwStyle | string
}

type TransitionChildProps<TTag> = Props<TTag, TransitionChildRenderPropArg> &
  PropsForFeatures<typeof TransitionChildRenderFeatures> &
  TransitionClasses &
  TransitionEvents & { appear?: boolean }

function getPropsWithTw(props: TransitionClasses) {
  const newProps = { ...props }
  newProps.enter =
    typeof props.enter == 'string' ? props.enter : css(props.enter)
  newProps.enterFrom =
    typeof props.enterFrom == 'string' ? props.enterFrom : css(props.enterFrom)
  newProps.enterTo =
    typeof props.enterTo == 'string' ? props.enterTo : css(props.enterTo)
  newProps.leave =
    typeof props.leave == 'string' ? props.leave : css(props.leave)
  newProps.leaveFrom =
    typeof props.leaveFrom == 'string' ? props.leaveFrom : css(props.leaveFrom)
  newProps.leaveTo =
    typeof props.leaveTo == 'string' ? props.leaveTo : css(props.leaveTo)

  return newProps
}

export function Transition<
  TTag extends ElementType = typeof DEFAULT_TRANSITION_CHILD_TAG,
>(props: TransitionChildProps<TTag> & { show?: boolean; appear?: boolean }) {
  // @ts-ignore
  return <TransitionBase {...getPropsWithTw(props)} />
}

Transition.Child = function Child<
  TTag extends ElementType = typeof DEFAULT_TRANSITION_CHILD_TAG,
>(props: TransitionChildProps<TTag>) {
  // @ts-ignore
  return <TransitionBase.Child {...getPropsWithTw(props)} />
}
Transition.Root = Transition

```

**Comment by itschrislow** [comment]
https://headlessui.dev/react/transition#transitioning-on-initial-mount

<img width="734" alt="Screen Shot 2021-09-30 at 11 46 08 AM" src="https://user-images.githubusercontent.com/21194612/135488181-aeb62e57-3cae-42f7-9ea9-d1fb184d35b6.png">

**Comment by Barbariansyah** [comment]
stack: tailwind + headless UI + Next.js

I've also faced the same issue running with `next dev`, using the first example from https://headlessui.dev/react/transition 

but when I do `next build` then `next start` it works just fine

is this an expected behavior? can anyone help explain what's happening? thanks a lot 🙏

**Comment by RobinMalfait** [comment]
@Barbariansyah see #681 for more information

**Comment by ifeoluwaayo** [comment]
Facing the same issue with next.js

**Comment by bavicj** [comment]
Also facing the issue with fresh nextjs + tailwind + headless ui

**Comment by RobinMalfait** [comment]
@ifeoluwaayo @bavicj see #681 for more information
