### ISSUE TITLE
[Bug]: Form submit triggers child Headless UI elements to open

### ISSUE THREAD

**Issue by Cartman720** [tailwindlabs/headlessui#803]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://jumpshare.com/v/IYNXNmnbEGx73vRmBaZ5

### Describe your issue

I am using Headless UI for my components, thus frequently I use them inside forms for selects and other elements. However when I try to submit form elements pressing enter, the Headless UI components get opened or changed the state.

For example there is a form with couple of inputs and `Listbox` element from Headless UI and when I hit enter inside the focused input element the Listbox element gets opened, instead of submitting the form as supposed. For form submission I use formik hook. 

I think it's supposed to enter into submission function instead of focusing `Listbox` element. This kind of error happens with `Popover` element implementation of select box, also same issue with `Switch` element. Basically if there is a `headlessui/react`  component instead form, it's being triggered instead of form submission.

Here the code of list box wrapper element.

```

import { FC } from 'react';
import { Listbox } from '@headlessui/react';
import { ChevronDownIcon, XIcon } from '@heroicons/react/outline';
import styles from '@modules/admin/styles/Form.module.scss';
import classNames from 'classnames';

type SelectValue = any;

interface IOptionProps {
  label: string;
  value: SelectValue;
}

interface SelectProps {
  value: SelectValue;
  onChange(value: SelectValue): void;
  options: IOptionProps[];
  className?: string;
  placeholder?: string;
}

const Select: FC<SelectProps> = ({
  value = [],
  onChange,
  options = [],
  className,
  placeholder,
}) => {
  const selectedOption = options.find((i) => i.value === value);

  const handleClear = () => {
    onChange('');
  };

  return (
    <Listbox value={value} onChange={onChange}>
      {({ open }) => (
        <>
          <div className={classNames(className, 'relative')}>
            <Listbox.Button
              as="div"
              style={{ height: 46 }}
              className={classNames(
                'flex justify-between items-center',
                styles.selectContainer
              )}
            >
              <span className="line-clamp-1">
                {selectedOption?.label || value || placeholder}
              </span>

              {!open && (
                <button className="ml-auto">
                  <ChevronDownIcon width="20" aria-hidden="true" />
                </button>
              )}

              {open && value && (
                <button onClick={handleClear} className="ml-auto">
                  <XIcon width="20" aria-hidden="true" />
                </button>
              )}
            </Listbox.Button>

            {open && (
              <Listbox.Options
                as="ul"
                style={{ maxHeight: '17.5rem' }}
                className={classNames(
                  'border-light mt-1 w-full z-10 panel p-0 overflow-auto',
                  'absolute scrollbar-cyan text-sm outline-none'
                )}
              >
                {options.map(({ value, label }) => (
                  <Listbox.Option key={value} value={value}>
                    {({ active, selected }) => (
                      <div
                        className={classNames(
                          'py-1 px-2 font-medium',
                          'hover:bg-black hover:bg-opacity-10 transition-all',
                          (active || selected) && 'bg-black bg-opacity-10'
                        )}
                      >
                        {label}
                      </div>
                    )}
                  </Listbox.Option>
                ))}
              </Listbox.Options>
            )}
          </div>
        </>
      )}
    </Listbox>
  );

};
```

And the component that contains form 
```

import Button from '@components/Button';
import AdminWorkplaceContainer from '@modules/admin/workplace/Container';
import {
  createEmployeeRecord,
} from '@modules/admin/workplace/services/clients';
import Select from '@modules/admin/components/Select';
import { useFormik } from 'formik';
import { useRouter } from 'next/router';
import React, { useCallback } from 'react';
import { toast } from 'react-toastify';
import Input from '@components/Form/Input';

interface EmployeeFromValues {
  firstname: string;
  lastname: string;
  email: string;
  ethnicity: string;
  gender: 'F' | 'M' | 'NB' | 'N/A';
}

const initialValues: EmployeeFromValues = {
  firstname: '',
  lastname: '',
  email: '',
  ethnicity: '',
  gender: 'N/A',
};

const employees = () => {
  const router = useRouter();
  const { workplaceId } = router.query as RouteParams;

  const form = useFormik({
    initialValues,
    onSubmit: async (values) => {
      await createEmployeeRecord(workplaceId, values);
      toast('Employee record added!', {
        type: toast.TYPE.SUCCESS,
      });
    },
  });

  return (
    <AdminWorkplaceContainer>
      <div className="panel max-w-2xl">
        <div className="mb-2 font-semibold text-lg">Add employee record</div>

        <form onSubmit={form.handleSubmit}>
          <Input
            name="firstname"
            onChange={form.handleChange}
            className="mb-2"
            label="Firstname"
            placeholder="Employee firstname"
          />

          <Input
            name="lastname"
            onChange={form.handleChange}
            className="mb-2"
            label="Lastname"
            placeholder="Employee lastname"
          />

          <Input
            type="email"
            name="email"
            onChange={form.handleChange}
            className="mb-2"
            label="Email"
            placeholder="Employee email"
          />

          <Input
            name="ethnicity"
            onChange={form.handleChange}
            className="mb-2"
            label="Ethnicity"
            placeholder="Employee Ethnicity"
          />

          <div className="mb-4">
            <p className="text-typography-secondary ml-2">Gender</p>

            <Select
              value={form.values.gender}
              onChange={(val) => form.setFieldValue('gender', val)}
              options={[
                { label: 'Male', value: 'M' },
                { label: 'Female', value: 'F' },
                { label: 'non-binary', value: 'NB' },
                { label: 'N/A', value: 'N/A' },
              ]}
            />
          </div>

          <div className="text-right">
            <Button type="submit" size="small">
              Add
            </Button>
          </div>
        </form>
      </div>
    </AdminWorkplaceContainer>
  );
};

export default employees;
```

**Comment by darvanen** [comment]
Can confirm that wrapping in a `<form>` element (as is recommended in TailwindUI components) causes this behaviour.

**Comment by Cartman720** [comment]
Hi @darvanen,

I have done little more research and found out that this isn't related directly to HeadlessUI, rather it's a behavior caused by React itself. Bascially, in `React` if your `button` elements inside `form` don't have a `type` attribute`, it may behave in an unexpected way. The solution for this problem is fairly simple, you just need to specify the `type` attribute for your `button` elements, It can be `submit` or just `button` based on the functionality of the `<button></button>` element. 

[Here ](https://stackoverflow.com/questions/41904199/whats-the-point-of-button-type-button) the stackoverflow link related to this. 

Closing the issue, as this isn't HeadlessUI bug.

**Comment by darvanen** [comment]
Well, that's mildly embarrassing for me, thanks for clearly that up 🙂

**Comment by Cartman720** [comment]
Similarly ;)

**Comment by darvanen** [comment]
See... I had type="submit" on the button at the end of the form because I *want* it to submit the form. I don't think I should have to change that button to type="button" to prevent this behaviour from a HeadlessUI switch in the same form - it did work though.
I'll leave this closed, maybe the maintainers will pick it up but I suspect they have much more important things to turn their attention to :)

**Comment by Cartman720** [comment]
You don't need to change `submit` to `button`. Just  don't use `<button>` without attribute `type` **inside forms**. if it's plain button you should do it like `<button type="button">`. 

Simply, if attribute `type` missing on the `<button>`, it will cause the issue inside React forms. This isn't related to HeadlessUI at all, but React behavior. 

However, please provide your code. That way will be possible to find the issue on your code.

**Comment by darvanen** [comment]
My code is a giant application with a few other libraries involved. The behaviour I was seeing was a HeadlessUI `<Switch>` changing state whenever the Enter key was pressed while focussed in a text input inside a form element, if there was a button *with* type"submit" inside a form element. Didn't even have to be the same form element.

I would try to replicate in a codesandbox.io or similar but I can't find find a template with tailwind and headless preconfigured and I don't have the time to remake one.
