### ISSUE TITLE
[Bug]: Attempted import error: 'Tab' is not exported from '@headlessui/react'.

### ISSUE THREAD

**Issue by rdoyle99** [tailwindlabs/headlessui#811]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome

### Reproduction repository

Using "Basic Example" from this: https://headlessui.dev/react/tabs

### Describe your issue

Have been trying to use Tabs. I can use other HeadlessUI components just fine, but Tab is not able to be imported.

Check out these Screenshots:

The Code & The Error:
<img width="976" alt="Screen Shot 2021-09-15 at 11 08 52 AM" src="https://user-images.githubusercontent.com/37251457/133478696-57c1fbd7-4fff-4657-ab8c-486037ae2fde.png">
<img width="353" alt="Screen Shot 2021-09-15 at 11 08 57 AM" src="https://user-images.githubusercontent.com/37251457/133478700-744ea488-ea6a-4d2f-a853-02f151069f4f.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you provide a minimal reproduction repo? The `Tab` component is definitely exported so hard to guess what is going on.

I have 2 guesses in the meantime that you can check:
- You don't have the latest version installed (double check your package.json / node_modules)
- You are using Next.js and have a cached folder (remove the `.next` folder and restart your server)

**Comment by rdoyle99** [comment]
Hey @RobinMalfait! Appreciate the quick response  - you were right to suggest removing the .next folder. Couldn't find that answer elsewhere and it solved my problem!

Thanks,
Ryan
