### ISSUE TITLE
[Bug]: Dialog overlay needs an `event.target === event.currentTarget` check

### ISSUE THREAD

**Issue by itsMapleLeaf** [tailwindlabs/headlessui#812]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headless-ui-overlay-target-check-bug-n86cb?file=/src/App.js

### Describe your issue

My use case: I want to have the dialog panel scroll the overlay area if it's too tall (not scroll within the _panel_, but the whole screen). From experimentation, I've found the easiest way to do this is to nest the panel within the Dialog.Overlay, with the following styles:

```tsx
<Dialog.Overlay className="fixed inset-0 flex flex-col p-4 overflow-y-auto bg-black/50">
	<div className="bg-white m-auto w-full max-w-md p-4 grid gap-4 pointer-events-auto">
		<p>dialog content</p>
	</div>
</Dialog.Overlay>
```

The issue: when clicking anywhere within the panel, the dialog will close, not allowing any interaction. You can see this in the sandbox. Open the dialog with headless and try to click on the input. Then open the dialog with the target check, and you can click around the panel freely, but still close the panel by clicking on the overlay. This is accomplished by checking if `event.target === event.currentTarget`.

I can work around this by adding an `event.stopPropagation()` on the panel, but that feels like an unnecessary hack that could cause other issues. I think it would be more correct for the overlay to check explicitly if _it_ is the element being clicked on

The overlay also needs to remove its `aria-hidden` attribute to allow this usage, to not hide all of the nested aria roles... I hope this isn't a deal breaker? 😅

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
- `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.

**Comment by itsMapleLeaf** [comment]
Awesome, thanks for the quick response and fix 😄

Though, there's actually another issue with elements inside the overlay 😅 (the aria-hidden problem) I'll make a followup issue, that one might be more nuanced
