### ISSUE TITLE
[Bug]: Issue with absolute div being hidden by modal overlay (stacking context bug?)

### ISSUE THREAD

**Issue by krthush** [tailwindlabs/headlessui#813]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

^1.2.0

### What browser are you using?

Chrome, Firefox, Edge

### Reproduction repository

Unable due to private repo (commercial) - example code include in description

### Describe your issue

I'm having an issue with the headlessui modal, as I'd like to have "dropdown" that extends outside of the modal body. Unfortunatly whatever that goes outside of this body seems to be hidden by the modal overlay, no matter what fixes I've attempted to address the stacking context?

I've tried playing around with transform/relative and changing z-indexs on the appropriate parent elements, but nothing seems to work? Am I missing something?

I've included a image and output html file showing the issue.

Demo image using 3D view to debug context issue:
<img width="2880" alt="modal_issue" src="https://user-images.githubusercontent.com/33790334/133578327-524f9669-9680-473d-bb3c-a315ab872d75.png">

Demo output html files with issue:
[meh.zip](https://github.com/tailwindlabs/headlessui/files/7176163/meh.zip)

**Comment by DaveyGiesen** [comment]
Same problem with a dropdown item that opens a modal window. When trying to edit/click a field the modal pops away. Some one has a solution?

**Comment by OmerWow** [comment]
I'm not sure if it's the same problem I had, but after removing all the 'transform' classes from my project (since TailwindCSS v3 doesn't require them anymore) my modal had a weird overlay bug and was closing on click.

Try adding a 'transform' class to where you think it is needed (or was before if you are like me and removed it).
In my modal it was the first dic child of Transition.Child.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you want to render something outside of the dialog, then you probably want to render that inside a `Portal` component and use something like [Floating UI](http://floating-ui.com) to position it correctly.

Here is an example from the Headless UI codebase: https://github.com/tailwindlabs/headlessui/blob/cefb8990a1b4db7a47d6dad16d5b1a0ab4bac419/packages/playground-react/pages/dialog/dialog.tsx#L164
