### ISSUE TITLE
Dropdown menu remains open upon navigation in Next.js

### ISSUE THREAD

**Issue by lensbart** [tailwindlabs/headlessui#818]
Hello!

**What component (if applicable)**
- URL for category: [dropdowns](https://tailwindui.com/components/application-ui/elements/dropdowns)
- Component name: [with dividers](https://tailwindui.com/components/application-ui/elements/dropdowns#component-1f10562f6266c9b3ef15ff792edd508e)

**Describe the bug**
I have a dropdown menu where each item is something like this:
```tsx
<Menu.Item key={key}>
{({ active }) => (
  <Link href={href}>
    <a>
      {name}
    </a>
  </Link>
)}
</Menu.Item>
```
which is the default way to include hyperlinks in Next.js. When I click on such an item in the dropdown menu, the menu remains open upon navigation to a new page.

**Expected behavior**
The most natural behaviour would be that the dropdown menu closes on page navigation. This is what would happen in browsers for native dropdown menus.

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is that the `Link` component from Next.js doesn't forward props to the underlying `a` tag. I would recommend to implement a `NextLink` component:

```js
function NextLink(props) {
  let { href, children, ...rest } = props;
  return (
    <Link href={href}>
      <a {...rest}>{children}</a>
    </Link>
  );
}
```

Now you can use this as:
```js
<Menu.Item key={key}>
  {({ active }) => (
    <NextLink href={href}>
      {name}
    </NextLink>
  )}
</Menu.Item>
```

I'm going to add a section to the docs to describe this issue. 
Hope this helps already!

**Comment by madsh93** [comment]
How is this done in other frameworks, Vue, Nuxt and Inertia?

**Comment by henningko** [comment]
This issue also exists with Nuxt using `NuxtLink`—would be great to see how to fix it there.
