### ISSUE TITLE
[Bug]: Aria roles inside Dialog.Overlay are hidden

### ISSUE THREAD

**Issue by itsMapleLeaf** [tailwindlabs/headlessui#819]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.0.0-aa1a48c

### What browser are you using?

Chrome

### Reproduction repository

https://user-images.githubusercontent.com/19603573/133799250-c9b7d131-9160-43f1-bbeb-1ee8ef87fa6a.png

### Describe your issue

Related to https://github.com/tailwindlabs/headlessui/issues/812

See here:
![image](https://user-images.githubusercontent.com/19603573/133799250-c9b7d131-9160-43f1-bbeb-1ee8ef87fa6a.png)

The overlay has `aria-hidden` on it, therefore making every other aria role inside of it hidden. I noticed this when my testing-library `findByRole` calls in my e2e tests didn't pass.

I can't override it with `aria-hidden={false}`, and adding `aria-hidden={false}` to the inner dialog panel doesn't work either. This _does_ work (but not for SSR):

```js
        <Dialog.Overlay
          className="fixed inset-0 flex flex-col p-4 overflow-y-auto bg-black/50"
          ref={(element: HTMLElement | null) => {
            element?.removeAttribute("aria-hidden")
          }}
        >
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I know we did a few fixes for the `Dialog.Overlay`, but I think that it is better to refactor your usage and not put any contents inside the `Dialog.Overlay` at all.

I would recommend to render your Dialog more like this instead:

```js
import { useState } from 'react'
import { Dialog } from '@headlessui/react'

function MyDialog() {
  let [isOpen, setIsOpen] = useState(true)

  return (
    <Dialog open={isOpen} onClose={() => setIsOpen(false)}>
      <Dialog.Overlay />

      <Dialog.Title>Deactivate account</Dialog.Title>
      <Dialog.Description>
        This will permanently deactivate your account
      </Dialog.Description>

      <p>
        Are you sure you want to deactivate your account? All of your data will
        be permanently removed. This action cannot be undone.
      </p>

      <button onClick={() => setIsOpen(false)}>Deactivate</button>
      <button onClick={() => setIsOpen(false)}>Cancel</button>
    </Dialog>
  )
}
```
