### ISSUE TITLE
Popover Button Doesn't Properly Close Panel on Safari

### ISSUE THREAD

**Issue by pkscout** [tailwindlabs/headlessui#821]
**What component (if applicable)**
- Component name: @headlessui/react/Popover

**Describe the bug**
We are using the new react components to generate the dropdown panel menu for our UI.  On Safari, the panel doesn't always properly close (Microsoft Edge and Firefox are fine). If you click on the text of a button, the panel closes and then reopens. Clicking it again will then close it. Clicking anywhere else on the page properly closes the panel.  We didn't have this issue with our old implementation of the dropdown that didn't use the new react component.

**To Reproduce**
1. Go to https://kodi-tv-staging.netlify.app
2. Click on one of the menus with an arrow (those are the dropdowns) from one of the problem platforms/browsers listed
3. Click the text of the menu again.
4. See the panel close and reopen (worth noting, if you click the arrow - which changes state when the panel is open - the menu closes properly)

**Expected behavior**
The panel should close and not reappear when clicking the popover button again.

**Browser/Device (if applicable)**
 - OS: Mac OSX
 - Browser Safari
 - version 14.03 (Bug Sur)

**Additional context**

**Comment by reinink** [comment]
@pkscout Thanks for your patience on this. I've moved this over to the Headless UI issues. However, I'm pretty sure that this issue has been fixed. Are you able to update to the latest version to verify that it's now working?

If it is still not working for you, please share a minimal reproduction repo for this issue. 👍

**Comment by pkscout** [comment]
I'll put this on my list to update and test. We reverted to the non-React buttons, so I need to do some work to update again to the React ones.

**Comment by reinink** [comment]
Thanks @pkscout, if you're able to test it out that would be great. 👍
