### ISSUE TITLE
[Docs]: Typo in Dialog (Modal) example

### ISSUE THREAD

**Issue by SelleslaghGianni** [tailwindlabs/headlessui#823]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

N/A

### What browser are you using?

Chrome

### Reproduction repository

https://www.youtube.com/watch?v=ZKBlMWI6nO4

### Describe your issue

![image](https://user-images.githubusercontent.com/7468683/133934170-cfe51259-5af2-435d-8fac-ac1feeb5f70a.png)
There's a small typo. "your" in "We've sent your an email" should be "you".

https://headlessui.dev/react/dialog

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed for both the React and Vue version!
