### ISSUE TITLE
[Bug]: Unable to transition components that contain input field with autofocus

### ISSUE THREAD

**Issue by Xeronic** [tailwindlabs/headlessui#827]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

chrome

### Reproduction repository

---

### Describe your issue

When transitioning a component containing an input field with autofocus will cause the component to just jump into place. It will transition out as expected.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The browser by default will cancel transitions if you focus an input that is not fully visible yet.

That said, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
