### ISSUE TITLE
Next set of components? :)

### ISSUE THREAD

**Issue by animeshchat** [tailwindlabs/headlessui#83]
Hey! Thanks a bunch for this library. Its awesome. So awesome that I'd rather wait for you guys to come out with components rather than build myself or use something else. 

On that note, is an accordion component in the works? It would be great to have visibility into what's coming up next.

**Comment by adamwathan** [comment]
Literally deciding what we're going to build next this afternoon, right now it's not 100% certain. Accordion is a good candidate!

**Comment by hmaesta** [comment]
_Uh, I hope I am not too late..._ My vote would be to **datepicker.**

Although React has [great](https://github.com/airbnb/react-dates) [and](https://github.com/gpbl/react-day-picker) [nice](https://react.carbondesignsystem.com/?path=/story/datepicker--range) [options](https://github.com/Hacker0x01/react-datepicker), Vue doesn't have so much lucky. The most popular package is [v-calendar](https://github.com/nathanreyes/v-calendar). It's very complete and uses TailwindCSS, but it's kind of abandoned and the build has [almost 250 KB.](https://github.com/nathanreyes/v-calendar/issues/479)

Right now I am using a [Vue wrapper of Flatpickr](https://github.com/ankurk91/vue-flatpickr-component). It's lightweight and has a lot of features, but the code is... kind of bad. And I am sure you don't want to see my >500 lines of `@apply` to make it looks familiar with my application 😩

This lack of good options to Vue can be an opportunity.

#### Needs mention:

- [duetds/date-picker](https://github.com/duetds/date-picker) is a universal web component, only 10 KB and it does a **great** a11y work
- [dbrekalo/vue-date-pick](https://github.com/dbrekalo/vue-date-pick) has a nice interface and weights only 5 KB, but it's very limited


#### Features that I believe are nice to have:

- Date range with only one calendar
- Possibility to see multiple months at once
- i18n [with native internationalization](https://caniuse.com/internationalization)
- Allow system native datepicker on mobile

**Comment by taylorharwin** [comment]
Something I would love in the next set of components would be a Combobox -- an extension of the ListBox based around a text input rather than a select

**Comment by mateomurphy** [comment]
Personally, I would love lower level components for building things like tooltips and popovers. It feels like Menu could be repurposed for that, but a dedicated API would be ideal!

**Comment by lizy0329** [comment]
datepicker and timepicker have two different Interactive logic, headlessui is a `PC Component Library` or  `Mobile Component Library` or `two of them`?

**Comment by RobinMalfait** [comment]
Thanks for the suggestions. We are currently focusing on components that we need for Tailwind UI. Spoiler, one of them will be the Accordion component.

**Comment by aimproxy** [comment]
Not sure why this hasn't been re-open, and about the "accordion" component it's real name is "Disclosure" if I am correct!
From the two libraries that @hmaesta have mention, the first one catch my attention, what took me a little adventure on the react world, I found BlueprintJs who provides several components to interacts with dates, times and times zones very well!

You mind take a look at this: https://blueprintjs.com/docs/#datetime

There definitely missing one of this for Headless UI!

Keep your great job guys! We love Tailwind over here!

**Comment by SalahAdDin** [comment]
There is no more components, right?
