### ISSUE TITLE
[Bug]: Vue components doesn't focus back to button

### ISSUE THREAD

**Issue by sibbng** [tailwindlabs/headlessui#844]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.4.1

### What browser are you using?

Chrome

### Reproduction repository

Read below

### Describe your issue

https://headlessui.dev/vue/menu
https://headlessui.dev/vue/listbox
https://headlessui.dev/vue/dialog

These components doesn't focus back to button after clicking outside. You can check `document.activeElement` inside demo iframe. Their React versions are work as expected.

But `Popover` component is work as expected: https://headlessui.dev/vue/popover

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1186, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
