### ISSUE TITLE
[Bug]: Vue v3.2.x TypeScript Errors

### ISSUE THREAD

**Issue by micDropper** [tailwindlabs/headlessui#849]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.4.1

### What browser are you using?

Chrome

### Reproduction repository

N/A

### Describe your issue

Please bump vue to ~v3.2.0 so that your typescript definitions will be updated for your vue components. I believe some of their typescript definitions have changed slightly in vue v3.2.x. We're getting typescript errors when passing props to your components because of your emitted *.d.ts files.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed in the latest version where we bumped to a new TypeScript version and improved the TypeScript errors.
