### ISSUE TITLE
Listbox selected render prop argument does not work

### ISSUE THREAD

**Issue by mzalevski** [tailwindlabs/headlessui#85]
Hi, in the second Listbox example [here](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#styling-the-active-and-selected-option) the `selected` render prop argument does not work. It worked for me only after I changed the `Listbox.Option` `value` to `person.name` instead of `person`. Im working on CRA without any other dependencies.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Do you mean that you get a TypeScript error or do you get another error?
We had a similar error which is already fixed, but not yet released: https://github.com/tailwindlabs/headlessui/commit/7701a48c6441ce26682526109559b630a8d869bd

**Comment by mzalevski** [comment]
I did not use TypeScript. Nor did I get any error really. I just tried to follow the examples and conditionally render "x" when Listbox.Option is selected.

**Comment by adamwathan** [comment]
Sounds like maybe there is an issue with an equality check for the actual `person` object value that's causing `selected` to never be true. Can you reproduce in CodeSandbox by any chance?

**Comment by merodiro** [comment]
I just had the same problem, the problem is in the example `people` array is inside the component function so it's created every time with new objects. I was able to fix it by moving the array outside the component

here's an example of the working and the broken ones

https://codesandbox.io/s/elastic-swartz-ruy9e?file=/src/App.js

**Comment by RobinMalfait** [comment]
@merodiro yep you are correct, I fixed the readme's. Thanks!
