### ISSUE TITLE
[Bug]: Error when render <Menu.Button> as a custom component

### ISSUE THREAD

**Issue by adamlindqvist** [tailwindlabs/headlessui#856]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/wonderful-leaf-t4899?file=/src/App.js

### Describe your issue

When trying to use <Menu.Button /> with a custom component it doesn't work as expected and I get the following warning:
 `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Simplified example:
```jsx
const CustomButton = ({ children, onClick }) => (
  <button onClick={onClick}>{children}</button>
);

<Menu.Button as={CustomButton}>More</Menu.Button>
```

Does headless-ui require the `<CustomButton/>`-component to forward unknown props down to the html `<button>` element am I using it wrong?

**Comment by adamlindqvist** [comment]
I close this as I realize that it needs to forward the ref to the underlying button component.

**Comment by StErMi** [comment]
could you explain your solution because I've the same problem

**Comment by adamlindqvist** [comment]
> could you explain your solution because I've the same problem

You'll have to do like this example in the react doc: https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components

**Comment by ctsstc** [comment]
## Example

```tsx
const CustomButton = React.forwardRef(({ children, onClick }, ref) => (
  <button ref={ref} onClick={onClick}>
    {children}
  </button>
));
```

**Comment by RobinMalfait** [comment]
When you are adding custom components, make sure to passthrough all the props you get from Headless UI. These include event handlers, but also aria related attributes.

E.g.:
```js
// This is incorrect
const CustomButton = ({ children, onClick }) => (
  <button onClick={onClick}>{children}</button>
);

<Menu.Button as={CustomButton}>More</Menu.Button>
```

```js
// This is correct
const CustomButton = React.forwardRef((props, ref) => (
  <button ref={ref} {...props} />
);

<Menu.Button as={CustomButton}>More</Menu.Button>
```

**Comment by adamlindqvist** [comment]
> When you are adding custom components, make sure to passthrough all the props you get from Headless UI. These include event handlers, but also aria related attributes.
> 
> E.g.:
> 
> ```js
> // This is incorrect
> const CustomButton = ({ children, onClick }) => (
>   <button onClick={onClick}>{children}</button>
> );
> 
> <Menu.Button as={CustomButton}>More</Menu.Button>
> ```
> 
> ```js
> // This is correct
> const CustomButton = React.forwardRef((props, ref) => (
>   <button ref={ref} {...props} />
> ));
> 
> <Menu.Button as={CustomButton}>More</Menu.Button>
> ```

It might be worth mentioning this in the documentation?

**Comment by wottpal** [comment]
> It might be worth mentioning this in the documentation?
yes, please. solved my exact issue. thanks, adam!
