### ISSUE TITLE
[DOCS]: Tab disabled prop

### ISSUE THREAD

**Issue by Shaglock** [tailwindlabs/headlessui#904]
Hello.
On the https://headlessui.dev/vue/tabs#disabling-a-tab it says

> use the disabled prop on the Tab component

But on the Tab Component API https://headlessui.dev/vue/tabs#tab this prop is never mentioned. 
The same for react component.

Is that a missed part of documentation or is it intended and I am missing something?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is fixed and documented now.
