### ISSUE TITLE
Transitions sometimes flicker in React 18 concurrent mode

### ISSUE THREAD

**Issue by itsMapleLeaf** [tailwindlabs/headlessui#908]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.4.1

**What browser are you using?**

Edge

**Reproduction URL**

https://github.com/itsMapleLeaf/headless-flicker-bug

**Describe your issue**

See the video below. When transitioning out, the square sometimes flickers before disappearing.

https://user-images.githubusercontent.com/19603573/140186207-b9d5b9fd-3450-44f3-9020-d1aa6a56f811.mp4

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We haven't worked on React 18 support yet since this also introduces breaking changes. Will close this in favor of a tracking issue for React 18: https://github.com/tailwindlabs/headlessui/issues/681
