### ISSUE TITLE
Can't ForwardRef into Listbox Component

### ISSUE THREAD

**Issue by jvanderen1** [tailwindlabs/headlessui#910]
**What package within Headless UI are you using?**

- @headlessui/react

**What version of that package are you using?**

- v1.4.1

**What browser are you using?**

- Edge

**Reproduction URL**

https://codesandbox.io/s/headlessui-listbox-ref-0odjh?file=/src/App.js

**Describe your issue**

In order to use [react-hook-form](https://react-hook-form.com/), I need to be able to listen on changes to the underlying component properly through the `ref` prop. When trying to integrate with `Listbox`, I am running into issues. The values are not being set or changed properly because the value changed trigger is not being fired properly since react-hook-from does not have a handle to the underlying component. Only when I click the submit button does `handleSubmit` properly get the values (and the `Listbox.Button` is updated).

**Comment by ulken** [comment]
1. You need to forward `name` to the `Listbox` component
2. You should use `useWatch` (or `watch`) instead of `getValues`

Updated CSB: https://codesandbox.io/s/headlessui-listbox-ref-forked-3ddfj?file=/src/App.js

**Comment by jvanderen1** [comment]
Thanks! That resolves my issue.

**Comment by StErMi** [comment]
as far as I can see there's not any `name` prop on the [ListBox docs](https://headlessui.dev/react/listbox#listbox). Am I missing something?

Also, ref would be needed for the auto-focus on error

is there a solution for that?

**Comment by ulken** [comment]
> as far as I can see there's not any name prop on the ListBox docs. Am I missing something?

The docs only list properties unique to the components. The rest of the properties will be forwarded to whatever element you choose to render it as. The available props follows.

Not sure what you mean by you need the ref to auto-focus. If it auto-focuses it already has a ref? Otherwise you can access a ref in the validation error object.
