### ISSUE TITLE
[BUG]: Menu/Dropdown click-away doen't seem to close a Menu/Dropdown instance on iOS/iPadOS Safari (Vue)

### ISSUE THREAD

**Issue by oberocks** [tailwindlabs/headlessui#919]
**What package within Headless UI are you using?**

### @headlessui/vue

<br>

**What version of that package are you using?**

### (NOTE: v1.4.3 seems to have resolved this issue! 🙇)

<br>

**What browser are you using?**

* Bug exists on both Firefox for iOS and Safari for iOS on both iPhone (iOS v14.8) and iPad (iPadOS v14.8) devices/browsers
*  All other desktop [Safari, Firefox, Chrome, Opera] and mobile browsers [Chrome] worked perfectly and as expected

<br>

**Reproduction URL:**

[headlessui-ios-safari-menu-dropdown-clickaway-not-working](https://github.com/oberocks/headlessui-ios-safari-menu-dropdown-clickaway-not-working)

<br>

**Describe your issue:**

There is a bug when the headlessUI menu/dropdown component is listening for a tap outside of an opened Menu/Dropdown instance - as the menu just won't seem to close from any other interaction besides clicking the original menu open button/trigger (specifically on iOS/iPadOS Safari). 👀 

So the opening trigger interaction is perfect - and opens fine for tap 🖐️  interactions, too. However the "click-away" functionality does not fire, like ever, ultimately causing an end user to need to know and necessitate clicking the original trigger to hide the menu. 

The linked example repo also wouldn't "hear" the tap outside of the menu element(s), and for transparency - I threw the vue file in the example repo into a VILT stack vue spc file with nothing else in it - then did a localhost session on both devices for that page - and neither compo closed on a click-away. 

Please let me know if there's anything more I can or should do to help. 🍻 

<br>

- Edit: updated to more precise browser findings!

**Comment by oberocks** [comment]
I ended up updating some packages in a current build, and updated to headless v1.4.2 - still finding the problem on iOS Safari and Firefox, the menu DOES however close as expected on a tap-away in iOS in Chrome!

**Comment by pstieger92** [comment]
experiencing the same issue with v.1.4.2 on iphone/safari

**Comment by oberocks** [comment]
@pstieger92 Hey, I figured maybe I should just share my shim for this - just in case your project needs to clean up that interaction. Just note - I'm using a VILT stack, so this may not work exactly like it would need to for you in your project's contexts - but it might give you a way to get to interaction parity across the browsers in the meantime:

(this is just copied markdown from the little notes I made for myself - again in a VILT stack context)

> PS - I toggle the `document.activeElement.blur()` line after an update to see if it's fixed, and if it's not, then I just bring it back and get back to work lol

---

## `v-click-away-to-close`

The `v-click-away-to-close` custom directive essentially addresses an issue that can arise with HeadlessUI Menu, Listbox, etc. components on touch devices (at the time of this on Firefox and Safari iOS + iPadOS).

The issue is that the overlaid interfaces don't register an un-focus event, like the event that registers when clicking a HeadlessUI overlay. So at times on the client device with the wrong browser, the menus and listboxes end up stuck open until a user can find something else to take that focus away from the HeadlessUI component.

So this directive is meant to be appled strictly to HeadlessUI components that have overlaid elements/panels/etc., and should ALWAYS be applied to the PARENT of any listed menu/listbox items themselves. This avoids the listener in this directive from firing once for each menu/listbox item, which is obviously not ideal for end-user performance.

### Install The Directive

To install the `v-click-away-to-close` custom directive, open up the VILT stack's `./resources/js/app.js` file.

To add the `v-click-away-to-close` custom directive, we'll need to chain a `.directive()` call onto the `createApp()` method that is returned by the `setup()` method in the object passed into the app's `createInertiaApp()` method... whew! 

So your `./resources/js/app.js` file should contain something like this:


```javascript
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .mixin({ methods: { route } })
            // START custom directive
            .directive('click-away-to-close', {
                mounted(el, binding, vnode) {
                    el.clickOutsideEvent = function (event) {
                        if (!(el === event.target || el.contains(event.target))) {
                            console.log('The click-away-to-close directive was triggered!')
                            document.activeElement.blur()
                        }
                    }
                    document.body.addEventListener('click', el.clickOutsideEvent)
                },
                unmounted(el) {
                    document.body.removeEventListener('click', el.clickOutsideEvent)
                },
            })
            // END custom directive
            .mount(el);
    },
})
```

### Using the Directive

So with the directive installed, it can now be used inside a Vue (v3 not sure about v2) Single Page Component's `<template>` tag like so:

```html
<!-- DIRECTIVE ON PARENT OVERLAPPING ELEMENT -->

<MenuItems v-click-away-to-close>

    <MenuItem/> <!-- DON'T PUT DIRECTIVE ON CHILD ITEMS THEMSELVES! -->  

</MenuItems>
```

**Comment by pstieger92** [comment]
@oberocks thank you for sharing your solution! :)

**Comment by seismicsix** [comment]
We are seeing that same issue with React version, I think its because the click outside event only supports mousedown - i'm not sure if anyone or @RobinMalfait could shed any light if this is by design or not - but I tested it with pointerdown and it worked on ios and desktop as expected.

**Comment by oberocks** [comment]
@seismicsix Sweet and thank you for sharing your results for the pointerdown event 🍻 

And I'm quite curious if there is a design intent here as well. Could see it going either way.

**Comment by ddahan** [comment]
In a desperate effort trying to solve this, I found something interesting when trying to reproduce the bug.
I built 2 code sandboxes with the (almost) exact same code (index.html, app.Vue) and same package versions (last Vue, last HeadlessUI, ...). The only significant change is I use Vite in the first sandbox, and Vue CLI in the other one.

### Test with Vite
The code sandbox using Vite **DOES NOT WORK** as expected: https://codesandbox.io/s/laughing-napier-e10zb0
> If you touch the button, the menu is displayed. But if you touch outside, nothing happen. The only way to hide the menu is to touch the button again.

### Test with Vue-CLI
- The code sandbox using Vue-CLI **WORKS** as expected: https://codesandbox.io/s/headlessui-vue-menu-example-forked-gp0d36
> If you touch the button, the menu is displayed. And if you touch outside, the menu is hidden.

### Side notes
- Issue only happens with touch event on my iPad with Brave (Chromium based) and Safari browsers (can't test on android tablet). I did not find any issue with click event on desktop, within all famous browsers.
- I used a Popover component but it should be the same with the ones mentioned in the issue.
- I did not install TailwindCSS itself, as it seems it's not related to the issue.


Can someone take a look to the code sandboxes and confirm the issue would be related to Vite? Or maybe it's something else I missed.

Thanks.

**Comment by ddahan** [comment]
@oberocks thanks for the `v-click-away-to-close` custom directive.
In my case, using a Popover, it works closing the popover, however, the directive is triggered on input fields in my page, which means as soon as I click on an input field, the focus is instantly lost, and I can not use the field.
Any idea?

**Comment by oberocks** [comment]
@ddahan Hi and thank you for adding in what you've run into as well!

I'm working on a design sys using vue3/tw3/laravel, so I'm down to rig up what you have and take a look.

> Forewarning though: I'm not currently using vite in my own case, and i don't remember exactly, but I had to bail on using the headlessUI popover in general a month or so back. Pivoted to an off-canvas modal instead.

That said though, it's lame if my sys doesn't have something that can be used as a bit of a mega menu, so I defs want/need to get a compo to cover that base - hopefully using only current dependencies like headlessUI. 

Have a feeling this is going to require some TypeScript diving - which I'm still new to - as also having issues with Jest tests for a teleport wrapped headlessUI TransitionRoot/Child structure (growl notification) feature. So I have a feeling I need to spend some quality time with the headless tests and the source to learn more.  

---

Otherwise re: your comment with examples, the second link with (vue-cli) worked for my iOS devices (Safari) perfectly. 💪 

However the first example - I couldn't get it to run on either iOS Safari and desktop Firefox. A 502 was being thrown.

**Quick ?: Can you give me the schema of your popover component with the nested input?** I want to try that out, too. Will be a day or two before I can report back though!

**Comment by oberocks** [comment]
@pstieger92 @ddahan @seismicsix 

Hey all, just edited the issue - and wanted to quickly mention:

v1.4.3 just tested as expected on iPad iOS and iOS Safari. I removed my `v-click-away-to-close` directive from both a `ListboxOptions` and a `MenuItems` HeadlessUI component. Both close from a tap (and click) away as expected in all browsers in my tests just now.

I'm going to need to mark this as resolved, but want to take a look at @ddahan 's situation with the popover element and report back here as I said I would before closing it. Then from there i can either help out @ddahan or if I get nowhere - then he can maybe open up an issue for the popover situation specifically.

Cheers and thank you 🍻

**Comment by ddahan** [comment]
@oberocks thanks a lot for helping.
Here is a [stackblitz](https://stackblitz.com/edit/vue-vh1dtw?file=src/App.vue) showing the issue with your custom directive:

When the menu is closed (default behaviour), if you try to focus the input by clicking on it, your directive is trigerred and unfocus the input (but should not). Hence, it's impossible to use the input normally.

I never built custom directive and am not sure how to modify it to make it work. If you have an idea....

-----

Otherwise, without the use of this custom directive, I can confirm that using a Menu or Popover lead to the same issue for me with headless 1.5.0. Which makes me think we have different issues and that I should create a new one indeed.

**Comment by ddahan** [comment]
I reproduced the touch issue with Vue-CLI too, so it's not directly related to Vite VS Vue-CLI, as I could have thought initially.
As the issue may be different from @oberocks one, i decided to create a new dedicated issue: https://github.com/tailwindlabs/headlessui/issues/1173

**Comment by oberocks** [comment]
@ddahan - Awesome of you to put up the new stackblitz imp!

And I think I can possibly help thanks to your efforts though!

If you move the `v-click-away-to-close` directive off of the `Popover` wrapping element, and instead put it on the `PopoverPanel` (child component), then the directive stays in it's lane and doesn't impact the sibling `input` element of the Popover component.

Also, I added a comment to your new issue to try and help in the nominal way that I can to get your issue seen.

**Comment by ddahan** [comment]
@oberocks Thanks a lot, this works now! I'll use it as a workaround until there is an official clean fix!
