### ISSUE TITLE
### I got the following error while using the <Transition.Child> the tag .

### ISSUE THREAD

**Issue by rahulMehndiratta2602** [tailwindlabs/headlessui#932]
### I got the following error while using the <Transition.Child> the tag . 
**Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got:** **undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**

**Check the render method of `TransitionChild`**

If i comment out the Transition.Child Element and then display the modal,it is being displayed. 
I am using 
_"@headlessui/react": "^1.4.1", "tailwindcss": "^2.2.4" ,"next": "latest", and for state management I am using  "recoil": "^0.5.2",_

Here is my code
```
import { Dialog } from '@headlessui/react'
import { Transition } from '@headlessui/react'
import React, { Fragment } from 'react'
import { useRecoilState } from 'recoil'
import { modalState } from '../atoms/ModalState'


const Modal = () => {
    const [isOpen, setIsOpen] = useRecoilState(modalState);
    return (
        <Transition show={isOpen} as={Fragment}>
            <Dialog
                as="div"
                className=" top-16 z-10 fixed inset-x-0 bottom-0 overflow-y-auto bg-green-50"
                onClose={() => setIsOpen(false)}
            >
                <div className=" flex  items-end justify-center min-h-[800px] sm:min-h-screen pt-4 px-4 
                            pb-20 sm:block sm:p-0 bg-green-500">
                    <Transition.Child
                        as={Fragment}
                        enter="ease-out duration-300"
                        enterFrom="opacity-0 scale-95"
                        enterTo="opacity-100 scale-100"
                        leave="ease-in duration-200"
                        leaveFrom="opacity-100 scale-100"
                        leaveTo="opacity-0 scale-95"
                    >
                        <Dialog.overlay className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />

                    </Transition.Child>
                </div>
            </Dialog>
        </Transition>
    )
}


export default Modal

```

_Originally posted by @rahulMehndiratta2602 in https://github.com/tailwindlabs/headlessui/discussions/931_

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You are using `Dialog.overlay` instead of `Dialog.Overlay`. Notice the uppercase `O` in `Overlay`.
