### ISSUE TITLE
Bug : Scroll lock mechanism does not work on Safari mobile 14 when the viewport is expanded

### ISSUE THREAD

**Issue by francoislevesque** [tailwindlabs/headlessui#949]
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

For example: v1.4.2

**What browser are you using?**

Safari Mobile 14 - iOS 14.8.1

**Reproduction URL**

https://codesandbox.io/embed/headlessui-vue-dialog-example-forked-n3q2p?fontsize=14&hidenavigation=1&theme=dark

[![Edit @headlessui/vue dialog Example (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headlessui-vue-dialog-example-forked-n3q2p?fontsize=14&hidenavigation=1&theme=dark)

**Describe your issue**

Open this URL [https://n3q2p.csb.app/](https://n3q2p.csb.app/) on Safari Mobile, scroll towards the center, and click on "open modal".
The scroll lock does not work. It only seems to happen when the toolbar is minimized / when the viewport is extanded.

The current scroll lock mechanism appears incomplete for Safari Mobile. 

We used to have the same issue with another project, we resolved it using this package: (https://github.com/FL3NKEY/scroll-lock)[https://github.com/FL3NKEY/scroll-lock].

**Comment by mirshko** [comment]
This occurs with the react package as well.

**Comment by VladSez** [comment]
Maybe we can adopt this [hook ](https://react-spectrum.adobe.com/react-aria/usePreventScroll.html) from `react-aria`?

**Comment by mockingjet** [comment]
AS for Vue, we can use [useScrollLock](https://vueuse.org/core/usescrolllock/#usescrolllock)

**Comment by ctholho** [comment]
This is still a problem. Anything which is supposed to have a scroll lock looks terrible right now. 

https://vueuse.org/core/usescrolllock/#directive-usage

Maybe the package [source](https://github.com/vueuse/vueuse/blob/main/packages/core/useScrollLock/index.ts) helps with a fix?

**Comment by jdpowell1** [comment]
I'm having issues with the scroll lock on the dialog, which is resetting the scroll position whenever it activates due to the weird way scrolling is implemented in our app. May I suggest a boolean value that allows developers to disable scroll locking so they can implement their own solutions?

**Comment by RobinMalfait** [comment]
This should be improved by #1824, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by rphlmr** [comment]
Hello,
I tried `npm install @headlessui/react@insiders` and maybe I'm doing something wrong but if I've some scrollable content in Dialog, it no more scrolls :/ 
I'll try to give you a reproducible demo.
