### ISSUE TITLE
[DOCS]: suggest adding github 'headless-ui' tag

### ISSUE THREAD

**Issue by techieshark** [tailwindlabs/headlessui#969]
I was looking at https://github.com/LXSMNSYC/solid-headless and notice they had a few github tags. Perhaps adding some to this repo would help people find this repo from there or vice versa.

![image](https://user-images.githubusercontent.com/1072292/144134238-483549d5-5ecb-4ad3-916b-bbc962c9b8e7.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

Added some tags for you!
