### ISSUE TITLE
How to to customize button/menu ids on menu button component?

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/headlessui#97]
I noticed that buttons are given auto generated ids of "headlessui-menu-button-x" and list items are given randomly generated ids as well. I am assuming that this is necessary for operation. Is there any way we can give a custom prefix or somehow customize this?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

ID's are pretty important and used by a lot in accessibility `aria-*` related roles. My first question would be, what is your main use case for changing the ID's?

**Comment by agusterodin** [comment]
Thanks for the quick response!

I have inspected dom and understand list structure is defined though aria by the means of automatically generated ids. I have no real reason other than that it would feel weird having elements with the ids "headlessui-menu-button-1", "headlessui-menu-button-2", ... on a production site. OCD probs. I totally understand if you deem it unnecessary. 

It would be nice at the bare minimum to be able to provide a custom prefix as a single prop to the menu that would be used for automatic id generation of both the menu button and the list items. The obvious concern would be potential id name collisions if the developer is not careful.

**Comment by RobinMalfait** [comment]
I'm going to write it down as a possible future addition/improvement, but for now I am going to close this issue.

**Comment by vincaslt** [comment]
Additional use case for this: <label> tags.

```
<label htmlFor="button-id">
  ...
  <input type="text" />
  <Menu.Button id="button-id">
    ...
  </MenuButton>
</label>
```

I would like to do something like this, where I have label wrapping 2 active elements, so I need to provide the id or it gets confused.

**Comment by stramel** [comment]
I'm using a `button` inside the `Menu.Item` to trigger a third party script which ties into a specific `id` selector. 

```html
<Menu.Item>
  <button id="LiveChat">Support</button>
</Menu.Item>
```
