### ISSUE TITLE
Glitch when switching focus from opened menu dropdown to text input

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/headlessui#98]
I am experiencing what I believe to be unexpected behavior when clicking into an html input while I have a menu dropdown opened. This might occur with other types of html elements as well, I haven't checked.

Steps to reproduce: 
1) Click the dropdown to open it (or open it via keyboard navigation)
2) Click the html input, notice that focus jumps back to the menu button and you have to click the input again if you want to enter text

https://codesandbox.io/s/headlessuireact-menu-example-forked-2uujc?fontsize=14&hidenavigation=1&theme=dark

MacOS 10.15.6
Google Chrome 85.0.4183.121

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed a bug. I'll open a PR that references this issue and it will be fixed in the next version.

**Comment by ericclemmons** [comment]
I just noticed the same thing. Confirmed it affects regular `<input>`s as well.
