### ISSUE TITLE
[DOCS]: Using HeadlessUI from a CDN

### ISSUE THREAD

**Issue by sfermigier** [tailwindlabs/headlessui#990]
Hi,

I'd like to use HeadlessUI (+ Vue) from a CDN for a static website, instead of setting up an additional JS project just for the components. 

For HeadlessUI, the documentation seems to only cover the latter case ("To get started, install Headless UI via npm or yarn").

Is there a simple way to use HeadlessUI without the JS/npm ceremony, and if so, can it be documented ?

**Comment by LoganDark** [comment]
Headless UI uses ESM modules, so it can't be loaded directly in the browser. It's meant to be consumed by a bundler like browserify or webpack.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

We currently don't support loading Headless UI from a CDN. You will get the best results if you use it as a proper dependency so that your bundler can also tree-shake the parts you don't need.

**Comment by renhiyama** [comment]
> Headless UI uses ESM modules, so it can't be loaded directly in the browser. It's meant to be consumed by a bundler like browserify or webpack.

esm is now allowed by browsers? also I am working on a no-build-needed framework so it would be highly appreciated if you guys could allow using this via cdn ;-;

**Comment by craigerskine** [comment]
> esm is now allowed by browsers? also I am working on a no-build-needed framework so it would be highly appreciated if you guys could allow using this via cdn ;-;

+1 for this! I need to be able to use this in a CDN env for rapid prototyping and for our devs to learn from.

**Comment by naoyuyan** [comment]
Is there a way to implement the CND version of Headless UI testing before placing it on projects with NPM? thanks
