### ISSUE TITLE
[BUG] Menu component with dynamic content skips through items when using arrows

### ISSUE THREAD

**Issue by ospfranco** [tailwindlabs/headlessui#994]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.4.2

**What browser are you using?**

Safari

**Reproduction URL**

Here is a reproducible example

https://github.com/ospfranco/headless_ui_test

It's a simple creact-react-app, just use the text field to filter for an item (e.g. "6") after delete the field and try to move through the items with the arrows, the item "6" will be magically skipped

**Describe your issue**

Hi, I created a sort of combo box using a HeadlessUI Menu component, everything works fine until the point where I need to filter/interact with the component, I filter the elems based on an input, that works fine the first time the list is filtered, but later if I remove the query (and therefore reset all the contents of the menu), somehow arrow navigation is not working properly anymore, but rather it just skips over the items

https://user-images.githubusercontent.com/1634213/146638988-3461bd90-0e44-45c6-b6ba-01d1c4c6103e.mov

is there any way to work around this behavior?

**Comment by andrewbeckman** [comment]
@ospfranco did you ever figure out a solution to this? Also, I think the example you attached doesn't include any headless ui code. Any chance you forgot to push up a commit?

**Comment by ospfranco** [comment]
Oopsie, forgot to push indeed, no, I haven't figured it out yet, but the code should be there in the example now

**Comment by andrewbeckman** [comment]
Ah okay thanks! I'm trying to build a combobox as well, but am thinking it might be better to just reach for a different solution until headless has a better out of the box solution for such a component.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by silvenon** [comment]
Hi @RobinMalfait 👋 I'm experiencing this issue as well, unfortunately. I'm using the latest version of Headless UI. Here is the repro: https://github.com/silvenon/repro/tree/headlessui-combobox-order (branch `headlessui-combobox-order`, run `npm run dev`)

To reproduce, first type "a" and navigate across results using arrows, things should work normally, but then type "e" ("ae" in total) and you should clearly see the problem when navigating with arrows again.

Or maybe I'm doing something wrong?

**Comment by RobinMalfait** [comment]
@silvenon aha, that's very odd. Let me investigate 👍

**Comment by RobinMalfait** [comment]
@silvenon figured it out, PR incoming!

**Comment by RobinMalfait** [comment]
Should be fixed by https://github.com/tailwindlabs/headlessui/pull/1168

**Comment by silvenon** [comment]
Thank you so much, that's much better!

I find another small one, hopefully the last one, in a specific case when adding a letter which doesn't remove the currently selected item, but (re)moves some next to it. Then moving the arrow in that direction skips over the newly added ones, I think. It's a bit hard to define, maybe you'll understand it better.

https://user-images.githubusercontent.com/471278/155999385-8d621dc4-e680-4409-a3ef-716ae6ab70b1.mov

**Comment by RobinMalfait** [comment]
@silvenon do you mind creating a new issue for this, that will be a bit easier to keep track of things, thanks!
